### ISSUE TITLE
Update benchmarks on wiki

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#1006]
The benchmark numbers on the wiki are seriously out-of-date, and probably misleading about Turing's performance. Better to update the numbers using the current releases. 

https://github.com/TuringLang/Turing.jl/wiki

**Comment by yebai** [comment]
@xukai92 are these models available somewhere? Perhaps we can add them to https://github.com/TuringLang/Turing.jl/tree/master/benchmarks

**Comment by xukai92** [comment]
Seems that they are avaiable in an old branch here https://github.com/TuringLang/TuringExamples/tree/old-models/old-models. 

For the benchmark suite, can we add the Stan version as well?

**Comment by yebai** [comment]
> For the benchmark suite, can we add the Stan version as well?

I think so, Github actions are quite generous with build time compared to Travis. So we can run these benchmarks altogether, then produce a table on the fly.

**Comment by xukai92** [comment]
Sounds good. I will take a look after finishing the remaining issues for AABI in AHMC.

**Comment by xukai92** [comment]
Will be fixed via https://github.com/TuringLang/TuringExamples/pull/22

**Comment by xukai92** [comment]
Here is a new table we can use

| model          | ppl    | time_mean           | time_std             |
|----------------|--------|---------------------|----------------------|
| lda            | stan   | 43.88816666666667   | 0.5039800227522238   |
| lda            | turing | 378.761714601       | 7.909938774234817    |
| sto_volatility | stan   | 0.918003            | 0.014350435115354504 |
| hmm_semisup    | stan   | 5.033236666666667   | 0.05811060258965908  |
| hmm_semisup    | turing | 463.21294081799994  | 26.044647410932335   |
| sto_volatility | turing | 75.026135433        | 30.578969778291953   |
| logistic_reg   | stan   | 56.15036666666666   | 2.273743438326613    |
| logistic_reg   | turing | 3.941581426         | 1.3307076036097722   |
| naive_bayes    | stan   | 13.677266666666666  | 0.14249036224718234  |
| naive_bayes    | turing | 6.8484756503333335  | 0.14433950672588655  |
| h_poisson      | stan   | 0.134482            | 0.06807910113977711  |
| h_poisson      | turing | 0.32486384333333335 | 0.01326488901201825  |
| gauss_unknown  | stan   | 0.34249333333333337 | 0.01481764496582818  |
| gauss_unknown  | turing | 2.210986531666667   | 0.06147874178072369  |
| high_dim_gauss | stan   | 11.609              | 0.3055549705044906   |
| high_dim_gauss | turing | 9.765776499         | 0.22158755377592457  |

What's the best place to host it? Not sure if we still want it on the wiki page.

**Comment by yebai** [comment]
Let's make a nice table, and put it on the front page of turing.ml, with a link the script to reproduce all the numbers.

**Comment by xukai92** [comment]
Slightly improved the table. Another other change to make?

**Comment by yebai** [comment]
cc @trappmartin and @cpfiffer, who might have ideas/suggestions regarding how to format and publish this benchmarking result on the front page.

**Comment by yebai** [comment]
here is an example for Julia's benchmarking page: https://julialang.org/benchmarks/

**Comment by xukai92** [comment]
Thanks for the pointer. I can make the visualiation. I will also improve the table a bit more - got an idea.

**Comment by xukai92** [comment]
Its a bit hard to make the markdown table nice as white spaces would be ignored. Plain text actually looks nice.

```
PPL                                            Stan              Turing
Model
Gaussian with Unknown Parameters   0.342 +/-  0.015    2.211 +/-  0.061
Hierarchical Poisson               0.134 +/-  0.068    0.325 +/-  0.013
High Dimensional Gaussian         11.609 +/-  0.306    9.766 +/-  0.222
LDA                               43.888 +/-  0.504  378.762 +/-  7.910
Logistic Regression                56.15 +/-  2.274    3.942 +/-  1.331
Naive Bayes                       13.677 +/-  0.142    6.848 +/-  0.144
Semi-supervised HMM                5.033 +/-  0.058  463.213 +/- 26.045
Stochastic Volatility              0.918 +/-  0.014   75.026 +/- 30.579
```

**Comment by cpfiffer** [comment]
Turing should probably be the first column, and we should organize them by which models Turing performs better in.

**Comment by xukai92** [comment]
Also made a plot

![results](https://user-images.githubusercontent.com/5985769/72212708-da673a80-34d8-11ea-9af2-a1159f6582b6.png)

**Comment by devmotion** [comment]
Maybe you could add error bars of the standard deviation to the plot?

**Comment by trappmartin** [comment]
Would it be possible to add some benchmarks on which we evaluate how Stan and Turing performs with increasing number of observations? Basically a line plot with the number of observations on the x-axis.

**Comment by xukai92** [comment]
> Maybe you could add error bars of the standard deviation to the plot?

Sure

> Would it be possible to add some benchmarks on which we evaluate how Stan and Turing performs with increasing number of observations? Basically a line plot with the number of observations on the x-axis.

Sure. But let improve those we are slow first. Otherwise it's hard to benchmark them (inference time is too long).

**Comment by xukai92** [comment]
I've copied and pasted the current table and figure to the wiki.

**Comment by KDr2** [comment]
Test Github Action: !benchmark(i, j)
