### ISSUE TITLE
Integration with the BUGS language via a customised DSL? 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#1011]
There are several projects extending the BUGS ([WinBUGS](http://www.mrc-bsu.cam.ac.uk/bugs/), [OpenBUGS](http://www.openbugs.net/w/FrontPage)) language, e.g. 

- https://github.com/nimble-dev/nimble
- https://github.com/biips/biips

and 

- Multi-core BUGS for fast Bayesian inference of large hierarchical models https://github.com/MultiBUGS/MultiBUGS

Maybe we can consider supporting the BUGS modelling language (as a frontend), but with Turing's inference algorithms, via a DSL? 

A similar approach would also apply to the [Stan](https://github.com/stan-dev/stanc3) modelling language. 

Related: https://github.com/TuringLang/Turing.jl/issues/905, https://github.com/TuringLang/Turing.jl/issues/976#issuecomment-555545587

See also, [Birch](https://birch-lang.org/) and [LibBi](http://libbi.org/).

**Comment by mohamed82008** [comment]
I hope these don't involve writing a full C++ to Julia transpiler!

**Comment by yebai** [comment]
> I hope these don't involve writing a full C++ to Julia transpiler!

Unlikely, we don't want to go back to the two language world anyway. The new Stan compiler is in OCaml, and it appears to be a reasonably light-weight library. I suspect a pure Julia parser for these DSLs is manageable if we leverage the existing Julia ecosystem for parsers.

**Comment by yebai** [comment]
cc @seantalts who is a main contributor of the new Stan compiler

**Comment by yebai** [comment]
Just a reminder for the future, the new Stan compiler is using Bison + Flex to parse models, which is available in a pure python package:  https://github.com/dabeaz/ply. The `ply` package can be used to implement any DSLs including Stan and WinBUGS in principle.

**Comment by seantalts** [comment]
We're actually using Menhir, but many of the constructs we currently use work in Bison and Flex.

Should be easy enough to add a new backend for Julia. Some of us are working on the same thing for Tensorflow Probability.

**Comment by yebai** [comment]
> We're actually using Menhir, but many of the constructs we currently use work in Bison and Flex.

Thanks for the clarification!

> Should be easy enough to add a new backend for Julia. Some of us are working on the same thing for Tensorflow Probability.

It would be great to have a Julia backend. 

The [`Bijectors.jl`](https://github.com/TuringLang/Bijectors.jl) and [`AdvancedHMC.jl`](https://github.com/TuringLang/AdvancedHMC.jl) packages provide good coverage (if not all) math functions and NUTs sampler available in Stan. In particular, the AdvancedHMC provides a robust re-implementation of Stan's NUTS sampler, including windowed adaption.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/AbstractPPL.jl/pull/44
