### ISSUE TITLE
Sanity check is missing for space of Gibbs sampler and model parameter space

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Turing.jl#1012]
PR #965 introduced the ability to pass user-defined variable names. The symbols of the parameters of a model is therefore no longer baked into the type of the model. This makes it less straightforward to check the space of the model since the variable names may only be known at run-time. One solution is to run `vi = VarInfo(model)` and check that the keys of `vi.metadata` are the same as the space of the Gibbs sampler.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/1904
