### ISSUE TITLE
Turing Release

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#1015]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
I'm undoing 0.9.1 by release the contents of 0.9 as 0.9.2, so that 0.9.1 can be released as a minor version. 

@JuliaRegistrator register branch=turing/v0.9.2

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by mohamed82008** [comment]
@JuliaRegistrator register()

**Comment by cpfiffer** [comment]
@JuliaRegistrator register
