### ISSUE TITLE
To inline, or not to inline, that is the question

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Turing.jl#1034]
We have a lot functions in Turing, some call others, all working in a beautiful harmonious dispatch tree giving us the amazing Turing we all love. However, function calls are not free. Every function call incurs a cost. Inlining a function can also sometimes enable certain compiler optimizations that wouldn't be otherwise possible. However, the opposite can also be true sometimes. This is why the Julia compiler has heuristics to decide when a function is worth inlining and when it is not. These heuristics can often be helped by the developer though leading to an essentially free speedup. 

At some point, I think we need to go through every boilerplate function in Turing and see if preceding its definition with `@inline` speeds up inference or not. It is a simple enough but arduous task. Some may call it micro-optimization, but many of those single digit percent speedups can add up at the end, especially for small models.

**Comment by cpfiffer** [comment]
Sounds like a good plan to me. I'll take a look at inlining upstream in AbstractMCMC and the inference functions, but I imagine the overhead there is quite slim.
