### ISSUE TITLE
HMC `n_adapts` should be better handled

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#1058]
This issue was highlighted over in #1042. The number of adaptation samples for the Hamiltonian samples is handled in `sample_init!` and not the inference method constructor, which is not great behavior.

@xukai92:

>I think the current order of automatically setting the number of adaptation is flawed. What would happen if one is intended to set it to 0? The current behaviour will still change it to something else.
>
> I think what we had before could handle it correctly, i.e. setting it during the construction of algorithm.

@cpfiffer:

> > I think the current order of automatically setting the number of adaptation is flawed. What would happen if one is intended to set it to `0`? The current behaviour will still change it to something else.
> 
> Yeah, but this was also our old logic carried in from the original Hamiltonian implementations -- I mostly just moved it around.
> 
> The problem with handling this during the construction of the algorithm is that currently the inference algorithm constructor does not know the total number of iterations because `N` is part of the outer `sample` call. We could probably get around that, though.
> 
> Maybe a better way to do this would be to move the number of adapatation samples to the keyword side:
> 
> ```julia
> sample(model, NUTS(500, 0.65), 1000)
> ```
> 
> would become
> 
> ```julia
> sample(model, NUTS(0.65), 1000; n_adapts=500)
> ```
> 
> Then we could handle all this more robustly at the inference constructor by passing keywords around. Having the number of adaptations in the inference constructor always seemed a little weird to me anyway.

**Comment by cpfiffer** [comment]
I noticed several things I might like to change while I was writing #1063:

1. We should allow the `Sampler(. . .)` constructor to accept arbitrary keywords, which will now be handled at DynamicPPL.jl. One reason I would like to do this is that it will allow us to pass in information from the sample environment to the inference algorithm. Currently inference algorithm constructors have very little information about the total number of samples, random number generator, you name it. It'd be a quick fix and samplers would be able to use whatever info they wanted.
2. I think we should change how adaptation samples are handled -- if someone requests 1,000 samples and 500 adaptation samples, we should not return only 500 samples as we do right now. We should run the 500 independently and then return the full 1,000 that they requested. If there is interest, it might be worth adding a keyword argument `n_adapt` to `sample` and removing adaptation from the inference algorithm constructor entirely. 

How does anyone feel about either of these? The first one is small and won't impact much. The second is a breaking change that is maybe less important.

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/AbstractPPL.jl/pull/44 since AHMC now adopts AbstractMCMC interface.
