### ISSUE TITLE
Support static modelling / BUGS block within `model`

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#1061]
This is an (tentative) example derived during a discussion with @mohamed82008. The aim is to introduce a feature into `@model` so that users can write BUGS/JAGS style model definitions, but using the Julia syntax. We can track the DAG for these static blocks and compute Gibbs conditionals in an efficient way, which helps support #905. 

```julia
@model demo()

# Some random code
x ~ Dist()
if x > 1 
  y ~ Normal()
else 
  y ~ Normal()
end

# The BUGS block defines an embedded, self-contained static model without any control flows, where 
# we can efficiently compute Gibbs conditionals by tracking and storing DAG in VarInfo. 
z ~ BUGS(x, y) do x, y 
   rv1 ~ SomeDist(x)
   rv2 ~ SomeDist(y)
   var = rv1 + rv2
   Normal(var)
end 

end
```

cc @itsdfish

**Comment by itsdfish** [comment]
Awesome!

Out of curiosity, are there limitations on the use of Julia with this approach? The reason I ask is that I use Turing because it allows me to write custom likelihood functions where I can leverage Julia's core language and and various packages.

**Comment by yebai** [comment]
The only limitation is it has to be static, that is the dimensionality and graph structure remains the same during inference. We might start from a basic prototype (a Julia equivalent of BUGS modelling language), gradually adding more flexibilities.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/AbstractPPL.jl/pull/44
