### ISSUE TITLE
Anyone can help me? " TypeError: descriptor 'bind' of 'kivy._event.EventDispatcher' object needs an argument"

### ISSUE THREAD

**Issue by csd051008** [TuringLang/Turing.jl#1077]
[INFO   ] [Logger      ] Record log in C:\Users\Administrator\.kivy\logs\kivy_20-01-17_77.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.10
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\ProgramData\Anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\ProgramData\Anaconda3\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 24.20.100.6299'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 515'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 24.20.100.6299'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "kivyapp.py", line 97, in <module>
     chat_app.run()
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 829, in run
     root = self.build()
   File "kivyapp.py", line 84, in build
     screen.add_widget(self.connect_page)
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\uix\floatlayout.py", line 139, in add_widget
     pos_hint=self._trigger_layout)
 TypeError: descriptor 'bind' of 'kivy._event.EventDispatcher' object needs an argument
[kivyapp.txt](https://github.com/TuringLang/Turing.jl/files/4075897/default.txt)

**Comment by cpfiffer** [comment]
This is unrelated to Turing.

**Comment by csd051008** [comment]
> This is unrelated to Turing.
I solved it! Thanks your riply.
