### ISSUE TITLE
Handle gradient = nothing case when doing reverse diff with Zygote

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Turing.jl#1081]
Zygote returns `nothing` for the gradient if the output of the function is a constant. This can happen if a uniform distribution is used alone in the model, so the logpdf is constant in the random variable. Currently, https://github.com/TuringLang/DistributionsAD.jl/pull/25 defines an adjoint for `Uniform` to return a zero derivative for `x`, the random variable. However, it's probably more robust to just handle the `nothing` case in Turing directly because other constant functions might also trigger it.

**Comment by yebai** [comment]
Likely fixed in https://github.com/TuringLang/DistributionsAD.jl/pull/25
