### ISSUE TITLE
NUTS Adaptation Samples Docu

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#1085]
The current docu doesn't clearly state that the adaptation samples get thrown away after inference. We should update this so that users don't get confused about this behaviour.

Maybe also add a sanity check that the number of samples is larger than the number of adaptation samples.

**Comment by cpfiffer** [comment]
Related: https://github.com/TuringLang/Turing.jl/issues/1058. The gist is that I would prefer it if when someone calls `sample(model, NUTS(100, 0.65), 1000)`, they should actually receive 1,000 samples and not 900. Is this something other people think we should do? I don't know if this is something I'm just grumpy about that other people don't care about, or if it's actually strange functionality that should be changed.

But yes, we can document the behaviour of `discard_adapt`, which is the keyword that governs this behaviour.

**Comment by yebai** [comment]
Fixed in [`AbstractMCMC`](https://github.com/TuringLang/AbstractMCMC.jl/pull/47).
