### ISSUE TITLE
Is von Mises distribution broken?

### ISSUE THREAD

**Issue by SosUts** [TuringLang/Turing.jl#1086]
I want make a mixture model of circular data(-pi to +pi).
When I tried modelling referring [this tutorial](https://turing.ml/dev/tutorials/1-gaussianmixturemodel/), so many errors occurred .
Is von Mises distribution still broken?

**Comment by SosUts** [comment]
Right after making this issue,  I found that it's still broken.
https://github.com/TuringLang/DistributionsAD.jl/issues/2

**Comment by mohamed82008** [comment]
The problem is the `besselix` function in `SpecialFunctions`. It needs a custom adjoint.

**Comment by SosUts** [comment]
Thank you. Sorry for the late reply...
I wish I could fix it myself...
