### ISSUE TITLE
Generalise TArray

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#110]
The self-copying mechanism in `TArray` could be generalised, e.g. create a macro `@T`, that can automatically lift existing data structures to Turing-safe ones. 

On a side note, `TArray`'s copying detection mechanism can be documented and improved, ie. `taskcopy` can set a flag (e.g. `flag=gensym()`) in `task.localstorage` to inform that a task has been copied.

**Comment by xukai92** [comment]
This sounds very useful!

**Comment by yebai** [comment]
This could be done through introduce an abstract type (e.g. `TSafe`). All data structures that requires self-copying can be defined as subtypes of `TSafe`.
