### ISSUE TITLE
Question: error in initializing undefined variable

### ISSUE THREAD

**Issue by vsaase** [TuringLang/Turing.jl#1102]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/1_GaussianMixtureModel.md

Hi, I am new to Turing, trying to understand the ~ notation:
I noticed that this line: `k = Vector{Int}(undef, N)` initializes the vector to zeros(N), but it should be undefined values, so the values get sampled in the next lines. I suppose this should be `k = Vector{Integer}(undef, N)` ?

**Comment by devmotion** [comment]
> I noticed that this line: k = Vector{Int}(undef, N) initializes the vector to zeros(N)

Actually, this line constructs an uninitialized vector of integers of the length `N`:
```julia
julia> k = Vector{Int}(undef, 10)
10-element Array{Int64,1}:
             120
              16
 140153497918977
             137
              21
 140153497201153
             206
              46
 140153497201153
 140153497201328
```

> I suppose this should be k = Vector{Integer}(undef, N) ?

This would construct an uninitialized vector of `Integer`s of length `N`. However, `Integer` is an abstract type (in contrast to `Int`), which [should be avoided if possible](https://docs.julialang.org/en/v1/manual/performance-tips/index.html#Avoid-containers-with-abstract-type-parameters-1).

```julia
julia> k = Vector{Integer}(undef, 10)
10-element Array{Integer,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
```

Does this answer your question?

**Comment by vsaase** [comment]
So how does the ~ operator then know if the value is real input data or should be sampled from the distribution? Is any variable declared in the model considered a free variable?

**Comment by xukai92** [comment]
Any variable declared as the argument of the model is data. That is `@model f(data1, data2, ...) = begin ... end`. Anything else on the left of the tilde notation (`~`) inside the begin/end are variables to sample.

**Comment by vsaase** [comment]
ok, thanks

now it seems to be not so easy to use the right type, tried this
```
    p_kv = Array{Float64, 2}(undef, (K,V))
    for k in 1:K
        for v in 1:V
            p_kv[k,v] ~ Uniform(0,1)
        end
    end
```

which lead to the following error:
```

TypeError: in typeassert, expected Float64, got ForwardDiff.Dual{Nothing,Float64,10}
in top-level scope at home/vsaase/src/dcm2df.jl/generative_models.jl:46
in mapreduce at base/reducedim.jl:307
in #mapreduce#584 at base/reducedim.jl:307 
in _mapreduce_dim at base/reducedim.jl:312
in _mapreduce at base/reduce.jl:309
in  at home/vsaase/src/dcm2df.jl/generative_models.jl:46
in sample at Turing/LONxt/src/inference/Inference.jl:158
in #sample#2 at Turing/LONxt/src/inference/Inference.jl:159
in Sampler at DynamicPPL/nsoCZ/src/sampler.jl:44 
in DynamicPPL.Sampler at base/tuple.jl:140
in  at Turing/LONxt/src/inference/gibbs.jl:73
in DynamicPPL.Sampler at Turing/LONxt/src/inference/hmc.jl:310
in Turing.Inference.HMCState at Turing/LONxt/src/inference/hmc.jl:530
in #HMCState#51 at Turing/LONxt/src/inference/hmc.jl:559
in sample_init at AdvancedHMC/Sn9Ek/src/sampler.jl:13 
in phasepoint at AdvancedHMC/Sn9Ek/src/hamiltonian.jl:129 
in phasepoint at AdvancedHMC/Sn9Ek/src/hamiltonian.jl:59
in ∂H∂θ at AdvancedHMC/Sn9Ek/src/hamiltonian.jl:28 
in ∂logπ∂θ at Turing/LONxt/src/inference/hmc.jl:400 
in gradient_logp at Turing/LONxt/src/core/ad.jl:68 
in gradient_logp_forward at Turing/LONxt/src/core/ad.jl:104
in gradient! at ForwardDiff/vt5F1/src/gradient.jl:33
in gradient! at ForwardDiff/vt5F1/src/gradient.jl:37
in chunk_mode_gradient! at ForwardDiff/vt5F1/src/gradient.jl:140
in f at Turing/LONxt/src/core/ad.jl:95 
in runmodel! at DynamicPPL/nsoCZ/src/varinfo.jl:598 
in runmodel! at DynamicPPL/nsoCZ/src/varinfo.jl:602 
in Model at DynamicPPL/nsoCZ/src/model.jl:24 
in #_#3 at DynamicPPL/nsoCZ/src/model.jl:24 
in  at DynamicPPL/nsoCZ/src/compiler.jl:591
in macro expansion at home/vsaase/src/dcm2df.jl/generative_models.jl:20 
in macro expansion at DynamicPPL/nsoCZ/src/compiler.jl:458 
in setindex! at base/array.jl:784 

```

**Comment by devmotion** [comment]
The problem seems to be that you use HMC for inference with ForwardDiff, which leads to dual numbers that can't be written to `p_kv`. Maybe changing the first line to
```julia
    p_kv = Array{Real, 2}(undef, (K,V))
```
helps.

**Comment by vsaase** [comment]
yes that helps, thank you

one further question, but still related, can I use the tilde operator like so:

```
    for n in 1:N
        k = protocol_m[studies[n]]
        v = sequences[n]
        1 ~ Bernoulli(p_kv[k,v])
    end
```
