### ISSUE TITLE
Build an offical docker for Turing

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#1113]
- Make it available at https://hub.docker.com/

**Comment by KDr2** [comment]
@xukai92 had you started on this issue? If not I could do this. Do we have an Org account on hub.docker.com now? My account is `kdr2`, I'll appreciate it if you add me as a member 😄

**Comment by xukai92** [comment]
I haven't. Please feel free to take over this issue. We created one org for Turing and added you :)

**Comment by KDr2** [comment]
OK, I will do it this or next week.
