### ISSUE TITLE
Build failing. "AbstractChains not defined"

### ISSUE THREAD

**Issue by rna1990** [TuringLang/Turing.jl#1121]
Good day.

I recently installed Turing.jl but the precompiling process is failing with the following error message:

julia> using Turing
[ Info: Precompiling Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0]
  Building Libtask → `C:\Users\******\.julia\packages\Libtask\RjRkK\deps\build.log`
WARNING: could not import MCMCChains.AbstractChains into Turing
ERROR: LoadError: LoadError: UndefVarError: AbstractChains not defined
Stacktrace:
 [1] include at .\boot.jl:328 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1105
 [3] include at .\Base.jl:31 [inlined]
 [4] include(::String) at C:\Users\rodrigo.nava\.julia\packages\Turing\xFzfF\src\Turing.jl:1
 [5] top-level scope at C:\Users\rodrigo.nava\.julia\packages\Turing\xFzfF\src\Turing.jl:124
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:425
 [12] top-level scope at .\none:3
in expression starting at C:\Users\rodrigo.nava\.julia\packages\Turing\xFzfF\src\utilities\Utilities.jl:6
in expression starting at C:\Users\rodrigo.nava\.julia\packages\Turing\xFzfF\src\Turing.jl:124
ERROR: Failed to precompile Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0] to C:\Users\rodrigo.nava\.julia\compiled\v1.3\Turing\gm4QC_jFlht.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917

**Comment by cpfiffer** [comment]
I believe you are probably using an outdated version of Turing. Can you post the results of `] status`?

You can also try running `] up` to update your packages.

**Comment by rna1990** [comment]
Sure, here it is. I already tried ] update, but it's still not working:

(v1.3) pkg> status
    Status `C:\Users\rodrigo.nava\.julia\environments\v1.3\Project.toml`
  [6e4b80f9] BenchmarkTools v0.4.3
  [4c24c29e] BoxCoxTrans v1.0.0 #master (https://github.com/tk3369/BoxCoxTrans.jl)
  [336ed68f] CSV v0.5.24
  [a93c6f00] DataFrames v0.20.2
  [31c24e10] Distributions v0.21.12
  [c43c736e] Genie v0.26.1
  [09f84164] HypothesisTests v0.9.0
  [7073ff75] IJulia v1.21.1
  [6deec6e2] IndexedTables v0.12.6
  [a93385a2] JuliaDB v0.13.0
  [91a5bcdd] Plots v0.29.1
  [438e738f] PyCall v1.91.3
  [d330b81b] PyPlot v2.8.2
  [2913bbd2] StatsBase v0.32.1
  [f3b207a7] StatsPlots v0.14.0
  [9e3dc215] TimeSeries v0.16.0
  [fce5fe82] Turing v0.7.1
  [fdbf4ff8] XLSX v0.6.0
  [37e2e46d] LinearAlgebra

**Comment by cpfiffer** [comment]
Try running `] add Turing@0.8.3`, and it should tell you what packages are preventing Turing from updating correctly.

**Comment by rna1990** [comment]
thanks! I tried and got the following:

(v1.3) pkg> add Turing@0.8.3
  Updating registry at `C:\Users\rodrigo.nava\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Turing [fce5fe82]:
 Turing [fce5fe82] log:
 ├─possible versions are: [0.5.0-0.5.1, 0.6.0-0.6.2, 0.6.4-0.6.9, 0.6.11-0.6.15, 0.6.17-0.6.19, 0.6.21-0.6.23, 0.7.0-0.7.4, 0.8.0-0.8.3] or uninstalled
 ├─restricted to versions 0.8.3 by an explicit requirement, leaving only versions 0.8.3
 └─restricted by compatibility requirements with Distributions [31c24e10] to versions: [0.5.0-0.5.1, 0.6.0-0.6.2, 0.6.4-0.6.9, 0.6.11-0.6.15, 0.6.17-0.6.19, 0.6.21-0.6.23, 0.7.0-0.7.4, 0.8.0-0.8.2] or uninstalled — no versions left
   └─Distributions [31c24e10] log:
     ├─possible versions are: [0.16.0-0.16.4, 0.17.0, 0.18.0, 0.19.1-0.19.2, 0.20.0, 0.21.0-0.21.3, 0.21.5-0.21.12, 0.22.0-0.22.4] or uninstalled
     └─restricted to versions 0.21.12 by an explicit requirement, leaving only versions 0.21.12

**Comment by rna1990** [comment]
I guess Distributions is the problem, right? Should it be upgraded or downgraded?

**Comment by cpfiffer** [comment]
I would try removing Distributions and then running `] add Turing@0.8.3`. If something else is blocking updating as well, try removing that and rerunning the command above.

**Comment by RoyCCWang** [comment]
If I use ```[ add Turing``` in Julia v1.4.0, I get the AbstractChains error. This currently installs Julia v0.7.1.

If I use ```] add Turing@0.8.3```, I do not get an error.

It seems the Julia package registry is pointing to Turing v0.7.1 for some reason.

If I use ```] add https://github.com/TuringLang/Turing.jl```, I get ```ERROR: Unsatisfiable requirements detected for package CoupledFields```.

For now, I suggest updating the Julia package registry to point to Turing v 0.8.3.

**Comment by cpfiffer** [comment]
At this point, you should be doing `] add Turing@0.10.1` since there's been several bug fixes since 0.8.3.

**Comment by kadir-gunel** [comment]
Hello, 

I had the same problem with julia v1.2 . I found the solution in removing the ~/.julia. By doing that the registries got updated to the latest version of Turing (0.10.1). 

A better solution would be creating a virtual environment and install Turing inside that.

**Comment by cpfiffer** [comment]
Closing as this seems to be resolved.
