### ISSUE TITLE
Transformation of inputs?

### ISSUE THREAD

**Issue by tpoisot** [TuringLang/Turing.jl#1139]
Following up on https://discourse.julialang.org/t/turing-jl-update-variables-within-the-model/35168/4

We (@FrancisBanville and @aammd) are using Turing to fit a model, where every data point is a pair (S,L), as we describe in the following paper: https://www.biorxiv.org/content/10.1101/2020.02.13.947531v1

In practice, we do not use L to fit the model, but L-(S-1), and I have not been able to use this directly from within Turing - what I had to do was create a variable (equal to L.-(S.-1)) and then call the model on this.

The model is as follows:

```
@model flexible_links(s,f) = begin
    N = length(s)
    # Transformed data
    F = (s.*s) .- (s .- 1.0)
    # Parameters
    ϕ ~ Normal(3.0, 0.5)
    μ ~ Beta(3.0, 7.0)
    for i in 1:N
        f[i] ~ BetaBinomial(F[i], μ*exp(ϕ), (1-μ)*exp(ϕ))
    end
    return μ, ϕ
end
```

What I would like to write instead would look something like this:

```
@model flexible_links(s,l) = begin
    N = length(s)
    # Transformed data
    f = [l[i]-(s[i]-1) for i in 1:N]
    F = (s.*s) .- (s .- 1.0)
    # Parameters
    ϕ ~ Normal(3.0, 0.5)
    μ ~ Beta(3.0, 7.0)
    for i in 1:N
        f[i] ~ BetaBinomial(F[i], μ*exp(ϕ), (1-μ)*exp(ϕ))
    end
    return μ, ϕ
end
```

We think it would be cool to be able to transform the inputs inside the model, just for convenience.

**Comment by yebai** [comment]
This is probably better done during the pre-processing step, outside of a model.
