### ISSUE TITLE
Print update message in the future

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#1141]
Some packages print a message to notify what's new in the recent release when loading the package for the first time, e.g. DrWatson.jl

```
Update message: DrWatson v1.8.0

A cool new feature was added to the `@quickactivate` macro!
```

This is how they do this: https://github.com/JuliaDynamics/DrWatson.jl/blob/46e7cceb7c25e2eb21abf059e6b3fb6ad7fe33e7/src/DrWatson.jl#L48

Maybe we should do this as well to notify major changes?

**Comment by devmotion** [comment]
Maybe it would be (more) important to keep https://github.com/TuringLang/Turing.jl/blob/master/RELEASE.md up to date and/or create a CHANGELOG.md/NEWS.md file with more detailed human-readable information?

**Comment by yebai** [comment]
> Maybe it would be (more) important to keep 
> https://github.com/TuringLang/Turing.jl/blob/master/RELEASE.md up to date and/or create a CHANGELOG.md/NEWS.md file with more detailed human-readable information?

Seconded - we need to take breaking changes and release updates more seriously.
