### ISSUE TITLE
Bayesian HMM tutorial shows errors inline

### ISSUE THREAD

**Issue by kmsquire** [TuringLang/Turing.jl#1148]
Everything after the following example shows errors at https://turing.ml/dev/tutorials/4-bayeshmm/ (although running it locally seems to work).

> Time to run our sampler.
> 
> ```julia
> g = Gibbs(HMC(0.001, 7, :m, :T), PG(20, :s))
> c = sample(BayesHmm(y, 3), g, 100);
> ```
> ```julia
> Error: MethodError: no method matching Float64(::Tracker.TrackedReal{Float6
> 4})
> Closest candidates are:
>   Float64(::Real, !Matched::RoundingMode) where T<:AbstractFloat at roundin
> g.jl:185
>   Float64(::T<:Number) where T<:Number at boot.jl:725
>   Float64(!Matched::Int8) at float.jl:60
>   ...
> ```

**Comment by cpfiffer** [comment]
Thanks for pointing this out -- I'll fix this over the weekend.

**Comment by cpfiffer** [comment]
Fixed with https://github.com/TuringLang/TuringTutorials/pull/60, thanks @kmsquire!
