### ISSUE TITLE
Libtask error:   setindex! not defined for TArray{Float64,1}

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#1155]
It seems the new version of `Libtask` introduces some issues. See https://travis-ci.org/TuringLang/Turing.jl/jobs/660642720#L472

**Comment by cpfiffer** [comment]
Should we roll back the release for now (i.e., make a new release 0.3.3 = 0.3.1)? The only real reason Libtask 0.3.2 was released was for Julia 1.4 support, which is still in preview. Everyone using supported Julia versions has a broken install at the moment.

**Comment by yebai** [comment]
> Should we roll back the release for now (i.e., make a new release 0.3.3 = 0.3.1)? The only real reason Libtask 0.3.2 was released was for Julia 1.4 support, which is still in preview. Everyone using supported Julia versions has a broken install at the moment.

Sounds good to me if that's possible.

**Comment by mohamed82008** [comment]
The issue is not resolved yet https://travis-ci.org/TuringLang/Turing.jl/jobs/660884398#L776.

**Comment by mohamed82008** [comment]
Oh the new release was not made yet, my bad.

**Comment by yebai** [comment]
Fixed by Libtask v0.3.3
