### ISSUE TITLE
Turing.ml opens to dev instead of stable + other typos in references

### ISSUE THREAD

**Issue by deepaks4077** [TuringLang/Turing.jl#1157]
https://turing.ml/ opens to https://turing.ml/dev instead of https://turing.ml/stable

The contributions link on the [github readme](https://github.com/TuringLang/Turing.jl) is [missing](http://turing.ml/docs/contributing/)

The getting started page referenced by the github readme is the [dev](https://turing.ml/dev/docs/using-turing/get-started) version instead of the [stable](https://turing.ml/stable/docs/using-turing/get-started) version.

NOTE: I couldn't find any guidelines to opening issues in Turing.

**Comment by trappmartin** [comment]
Thanks! I think we currently don't have guidelines for issue. @yebai this might be a good idea to add for further reporting of issues.

**Comment by yebai** [comment]
This has been fixed.
