### ISSUE TITLE
Switch to ReverseDiff for default AD?

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#1164]
Are there any known issues that could prevent a switch? If not, maybe consider switching the default AD to ReverseDiff after https://github.com/TuringLang/DistributionsAD.jl/pull/44 is merged? Based on our benchmarks, ReverseDiff provides the most efficient reverse-mode AD implementation at the moment.

**Comment by mohamed82008** [comment]
It might be good to have a macro that prettifies custom adjoints in ReverseDiff for users.

**Comment by mohamed82008** [comment]
Some users like to define their own adjoints.

**Comment by yebai** [comment]
> It might be good to have a macro that prettifies custom adjoints in ReverseDiff for users.

That would be great!

**Comment by yebai** [comment]
@mohamed82008 It seems the new DistributionsAD release introduced some issues, see

```julia
 [6] include_relative(::Module, ::String) at ./loading.jl:1044
 [7] include at ./sysimg.jl:29 [inlined]
 [8] include(::String) at /home/runner/.julia/packages/DistributionsAD/U9qRl/src/DistributionsAD.jl:1
 [9] top-level scope at none:0
 [10] include at ./boot.jl:317 [inlined]
 [11] include_relative(::Module, ::String) at ./loading.jl:1044
 [12] include(::Module, ::String) at ./sysimg.jl:29
 [13] top-level scope at none:2
 [14] eval at ./boot.jl:319 [inlined]
 [15] eval(::Expr) at ./client.jl:393
 [16] top-level scope at ./none:3
in expression starting at /home/runner/.julia/packages/DistributionsAD/U9qRl/src/reversediff.jl:392
in expression starting at /home/runner/.julia/packages/DistributionsAD/U9qRl/src/DistributionsAD.jl:55
ERROR: LoadError: Failed to precompile DistributionsAD [ced4e74d-a319-5a8a-b0ac-84af2272839c] to /home/runner/.julia/compiled/v1.0/DistributionsAD/mhHYG.ji.
```

https://github.com/TuringLang/Turing.jl/runs/524084297?check_suite_focus=true#step:4:251

**Comment by mohamed82008** [comment]
Interesting. It's weird that I didn't get this error in DistributionsAD tests on Julia 1.0. I will fix, it is simple enough.

**Comment by mohamed82008** [comment]
I restarted the tests, seem to be fine now.
