### ISSUE TITLE
More comprehensive AD benchmarking

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#1184]
Our benchmarking about AD is a bit ad-hoc, and in-complete at the moment. There are some nice benchmarking scripts in the following repos:

- https://github.com/JuliaDiff/ReverseDiff.jl/blob/master/benchmark/benchmark.jl
- https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/benchmarks/benchmarks.jl

Maybe we can adapt these examples, and run them on Tracker, ReverseDiff, Zygote and ThArrays to get a better picture of Julia reverse-mode AD libraries' true performance. 

In addition to the examples above, we should try to include at least one example for each of the following

- branching
- loops
- array indexing
- broadcasting

Related https://github.com/TuringLang/Turing.jl/issues/1140

**Comment by xukai92** [comment]
+ numerical stability

I've been experienced a few cases that Zygote can have quite different stability agasint Tracker when using Flux (e.g. https://github.com/FluxML/Flux.jl/issues/914 and https://github.com/FluxML/Flux.jl/issues/876). 

A recent case where the (naively-implemented) logistic regression model was runnable with Tracker but fails with ReverseDiff seems to be another case which makes me think we should inlcude numerical statbility as an aspect.
