### ISSUE TITLE
@. $ does not work inside @model

### ISSUE THREAD

**Issue by baggepinnen** [TuringLang/Turing.jl#1196]
One can use `$` to denote that a part of an expression should not use broadcasting inside `@.`, but this does not work inside `@model`
```julia
@model gdemo(x) = begin
  # Set priors.
  s ~ InverseGamma(2, 3)
  m ~ Normal(0, sqrt(s))

  # Observe each value of x.
  @. x ~ Normal(m, $sqrt(s))
end
```
The error produced is
```
syntax: "$" expression outside quote
top-level scope at turing.jl:98
```

**Comment by mohamed82008** [comment]
Thanks for opening this. I will try to address this in the next refactor of `.~` and `@.` in the model macro.

**Comment by mohamed82008** [comment]
Seems @devmotion has beaten me to it :)

**Comment by cpfiffer** [comment]
A problem I frequently experience. I think if we waited long enough, @devmotion would solve general AI.
