### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by DilumAluthge** [TuringLang/Turing.jl#1198]
Page: https://turing.ml/dev/tutorials/6-infinitemixturemodel/

Section: "Finite Mixture Model": https://turing.ml/dev/tutorials/6-infinitemixturemodel/#finite-mixture-model

The link `Gaussian mixture model tutorial` is broken.

**Comment by cpfiffer** [comment]
This one is currently going to be tricky to fix in a good way, since we can't currently weave a lot of the tutorials (see https://github.com/JunoLab/Weave.jl/issues/290).

I'll see if there's something I can do. Thanks!

**Comment by cpfiffer** [comment]
I fixed this upstream in [TuringTutorials](https://github.com/TuringLang/TuringTutorials). Should show up on the site in a day or two. Thanks, @DilumAluthge!
