### ISSUE TITLE
StackOverflowError raised by the pdf of BinomialLogit

### ISSUE THREAD

**Issue by HarrisonWilde** [TuringLang/Turing.jl#1210]
Hi, I raised this question in the Slack and was told to make a short PR for this bug:

```
pdf(BinomialLogit(1, 0.5), 1)
```
Results in:
```
ERROR: StackOverflowError:
Stacktrace:
 [1] pdf(::BinomialLogit{Float64,Int64}, ::Int64) at /Users/harrisonwilde/.julia/packages/Distributions/6HQ2U/src/univariates.jl:333 (repeats 80000 times)
```

The fix is to assign the following:
```
Distributions.pdf(d::BinomialLogit{<:Real}, k::Int) = exp(logpdf(d, k))
```

Where should this go in the source code? Additionally, I was wondering if it was worth defining `BernoulliLogit` as an explicit entity, to me it reads better than a `BinomialLogit` with `n=1` when doing logistic regression etc.

**Comment by devmotion** [comment]
Hej!

As [I've said before](https://github.com/TuringLang/Turing.jl/pull/1089#issuecomment-580720488), IMO the default implementation in Distributions should be changed.

If you want to make a PR to Turing, it should go to src/stdlib/distributions.jl, just [as in the other PR](https://github.com/TuringLang/Turing.jl/pull/1089).

**Comment by HarrisonWilde** [comment]
I will do a PR for Turing for now, what are your thoughts on the BernoulliLogit being explicitly defined? I will also raise an issue over on Distributions.jl

**Comment by devmotion** [comment]
I guess one could just define
```julia
BernoulliLogit(p) = BernoulliBinomial(1, p)
```
it that feels more convenient?

**Comment by HarrisonWilde** [comment]
Precisely, I don't see a reason not to include it in Turing, do you mean for me to raise a PR or just that people should define this in their own code?
