### ISSUE TITLE
Normal: the condition σ >= zero(σ) is not satisfied for well-specified model

### ISSUE THREAD

**Issue by baggepinnen** [TuringLang/Turing.jl#1215]
Inference on the following model  complains about the variance parameters not fulfilling `sigma > 0` if sampled with HMC or NUTS, even though all variance paramaters have priors with only nonnegative support.

I tried adding early termination if any sampled variance parameter is nonfinite and that gets rid of the exception.
```julia
Turing.@model model(Ir, p, ::Type{T}=Float64) where {T} = begin

    N = length(Ir)
    np = length(p)
    I,Ir,R = ntuple(i->Vector{T}(undef, N), 3)

    nq = 1 # Assuming one lag for now
    q = Vector{T}(undef, 1)
    q[1] ~ Uniform(0,1) # this is a bad prior, but something to get us started

    # Distribution of initial state
    Ir[1] ~ truncated(Normal(1,1), 0, Inf)
    I[1] ~ Gamma(10)
    R[1] ~ Normal(3,0.5) # A guess

    σI ~ Gamma(100) # These are all bad choices and have to be tuned with prior predictive checks
    σIr ~ Gamma(50)
    σR ~ truncated(Normal(0,0.03), 1e-6, Inf) # Random walk for R

    if !isfinite(σI) || !isfinite(σIr) || !isfinite(σR) # This does not solve the problem
        @logpdf() = -Inf
        return @namedtuple(I,Ir,R,σI, σIr, σR)
    end
    for k = 2:N
        I[k] ~ Normal(R[k] * sum(p[i]*I[k-i] for i = 1:min(np,k-1)), σI) # double check expression 1:min(np,k-1)
        Ir[k] ~ Normal(sum(q[i]*I[k-i] for i = 1:nq), σIr)
        R[k] ~ Normal(R[k-1], σR)
    end
    @namedtuple(I,Ir,R,σI, σIr, σR) # These parameters will be saved
end;

fake_Ir_data = round.(Int, exp.(0.2 .* (1:30)))
p = rand(Dirichlet(4, 1)) # A random vector that sums to 1
m = model(fake_Ir_data, p)
@time chain = sample(m, HMC(0.03,10), 100)
```

**Comment by devmotion** [comment]
Regardless of the issue, are you sure you want to initialize a new `Ir` in
```julia
    I,Ir,R = ntuple(i->Vector{T}(undef, N), 3)
```
although you provide `Ir` as argument to your model?

**Comment by xukai92** [comment]
> I tried adding early termination if any sampled variance parameter is nonfinite and that gets rid of the exception.

While you also comment "if !isfinite(σI) || !isfinite(σIr) || !isfinite(σR) # This does not solve the problem". Can you clarify if the early termination solved the problem or not?

**Comment by devmotion** [comment]
Have you tried using
```julia
    if !(σI > 0 && σIr > 0 && σR > 0)
```
instead of `!isfinite`?

**Comment by devmotion** [comment]
```julia
        I[k] ~ Normal(R[k] * sum(p[i]*I[k-i] for i = 1:min(np,k-1)), σI) # double check expression 1:min(np,k-1)
```
looks incorrect. You use `R[k]` before you have sampled a value for it.

**Comment by baggepinnen** [comment]
It appears that the order of sampling of `R` was the problem. Somehow I thought the order doesn't matter (maybe it's Soss that automatically takes care of this). 

Thanks for all your comments and help, we can consider this issue closed.

**Comment by devmotion** [comment]
Additionally, coming back to my first comment about redefining `Ir`: every provided argument is considered to be an observation. However, since you redefine `Ir` I guess that's not intended?

**Comment by baggepinnen** [comment]
No, the redefinition of `Ir` was an oversight
