### ISSUE TITLE
Register a new release?

### ISSUE THREAD

**Issue by DilumAluthge** [TuringLang/Turing.jl#1223]
The latest registered release of Turing is 0.10.1.

However, this does not include recent PRs, specifically https://github.com/TuringLang/Turing.jl/pull/1202.

Would it be possible to register a new release of Turing?

**Comment by cpfiffer** [comment]
Anyone have a reason not to release 0.10.2? As far as I can tell there's no breaking changes.

**Comment by devmotion** [comment]
https://github.com/TuringLang/Turing.jl/commit/d5c47f186bdc85b3a5c413d3efb0e6d6eda7e11f is breaking.

**Comment by mohamed82008** [comment]
We can re-introduce `VecBinomialLogit` temporarily.

**Comment by mohamed82008** [comment]
But deprecate and ask the user to use `arraydist` instead.

**Comment by yebai** [comment]
> We can re-introduce VecBinomialLogit temporarily.

I don't think this is used anywhere, but happy to add a deprecation warning to avoid surprises.

**Comment by devmotion** [comment]
We could just release `0.11`, couldn't we?

**Comment by cpfiffer** [comment]
No, because the highest minor/patch version should have deprecations for missing functions.

Honestly, we should release a 0.10.2 and consider going to 1.0 right afterwards so we can adhere to semver a little better.

**Comment by devmotion** [comment]
> But deprecate and ask the user to use arraydist instead.

`filldist` would be a more correct replacement for VecBinomialLogit (the parameter was the same for all components IIRC). And as @cpfiffer writes, deprecations are not useful here but I don't see why we would need to add any deprecations at all? 0.11 is supposed to be breaking, so it's fine to break things.

**Comment by cpfiffer** [comment]
The deprecations are to warn people who may be stuck in 0.10 that a method they use will go away in the next minor release -- breaking changes doesn't mean no deprecation warnings.

**Comment by devmotion** [comment]
As far as I understood semver (in particular https://semver.org/#spec-item-4), prior to 1.0.0 everything is allowed to break at any time and their is no stable public API. The common consensus in the Julia community, AFAIK, is just that breaking changes prior to 1.0.0 demand a new minor release. Since their is no stable public API prior to 1.0.0 according to semver, there's no need to deprecate anything it seems?

**Comment by devmotion** [comment]
Additionally, due to the way Pkg handles versions < 1.0.0 no package that depends on Turing with proper upper bounded compatibilities will get 0.11 automatically but it must manually declare that the breaking changes due not affect it (or include some bugfixes).

**Comment by cpfiffer** [comment]
Fair enough -- I'm fine with a 0.11.0 release.

**Comment by cpfiffer** [comment]
Am I good to proceed here?

**Comment by yebai** [comment]
Sounds good to me!

**Comment by cpfiffer** [comment]
Release 0.11.0 is tagged [here](https://github.com/TuringLang/Turing.jl/commit/fd66d2b0b8e8a27aa00d366a7dc10746979dcf6f). Thanks @DilumAluthge!
