### ISSUE TITLE
Make it easier to choose resampling method and threshold when using `SMC()`

### ISSUE THREAD

**Issue by awellis** [TuringLang/Turing.jl#1226]
Currently, changing the resampling method and threshold when using `SMC()` isn't very straightforward - it's necessary to write something like this:
```
SMC(Turing.Core.ResampleWithESSThreshold(Turing.Inference.resample_systematic, 0.7))
```

Could this be made easier to use?

**Comment by devmotion** [comment]
With https://github.com/TuringLang/Turing.jl/pull/1228 it is now possible (on Turing master) to use
```julia
SMC(0.7)
```
or
```julia
SMC(resample_systematic, 0.7)
```
instead. I hope this helps!
