### ISSUE TITLE
Data leakage in Bayesian logistic regression example

### ISSUE THREAD

**Issue by SebastianCallh** [TuringLang/Turing.jl#1235]
In the end of the [Data Cleaning & Set Up](https://turing.ml/dev/tutorials/2-logisticregression/#data-cleaning--set-up) section the entire data set is used to estimate mu and sigma when standardizing the `Balance` and `Income` features, which introduces a small data leakage.

To avoid this we should partition the data _beforehand_, and estimate the parameters only on the training part.

**Comment by trappmartin** [comment]
Thanks, could you please open a PR for this?

**Comment by SebastianCallh** [comment]
Absolutely! The readme in the docs folder tells me to look in the src folder, but the [src/tutorial folder](https://github.com/TuringLang/Turing.jl/tree/master/docs/src/tutorials) seems to only contain an index md file. i was expecting to find md files with the different tutorial pages in there, but perhaps you can point me to where they are?

**Comment by devmotion** [comment]
They're in a separate repository: https://github.com/TuringLang/TuringTutorials

**Comment by SebastianCallh** [comment]
I was unaware of the separate repo. Thank you! 
Should I close this issue and re-open over there? Perhaps an easy fix to avoid future confusion could be to update the docs readme to refer to that repo.

**Comment by devmotion** [comment]
The [markdown file that you mentioned](https://github.com/TuringLang/Turing.jl/blob/master/docs/src/tutorials/index.md) and the [tutorial webpage](https://turing.ml/dev/tutorials/) (which is generated from this markdown file) link to the separate repository. But it seems it might be helpful to also add this information to the README. If you have any suggestions, feel free to open a PR!
