### ISSUE TITLE
Request help for a customize distribution

### ISSUE THREAD

**Issue by JackRab** [TuringLang/Turing.jl#1244]
Thanks for writing this package. I am trying to implement a quite complicated model by customizing a distribution. A mini version of my model would look like the following
```Julia
import Distributions
using Turing

# define a struct for the distribution
struct RdExp{T} <: ContinuousUnivariateDistribution
    "the autoregressive coefficient of Markov process"
    ρ_z::T
    "standard error of μ"
    σ_μ::T
    "the mean of fixed and sunk cost"
    γᴵ::T
    γᴰ::T
end
function Distributions.logpdf(θ::T, data::RdExpData) where {T<:RdExp}
    return LogLikelihood(data, θ) # calculation of likelihood involving a quite complex process
end

# fake rand to get inintial values
function Distributions._rand!(rng::AbstractRNG, d::RdExp)
    d.ρ_z=.76 + rand(rng)
    d.σ_μ=0.8105842459701871 + rand(rng)
    d.γᴵ=70.0 + rand(rng)
    d.γᴰ=380.0 + rand(rng)
end

Distributions.minimum(d::RdExp) = -Inf
Distributions.maximum(d::RdExp) = +Inf

@model rdexp_model(data) = begin
        # priors
        ρ_z ~ Uniform(0, 1)
        σ_μ ~ InverseGamma(1, 1)
        γᴵ  ~ Uniform(1, 10000)
        γᴰ ~ Uniform(1, 10000)

        if !(σ_μ > 0 && γᴵ >0 && γᴰ > 0) # without this a will get error for Normal and Exponential distribution
            #@logpdf() = -Inf # this is commentted out since I don't know how to writing this with my specif logpdf
            return
        end

        # observations
        data ~ RdExp(ρ_z, σ_μ, γᴵ, γᴰ)
    end

chain = sample(rdexp_model(rdexp_data), HMC(0.05, 2), 100,
                   init_theta=[0.76, 0.81058, 70.0, 380.0])
```

I implemented this as I have received some guidance from a few places: [Julia discourse by Kai Xu](https://discourse.julialang.org/t/mcmc-landscape/25654/22?u=jack_rabbit), [Turing manual advanced usage](https://turing.ml/dev/docs/using-turing/advanced), [an example here by itsdfish](https://github.com/itsdfish/Miscellaneous/blob/master/examples/LNR/LNR.jl), [How to pass initial state in HMC](https://github.com/TuringLang/Turing.jl/issues/571#issuecomment-541064626).
My problem is that my model never moves as I receive the following warnings continuously
```Julia
┌ Warning: The current proposal will be rejected due to numerical error(s).
│   isfinite.((θ, r, ℓπ, ℓκ)) = (false, false, false, false)
└ @ AdvancedHMC ~/.julia/packages/AdvancedHMC/jxDha/src/hamiltonian.jl:47
┌ Warning: The current proposal will be rejected due to numerical error(s).
│   isfinite.((θ, r, ℓπ, ℓκ)) = (true, true, false, true)
```
Could anyone give me some guidance on what my customization of distribution may be problematic? And how can I debug the model to find out the real issue? Any help/comments are greatly appreciated. Thanks in advance.

**Comment by mohamed82008** [comment]
`rdexp_data` is not defined. I can't run the above.

**Comment by torfjelde** [comment]
This is quite difficult to debug without knowing `LogLikelihood` :confused:

**Comment by JackRab** [comment]
> This is quite difficult to debug without knowing `LogLikelihood` 😕

Yes, I agree, unfortunate the calculation of likelihood is quite complex so I mainly intended to see if there are some problems with how I defined the customized distribution. I will close it for now and come back if I could abstract my likelihood calculation. Thanks to both of you.
