### ISSUE TITLE
The Bayes loss is higher than the OLS loss.

### ISSUE THREAD

**Issue by npschafer** [TuringLang/Turing.jl#1274]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/5_LinearRegression.md

At the bottom of this page it says that the Bayes predictor predicts better out of sample, but the Bayes loss is shown to be higher than the OLS loss.

**Comment by cpfiffer** [comment]
I fixed this upstream at [TuringTutorials.jl](https://github.com/TuringLang/TuringTutorials) and added a little update. It should show up on the site next time it is built, typically in a day or two.

Thanks for the issue!
