### ISSUE TITLE
Question: Mistakes in Custom Distribution documentation? 

### ISSUE THREAD

**Issue by marty0801** [TuringLang/Turing.jl#1287]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_docs/using-turing/advanced.md

I'm concerned about mistakes in the CustomUniform example. Should `Flat` be replaced by `CustomUniform` in the below? 
```
Distributions.rand(rng::AbstractRNG, d::Flat) = rand(rng) # sample in [0, 1]
Distributions.logpdf(d::Flat, x::Real) = zero(x)          # p(x) = 1 → logp(x) = 0
```
 Also, it is unclear how/whether the "rand", and "logpdf" functions mentioned under "3. Define Helper Functions" is related to the functions defined just before.

**Comment by torfjelde** [comment]
> I'm concerned about mistakes in the CustomUniform example. Should Flat be replaced by CustomUniform in the below?

Yes it should:)

> Also, it is unclear how/whether the "rand", and "logpdf" functions mentioned under "3. Define Helper Functions" is related to the functions defined just before.

Yeah that's a typo; `rand` and `logpdf` shouldn't be mentioned in section 3. Also, should probably make it clear that Turing.jl will perform the transformation internally when necessary using the defined `bijector`?

**Comment by marty0801** [comment]
Thanks!
