### ISSUE TITLE
Package conflict on LogisticRegression tutorial

### ISSUE THREAD

**Issue by arolihas** [TuringLang/Turing.jl#1291]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/2_LogisticRegression.md

When I try to follow along on this guide in my own notebook, there are some package management issues. When loading the RDataset, there is an identifier not found error, which was resolved by using the RData#master package as recommended [here](https://discourse.julialang.org/t/rdata-undefvarerror-identifier-not-defined/39276). 

I can download the dataset now, but the MLDataUtils package is now incompatible. When I try to add it, I get this error due to some conflict with required versions of DataFrames packages:
````ERROR: Unsatisfiable requirements detected for package MLDataUtils [cc2ba9b6]:
 MLDataUtils [cc2ba9b6] log:

 ├─possible versions are: [0.4.0, 0.5.0-0.5.1] or uninstalled

 ├─restricted to versions * by an explicit requirement, leaving only versions [0.4.0, 0.5.0-0.5.1]

 └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: uninstalled — no versions left

   └─DataFrames [a93c6f00] log:

     ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.1] or uninstalled

     └─restricted to versions 0.21 by RData [df47a6cb], leaving only versions 0.21.0-0.21.1

       └─RData [df47a6cb] log:

         ├─possible versions are: 0.7.2 or uninstalled

         └─RData [df47a6cb] is fixed to version 0.7.2
````

**Comment by cpfiffer** [comment]
I hate to say it, but this is not a Turing issue. MLDataUtils is not compatible with DataFrame 0.21 -- there is an issue to fix this (https://github.com/JuliaML/MLDataUtils.jl/pull/56) but it seems to have stalled. 

If you just want to get on with your life, try running the previous version of DataFrames by using `] add DataFrames@0.20` and seeing if that works.

**Comment by arolihas** [comment]
It won't work because Rdata is restricted to DataFrames@0.21. I was just reporting an issue with the Turing tutorial on the official documentation and guides. I clicked on the link and it brought me here.

**Comment by arolihas** [comment]
I submitted this issue to the TuringTutorial repository
