### ISSUE TITLE
Tutorial "Bayesian Hidden Markov Models" was not reproducible

### ISSUE THREAD

**Issue by SosUts** [TuringLang/Turing.jl#1302]
I walked through the [Bayesian Hidden Markov Models](https://turing.ml/dev/tutorials/4-bayeshmm/) tutorial and noticed that the result was not reproducible.
The result are also not good.

Is this due to a difference of other packages version?
(I've copied and pasted the the tutorial, so I won't attach the code.)

![anim_fps15](https://user-images.githubusercontent.com/46147087/83326560-ea2cc300-a2af-11ea-9176-2786790a2590.gif)

Julia v1.3.1
Turing v0.10.1

**Comment by devmotion** [comment]
That's a quite old version of Turing. Have you tried it with Turing 0.13 as well?

**Comment by SosUts** [comment]
I updated to 0.13 but the result didn't improve so much...

I also noticed that the sample number in tutorial's gif animation is different from the code.
There should be only 100 samples but the gif is sampling 500 samples.

```Julia
g = Gibbs(HMC(0.001, 7, :m, :T), PG(20, :s))
c = sample(BayesHmm(y, 3), g, 100);
# changing the sample number to 500 didn't improve the result as well.

# Extract our m and s parameters from the chain.
m_set = c[:m].value.data
s_set = c[:s].value.data

# Iterate through the MCMC samples.
Ns = 1:length(c) # there're only 100 samples

# Make an animation.
animation = @animate for i in Ns
    m = m_set[i, :]; 
    s = Int.(s_set[i,:]);
    emissions = collect(skipmissing(m[s]))
    
    p = plot(y, c = :red,
        size = (500, 250),
        xlabel = "Time",
        ylabel = "State",
        legend = :topright, label = "True data",
        xlim = (0,15),
        ylim = (-1,5));
    plot!(emissions, color = :blue, label = "Sample $$N")
end every 10;
```
![50612436-de588980-0e8e-11e9-8635-4e3e97c0d7f9](https://user-images.githubusercontent.com/46147087/83333840-9638d300-a2dd-11ea-8ec3-ccdd2fc9f34c.gif)

**Comment by xukai92** [comment]
I looks like an initialisation issue related to that seed. Below is the gif produced by `Random.seed!(12345678)` and a longer chain `sample(BayesHmm(y, 3), g, 500)`.

![tmp](https://user-images.githubusercontent.com/5985769/84907251-e0c29980-b0aa-11ea-9ca4-c3d1e662b66d.gif)

**Comment by SosUts** [comment]
Wow, I didn't expect that seed value would make such a big difference...

Thank you so much for letting me know!
I learnt something new.

**Comment by xukai92** [comment]
I mean it's fixed seed, so if it's too bad, it could be hard to give sensible results for a short chain (500 here). What I did is increasing the chain length to 500, run the sample call a few times and I found some of the runs are good. Then I realized this is probably an initialization problem. I ended up trying a few seed that works and reproducible.
