### ISSUE TITLE
Typo in Infinite Mixture Models tutorial (number of clusters formula)

### ISSUE THREAD

**Issue by luiarthur** [TuringLang/Turing.jl#1304]
I spotted this typo in the docs: https://turing.ml/dev/tutorials/6-infinitemixturemodel/

Here's the snippet:

> ![image](https://user-images.githubusercontent.com/5297817/83434236-ece20200-a3ee-11ea-8451-e3d1e92eb97c.png)

1. The **minus** should be a **plus** in the equation.
2. I believe the (corrected) approximation is "good" only when N, alpha >> 0

If this looks alright, I'd be happy to make the changes and submit a PR.

**Comment by trappmartin** [comment]
1. Yes, that was a typo. Should be a plus. :)
2. Yes, alpha should anyways be defined to be positive.

**Comment by luiarthur** [comment]
Cool. Is this the file I need to edit?

https://github.com/TuringLang/TuringTutorials/blob/master/6_InfiniteMixtureModel.ipynb

Just noticed this is a different repo...

**Comment by trappmartin** [comment]
Yes, that's the one. The documentation page will be build based on those jupyter notebooks. It's a way to keep the core repo slick and free of clutter.

**Comment by luiarthur** [comment]
Submitted a fix here:

https://github.com/TuringLang/TuringTutorials/pull/78
