### ISSUE TITLE
Documentation build CI is failing 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#1319]
See https://github.com/TuringLang/Turing.jl/runs/754677748

**Comment by cpfiffer** [comment]
Woops, there was a missing quote in the table of contents file. I fixed it with 28aa8a184aad82eeb2ec2e7deb9086956e0d9763.

**Comment by cpfiffer** [comment]
Seems to be building the docs on my machine, let's see if it works on Travis.

**Comment by devmotion** [comment]
Seems to be fixed :smiley:
