### ISSUE TITLE
Enable Prior for Gibbs compositional sampling

### ISSUE THREAD

**Issue by MFairley** [TuringLang/Turing.jl#1321]
As per this discussion, https://discourse.julialang.org/t/turing-jl-fix-some-parameters-to-prior-distribution/41095/11, I would like to be able force some parameters to remain at their prior distribution and only perform inference on a subset of parameters. Could this be achieved by enabling `Prior` Gibbs for compositional sampling? For example to do inference on `a` but not on `b`:

```
chn = sample(model, Gibbs(NUTS(-1, 0.65, :a), Prior(:b)), 1000)
```

**Comment by devmotion** [comment]
Hmm, I'm still curious why you would want to do that. To me it seems, if you specify a model of your observations and if they are not completely independent of `b`, then you will always learn something about `b` from your data and hence there's no reason to work with the prior. If the data is completely independent of `b`, then you could remove `b` from the model in the first place. And if you're just not interested in `b` in your downstream computations, you could just discard the samples of `b` and only work with the samples of `a`.

That being said, you can already achieve this by writing something like
```julia
@model function model(x)
    ...
	b = rand(Uniform()) # or just b = rand() in this special case
	Turing.acclogp!(_varinfo, logpdf(Uniform(), b))
	...
end
```
Turing only handles tilde assignments (i.e., statements of the form `x ~ RHS`) in a special way, so it won't interfere with the sampling of `b`.

**Comment by ElOceanografo** [comment]
I came across this issue looking for a way to do the exact same thing. In my case, it would basically be a hack for sampling efficiency: I have a model with the basic form `y ~ A * x`, where `y` is a vector of observations, `x` is a vector of unobserved variables, and `A` is a matrix of basis functions that are known beforehand, +/- some margin of error.  I want to do inference about `x` while accounting for uncertainty in `A`.  In my problem, `y` has ~500 elements and `x` has 2-5.  

While it's true that if I treat `A` as a parameter in the model I'll always learn *something* about it, in practice, the data reveal (approximately) nothing about `A` --its posterior is indistinguishable from its prior--but the sampler spends >99% of its time doing HMC integration on `A`.  If I could use a Gibbs sampler with `NUTS()` for `x` and `Prior()` for `A`, it would speed up my model ~100x without losing any information I care about.   Maybe a non-standard, technically-incorrect approach, but it would be extremely useful for me in this case.

**Comment by yebai** [comment]
We now have a `Prior()` sampler.

**Comment by ElOceanografo** [comment]
This just came up again [on Discourse](https://discourse.julialang.org/t/fixed-distribution-in-turing/103540/2), and it looks like the `Prior()` sampler does not work in Gibbs sampling. For instance, taking the example from the documentation [here ](https://turing.ml/v0.22/docs/library/#Turing.Inference.Gibbs) and changing `PG(20, :v2)` to `Prior(:v2)` gives a `MethodError: no method matching Prior(::Symbol)`. Would that capability be difficult to add?

**Comment by ElOceanografo** [comment]
My comment above (Feb  10 2021) explains why I would find this useful (the discourse discussions provide some others). I would find sampling from the prior for `A` useful when:
* `A` is high-dimensional and therefore expensive to sample from using HMC,
* I have a decent prior estimate for it, and 
* The data are not very informative with respect to `A`.
You could think of it as a way to combine MCMC with a parametric bootstrap, i.e. it would be a lot easier to do this:
```julia
mod = my_model(some_data)
chn = sample(mod, Gibbs(HMC(0.2, 3, :x), Prior(:A)), 1000)
```
instead of this:
```julia
chns = map(1:1000) do _
    A = rand(HighDimensionalDistribution())
    mod = my_parameterized_model(some_data, A)
    sample(mod, HMC(0.2, 3), 1000)
end
# concatenate chns etc....
```
