### ISSUE TITLE
Bayesian neural network using VI tutorial does not solve the problem

### ISSUE THREAD

**Issue by DoktorMike** [TuringLang/Turing.jl#1326]
In https://turing.ml/dev/tutorials/3-bayesnn/ where you use ADVI to fit the parameters of the network the resulting posterior doesn't seem to correctly solve the problem. VI should have no problem solving this particular problem so maybe it's sensitive to the initialization or the optimizer doesn't get enough time to converge. 

The plot showing the issue is given below which is copied from the tutorial.

![image](https://user-images.githubusercontent.com/4715779/84645178-7bcb4000-af00-11ea-942e-9e5f7a48bfa7.png)

**Comment by torfjelde** [comment]
Yeah, it's probably the number of steps. Remember running this experiment locally and it took a bit to converge. Don't know why we set it to only 1000 in this case :confused: Thanks @DoktorMike !
