### ISSUE TITLE
type Wishart has no field c0 error

### ISSUE THREAD

**Issue by wupeifan** [TuringLang/Turing.jl#1336]
`] test Turing` yields the following error:

``` Julia
matrix support: Error During Test at C:\******\.julia\packages\Turing\GMBTf\test\test_utils\staging.jl:42
  Got exception outside of a @test
  type Wishart has no field c0
```
I think this is a known issue -- the current Distribution library changed its Wishart (and probably also InverseWishart) fields from previous versions.

**Comment by devmotion** [comment]
The issue is already fixed in the master branch of Turing. If you run `] add Turing#master` first the error should be resolved.
