### ISSUE TITLE
Adding an implementation of the EM Algorithm to Turing for fitting latent variable models or mixture models

### ISSUE THREAD

**Issue by 00krishna** [TuringLang/Turing.jl#1340]
Hello, after talking to @trappmartin on Slack, he suggested I open an issue. The request is to add an implementation of the EM (Expectation-Maximization) algorithm to Turing. The EM Algorithm is used to estimate latent variable models, mixture models, and other statistical models. 

The [GaussianMixtures](https://github.com/davidavdav/GaussianMixtures.jl) package does seem to have a nice implementation of the EM algorithm. Perhaps the Turing developers could just create a wrapper around that package to keep the interface to the EM algorithm consistent with the Turing API.

**Comment by yebai** [comment]
Probably better to create a new EM package that supports Turing.
