### ISSUE TITLE
Trigger benchmarking with Bors commands

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#1341]
Turing's benchmarking is not used often at the moment. I think part of the reason is that the benchmarking process is a bit complicated, even with Nanosoldiers. Would it make sense to try to 

- trigger benchmarking for PRs using bors bot, with a customised command (see below)
- replace Nanosoldier with [`PkgBenchmark` ](https://github.com/JuliaCI/PkgBenchmark.jl), which is designed specifically for track performance changes of Julia packages.

Ps: some references: 

- `bors try` [arguments](https://bors.tech/devdocs/bors-ng/BorsNG.Command.html): these arguments are stored as commit message, and can be extracted by the benchmarking script.
- perhaps: `bors try --benchmarking`?

**Comment by devmotion** [comment]
Maybe https://github.com/tkf/BenchmarkCI.jl could be useful. The trigger of the Github action could be adjusted to whatever we think would be suitable.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/DynamicPPL.jl/pull/346
