### ISSUE TITLE
Importing AdvancedSMCExtensions algorithms

### ISSUE THREAD

**Issue by dominikstrb** [TuringLang/Turing.jl#1354]
Hi everyone,

I was wondering why the algorithms from `src/contrib/inference/AdvancedSMCExtensions.jl` are currently not accessible from Turing's API. Are they accessible from any other package?

Thanks!

**Comment by cpfiffer** [comment]
No, these currently aren't available -- we made some internal changes a while ago and haven't gone back to update the code in that file. I believe they should _eventually_ go into [AdvancedPS.jl](https://github.com/TuringLang/AdvancedPS.jl).
