### ISSUE TITLE
log: DomainError with -960.1841700397322

### ISSUE THREAD

**Issue by krishvishal** [TuringLang/Turing.jl#1374]
Running the code results in the following error
```
using Turing, ReverseDiff, Memoization
Turing.setadbackend(:reversediff)
Turing.setrdcache(true)

y1 = rand(10)
A1 = rand(10, 10)

function logsumexp(mat) 
    max_ = maximum(mat, dims=1)
    exp_mat = exp.(mat .- max_) .- (mat .== max_)
    sum_exp_ = sum(exp_mat, dims=1)
    res = log1p.(sum_exp_) .+ max_
end

@model function mwe(y, A, ::Type{T} = Vector{Float64}) where {T}
    n,m = size(A)
    scale = rand(10)
    vec_raw = T(undef, n)
    for i in eachindex(vec_raw)
        vec_raw[i] ~ truncated(Laplace(0, 1), ((10-30)./scale[i]), ((100-30)./scale[i]))
    end
    vec = vec_raw .* scale .+ 30
    μ = logsumexp(A .- vec_raw)[1,:]
    y .~ Normal.(μ, 1)
    return vec
end

model = mwe(y1, A1);
chain = sample(model, NUTS(.65), 300);
```

Error: 

```
DomainError with -9.892202109140928:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).
```

Full Stacktrace: https://pastebin.com/GzfY3Qfu

If I change

`vec_raw[i] ~ truncated(Laplace(0, 1), ((10-30)./scale[i]), ((100-30)./scale[i]))`

to

`vec_raw[i] ~ truncated(Laplace(0, 1), 5,  6) # any number for bounds are fine`

the model starts sampling but, this is not how I want to paremeterize the model.

The sampling starts if I make the change `scale = ones(10) * any integer`. The error resumes if I change to `scale = rand(10:15, 10)`.

What's the problem here? Is there a way to fix this?

**Comment by mohamed82008** [comment]
I responded in the discourse thread.

**Comment by mohamed82008** [comment]
As a rule, always start without caching then consider turning it on if you are sure that there are no branches in your code and double check that the results are the same for some toy runs.

**Comment by devmotion** [comment]
Your implementation of `logsumexp` looks a bit strange to me. Can you check if the error persists with
```julia
function logsumexp(mat)
    maxima = maximum(mat, dims=1)
    exp_mat = exp.(mat .- maxima)
    sum_exp_mat = sum(exp_mat, dims=1)
    return maxima .+ log.(sum_exp_mat)
end
```
?
Maybe you could also just use `StatsFuns.logsumexp` (not sure how well it works with AD though).

**Comment by krishvishal** [comment]
@devmotion  the error persists with the `logsumexp` you have provided. The implementation of `logsumexp` I'm using is even more numerically stable. https://discourse.julialang.org/t/fast-logsumexp/22827/9 

@mohamed82008 Thank you. Would disabling caching slow down sampling?

**Comment by devmotion** [comment]
Your implementation is different from the vector version in that it will yield incorrect results if the maxima are not uniquely attained.

**Comment by krishvishal** [comment]
@devmotion I didn't understand. Can you provide an example, I want to fix this function.

**Comment by mohamed82008** [comment]
>Can you explain a bit more on what do branches in code mean? Would disabling caching slow down sampling?

Branches mean if statements and loops that run for a different number of iterations based on a condition. There could be no if statements in the model body but a function inside can be using one. So it's always best to check the results are identical when turning on caching and using the same seed. Disabling caching slows down sampling yes.

**Comment by devmotion** [comment]
> I tested both function with an array with no unique maxima but the answers turned out to be equivalent.

You chose an unfortunate scaling in your example. The following example illustrates that they are not equivalent and your implementation yields incorrect values in such a case:
```julia
julia> a = ones(10, 1);

julia> log.(sum(exp.(a); dims = 1))
1×1 Array{Float64,2}:
 3.3025850929940455

julia> logsumexp(a)
1×1 Array{Float64,2}:
 1.0

julia> logsumexp1(a)
1×1 Array{Float64,2}:
 3.302585092994046
```

**Comment by devmotion** [comment]
BTW did you make sure to start a fresh Julia session when testing the alternative `logsumexp` implementation? I'm wondering if you accidentally used a cached version of the old implementation.

**Comment by krishvishal** [comment]
I've used the cached version, my bad. 

In your opinion, is the version of `logsumexp` I'm using really necessary to be used in Turing? Does it give more accuracy in calculations than the `logsumexp1`? Will it be a significant hit in accuracy if I used `logsumexp1`? I feel the cases covered by `logsumexp` are very corner.

**Comment by devmotion** [comment]
I'm sorry, I just don't understand what you mean. I'm just pointing out that there are issues with your implementation of `logsumexp` - it is just plain wrong mathematically in certain cases, so instead of any potential (I doubt it matters in your example) increased numerical stability you'll get completely incorrect results.

Apart from that I think you should implement your model differently. I'm not sure what your mathematical model is - do you want `scale` to have a uniform distribution on the unit interval as prior distribution? There is also a mismatch between the number of scale parameters (10) and the number of indices `i` (`n`) - I assume it should be `n` as well? Moreover, it should be written as `scale ~ filldist(Uniform(), n)` instead of `scale = rand(10)` - otherwise Turing won't use the correct random number generators and not save the `scale` parameters correctly. In the definition of the scaled and truncated Laplace distributions you could just write
```julia
vec_raw[i] ~ truncated(Laplace(), -20 / scale[i], 70 / scale[i])
```
or replace the initialization of `vec_raw` and the for loop with
```julia
vec_raw ~ arraydist(@. truncated(Laplace(), -20 / scale, 70 / scale)
```
(then you can also remove `T`). Finally you could also write `μ = vec(logsumexp(A .- vec_raw))` instead of creating a new array.

**Comment by xukai92** [comment]
@mohamed82008 Is this related to issue in which the support of the distribution cannot be varied.

**Comment by krishvishal** [comment]
@devmotion 

>I'm sorry, I just don't understand what you mean

I completely agree with you on the mathematical incorretness of `logsumexp`. I should have said the logsumexp function for vectors described in the discourse thread I've posted instead of `logsumexp`. I wanted to know if I use accurately converted matrix version of that function, will I get any significant numerical accuracy. Does it matter? If it's not the case then, I can go back to using the version you have posted. I see that you said it might not be worth using it for my case. 

> do you want scale to have a uniform distribution on the unit interval as prior distribution? There is also a mismatch between the number of scale parameters (10) and the number of indices i (n) - I assume it should be n as well?

The model I'm using is more complex, but I narrowed down the cause of the error to the `vec_raw[i] ~ .... ` line. So I posted whatever model definition I was using during that process as an mwe. Removing caching solved the issue for me. 

>vec_raw ~ arraydist(@. truncated(Laplace(), -20 / scale, 70 / scale)

Thank you for this suggestion. So if I use `vec_raw = T(undef, n)`, will this create and destroy memory every time the model function is called? I'm guessing it would, I just want to know if it's really the case.

**Comment by mohamed82008** [comment]
>@mohamed82008 Is this related to issue in which the support of the distribution cannot be varied.

Yes! I totally missed this. @krishvishal check the discussion in https://github.com/TuringLang/Turing.jl/issues/1270. It should help you fix your model.

**Comment by devmotion** [comment]
> Thank you for this suggestion. So if I use vec_raw = T(undef, n), will this create and destroy memory every time the model function is called? I'm guessing it would, I just want to know if it's really the case.

Yes, it will but also the alternative will allocate memory for `vec_raw` and the array of truncated distributions. It just removes the need for preallocating `vec_raw` and the type parameter `T`. It could (untested) be a bit more efficient since the cache of random variables and thenlog probability are updated only once instead of in every step in the for loop.

**Comment by krishvishal** [comment]
> Yes! I totally missed this. @krishvishal check the discussion in #1270. It should help you fix your model.

@mohamed82008 can you tell me how to pass scale into `MyDistribution`?

**Comment by mohamed82008** [comment]
@krishvishal you will need to sample both `scale` and `vec_raw` simultaneously. Try the following. I haven't tested it.

```julia
using Distributions, Bijectors

struct MyDistribution <: ContinuousMultivariateDistribution
    n::Int
end

function Base.rand(d::MyDistribution, scale::AbstractVector)
    scale = rand(d.n)
    vec_raw = zeros(d.n)
    for i in 1:d.n
        vec_raw[i] = rand(truncated(Laplace(0,1), ((-20) ./ scale[i]), ((70) ./ scale[i])))
    end
    return [scale; vec_raw]
end

function Distributions.logpdf(d::MyDistribution, scale_vec_raw::AbstractVector)
    scale = scale_vec_raw[1:d.n]
    l = sum.(logpdf(Normal(), scale))
    vec_raw = scale_vec_raw[d.n+1:2*d.n]
    for i in 1:d.n
        l += logpdf(truncated(Laplace(0,1), ((20) ./ scale[i]), ((70) ./ scale[i])), vec_raw[i])
    end
    return l
end

struct MyBijector <: Bijectors.Bijector{1} 
    n::Int
end
function (b::MyBijector)(x::AbstractVector)
    scale = x[1:b.n]
    vec_raw = x[b.n+1:2*b.n]
    y = similar(vec_raw)
    for i in 1:length(scale)
        y[i] = bijector(truncated(Laplace(0,1), ((-20) ./ scale[i]), ((70) ./ scale[i])))(vec_raw[i])
    end
    return [scale; y]
end

function (ib::Inverse{<:MyBijector})(y::AbstractVector)
    scale = y[1:ib.orig.n]
    y_vec_raw = y[ib.orig.n+1:2*ib.orig.n]
    x = similar(y_vec_raw)
    for i in 1:length(scale)
        x[i] = inv(bijector(truncated(Laplace(0,1), ((-20) ./ scale[i]), ((70) ./ scale[i]))))(y_vec_raw[i])
    end
    return [scale; x]
end

function Bijectors.logabsdetjac(b::MyBijector, x::AbstractVector)
    l = float(zero(eltype(x)))
    scale = x[1:b.n]
    vec_raw = x[b.n+1:2*b.n]
    for i in 1:length(scale)
        l += logabsdetjac(bijector(truncated(Laplace(0,1), ((-20) ./ scale[i]), ((70) ./ scale[i]))), vec_raw[i])
    end
    return l
end
Bijectors.bijector(d::MyDistribution) = MyBijector(d.n)
```

**Comment by krishvishal** [comment]
`rand(MyDistribution(5), 1)`

Error:

Same error as before.

```
MethodError: no method matching length(::MyDistribution)
Closest candidates are:
  length(::Sampleable{Multivariate,S} where S<:ValueSupport) at /home/v/.julia/packages/Distributions/dTXqn/src/common.jl:39
  length(::Sampleable) at /home/v/.julia/packages/Distributions/dTXqn/src/common.jl:37
  length(!Matched::Core.SimpleVector) at essentials.jl:596
  ...

Stacktrace:
 [1] length(::MyDistribution) at /home/v/.julia/packages/Distributions/dTXqn/src/common.jl:39
 [2] rand(::Random._GLOBAL_RNG, ::MyDistribution, ::Int64) at /home/v/.julia/packages/Distributions/dTXqn/src/multivariates.jl:70
 [3] rand(::MyDistribution, ::Int64) at /home/v/.julia/packages/Distributions/dTXqn/src/multivariates.jl:69
 [4] top-level scope at In[3]:1

```

**Comment by devmotion** [comment]
Seems you also have to define
```julia
Base.length(d::MyDistribution) = 2 * d.n
```

**Comment by devmotion** [comment]
BTW I would have assumed that you don't have to include `scale` in your distribution and bijector as long as you use `scale ~ filldist(Uniform(), n)` in your model instead of `scale = rand(n)`. The logpdf implementation of `MyDistribution` seems to be incorrect as well, it seems you shouldn't compute the loglikelihood of `scale` based on `Normal` - or actually sample it from a Normal distribution.

**Comment by krishvishal** [comment]
I've made the change. 

```
MethodError: no method matching _rand!(::Random._GLOBAL_RNG, ::MyDistribution, ::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true})
Closest candidates are:
  _rand!(::AbstractRNG, !Matched::MvLogNormal, ::Union{AbstractArray{#s156,1}, AbstractArray{#s156,2}} where #s156<:Real) at /home/v/.julia/packages/Distributions/dTXqn/src/multivariate/mvlognormal.jl:233
  _rand!(::AbstractRNG, ::Sampleable{Multivariate,S} where S<:ValueSupport, !Matched::AbstractArray{T,2} where T) at /home/v/.julia/packages/Distributions/dTXqn/src/multivariates.jl:29
  _rand!(::AbstractRNG, !Matched::Union{Distributions.DirichletCanon, Dirichlet}, ::AbstractArray{#s62,1} where #s62<:Real) at /home/v/.julia/packages/Distributions/dTXqn/src/multivariate/dirichlet.jl:187
  ...

Stacktrace:
 [1] _rand!(::Random._GLOBAL_RNG, ::MyDistribution, ::Array{Float64,2}) at /home/v/.julia/packages/Distributions/dTXqn/src/multivariates.jl:33
 [2] rand at /home/v/.julia/packages/Distributions/dTXqn/src/multivariates.jl:70 [inlined]
 [3] rand(::MyDistribution, ::Int64) at /home/v/.julia/packages/Distributions/dTXqn/src/multivariates.jl:69
 [4] top-level scope at In[2]:1
```
-------------------------------------------------------------------------------------------------------

`scale`  in my model is `filldist(Uniform(a, b), n)`.

**Comment by devmotion** [comment]
The default implementation for `rand(d::MultivariateDistribution, n::Int)` in https://github.com/JuliaStats/Distributions.jl/blob/253c3a0813e0a08bf41fdf22f83ea540cc89a4c5/src/multivariates.jl#L70-L71 uses the in-place method `Distributions._rand!`. Since you didn't define it you get an error when you call `rand(d::MyDistribution, n::Int)`. `rand(MyDistribution(5))` should work fine though, and AFAICT sampling in your model should only require the latter form.
