### ISSUE TITLE
Simple syntax error in coin example

### ISSUE THREAD

**Issue by darkflash** [TuringLang/Turing.jl#1376]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/0_Introduction.md
title = "Updated belief after $$N observations",
must be changed to:
title = "Updated belief after $N observations",

**Comment by devmotion** [comment]
This was fixed some time ago it seems (probably during the larger updates and refactorings): https://github.com/TuringLang/TuringTutorials/blob/80e843d0d7cb1e996619a6065fa351fa1716c3f5/tutorials/00-introduction/00_introduction.jmd#L105
