### ISSUE TITLE
Add instructions to check the gradient function

### ISSUE THREAD

**Issue by wupeifan** [TuringLang/Turing.jl#1383]
The users may include custom functions in a Turing `@model` environment. While Turing supports all the AD backends, the users may not have enough knowledge to know whether their codes are compatible with some AD backend they choose.
Therefore, (per slack discussion) I think it might make sense to add some instructions in the Turing documentation to suggest people checking the pushforwards or pullbacks when they have custom functions to sample with HMC/NUTS/VI/any method that requires a gradient from an AD backend.
cc @devmotion @trappmartin

**Comment by yebai** [comment]
See https://gist.github.com/torfjelde/cc5c41e97eb4c97e22a19b8440f6d506 and contained in https://github.com/TuringLang/Turing.jl/issues/1829
