### ISSUE TITLE
Generalised compositional sampling interface

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#139]
The current Gibbs sampler allows us to compose elementary sampling algorithms (e.g. PG, HMC). We may want to generalise this compositional sampling interface. One possible extension is that

```julia
g1=Gibbs(HMC(:m,:s), PG(:T)) # assume we have 3 variables in total: s, m, T
g2=Gibbs(HMC(:m), PG(:s, :T))
# Generalised compositional inference interface, we haven't implemented this yet.
g3=Gibbs(g1,g2,g2) 

sample(model, g3) 
```

**Comment by xukai92** [comment]
I think we need to update the current way of generating `group_id` to achieve this. Currently the `gid` is created inside `Gibbs` constructor, which will cause problem in this cause as 'base samplers' will have same IDs. We need somehow generate unique IDs for each sampler. Possible ways are
- use `gensym()`
- use some global counting on sampler constructors

**Comment by yebai** [comment]
Closing now since it has been implemented.
