### ISSUE TITLE
UndefVarError: AxisArrays not defined when loading saved chain with BSON

### ISSUE THREAD

**Issue by SebastianCallh** [TuringLang/Turing.jl#1394]
Saving and then trying to load a chain with either prior or posterior samples results in the error `UndefVarError: AxisArrays not defined`. It would be nice if BSON and Turing could play together as a way to cache computations. Please let me know if this issue would be better off in another repo like BSON or AxisArrays.

Reproduce with
```
using Turing
using BSON: @save, @load

@model model() = begin
    x ~ Normal(0, 1)
end

m = model()
chain = sample(m, Prior(), 10)
@save "chain.bson" chain
@load "chain.bson"
```

**Comment by devmotion** [comment]
I assume this is the same problem: https://github.com/JuliaIO/BSON.jl/issues/25 So it seems to be a known issue with BSON which tries to resolve everything in the Main namespace. It should work if you import AxisArrays explicitly before loading the chain, i.e. if you add a `using AxisArrays` before `@load ...`.

**Comment by SebastianCallh** [comment]
Indeed that seems to be the case! I suppose that makes sense. Thank you very much for the rapid response!
