### ISSUE TITLE
VI tutorial error

### ISSUE THREAD

**Issue by caxelrud** [TuringLang/Turing.jl#1416]
Using Julia 1.5.0, I get the following error at line:
```
_, sym2range = Variational.bijector(m; sym_to_ranges = Val(true));
ERROR: UndefVarError: bijector not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:26
 [2] top-level scope at REPL[39]:1
 [3] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1088

```
Any suggestions? Thanks

**Comment by devmotion** [comment]
Unfortunately, the tutorials are largely outdated since they are based on older versions of Turing and its dependencies. We, or more precisely @torfjelde currently, are working on updating them (see https://github.com/TuringLang/TuringTutorials/issues/86).
