### ISSUE TITLE
Documentation for MH sampler does not render properly

### ISSUE THREAD

**Issue by treigerm** [TuringLang/Turing.jl#1423]
On the website the documentation for the MH sampler does not render properly. See below for a screenshot of what it looks like on my machine. It seems there is possibly an extra ` somewhere. 

![Screenshot 2020-10-01 at 16 21 16](https://user-images.githubusercontent.com/17100163/94829387-607a3700-0402-11eb-8a1b-6c5f638b5c7b.png)

**Comment by cpfiffer** [comment]
Thanks for catching this!

**Comment by treigerm** [comment]
Thanks for fixing this so quickly!
