### ISSUE TITLE
Better name and return value for `turnprogress`

### ISSUE THREAD

**Issue by phipsgabler** [TuringLang/Turing.jl#1426]
[`turnprogress`](https://github.com/TuringLang/Turing.jl/blob/0d40f40b139e11ca0601b4bc1d1f773a0bf08587/src/Turing.jl#L22) currently returns the new state, but I think it would be convenient to have the old on instead.  I use this in a pattern of "switch off, do something, then restore".

```julia
const PROGRESS = Ref(true)
function turnprogress(switch::Bool)
    old_state = PROGRESS[]
    @info "[Turing]: progress logging is $(switch ? "enabled" : "disabled") globally"
    PROGRESS[] = switch
    AdvancedVI.turnprogress(switch)
    return old_state
end
```

And perhaps also change the name to `turnprogress!` and `Base.@deprecate turnprogress(s) turnprogress!(s)`?

Sorry for not making a PR myself, but I am currently in a somewhat fragile, pinned setup...

**Comment by devmotion** [comment]
I think changing the name to `turnprogress!` makes sense. Since the usual behaviour of in-place functions in Julia is to return either `nothing` or the updated variable (e.g., when modifying arrays in-place), I'm wondering if returning the old state is too surprising though.

**Comment by phipsgabler** [comment]
I can see your way of reasoning about the surprisingness, but I was actually surprised that it _didn't_ behave like that.  I thought it is a common pattern for global-state-modifying functions to return the old state, so that you can restore it later.  But maybe that's a Python thing; e.g., [`numpy.seterr`](https://numpy.org/doc/stable/reference/generated/numpy.seterr.html).

**Comment by torfjelde** [comment]
I'd also add that  `turnprogress` is really not an intuitive name, IMO. Something like `setprogress!` seems more intuitive.

**Comment by devmotion** [comment]
I like `setprogress!`, `turnprogress` sounds like a switch although the function is just setting `PROGRESS[]` to the specified value.

**Comment by torfjelde** [comment]
> I like setprogress!, turnprogress sounds like a switch although the function is just setting PROGRESS[] to the specified value.

Exactly :+1:

**Comment by devmotion** [comment]
Actually, I think we should maybe just remove `turnprogress` and the constant `PROGRESS` completely and just specify `progress = true` as the default keyword argument to `sample` in Turing. I am not a big fan of global states, and I am not sure if it provides any advantage over just specifying the keyword argument if desired. In particular, since `turnprogress` (or whatever alternative) also implicitly changes the progress logging behaviour of AdvancedVI (and possibly other downstream packages in the future) which is not completely transparent.

**Comment by devmotion** [comment]
Is this issue resolved by https://github.com/TuringLang/Turing.jl/pull/1427? Or should we add another `switchprogress` function that performs the way @phipsgabler initially suggested?

**Comment by torfjelde** [comment]
I'm fine with current solution :+1:

**Comment by phipsgabler** [comment]
I do think that a non-global solution is more elegant; but this specific one is probably really convenient for things like test cases, where you run a large number of separate `sample`s with the same setting, isn't it?
