### ISSUE TITLE
Combining Binomials 

### ISSUE THREAD

**Issue by natschil** [TuringLang/Turing.jl#1443]
I'd like to use the output of a Binomial for another Binomial, but I'm getting weird errors. 

Here is a minimal non-working example
```
using Turing, Distributions
@model function nonworkingexample(k)
    a ~ Beta(1,1)
    c ~ Binomial(20,a)
    k ~ Binomial(c, 0.5)
end
chain = sample(nonworkingexample(5), HMC(0.05, 10), 1, progress=true);
```

the error message I get is not pretty, but it starts with `ERROR: InexactError: Int64(7.047569771165934)` in `logpdf()`

**Comment by torfjelde** [comment]
`HMC` requires the logjoint to be differentiable wrt. latent variables, which also implies that the logjoint must be continuous in the latent variables. This means that `HMC` does not work for discrete variables, e.g. Binomial random variables. You can try something like `PG` for the `Binomial` variables. See https://turing.ml/dev/tutorials/4-bayeshmm/ for an example of sampling from discrete space :+1:

**Comment by natschil** [comment]
Makes sense, thanks! Is the fact that `HMC` nevertheless tries a bug?
