### ISSUE TITLE
Observing derived values via Turing.@addlogprob! are only handled by MH, not by IS, PG and SMC

### ISSUE THREAD

**Issue by hakank** [TuringLang/Turing.jl#1467]
(I asked about this at Discourse (https://discourse.julialang.org/t/turing-observing-sum-of-two-random-dice/50486/2 "Turing: Observing sum of two random dice)". mohamed82008 recommended that I filed an issue.

My model is simply to observe the sum of two dice (`d1+d2`) using `Turing.@addlogprob! -Inf`. Here I observe that the sum (`ss`) is 4, which should force both `d1` and `d2` to be 2.

```
using Turing

@model two_dice(ss) = begin
    d1 ~ DiscreteUniform(1, 6)
    d2 ~ DiscreteUniform(1, 6)

    d1+d2 == ss || begin Turing.@addlogprob! -Inf; return end
end

model = two_dice(4)
num_chains = 4 
chains = sample(model, MH(), MCMCThreads(), 10000, num_chains)
display(chains)
```

Using MH works: `d1` and `d2` are (mostly) 2. Here's the summary:
```
Summary Statistics
  parameters      mean       std   naive_se      mcse         ess      rhat 
      Symbol   Float64   Float64    Float64   Float64     Float64   Float64 

          d1    1.9737    0.8164     0.0041    0.0183   1730.3723    1.0033
          d2    2.0354    0.8216     0.0041    0.0183   1769.3695    1.0024

Quantiles
  parameters      2.5%     25.0%     50.0%     75.0%     97.5% 
      Symbol   Float64   Float64   Float64   Float64   Float64 

          d1    1.0000    1.0000    2.0000    3.0000    3.0000
          d2    1.0000    1.0000    2.0000    3.0000    3.0000

```

However, neither IS, PG, and SMC forces `d1` and `d2` to 2. Instead it's as if there is no observation in the model: the values of `d1` and `d2` are evenly distributed in `1:6`. Here's running IS(); and it's the about same output for PG(20) and SMC(1000):
```

chains = sample(model, IS(), MCMCThreads(), 1000, num_chains) 
# chains = sample(model, PG(20), 1000) 
# chains = sample(model, SMC(1000), 1000)
display(chain)
```

The output:
```
ummary Statistics
  parameters      mean       std   naive_se      mcse         ess      rhat 
      Symbol   Float64   Float64    Float64   Float64     Float64   Float64 

          d1    3.4867    1.6968     0.0268    0.0283   3936.0122    0.9997
          d2    3.5568    1.7053     0.0270    0.0256   4310.9671    0.9995

Quantiles
  parameters      2.5%     25.0%     50.0%     75.0%     97.5% 
      Symbol   Float64   Float64   Float64   Float64   Float64 

          d1    1.0000    2.0000    3.0000    5.0000    6.0000
          d2    1.0000    2.0000    4.0000    5.0000    6.0000
```

As I understand it, all these samplers (MH, IS, PG, and SMC) should be able to handle this kind of observations.

**Comment by hakank** [comment]
It should be mentioned that at least IS also seems to have problem with the "traditional" way of observing values. Here is an integer version of German Tank problem (https://en.wikipedia.org/wiki/German_tank_problem ) showing this:

```
using Turing

@model german_tank_int(y, nn=10_000) = begin
    n ~ DiscreteUniform(1,nn) # n is the calculated number of tanks
    for i in 1:length(y)
        y[i] ~ DiscreteUniform(1,n)  # observe this tank number
    end
end

y = [10, 256, 202, 97] # the observed tank numbers
nn = 10_000 # max possible value
model = german_tank_int(y,nn)

num_chains = 4

# chains = sample(model, Prior(), MCMCThreads(), 40_000, num_chains)
# chains = sample(model, MH(), MCMCThreads(), 40_000, num_chains)
# chains = sample(model, PG(20), MCMCThreads(), 40_000, num_chains)
# chains = sample(model, SMC(), MCMCThreads(), 40_000, num_chains)
chains = sample(model, IS(), MCMCThreads(), 40_000, num_chains)

display(chains)
```

The expected (theoretical value) is 382.  MH give a quite good solution with a mean around 382. PG(20) give a fair result (mean around  400). SMC is worse with a mean of around 950. 

But using IS() don't differ at all from the the Prior version with a mean of 5000 and a std of 2883.

**Comment by devmotion** [comment]
At least SMC and PG require you to specify explicitly that something is observed by using `~` (or its internal function call). More concretely, these algorithms are implemented with [Libtask.jl](https://github.com/TuringLang/Libtask.jl) for task copying and continuation and do not work properly if you have observations that do not call https://github.com/TuringLang/Turing.jl/blob/5335022c1986d5fa27cff83ae61f86527c4d620c/src/inference/AdvancedSMC.jl#L347-L350. You could add these calls manually by changing your example to
```julia
using Turing
using Libtask

@model function two_dice(ss)
    d1 ~ DiscreteUniform(1, 6)
    d2 ~ DiscreteUniform(1, 6)

    if d1 + d2 != ss
        if _sampler isa Turing.Sampler{<:Union{PG,SMC}}
            produce(-Inf)
        else
            Turing.@addlogprob! -Inf
        end
    else
        if _sampler isa Turing.Sampler{<:Union{PG,SMC}}
            produce(0.0)
        end
    end
end

sample(two_dice(4), SMC(), 10_000)
# sample(two_dice(4), PG(15), 10_000)
```

**Comment by devmotion** [comment]
> But using IS() don't differ at all from the the Prior version with a mean of 5000 and a std of 2883.

The problem is that the display of the chain is misleading for `IS`. You end up with samples that should be weighted but MCMCChains doesn't know about these weights and hence just computes the average of the samples, corresponding to uniform weights. If you are interested in the mean of the posterior you should rather compute
```julia
using StatsFuns
using LinearAlgebra

chain = sample(german_tank_int(y, nn), IS(), 10_000)
dot(chains[:n], softmax(chains[:lp])) # 384.09706644203965
```

**Comment by devmotion** [comment]
Similarly, for the initial example I get:
```julia
julia> chain = sample(model, IS(), 10_000);
Sampling 100%|██████████████████████████████████████████████| Time: 0:00:03

julia> dot(chain[:d1], softmax(chain[:lp]))
2.0119617224880653

julia> dot(chain[:d2], softmax(chain[:lp]))
1.9880382775119878
```

**Comment by hakank** [comment]
@devmotion  Thanks for your explanations, David. Both these suggestions works without any problem and I will test them further.

I wonder, however, if it's expected that a common user of Turing is to know about these special "tricks" for SMC, PGl, and IS? AFAIK, they are not documented in the Turing documentation.

**Comment by devmotion** [comment]
No, users should not have to know this but on the other hand regular users are also not expected to use `Turing.@addlogprob!` (hence it is not exported).

However, the problem with IS should definitely fixed since it is not related to `Turing.@addlogprob!`, probably by adding some way of weighting samples in MCMCChains.

SMC and PG is more difficult to handle since they are based on the special Libtask integration which often requires users to know about TArray etc. as well.

**Comment by hakank** [comment]
Thanks for your explanations on this, David.

It would be great if IS will be fixed.

In defense of my usage of `Turing.@addlogprob!`, it is actually mentioned in the documentation: "Advanced Usage"(https://turing.ml/dev/docs/using-turing/advanced ),  section "Update the accumulated log probability in the model definition?". 
Also, the TArray for IS, PG, and SMC is mentioned (https://turing.ml/dev/docs/using-turing/guide ) in the section "Working with Libtask.jl".  (For other models I've faithfully used TArray :-)) 

Again, thanks!

**Comment by devmotion** [comment]
> In defense of my usage of `Turing.@addlogprob!`, it is actually mentioned in the documentation: "Advanced Usage"

Sure, it is fine to use it (although apparently there are some caveats) but it was put into the "Advanced usage" section of the documentation on purpose :slightly_smiling_face:
