### ISSUE TITLE
Issues on https://turing.ml/dev/tutorials/1-gaussianmixturemodel/

### ISSUE THREAD

**Issue by nick-torenvliet** [TuringLang/Turing.jl#1478]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/1_GaussianMixtureModel.md

Hi - two issues on this tutorial page.  Using julia VERSION 1.5.3.

This code:
ids = findall(map(name -> occursin("μ", name), names(tchain)));
p=plot(tchain[:, ids, :], legend=true, labels = ["Mu 1" "Mu 2"], colordim=:parameter)
Throws an error with some type problem on the call to occursin which wants an AbstractString type not a Symbol. 

Fix with:
p=plot(tchain[:, [:μ1,:μ2], :], legend=true, labels = ["Mu 1" "Mu 2"], colordim=:parameter)

This code:
contour(range(-5, stop = 3), range(-6, stop = 2), 
    (x, y) -> predict(x, y, [0.5, 0.5], [mean(tchain[:μ1].value), mean(tchain[:μ2].value)])
)
Throws an empty axis error... 

Fix with:
contour(range(-5, stop = 3), range(-6, stop = 2), 
    (x, y) -> predict(x, y, [0.5, 0.5], [mean(tchain[:μ1]), mean(tchain[:μ2])])
)

**Comment by torfjelde** [comment]
Thank you for notifying us! 
This has been fixed but has not yet reached master (as it is part of the a larger effort to improve documentation: https://github.com/TuringLang/TuringTutorials/issues/86), so the website should also reflect this soon:)

**Comment by yebai** [comment]
@cpfiffer can you double-check whether this has been fixed? If so, let's consider closing this issue.

**Comment by cpfiffer** [comment]
I don't think it has since we're waiting on https://github.com/TuringLang/TuringTutorials/issues/86.

**Comment by yebai** [comment]
TuringLang/TuringTutorials#86 has been merged.
