### ISSUE TITLE
Discussion on `dprintln` levelling

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#148]
It's probably time to start organising debug print information, something like the following

- level 0: sampler progress information & warning messages.
- level 1: compiler information (and level 0 information)
- level 2: sampler runtime debugging information, e.g. variable allocation in each `step` 
- level 3: ...

The basic idea is that the higher the level is, the more verbose/detailed information is printed. High level `dprintln` should contain all low level `dprintln` information.

**Comment by xukai92** [comment]
I feel like compiler should be the lowest level.

**Comment by yebai** [comment]
> I feel like compiler should be the lowest level.
That makes sense.

In addition, remembering numbers are difficult. Perhaps we can define some constants, e.g.

```julia
compiler_level = 1
runtime_level = 2

# then we can call `dprintln` using 
dprintln(compiler_level, msg)
```

**Comment by yebai** [comment]
Perhaps a better way of managing debugging information is to use `label` instead of `level`

- ldefault: sampler progress information & warning messages.
- lcompiler: compiler information (and level 0 information)
- lruntime: sampler runtime debugging information, e.g. variable allocation in each `step` 
- lgrad: ...
- lhmc: ...
- ldualaveraging: ..
- lgrad

dprintln(ldefault, )

(use capital var names in the code)

**Comment by xukai92** [comment]
Maybe we should use some logging packages like
- https://github.com/c42f/MicroLogging.jl
- https://github.com/colinfang/MiniLogging.jl
- https://github.com/kmsquire/Logging.jl
