### ISSUE TITLE
Question: @addlogprob!

### ISSUE THREAD

**Issue by fmeulen** [TuringLang/Turing.jl#1486]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_docs/using-turing/advanced.md

I am trying to use `@addlogprob!`, but it appears not to be defined. 
Has this macro been renamed/removed?

**Comment by devmotion** [comment]
It is defined but not exported since it is intended for advanced users and one has to be aware of certain limitations (see, e.g., https://github.com/TuringLang/Turing.jl/issues/1467). You can use `Turing.@addlogprob!` or include `using Turing: @addlogprob!` at the top of your script.

**Comment by fmeulen** [comment]
Actually, my code looks like this
```julia
@model GraphLaplacianModel2(ci,L,nsample) = begin
    H ~ MvNormalCanon(L*τ)
    Turing.@addlogprob! loglik(ci, H, nsample)
end
```
So I have already followed your suggestion. Yet I get `loadError: undefVarError @addlogprob! notdefined`

**Comment by fmeulen** [comment]
Actually, I get the same for the example script
```julia
myloglikelihood(x, μ) = loglikelihood(Normal(μ, 1), x)

@model function demo(x)
    μ ~ Normal()
    Turing.@addlogprob! myloglikelihood(x, μ)
end
```

**Comment by devmotion** [comment]
Maybe you use an old version of Turing and/or DynamicPPL? What versions of these packages do you use?

**Comment by fmeulen** [comment]
Turing v0.13.0
 DynamicPPL v0.8.2

**Comment by devmotion** [comment]
Ah yes, these versions do not contain the macro, it was only introduced later. Updating Turing to 0.15, or 0.14, should fix the problem.

**Comment by fmeulen** [comment]
It seems that 0.13 is the most registered version. Does this mean I have to add a yet unregistered branch to use this macro? [Thanks for your help on this!]

**Comment by devmotion** [comment]
Turing 0.15.1 was registered today but maybe some other package holds Turing back. You can run
```julia
] add Turing@0.15
```
to check if you can update to the latest version, or why it fails.

**Comment by fmeulen** [comment]
Ah, that makes sense (I got a new computer last week, so I could hardly imagine I would not have the most up-to-date version...). Now `ERROR: Unsatisfiable requirements detected for package Distributions [31c24e10]:`. I can see this has to do with a restriction by a package I am working on myself. So I'll need to fix this myself. I guess that will resolve the issue.
