### ISSUE TITLE
Allow silencing variational inference log messages

### ISSUE THREAD

**Issue by solna86** [TuringLang/Turing.jl#1493]
Is it possible to disable variational inference log messages like:

```
┌ Info: [ADVI] Should only be seen once: optimizer created for θ                                                                                                              
└   objectid(θ) = 0x7e588a956c33cb39
```

```setprogress!(false)``` does not make a difference, and I could not find an alternative method in the documentation.

**Comment by devmotion** [comment]
IIRC these messages are generated by AdvancedVI. https://github.com/TuringLang/Turing.jl/issues/1398#issuecomment-687259280 contains two examples for how to suppress them.

**Comment by Red-Portal** [comment]
I'll close this since this seems to have been resolved.
