### ISSUE TITLE
Question: error "turnprogress not defined" and "no method matching _setadbackend(::Val{:reverse_diff})"

### ISSUE THREAD

**Issue by zhaotianjing** [TuringLang/Turing.jl#1495]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_docs/using-turing/guide.md

Hi, I just start to learn Turing by following the documentation. When I ran
```
Turing.turnprogress(true)
```
I got the error message: "UndefVarError: turnprogress not defined"

when I ran
```
Turing.setadbackend(:reverse_diff)
```
I got the error message: "MethodError: no method matching _setadbackend(::Val{:reverse_diff})" 

All of my code is below:
```
using Turing, Flux, Random

Turing.turnprogress(true)
Turing.setadbackend(:reverse_diff)
```

I'm using Atom, with Julia Version 1.5.2 (2020-09-23), and I installed Turing today. My computer is MacBook Pro (16-inch, 2019) with 2.6 GHz 6-Core Intel Core i7. 

I tried to re-start Julia, but it won't help. Could you please tell me how to fix it?

Thank you so much,
Tianjing

**Comment by devmotion** [comment]
With the latest Turing releases (version 0.15) you have to use `setprogress!(true)` and `setadbackend(:reversediff)`.

**Comment by zhaotianjing** [comment]
Thank you!
