### ISSUE TITLE
Differences between `Turing.Inference.NUTS` and `AdvancedHMC.NUTS`

### ISSUE THREAD

**Issue by ClaudMor** [TuringLang/Turing.jl#1510]
Hello,

This question could be due to me not being an expert in MCMC, HMC and bayesian inference in general, so I'm just hoping for some operative indications ( but help of any kind is highly apprecciated). Please criticize every step of the following reasoning.

From what I understood from the [documentation](https://turing.ml/dev/docs/using-turing/), `NUTS` is the sampler of choice in most applications. 

Anyway, It looks to me that there are two implementations of `NUTS`, one being  `Turing.Inference.NUTS` and the other `AdvancedHMC.NUTS`. Following [this comment](https://github.com/TuringLang/Turing.jl/issues/1505#issuecomment-753401549), I understood that `Turing.Inference.NUTS` is better supported than `AdvancedHMC.NUTS`. So I would ask:

-  **Apart from the current support difference, is one of the two "better" ( in some sense) than the other? What distinguishes them?**

Also, I noticed that when I do things like:

```julia
chain1 = @time sample(model2, Turing.Inference.NUTS(0.45), 1000, progress = true) 
```

I get warnings that seem to be launched by AdvancedHMC:

```
...
┌ Warning: The current proposal will be rejected due to numerical error(s).
│   isfinite.((θ, r, ℓπ, ℓκ)) = (true, false, false, false)
└ @ AdvancedHMC C:\Users\claud\.julia\packages\AdvancedHMC\MIxdK\src\hamiltonian.jl:47
...
```
Is it correct?

Thank you

**Comment by cpfiffer** [comment]
The difference is that `AdvancedHMC` is the "true" imlementation, in that it's the one that does all the work. The `Turing.Inference.NUTS` struct is just a wrapper around `AdvancedHMC`, so any real inference code goes to `AdvancedHMC`.

**Comment by storopoli** [comment]
And what is the difference between `DynamicHMC.NUTS` vs `Turing.Inference.NUTS`?

**Comment by cpfiffer** [comment]
`DynamicHMC.NUTS` is a separate inference algorithm implemented differently [here](https://github.com/tpapp/DynamicHMC.jl).

**Comment by storopoli** [comment]
Thank you! I think we can close this issue.

**Comment by cpfiffer** [comment]
Agreed, thanks!
