### ISSUE TITLE
unexpected number of latent variables in GM tutorial example

### ISSUE THREAD

**Issue by mkarikom** [TuringLang/Turing.jl#1514]
It seems like there should only be k[i], i=1:N chains for the label (one for each data point) but somehow it looks like we have double that number:

## GM code from docs

```
using Distributions, StatsPlots, Random, Plots

## sample data
Random.seed!(3)

# Construct 30 data points for each cluster.
N = 30

# Parameters for each cluster, we assume that each cluster is Gaussian distributed in the example.
μs = [-3.5, 0.0]

# Construct the data points.
x = mapreduce(c -> rand(MvNormal([μs[c], μs[c]], 1.), N), hcat, 1:2)

## specify model
using Turing, MCMCChains

@model GaussianMixtureModel(x) = begin
    
    D, N = size(x)

    # Draw the parameters for cluster 1.
    μ1 ~ Normal()
    
    # Draw the parameters for cluster 2.
    μ2 ~ Normal()
    
    μ = [μ1, μ2]
    
    # Uncomment the following lines to draw the weights for the K clusters 
    # from a Dirichlet distribution.
    
    # α = 1.0
    # w ~ Dirichlet(2, α)
    
    # Comment out this line if you instead want to draw the weights.
    w = [0.5, 0.5]
    
    # Draw assignments for each datum and generate it from a multivariate normal.
    k = Vector{Int}(undef, N)
    for i in 1:N
        k[i] ~ Categorical(w)
        x[:,i] ~ MvNormal([μ[k[i]], μ[k[i]]], 1.)
    end
    return k
end

## sample the model
gmm_model = GaussianMixtureModel(x);

gmm_sampler = Gibbs(PG(100, :k), HMC(0.05, 10, :μ1, :μ2))

tchain = mapreduce(c -> sample(gmm_model, gmm_sampler, 100), chainscat, 1:3);
names(tchain)
```
## Output
```
julia> names(tchain)
63-element Array{Symbol,1}:
 Symbol("k[1]")
 Symbol("k[2]")
 Symbol("k[3]")
 Symbol("k[4]")
 Symbol("k[5]")
 Symbol("k[6]")
 Symbol("k[7]")
 Symbol("k[8]")
 Symbol("k[9]")
 Symbol("k[10]")
 Symbol("k[11]")
 Symbol("k[12]")
 Symbol("k[13]")
 Symbol("k[14]")
 ⋮
 Symbol("k[51]")
 Symbol("k[52]")
 Symbol("k[53]")
 Symbol("k[54]")
 Symbol("k[55]")
 Symbol("k[56]")
 Symbol("k[57]")
 Symbol("k[58]")
 Symbol("k[59]")
 Symbol("k[60]")
 :lp
 :μ1
 :μ2
```

**Comment by devmotion** [comment]
There are 60 data points (30 for each cluster). So `k[1]`, ..., `k[60]` seems correct to me.

**Comment by mkarikom** [comment]
oops, sorry! 
I saw `N=30` and did not notice that `rand(MvNormal([μs[c], μs[c]], 1.), N)` is called twice to get the data

**Comment by yebai** [comment]
There is another minor mistake in the model. `k = Vector{Int}(undef, N)` should be replaced by `k = TArray{Int, 1}(undef, N)` in order to correctly use particle Gibbs sampling. See [here](https://turing.ml/dev/docs/using-turing/guide#working-with-libtaskjl
) for more details. 

We are working on automating this step in the future, but it's not yet available in the current release.

**Comment by torfjelde** [comment]
Does the replacement not work if you use a type-parameter for `TArray`, e.g. `TV` in the method + `k = TV(undef, N)` ?

**Comment by yebai** [comment]
> Does the replacement not work if you use a type-parameter for TArray, e.g. TV in the method + k = TV(undef, N) ?

I don't think this is implemented yet. 

@mohamed82008

**Comment by devmotion** [comment]
It is, it should be handled by https://github.com/TuringLang/Turing.jl/blob/339877206cb2f084cbd30eb6c36081d2f81565f9/src/inference/Inference.jl#L433-L439 and https://github.com/TuringLang/DynamicPPL.jl/blob/873d5e94fe778514d52e24338a3cd1bd0535eefa/src/compiler.jl#L382.
