### ISSUE TITLE
Question: I believe a correction needs to be made.

### ISSUE THREAD

**Issue by salbert83** [TuringLang/Turing.jl#1528]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/4_BayesHmm.md

I believe in constructing the animation, the lines
m_set = c[:m].value.data
s_set = c[:s].value.data

should be changed to

m_set = group(c, :m).value.data;
s_set = group(c, :s).value.data;

Of lesser concern, what is "$$" that appears in several pieces of the code.  Thank you.

**Comment by yebai** [comment]
thanks, @salbert83 - would you like to create a PR for your proposed fixes?
