### ISSUE TITLE
ERROR: cannot assign a value to variable MCMCChains.chains

### ISSUE THREAD

**Issue by rikhuijzer** [TuringLang/Turing.jl#1529]
Sometimes, `Turing.sample` will print
```
ERROR: cannot assign a value to variable MCMCChains.chains from module Main
```
and return an object, which is not a valid chains object. I've had it happen in Julia 1.5.3 and 1.6-beta1. 

Unfortunately, so far, I'm unable to pin it down further. As a minimal example, I now have a function
```
using Turing

function example_chains()     
    @model function globe_toss(n, k)
         θ ~ Beta(1, 1)
         k ~ Binomial(n, θ)
         return k, θ
    end
    chains = sample(globe_toss(9, 6), NUTS(0.65), 1000)
end
```
which worked fine for about 10 times, and gave the error on a next call. I also had similar problems when working on [TuringModels.jl](https://github.com/StatisticalRethinkingJulia/TuringModels.jl) for at least two different models, so it is not caused by this particular model.

Further information that I can think of is that there seems to be some underlying state being the culprit. Calling sample again will not solve it but restarting Julia will.

**Comment by devmotion** [comment]
`chains` is a function that is exported by MCMCChains (https://github.com/TuringLang/MCMCChains.jl/blob/8704b55c626f17d40b62f5d8b93b7c50a618dc48/src/MCMCChains.jl#L27) and reexported by Turing (Turing reexports MCMCChains and some other packages).

Generally in Julia you can't assign values to existing functions. This is not a problem with `sample` (which BTW is just reexported from StatsBase). E.g., the following will always fail:
```julia
julia> using Turing

julia> chains
chains (generic function with 1 method)

julia> chains = 42
ERROR: cannot assign a value to variable MCMCChains.chains from module Main
Stacktrace:
 [1] top-level scope at REPL[5]:1
```

I don't know why it would fail when you declare a new local variable though.

**Comment by rikhuijzer** [comment]
I think you have found the source of the issue! This makes complete sense with the situations where it occurred. I'll close this issue.
