### ISSUE TITLE
Turing does not dispatch on correct sample method for NUTS and possibly other samplers

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/Turing.jl#1537]
Hi all-

I discovered that Turing is not dispatching on the appropriate `sample` method. As a consequence, warmup/adaption samples are not being discarded and the [progress bar is not working](https://github.com/TuringLang/Turing.jl/issues/1532). 

The MWE example shows that the number of samples returned is incorrect:

```
using Turing, Distributions
y = rand(Normal(0,1), 30)
@model function model(y)
    μ ~ Normal(0,1)
    y .~ Normal(μ,1)
end
n_samples = 3000
n_adapt = 1500
specs = NUTS(n_adapt, .65)
n_chains = 4
chain = sample(model(y), specs, MCMCThreads(), n_samples, n_chains, discard_adapt=false)
```

Running the following code indicates that the [default sample method ](https://github.com/TuringLang/Turing.jl/blob/8886d35672b87f5c5b29caebd33a27326e2a3fa2/src/inference/Inference.jl#L182)is being called rather than the [intended method in Turing](https://github.com/TuringLang/Turing.jl/blob/8886d35672b87f5c5b29caebd33a27326e2a3fa2/src/inference/hmc.jl#L119):

`@edit sample(model(y), specs, MCMCThreads(), n_samples, n_chains, discard_adapt=false)`

It appears that part of the problem is that the following evaluates to false:

`NUTS <: Turing.Sampler{<:Turing.AdaptiveHamiltonian}`

which prevents the method from being selected as intended. 

I can confirm this problem affects Turing .15.8 on Julia 1.5.3 and Turing .15.1 on Julia 1.6 beta1. 

Considering that this is returning unexpected results (I didn't notice for almost three months), would it be possible to prioritize a patch release, or help me submit a PR? 

Thank you in advance.

**Comment by luiarthur** [comment]
Not sure if this will help you for the time being. Can you try

```julia
chain = sample(model(y), specs, MCMCThreads(), n_samples, n_chains, discard_initial=n_adapt)
```

This should discard the initial `n_adapt` samples used for adapting NUTS and return `n_samples` in the end.

**Comment by itsdfish** [comment]
Thanks. Unfortunately that does not appear to work because the default method does not have a keyword for `discard_initial`. It only has `kwargs...`.

**Comment by devmotion** [comment]
The type is not a problem, Turing wraps a all algorithms in a `Sampler` automatically. One just has to add an implementation of https://github.com/TuringLang/Turing.jl/blob/1a4b4e5a75d295742097e52e9bdd8ed0b7e5fd65/src/inference/Inference.jl#L205 for the hamiltonian samplers with all the keyword arguments. One has to be a bit careful since `DynamicNUTS` uses different keyword arguments IIRC. In the long term, probably it would be good to modify AbstractMCMC such that parallel and serial sampling support the same keyword arguments automatically.

**Comment by itsdfish** [comment]
Ok. I think I am beginning to understand. Here I will focus on the single chain case because it has a NUTS specific method, but does not discard adaption samples. When I place print statements in the code, I can trace the following sequence of method calls:

```
method on 127 of inference.jl of Turing
method on 135 of inference.jl of Turing
method on 110 of hmc.jl of Turing
method on 59 of sample.jl in AbstractMCMC
```
This[ last method in AbstractMCMC](https://github.com/TuringLang/AbstractMCMC.jl/blob/7e0967af0085e53f1c1cd1b1852d6669f58891d8/src/sample.jl#L59) performs all of the sampling, but does not have a keyword for `discard_adapt` and the handling of adaption samples has not been implemented. So it appears that `discard_adapt` is not supported for any sampler, serial or parallel.

**Comment by itsdfish** [comment]
My best guess is that `mcmcsample` needs to be modified as follows:

```
function mcmcsample(
    rng::Random.AbstractRNG,
    model::AbstractModel,
    sampler::AbstractSampler,
    N::Integer;
    progress = true,
    progressname = "Sampling",
    callback = nothing,
    discard_initial = 0,
    discard_adapt = false,
    thinning = 1,
    chain_type::Type=Any,
    kwargs...
)
    println("method on 59 of sample.jl in AbstractMCMC")
    # Check the number of requested samples.
    N > 0 || error("the number of samples must be ≥ 1")
    Ntotal = thinning * (N - 1) + discard_initial + 1

    @ifwithprogresslogger progress name=progressname begin
        # Obtain the initial sample and state.
        sample, state = step(rng, model, sampler; kwargs...)
        # access nadapt in sampler somehow
        n_discarded ? max(discard_initial, sampler.nadapt) : discard_initial
        # Discard initial samples.
        for i in 1:(n_discarded - 1)
            # Update the progress bar.
            progress && ProgressLogging.@logprogress i/Ntotal

            # Obtain the next sample and state.
            sample, state = step(rng, model, sampler, state; kwargs...)
        end

        # Run callback.
        callback === nothing || callback(rng, model, sampler, sample, 1)

        # Save the sample.
        samples = AbstractMCMC.samples(sample, model, sampler, N; kwargs...)
        samples = save!!(samples, sample, 1, model, sampler, N; kwargs...)

        # Update the progress bar.
        progress && ProgressLogging.@logprogress (1 + discard_initial) / Ntotal

        # Step through the sampler.
        itotal = 1 + n_discarded
        for i in 2:N
            # Discard thinned samples.
            for _ in 1:(thinning - 1)
                # Obtain the next sample and state.
                sample, state = step(rng, model, sampler, state; kwargs...)
                
                # Update progress bar.
                if progress
                    itotal += 1
                    ProgressLogging.@logprogress itotal / Ntotal
                end
            end

            # Obtain the next sample and state.
            sample, state = step(rng, model, sampler, state; kwargs...)

            # Run callback.
            callback === nothing || callback(rng, model, sampler, sample, i)

            # Save the sample.
            samples = save!!(samples, sample, i, model, sampler, N; kwargs...)

            # Update the progress bar.
            if progress
                itotal += 1
                ProgressLogging.@logprogress itotal / Ntotal
            end
        end
    end

    return bundle_samples(samples, model, sampler, state, chain_type; kwargs...)
end
```

Essentially, I added a keyword argument for `discard_adapt` and created a new variable called `n_discarded`, which is the max of  `discard_initial` and `nadapt` from the samper object. Is this roughly what needs to be done?

**Comment by devmotion** [comment]
No, AbstractMCMC does not have to be changed (and in general one should not add sampler/algorithm specific keyword arguments to it). The sampling logic is implemented in `AbstractMCMC.mcmcsample` with some default keyword arguments for e.g. thinning and burn-in periods and a catch-all `kwargs...` for other keyword arguments that are forwarded to all interface functions such as `step` etc.

Turing only implements `sample` by forwarding it to `AbstractMCMC.mcmcsample` by default in Inference.jl, with `Sampler`s automatically constructed from algorithms. Additionally, special keyword arguments such as `init_params` and `resume_from` are handled by Turing (ans DynamicPPL). In the same way, some HMC-specific keyword arguments such as `discard_adapt` are handled in `hmc.jl`. The only problem is that there is no special implementation (with the same keyword arguments) for parallel sampling of HMC algorithms, and hence it just falls back to the default in `Inference.jl` that just calls `AbstractMCMC.mcmcsample`.

**Comment by itsdfish** [comment]
My apologies. Part of the problem is that the new way that Turing handles adaption samples differs from what I expected. If I recall correctly, CmdStan.jl will have nadapt + N samples when the adaption samples are saved. Turing always returns N, which you said earlier thought might be the case. Now that I have a better understanding of how Turing works, I believe that adaption samples are discarded correctly. Here is what I found with 4 parallel chains:

```
method on 199 of inference.jl in Turing
method on 214 of inference.jl in Turing
method on 227 of sample.jl in AbstractMCMC
#chain 1
method on 110 of hmc.jl of Turing
#chain 2
method on 110 of hmc.jl of Turing
#chain 3
method on 110 of hmc.jl of Turing
#chain 4
method on 110 of hmc.jl of Turing
#chain 1 
method on 59 of sample.jl in AbstractMCMC
#chain 2
method on 59 of sample.jl in AbstractMCMC
#chain 3
method on 59 of sample.jl in AbstractMCMC
#chain 4
method on 59 of sample.jl in AbstractMCMC
Discarding 1500 samples
Discarding 1500 samples
Discarding 1500 samples
Discarding 1500 samples
```

This indicates that the parallel method in AbstractMCMC spawns 4 instances of the NUTS sample method. I also printed the thread id to verify that the chains were in parallel. If this comports with your understanding, I will close this issue. Again, sorry for the misunderstanding.

One last thing: does the documentation explain how adaption samples are handled? I could not find any information. This could be part of the problem. If that is true, I can open an issue.

**Comment by mgmverburg** [comment]
What is the fix you went with for this @itsdfish? Because I just realized this as well, in all the tutorials on Turing default behavior seems to be that it automatically discards this, and it is even what I learned from the Statistical Rethinking book. So suddenly when I realized my number of samples were too many, it was quite a surprise :P 
I guess for now I can just discard them manually by doing:
```julia
chain = chain[n_adapt+1:end, :, :]
```

**Comment by itsdfish** [comment]
In my previous post, I explain that the samplers are working _correctly_. I think the problem is that (1) the new treatment of adaption samples seems to be different from CmdStan, which was different from what I expected, and  (2) it appears that the documentation was never updated. So this appears to be a misunderstanding, but I think the documentation needs to be updated. 

Just to be clear about how the code works, in the following example, there are 2,000 total samples for each chain and the first 1,000 are removed. So you will need to adjust `n_samples` in your code accordingly. Does that make sense?

```
using Turing, Distributions
y = rand(Normal(0,1), 30)
@model function model(y)
    μ ~ Normal(0,1)
    y .~ Normal(μ,1)
end
n_samples = 1000
n_adapt = 1000
specs = NUTS(n_adapt, .65)
n_chains = 4
chain = sample(model(y), specs, MCMCThreads(), n_samples, n_chains)
```

**Comment by mgmverburg** [comment]
Oh wow that is confusing indeed. Yeah I see the problem now with the change and then using old tutorials. I indeed was passing in n_samples+n_adapt, while passing in n_adapt to NUTS as well, so I guess I was actually running longer chains than I thought I was. So indeed the n_samples you pass is really the number of samples you will get back. Thanks for the clarification! It's good to know how many samples I am actually running it with.

**Comment by itsdfish** [comment]
I didn't realize it changed for several months. When I realized something had changed, I thought the adapt samples were included in the chain and had a bit of panic. 

I am willing to add this information to the docs if one of the developers would like me to do so.

**Comment by cpfiffer** [comment]
Sure, we'd happily take more documentation!

**Comment by itsdfish** [comment]
I will add some documentation and close this issue this weekend.
