### ISSUE TITLE
Question: What is the true value of observation noise in SDE example?

### ISSUE THREAD

**Issue by zenkavi** [TuringLang/Turing.jl#1540]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/10_BayesianDiffEq.md

I posted this [on the forums a couple days](https://discourse.julialang.org/t/confusion-about-parameter-interpretation-in-turing-documentation/54655) ago but reposting here to get insight from whomever might have written the example: 

In the example titled: "Inference of a Stochastic Differential Equation" there are two noise parameters (phi1 and phi2) used to generate the simulated data. Then in the model there is a third noise parameter, sigma. I understand that this represents observation noise but since it is not used in the data simulation process I am having trouble understanding what its true value supposed to be and how it can be calculated. 

Any help would be appreciated.

**Comment by mahdiarsadeghi** [comment]
Solved [here](https://discourse.julialang.org/t/confusion-about-parameter-interpretation-in-turing-documentation/54655).

**Comment by zenkavi** [comment]
I posted that question as well. It's only clarified that sigma is indeed observation noise and how one _could_ set it to a specific value in the data generation process. 

It's still not clear to me what the author of the tutorial intended for the true value of sigma to be.

**Comment by cpfiffer** [comment]
Ah, I think it's 0.8. When the data is generated, we add `0.8 * randn(...)`:

```julia
sol1 = solve(prob1,Tsit5(),saveat=0.1)
odedata = Array(sol1) + 0.8 * randn(size(Array(sol1))) # Here is where sigma = 0.8 is set
plot(sol1, alpha = 0.3, legend = false); scatter!(sol1.t, odedata')
```

**Comment by zenkavi** [comment]
I'm sorry I think the confusion is because of the broken link in my original question on this thread (this link is broken: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/10_BayesianDiffEq.md).

I understand how Chris Rackauckas sets the observation noise to 0.8 in his response to my question on the forum. 

But this doesn't answer my question which is about the Turing documentation. In the example in the following link:
https://turing.ml/dev/tutorials/10-bayesiandiffeq/#inference-of-a-stochastic-differential-equation
under "Inference of a Stochastic Differential Equation" where is the observation noise sigma defined?

**Comment by cpfiffer** [comment]
I guess I'm not sure what your question is -- like where is it defined in the model?

**Comment by zenkavi** [comment]
Yes. Is it defined in the model, if so where and what is its true value?

**Comment by cpfiffer** [comment]
It's defined in the first line of the model:

```julia
@model function fitlv(data, prob)
    σ ~ InverseGamma(2,3) # defined here
    α ~ truncated(Normal(1.3,0.5),0.5,2.5)
    β ~ truncated(Normal(1.2,0.25),0.5,2)
    γ ~ truncated(Normal(3.2,0.25),2.2,4.0)
    δ ~ truncated(Normal(1.2,0.25),0.5,2.0)
    ϕ1 ~ truncated(Normal(0.12,0.3),0.05,0.25)
    ϕ2 ~ truncated(Normal(0.12,0.3),0.05,0.25)
    p = [α,β,γ,δ,ϕ1,ϕ2]
    prob = remake(prob, p=p)
    predicted = solve(prob,SOSRI(),saveat=0.1)

    if predicted.retcode != :Success
        Turing.acclogp!(_varinfo, -Inf)
    end
    for j in 1:length(data)
        for i = 1:length(predicted)
            data[j][i] ~ MvNormal(predicted[i],σ)
        end
    end
end;
```

As to the true value, I'm not sure. I'm not the best diffeq guy but I suspect you'd have to do a bit of math to figure out what precisely this noise term is.

**Comment by zenkavi** [comment]
Right, this is where it is defined in the model. And the data for the simulation is defined in the previous block 

```
u0 = [1.0,1.0]
tspan = (0.0,10.0)
function multiplicative_noise!(du,u,p,t)
  x,y = u
  du[1] = p[5]*x
  du[2] = p[6]*y
end
p = [1.5,1.0,3.0,1.0,0.1,0.1]

function lotka_volterra!(du,u,p,t)
  x,y = u
  α,β,γ,δ = p
  du[1] = dx = α*x - β*x*y
  du[2] = dy = δ*x*y - γ*y
end


prob_sde = SDEProblem(lotka_volterra!,multiplicative_noise!,u0,tspan,p)

ensembleprob = EnsembleProblem(prob_sde)
@time data = solve(ensembleprob,SOSRI(),saveat=0.1,trajectories=1000)
plot(EnsembleSummary(data))
```
 My question is the math bit since sigma is not directly defined in this block where the data are generated. Any thoughts on who might be a better person to ask?

**Comment by mschauer** [comment]
σ is a prior parameter for the in general unknown observation noise (extrinsic noise). `ϕ1` and `ϕ2` are parameters for the in general unknown diffusivity (*intrinsic* noise). The true values for `ϕ1` and `ϕ2` are 0.1. The true value for `σ` is (following the docs) 0, as there is no noise added to the trajectory before taking samples every `0.1`. Note that the prior puts no mass close to `0` so this parameter will not be learned correctly
https://www.wolframalpha.com/input/?i=InverseGammaDistribution%282%2C3%29

**Comment by lilianping** [comment]
> 

why I run this code ,it has a error as follows？
![image](https://user-images.githubusercontent.com/67664965/147062831-25daafd1-e910-4b0e-a447-08170a90d074.png)
