### ISSUE TITLE
Search bar doesn't work

### ISSUE THREAD

**Issue by zenkavi** [TuringLang/Turing.jl#1541]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_docs/using-turing/guide.md

I haven't been able to get the search bar in the documentation work neither in Chrome Version 88.0.4324.150 nor in Safari Version 14.0.2

**Comment by cpfiffer** [comment]
I can replicate this. Not sure what's up exactly -- stay tuned.

**Comment by cpfiffer** [comment]
Yup, it's yet another path issue. I'll correct this upstream: https://github.com/turinglang/turing.ml

**Comment by cpfiffer** [comment]
Fixed in https://github.com/TuringLang/turing.ml, thanks!
