### ISSUE TITLE
Error with filldist/bijectors?

### ISSUE THREAD

**Issue by sjwild** [TuringLang/Turing.jl#1543]
I am trying to teach myself splines in Turing. I decided to try running a spline as a mixed effect, but I get an error message. To see if it was error with my code, I tried running some of the multilevel model code from TuringModels. I get the same error message.

Below is the code for a reproducible example. Keeping in the spirit of McElreath, it uses his cherry blossom data.

```
using Plots, StatsPlots
using Distributions
using BSplines
using Turing, MCMCChains, AdvancedHMC
using CSV, DataFrames

# load content
url = "https://raw.githubusercontent.com/rmcelreath/rethinking/master/data/cherry_blossoms.csv"
download(url, "cherry_blossoms.csv")
df = CSV.File("cherry_blossoms.csv", missingstring = "NA") |> DataFrame


dropmissing!(df, :doy)
doy = Vector{Float64}(df[:, :doy])
yr = Vector{Float64}(df[:, :year])

# build matrix
num_knots = 15
d = maximum(yr) - minimum(yr)
k = Array{Float64}([812:(d/num_knots):2015;])
basis = BSplineBasis(4, k)
B = basismatrix(basis, yr)

# Turing model
@model function spline_me(y, Z)

    # dims 
    n_z, m_z = size(Z)
    

    # priors
    σ_z ~ truncated(Normal(0, 10), 0, Inf)
    σ ~ truncated(Normal(0, 10), 0, Inf)
    α ~ Normal(100, 10)

    # build μ
    μ ~ filldist(Normal(0, σ_z), m_z)

    # model
    y .~ Normal.(α .+ Z * μ, σ)

end

model_me = spline_me(doy, B)
chain_me = sample(model_me, Turing.NUTS(1000, 0.65), 2000)

```

When I run the code, I get the following error message:

> ERROR: MethodError: no method matching bijector(::DistributionsAD.TuringScalMvNormal{Array{Float64,1},Float64})
> Closest candidates are:
>   bijector(::KSOneSided) at /Users/stephenjwild/.julia/packages/Bijectors/L39Ij/src/transformed_distribution.jl:59
>   bijector(::Product{Discrete,T,V} where V<:AbstractArray{T,1} where T<:Distribution{Univariate,Discrete}) at /Users/stephenjwild/.julia/packages/Bijectors/L39Ij/src/transformed_distribution.jl:41
>   bijector(::Product{Continuous,T,V} where V<:AbstractArray{T,1} where T<:Distribution{Univariate,Continuous}) at /Users/stephenjwild/.julia/packages/Bijectors/L39Ij/src/transformed_distribution.jl:42
>   ...
> Stacktrace:
>  [1] link(::DistributionsAD.TuringScalMvNormal{Array{Float64,1},Float64}, ::Array{Float64,1}) at /Users/stephenjwild/.julia/packages/Bijectors/L39Ij/src/Bijectors.jl:121
>  [2] macro expansion at /Users/stephenjwild/.julia/packages/DynamicPPL/wf0dU/src/varinfo.jl:728 [inlined]
>  [3] _link!(::NamedTuple{(:σ_z, :σ, :α, :μ),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:σ_z,Tuple{}},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:σ_z,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:σ,Tuple{}},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:σ,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:α,Tuple{}},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:α,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:μ,Tuple{}},Int64},Array{DistributionsAD.TuringScalMvNormal{Array{Float64,1},Float64},1},Array{DynamicPPL.VarName{:μ,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}}, ::DynamicPPL.VarInfo{NamedTuple{(:σ_z, :σ, :α, :μ),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:σ_z,Tuple{}},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:σ_z,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:σ,Tuple{}},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:σ,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:α,Tuple{}},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:α,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:μ,Tuple{}},Int64},Array{DistributionsAD.TuringScalMvNormal{Array{Float64,1},Float64},1},Array{DynamicPPL.VarName{:μ,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}, ::NamedTuple{(:σ_z, :σ, :α, :μ),Tuple{Array{DynamicPPL.VarName{:σ_z,Tuple{}},1},Array{DynamicPPL.VarName{:σ,Tuple{}},1},Array{DynamicPPL.VarName{:α,Tuple{}},1},Array{DynamicPPL.VarName{:μ,Tuple{}},1}}}, ::Val{()}) at /Users/stephenjwild/.julia/packages/DynamicPPL/wf0dU/src/varinfo.jl:717
>  [4] link! at /Users/stephenjwild/.julia/packages/DynamicPPL/wf0dU/src/varinfo.jl:715 [inlined]
>  [5] initialstep(::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"#5#6",(:y, :Z),(),(),Tuple{Array{Float64,1},Array{Float64,2}},Tuple{}}, ::DynamicPPL.Sampler{Turing.Inference.NUTS{Turing.Core.ForwardDiffAD{40},(),DiagEuclideanMetric}}, ::DynamicPPL.VarInfo{NamedTuple{(:σ_z, :σ, :α, :μ),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:σ_z,Tuple{}},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:σ_z,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:σ,Tuple{}},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{DynamicPPL.VarName{:σ,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:α,Tuple{}},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:α,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:μ,Tuple{}},Int64},Array{DistributionsAD.TuringScalMvNormal{Array{Float64,1},Float64},1},Array{DynamicPPL.VarName{:μ,Tuple{}},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}; init_params::Nothing, nadapts::Int64, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/stephenjwild/.julia/packages/Turing/O1Pn0/src/inference/hmc.jl:160
>  [6] step(::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"#5#6",(:y, :Z),(),(),Tuple{Array{Float64,1},Array{Float64,2}},Tuple{}}, ::DynamicPPL.Sampler{Turing.Inference.NUTS{Turing.Core.ForwardDiffAD{40},(),DiagEuclideanMetric}}; resume_from::Nothing, kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:nadapts,),Tuple{Int64}}}) at /Users/stephenjwild/.julia/packages/DynamicPPL/wf0dU/src/sampler.jl:83
>  [7] macro expansion at /Users/stephenjwild/.julia/packages/AbstractMCMC/Nw3Wn/src/sample.jl:78 [inlined]
>  [8] macro expansion at /Users/stephenjwild/.julia/packages/ProgressLogging/6KXlp/src/ProgressLogging.jl:328 [inlined]
>  [9] macro expansion at /Users/stephenjwild/.julia/packages/AbstractMCMC/Nw3Wn/src/logging.jl:8 [inlined]
>  [10] mcmcsample(::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"#5#6",(:y, :Z),(),(),Tuple{Array{Float64,1},Array{Float64,2}},Tuple{}}, ::DynamicPPL.Sampler{Turing.Inference.NUTS{Turing.Core.ForwardDiffAD{40},(),DiagEuclideanMetric}}, ::Int64; progress::Bool, progressname::String, callback::Nothing, discard_initial::Int64, thinning::Int64, chain_type::Type{T} where T, kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:nadapts,),Tuple{Int64}}}) at /Users/stephenjwild/.julia/packages/AbstractMCMC/Nw3Wn/src/sample.jl:76
>  [11] sample(::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"#5#6",(:y, :Z),(),(),Tuple{Array{Float64,1},Array{Float64,2}},Tuple{}}, ::DynamicPPL.Sampler{Turing.Inference.NUTS{Turing.Core.ForwardDiffAD{40},(),DiagEuclideanMetric}}, ::Int64; chain_type::Type{T} where T, resume_from::Nothing, progress::Bool, nadapts::Int64, discard_adapt::Bool, discard_initial::Int64, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/stephenjwild/.julia/packages/Turing/O1Pn0/src/inference/hmc.jl:140
>  [12] sample at /Users/stephenjwild/.julia/packages/Turing/O1Pn0/src/inference/hmc.jl:123 [inlined]
>  [13] #sample#2 at /Users/stephenjwild/.julia/packages/Turing/O1Pn0/src/inference/Inference.jl:143 [inlined]
>  [14] sample at /Users/stephenjwild/.julia/packages/Turing/O1Pn0/src/inference/Inference.jl:143 [inlined]
>  [15] #sample#1 at /Users/stephenjwild/.julia/packages/Turing/O1Pn0/src/inference/Inference.jl:133 [inlined]
>  [16] sample(::DynamicPPL.Model{var"#5#6",(:y, :Z),(),(),Tuple{Array{Float64,1},Array{Float64,2}},Tuple{}}, ::Turing.Inference.NUTS{Turing.Core.ForwardDiffAD{40},(),DiagEuclideanMetric}, ::Int64) at /Users/stephenjwild/.julia/packages/Turing/O1Pn0/src/inference/Inference.jl:133
>  [17] top-level scope at REPL[40]:1

Hope that's enough info.

**Comment by devmotion** [comment]
The error message
```julia
ERROR: MethodError: no method matching bijector(::DistributionsAD.TuringScalMvNormal{Array{Float64,1},Float64})
```
seems surprising (i.e., should not be possible) since it is defined in https://github.com/TuringLang/Bijectors.jl/blob/50bb27661d724976c0d6c008cf164d4d35515f9e/src/compat/distributionsad.jl#L12 which is loaded automatically when DistributionsAD is available, which itself is loaded by Turing.

Indeed, with the latest releases of Bijectors (0.8.14) and DistributionsAD (0.6.19) I get:
```julia
julia> using Bijectors, DistributionsAD

julia> bijector(TuringScalMvNormal(zeros(3), 1.0))
Identity{1}()
```

Can you make sure that you do not use outdated versions of these packages?

**Comment by sjwild** [comment]
I went and double-checked, and I am using the most recent versions of both packages.


> (@v1.5) pkg> status Bijectors
> Status `~/.julia/environments/v1.5/Project.toml`
>   [76274a88] Bijectors v0.8.14

> (@v1.5) pkg> status DistributionsAD
> Status `~/.julia/environments/v1.5/Project.toml`
>   [ced4e74d] DistributionsAD v0.6.19

**Comment by sjwild** [comment]
Update: I got it to work after the third time uninstalling and reinstalling Turing and related packages.  It worked this time, unlike the first two times. 

Apologies for the trouble.
