### ISSUE TITLE
suggested utility function to gather/flatten samples across chains

### ISSUE THREAD

**Issue by drbenvincent** [TuringLang/Turing.jl#1544]
Maybe something like this already exists and I missed it, but if not, this might be a useful idea as a utility function for working with samples from a model.

If you have a parameter vector, such as a set of regression coefficients `β`, then you can grab the values from this a single parameter value using `chains["β[1]"]` or `chains["β[1]"].data`. The latter gives you an array of size `[n_samples, nchains]`. That's fine.

There is also a useful utility function where you can select out all the `β` coefficients using `group(chains, "β").value.data` will give you an array sized `[n_samples, n_params, n_chains]`.

What would be very useful however is the ability to collapse the chains together so that you end up with an array sized `[n_samples * n_chains, n_params]`. This would have multiple uses:
- You might want to pass in such a 2d array to something like `density()` to get posterior density plots of all your `β` values.
- Posterior prediction / plotting. If you wanted to produce a spaghetti plot, being able to grab out sample parameters just by pulling out a row from this 2d array, would be good.

I have a very basic implementation at the moment because I have an active need for it
```julia
function get_matrix(chains, param_name)
    array_of_samples = group(chains, param_name).value.data
    n_samples, n_params, n_chains = size(array_of_samples)
    desired_2d_array = zeros(n_samples*n_chains, n_params)
    for p in 1:n_params
        desired_2d_array[:, p] = vec(array_of_samples[:,p,:])
    end
    return desired_2d_array
end

β = get_matrix(chains, "β")
```
So now `β` will be size `[n_samples * n_chains, n_params]`.

That function is pretty crude and is not meant to be a general solution. It wouldn't work give a 2d array of model parameters for example. Are there any utility functions like this that already exist? 

One idea might be to modify the existing `group()` function - for example, you could pass in the argument `flatten_chains=true` in order to get out a set of values flattened across chains.

Just some ideas... could be useful?

**Comment by devmotion** [comment]
It seems you might be looking for `pool_chain(chains)` or `Array(chains)` (which appends chains by default and is explained a bit more in https://github.com/TuringLang/MCMCChains.jl#exporting-chains)?

**Comment by drbenvincent** [comment]
Thanks. Looks like `β = Array(get_matrix(chains, "β"))` does exactly what I'm after.
