### ISSUE TITLE
RWMH inside Gibbs sampling

### ISSUE THREAD

**Issue by julianjohs** [TuringLang/Turing.jl#1556]
Dear all, 

I wrote a model which would use multiple RWMH samplers inside a Gibbs sampler. See the example below. 
It seems like the MH() function inside the Gibbs sampler would not use RWMH even though I supplied a covariance matrix. 
Am I making any mistake? Thanks in advance. 

In the picture, I used a very small covariance matrix to see if the chain would actually only make small steps. That seems to be the case for chn2 (see below), but not chn. 

```
# reproducible example

using Random, Distributions, Turing
using Plots, LinearAlgebra

# generate data
x = rand(Normal(5, 10), 200)
y = rand(LogNormal(-3, 2), 200)

# Turing model
@model function twomeans(x, y)
    # Set Priors
    μ ~ MvNormal(2, 3)
    σ ~ filldist(Exponential(1), 2)

    # Distributions of supplied data
    x .~ Normal(μ[1], σ[1])
    y .~ LogNormal(μ[2], σ[2])

end
mod = twomeans(x, y)

# generate covariance matrix for RWMH
# with small-valued VC matrix to check if we only see very small steps
vc_μ = convert(Array, 1e-2*I(2))
vc_σ = convert(Array, 1e-2*I(2))

# Sample via Gibbs: RWMH doesn't work
chn = sample(mod,
    Gibbs(
        MH(:μ, vc_μ),
        MH(:σ, vc_σ),
        ), 3_000 # draws
    )
#save values to df
chn_df = DataFrame(chn)

# This works
# define new VC matrix
vc_total = convert(Array, 1e-2*I(4))
# and sample from only one RWMH
chn2 = sample(mod, MH(vc_total), 3_000)

chn2_df = DataFrame(chn2)

# see that the steps from chn are very large - can't be the result of the supplied VC matrix!
plot(chn_df.iteration, hcat(chn_df."μ[1]", chn2_df."μ[1]"), label=["Gibbs-MH" "RWMH over all parameters"])

```

Thanks in advance!

**Comment by cpfiffer** [comment]
Yeah, this is a bug here:
https://github.com/TuringLang/Turing.jl/blob/a4d277855b760d63f9cbbb27889f11f5f20cd25e/src/inference/mh.jl#L158

It just sees a symbol in the first argument for `MH` and says "ah whatever time for static MH". I can fix that.

**Comment by cpfiffer** [comment]
So, I've changed my initial perspective to say this is only partially a bug. For within-Gibbs stuff in MH, we support a tuple or pair operation to specify what to do specifically with a parameter. The specification you have here is ambiguous because there could be other parameters:

```julia
Gibbs(
        MH(:μ, vc_μ),
        MH(:σ, vc_σ),
        ), 3_000 # draws
    )
```

The supported syntax requires tuples

```julia
Gibbs(
        MH((:μ, vc_μ)),
        MH((:σ, vc_σ)),
        ), 3_000 # draws
    )
```

or pairs

```julia
Gibbs(
        MH(:μ => vc_μ),
        MH(:σ => vc_σ),
        ), 3_000 # draws
    )
```

Neither of these will work at the moment though until #1557 goes through.

**Comment by julianjohs** [comment]
Thanks a lot!
