### ISSUE TITLE
Turing still thinking of “canned” packages?

### ISSUE THREAD

**Issue by nickeubank** [TuringLang/Turing.jl#1560]
I was recently watching the 2019 Turing.jl presentation from Julia con, and saw that there was discussion of creating some high-level model interfaces in the spirit of our rstanarm. I also found it mentioned in two very old issues￼￼￼: #460 #774. 

As somebody just moving into Bayesian analysis and hoping to be able to do it within Julia, this seems like it would be a great feature. Is this still something the project is pursuing?￼

(Let me know if this belongs on discourse and not here)￼

**Comment by cpfiffer** [comment]
I had some demo work on that [here](https://github.com/cpfiffer/BayesModels), but it never made it into a full production. There's been some interest from people in a more focused development process for it, but I don't have a lot of time nowadays.

**Comment by nickeubank** [comment]
That's great! That's exactly the kind of think I think would be really helpful for beginners.

**Comment by yebai** [comment]
Please see https://github.com/TuringLang/TuringGLM.jl
