### ISSUE TITLE
Issues with conditionals inside loops?

### ISSUE THREAD

**Issue by bratslavia** [TuringLang/Turing.jl#1562]
I have a problem where I want to model an array of parameters, some of which are constrained in certain ways. I wanted to benchmark some different approaches, but ran into an error with one of the approaches I planned to try:

```julia
using Turing

@model loop1_test(data, constraints) = begin
    mu ~ arraydist([Truncated(Normal(0, 10), 0, Inf), Normal(0, 1)])

    for d in eachindex(data)
        if constraints[d]
            data[d] ~ Truncated(Normal(mu[1], 1), 0, Inf)
        else 
            data[d] ~ Normal(mu[2], 1)
        end
    end

end

# Make some test data, and indicators to assign distributions
testdat = rand(MvNormal(zeros(100), ones(100)), 5)
testconstraints = [(i==j) ? true : false for i in 1:100, j in 1:5]

m1 = sample(loop1_test(testdat, testconstraints), NUTS(50, 0.65), 50)
```

This produces nothing but numerical errors. I didn't know if this was somehow related to #1558? The indicator's not stochastic - it doesn't change during sampling - but it seems similar.

Also, is there an efficient way to handle this kind of situation, where a certain specific subset (known ahead of time) of parameters in a vector/matrix have different priors? In case anyone's curious, I'm trying to do a factor analysis, where certain parameters (the factor loadings) are constrained to be positive to handle reflection invariance.

The only method I have right now is to make a lot of separate singletons and vectors of parameters and then manually combine them into the proper arrays, which gets pretty impractical for anything more than a toy problem.

Edit:
I found a kind of work-around using a comprehension and `arraydist`:

```julia
mu ~ arraydist([x ? Truncated(Normal(0, 1), 0, Inf) : Normal(0, 1) for x in constraints])
```

Not sure if this is the best solution or not, but it seems to work.

**Comment by torfjelde** [comment]
Regarding the issue, I'm not certain.

But seems like the best approach is to just split `data`, no? E.g. 

```julia
@model function loop1_test(data_constrained, data_unconstrained)
    # ...

    data_constrained ~ filldist(trnucated(Normal(mu[1], 1), 0, Inf), length(data_constrained))
    data_unconstrained ~ filldist(Normal(mu[2], 1), length(data_unconstrained))
end
```

**Comment by bratslavia** [comment]
Thanks for the response - it's hard to tell from the MWE I made, but the issue I'm ultimately trying to deal with is that the parameters being constrained need to have a certain structure, and that structure makes doing separate "blocks" cumbersome.

So for example, I might have a matrix with two columns:

| C1 | C2 |
| --- | --- |
| 1 | 5  |
| 2 |  6 |
| 3 |  7 |
| 4 |  8 |

and I need one element from each column to have a distribution that's positively constrained. The complicating factor is that the constrained parameters have to be from different rows (otherwise it'd be simple to combine them the way you suggest). So for example, I might want to constrain parameter 2 in Column 1, and parameter 8 in column 2. And the choice can affect the quality of the model, so I'd like to be able to change which parameters are constrained very easily.

Still, that's what I had been doing until now -- making a bunch of different distributions for specific constrained parameters, and then combining them later into the matrix I actually needed using a mess of `vcat` and `hcat` calls. 

That works for small models, but my real data has hundreds of rows, and tens of columns; it quickly becomes too messy and difficult to write. That's why I was looking for "cleaner" ways to generate/use heterogenous priors for values of an array.

Of course, while I think I've found something that works for this particular problem, I'm still curious about the error in the original code -- it surprised me that I could not use an `if-then` statement inside the loop.

**Comment by torfjelde** [comment]
Ah, I see :+1: 
And for the record, I agree; it's weird that it doesn't work properly!

**Comment by devmotion** [comment]
To me it seems, the problem is that the data is not consistent with the model: all the data is sampled from an unconstrained multivariate normal distribution but you impose a truncated normal distribution as prior for some of the data points.

The following works as expected (note that one should use `truncated` instead of `Truncated`, as already shown by @torfjelde above - `Truncated` always returns an instance of type `Truncated` whereas `truncated` can yield optimized implementations for different distributions):
```julia
using Turing

@model function loop1_test(data, constraints)
    mu ~ arraydist([truncated(Normal(0, 10), 0, Inf), Normal(0, 1)])

    for d in eachindex(data)
        if constraints[d]
            data[d] ~ truncated(Normal(mu[1], 1), 0, Inf)
        else 
            data[d] ~ Normal(mu[2], 1)
        end
    end
end

testdat = rand(100, 5)
testconstraints = [i == j for i in 1:100, j in 1:5]

sample(loop1_test(testdat, testconstraints), NUTS(50, 0.65), 50)
```

The following works as well since all data with truncated prior is guaranteed to be non-negative:
```julia
using LinearAlgebra

testdat = rand(MvNormal(zeros(100), ones(100)), 5)
testdat[diagind(testdat)] .= abs.(testdat[diagind(testdat)])
testconstraints = [i == j for i in 1:100, j in 1:5]

sample(loop1_test(testdat, testconstraints), NUTS(50, 0.65), 50)
```

**Comment by bratslavia** [comment]
> To me it seems, the problem is that the data is not consistent with the model: all the data is sampled from an unconstrained multivariate normal distribution but you impose a truncated normal distribution as prior for some of the data points.

You can't hear the sound of my head hitting my desk, but I assure you it's there! 

In my "real" application, the truncation is over parameters, not data, so my brain completely ignored the incompatibility of the model and data used in the snippet I was testing.

Well, I didn't know that about `truncated`, so at least I learned something new in exchange for my embarrassment. :)

Thanks!

**Comment by devmotion** [comment]
I guess the issue can be closed then? :slightly_smiling_face:

**Comment by bratslavia** [comment]
Please do! And thanks for the reality check.
