### ISSUE TITLE
Does `particle_gibbs` perform filtering or smoothing?

### ISSUE THREAD

**Issue by chentau** [TuringLang/Turing.jl#1566]
Hi,

I have a very simple state-space model that I would like to fit:

```julia
using Turing
import StatsFuns: logistic
@model function state_space(x)
  # T = size(x)[2]
  T = length(x)
  z = Vector(undef, T)
  z[1] ~ Normal(0, 1)
  x[1] ~ Bernoulli(logistic(z[1]))
  for i in 2:T
    z[i] ~ Normal(z[i - 1], 1)
    x[i] ~ Bernoulli(logistic(z[i]))
  end
end


data = [ones(25); zeros(25)]
chain = sample(state_space(data), PG(100), 1000)
```

I'd like to do filtering but not smoothing for this model: that is, I want to estimate `p(z_t | x_1, \ldots x_t)` but not `p(z_t | x_1, \ldots x_T)`.
Upon fitting the model, I get the following posterior trajectory:

```julia
using Plots
y = zeros(50)
for i in 1:50
  y[i] = mean(chain["z[$i]"])
end
plot(y)
```

![filter_post](https://user-images.githubusercontent.com/36219739/113219126-a4c18500-9235-11eb-982b-20552e8c2658.png)

To me (and obv I could be wrong about this), this looks more like a smoothed posterior, since I would expect the estimates under a particle filter to increase monotonically until index 25, whereas this posterior starts dipping much sooner. So I was wondering: does the `PG` sampler uses the entire trajectory `x[1:T]` when estimating each value of `z[t]`? And if so, is there any way to force it to only use the first `t` observations instead of the entire trajectory?

**Comment by yebai** [comment]
`particle_gibbs` performs smoothing.
