### ISSUE TITLE
Multithreaded sampling with PG causes segfaults on Julia 1.5.4

### ISSUE THREAD

**Issue by devmotion** [TuringLang/Turing.jl#1571]
Multithreaded sampling with PG in test/inference/Inference.jl causes segfaults on Julia 1.5.4. Julia 1.5.3 works fine.

ref: https://github.com/TuringLang/Turing.jl/pull/1568#issuecomment-814105251

**Comment by yebai** [comment]
We currently lack support for parallel `PG`/`SMC`.
