### ISSUE TITLE
Odd issue with certain arraydist contents, ReverseDiff, and sum

### ISSUE THREAD

**Issue by bratslavia** [TuringLang/Turing.jl#1573]
I'm scratching my head at this a bit...

I have a Turing model where one variable has a prior in the form of a P x D arraydist. I have to take the column-wise sum of the resulting variable in my model.

However, certain combinations of distributions inside the arraydist cause problems when using ReverseDiff. See my MWE below:

```julia
using Turing, ReverseDiff

@model mwe(a) = begin
    w ~ arraydist(a)
    sum(w; dims=1)
end

Turing.setadbackend(:reversediff)

a1 = [Normal(0, 1), Normal(0, 10)]
a2 = [truncated(Normal(0, 10), 0, Inf), truncated(Normal(0, 10), 0, Inf)]
a3 = [truncated(Normal(0, 10), 0, Inf), Normal(0, 10)]
a4 = [InverseGamma(1, 1), Normal(0, 10)]

m1 = sample(mwe(a1), NUTS(10, 0.65), MCMCThreads(), 10, 4)
m2 = sample(mwe(a2), NUTS(10, 0.65), MCMCThreads(), 10, 4)
m3 = sample(mwe(a3), NUTS(10, 0.65), MCMCThreads(), 10, 4)
m4 = sample(mwe(a4), NUTS(10, 0.65), MCMCThreads(), 10, 4)
```

- If I use **ForwardDiff**, all models work fine. 
- If I use **ReverseDiff**, priors `a1` and `a2` work fine, but priors `a3` and `a4` cause errors in the `sum` function.
- If I remove the `sum` function, the model works fine (but in my real model, I need the sum function).
- If I remove the `dims` argument in `sum`, `a3` and `a4` work (but only in this MWE; my real model has a P x D prior, where D can be as low as 1, so I need to keep the the dims argument. But of course, it should work with dims=1 anyway).

I tried searching, and didn't see any Github issues or posts that seemed obviously related to this. If it matters, my particular problem looks more like `a3`.

Any idea what's going on? This is on Julia 1.6, Turing 0.15.1, and ReverseDiff 1.7.0 (but I confirmed the same behavior on 1.5.4/ 0.15.13/1.7.0).

For completeness, here's the relevant part of the error I get:
```julia
nested task error: MethodError: no method matching valtype(::Type{ReverseDiff.TrackedReal{Float64, Float64, O} where O})
        Closest candidates are:
          valtype(::ReverseDiff.TrackedReal{V, D, O} where {D<:Real, O}) where V at C:\Users\opus\.julia\packages\ReverseDiff\iHmB4\src\tracked.jl:110
          valtype(::Type{ReverseDiff.TrackedReal{V, D, O}}) where {V, D, O} at C:\Users\opus\.julia\packages\ReverseDiff\iHmB4\src\tracked.jl:111  
          valtype(::ReverseDiff.TrackedArray{V, D, N, VA, DA} where {D, N, VA, DA}) where V at C:\Users\opus\.julia\packages\ReverseDiff\iHmB4\src\tracked.jl:112
          ...
        Stacktrace:
          [1] convert(#unused#::Type{ReverseDiff.TrackedReal{Float64, Float64, O} where O}, x::Int64)
            @ ReverseDiff ~\.julia\packages\ReverseDiff\iHmB4\src\tracked.jl:264
          [2] zero(#unused#::Type{ReverseDiff.TrackedReal{Float64, Float64, O} where O})
            @ Base .\number.jl:261
          [3] _reducedim_init(f::typeof(identity), op::typeof(Base.add_sum), fv::typeof(zero), fop::typeof(sum), A::Vector{ReverseDiff.TrackedReal{Float64, Float64, O} where O}, region::Int64)
            @ Base .\reducedim.jl:117
          [4] reducedim_init(f::Function, op::typeof(Base.add_sum), A::Vector{ReverseDiff.TrackedReal{Float64, Float64, O} where O}, region::Int64)            @ Base .\reducedim.jl:109
          [5] _mapreduce_dim(f::Function, op::Function, #unused#::Base._InitialValue, A::Vector{ReverseDiff.TrackedReal{Float64, Float64, O} where 
O}, dims::Int64)
            @ Base .\reducedim.jl:324
          [6] #mapreduce#672
            @ .\reducedim.jl:310 [inlined]
          [7] #_sum#702
            @ .\reducedim.jl:900 [inlined]
          [8] _sum
            @ .\reducedim.jl:900 [inlined]
          [9] #_sum#701
            @ .\reducedim.jl:899 [inlined]
         [10] _sum
            @ .\reducedim.jl:899 [inlined]
         [11] #sum#679
            @ .\reducedim.jl:873 [inlined]
```

**Comment by bratslavia** [comment]
I also just noticed that `a3` and `a4` are apparently type-unstable, too (although that's not related to the issue). Although looking at the code, I suppose it seems a bit obvious now.

Constructing the vector as a Union seems to work pretty well and (if I remove the `sum` so the MWE above works) gives a nice speed-up:
```julia
a5 = Union{InverseGamma{<:Real}, Normal{<:Real}}[InverseGamma(1, 1), Normal(0, 10)]
m5 = sample(mwe(a5), NUTS(10, 0.65), MCMCThreads(), 10, 4)
```

**Comment by bratslavia** [comment]
As a temporary workaround, replacing `sum(x; dims=1)` with a simple sum over columns seems to work:

```julia
@model mwe(a) = begin
    w ~ arraydist(a)
    [sum(e) for e in eachcol(w)]
end
```

**Comment by torfjelde** [comment]
@mohamed82008 might be the best to answer this given that it's related to ReverseDiff?

**Comment by mohamed82008** [comment]
Ya things get iffy with ReverseDiff if you have Vector{<:Any}. I can look into why it's happening but I am not sure if I will be able to fix it.

**Comment by mohamed82008** [comment]
This is a ReverseDiff bug.

**Comment by bratslavia** [comment]
Interesting. If it matters at at all, I still see the same behavior even if I use two truncated distributions (with different truncation points), even through they appear to be the same type. E.g., 

```julia
using Turing, ReverseDiff

@model mwe(a) = begin
    w ~ arraydist(a)
    sum(w; dims=1)
end

Turing.setadbackend(:reversediff)

a1 = [truncated(Normal(0, 10), -Inf, Inf), truncated(Normal(0, 10), 0, Inf)]
m1 = sample(mwe(a1), NUTS(10, 0.65), MCMCThreads(), 10, 4)

typeof(a1[1]) == typeof(a1[2]) # Same types
```

**Comment by mohamed82008** [comment]
ya this is serious I will fix it in the weekend

**Comment by mohamed82008** [comment]
https://github.com/JuliaDiff/ReverseDiff.jl/pull/173

**Comment by mohamed82008** [comment]
New release underway https://github.com/JuliaRegistries/General/pull/34580
