### ISSUE TITLE
_params_to_array is very slow

### ISSUE THREAD

**Issue by haozhangphd** [TuringLang/Turing.jl#1584]
I am using Turing on a model with ~2 million parameters, I found out that doing just one sample takes 20 minutes. The time is almost exclusively taken by the `_params_to_array` function. In particular, line 252 to 256 of Inference.jl is equivalent to the following function
```
function foo(nms)
    names = Vector{Symbol}()
    for nm in nms
        if !(nm in names)
            push!(names, nm)
        end
    end
    return names
end
```
This is inefficient because testing for membership of a `Vector{Symbol}` is not efficient. We can modify this implementation to the following

```
function bar(nms)
    names = Vector{Symbol}()
    append!(names, nms)
    unique!(names)
    return names
end
```

Giving an argument of `nms = [Symbol("param_", i) for i in 1:2000000]`,  `foo(nms)` takes ~20 minutes to run, while `bar(nms)` takes 0.5 seconds.

Can we change the implementation of `_params_to_array`  in the same fashion?
```
function _params_to_array(ts::Vector)
    names = Vector{Symbol}()
    # Extract the parameter names and values from each transition.
    dicts = map(ts) do t
        nms, vs = flatten_namedtuple(getparams(t))
        append!(names, nms)
        # Convert the names and values to a single dictionary.
        return Dict(nms[j] => vs[j] for j in 1:length(vs))
    end
    unique!(names)
    vals = [get(dicts[i], key, missing) for i in eachindex(dicts), 
        (j, key) in enumerate(names)]

    return names, vals
end
```

**Comment by cpfiffer** [comment]
Yes, absolutely! Would you like to open a PR for it?

**Comment by haozhangphd** [comment]
Actually I have a question. For this code fragment
```
    dicts = map(ts) do t
        nms, vs = flatten_namedtuple(getparams(t))
        for nm in nms
            push!(names_set, nm)
        end
        # Convert the names and values to a single dictionary.
        return Dict(nms[j] => vs[j] for j in 1:length(vs))
    end
```
When will different `t` in the vector `ts` have different set of `nms`? Please forgive my naive understanding. Each `t` in `ts` is a transition, and I thought all of the transitions are working with the *same* set of parameter names?

**Comment by devmotion** [comment]
Not necessarily. Eg the size of multivariate variables can be different which leads to different names (they include the indices). IIRC this is actually the case in one of the SMC or PG tutorials.

**Comment by haozhangphd** [comment]
Thank you very much! I will look up more closely in the tutorials.
