### ISSUE TITLE
Some tests for MH fail for certain random seeds

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/Turing.jl#1587]
Ref: https://github.com/TuringLang/Turing.jl/pull/1567#issuecomment-817377941

This is where the failure happens: https://github.com/TuringLang/Turing.jl/blob/master/test/inference/mh.jl#L149-L152
In particular `v2` can sometimes be 0 (i.e. all samples are rejected).

**Comment by yebai** [comment]
Likely fixed by recent bumps to number of MCMC samples.
