### ISSUE TITLE
Sample from prior using inference algorithm

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/Turing.jl#1591]
As pointed out in [this Discourse thread](https://discourse.julialang.org/t/turing-jl-prior-on-quantiles/59510/4), there are cases where you sampling from the prior does not necessarily mean `sample(model, Prior(), num_samples)`, e.g. if you are "manually" making certain adjustments to the logjoint using `addlogrob!`. In these cases we need to use an actual inference algorithm to perform sampling.

As demonstrated in the thread, it's *possible* to do atm but requires a lot of manual work which seems unnecessary.

IMO we should provide a convenient way of doing this, e.g. make `Prior` optionally wrap an `alg` so it becomes`sample(model, Prior(NUTS()), num_samples)`. This also probably requires making `DynamicPPL.initialsampler` a bit more flexible, e.g. allow specification of `Context`.

**Comment by yebai** [comment]
We now have a `Prior()` sampler.
