### ISSUE TITLE
Feature Request: Additional Macros

### ISSUE THREAD

**Issue by ghost** [TuringLang/Turing.jl#1603]
Suggested macros that could improve code readability and help people using Turing.jl:

- [ `@noncentered` macro that converts a centered parametrization to a noncentered one ] 
- [ `@standardize` macro that tells the compiler to standardize a variable before doing inference with it, so that priors can be set by the programmer on the original scale (which might be more intuitive to work with) ] 
- [ `@tarray` macro that converts a DataFrame or normal Julia array into a TArray ]

**Comment by devmotion** [comment]
> [ @tarray macro that converts a DataFrame or normal Julia array into a TArray ]

Isn't `TArray(x)` or `convert(TArray, x)` sufficiently simple?

**Comment by torfjelde** [comment]
The two first points would be covered by https://github.com/TuringLang/DynamicPPL.jl/pull/220, though not automatic. That PR is on hold atm as I'll be quite occupied this week, but will return to it next week.

**Comment by Closed-Limelike-Curves** [comment]
> > [ @tarray macro that converts a DataFrame or normal Julia array into a TArray ]
> 
> Isn't `TArray(x)` or `convert(TArray, x)` sufficiently simple?

In the case of regular arrays, I think so. For DataFrames, it may be worth implementing something which can preserve column labels more easily.

**Comment by devmotion** [comment]
Maybe one can just use `TArray(StructArray(df))` but I think nobody has ever tried to use non-standard arrays with Libtask and so some things might not work.

**Comment by Closed-Limelike-Curves** [comment]
> Maybe one can just use `TArray(StructArray(df))` but I think nobody has ever tried to use non-standard arrays with Libtask and so some things might not work.

Hmm -- maybe this can be done by working with some of the features in KeyedDistributions.jl, so that you can use something like `TKeyedArray(KeyedArray)` which is just a `TArray` that keeps track of the keys from the `KeyedArray`.

**Comment by devmotion** [comment]
There should be no need for a different `TKeyedArray` - `TArray` is supposed to work with general `AbstractArray`s. I just don't think anyone has ever tested or used it with anything else than `Array`s, and I don't know if it's a good idea here since it would copy always the whole array, i.e., for all keys, and I am not sure if this is desired. I guess often it might be better to unpack the desired components before constructing the `TArray`.

**Comment by storopoli** [comment]
What about a `@qr` macro that would QR-decompose a matrix of data `X`.

I would use it a lot in my regression models.

**Comment by torfjelde** [comment]
> What about a @qr macro that would QR-decompose a matrix of data X.

I feel like I'm missing something: how is this "easier" to write than just `qr(X)`? :confused:

**Comment by storopoli** [comment]
We don’t have to reconstruct the coefficients back to interpret them or make a whole boilerplate code to have the model returning those coefficients.

I might be missing something….

**Comment by torfjelde** [comment]
Could you give an example? Things are still a bit unclear to me :confused:

**Comment by storopoli** [comment]
My deeply apologies. Let me make it clear (I need to stop the habit of commenting PR and issues in my mobile...).

Take the example of the proposed `@standardize` macro. We could do it with:

```julia
using MLDataUtils: rescale!

# Rescale data
μ, σ = rescale!(df[!, features])

X = Matrix(df[:, features])
y = df[:, :y]

# then we need to rebuild the coefficients β back with something like

betas = mapslices(x -> σ * x + μ, chain[:, namesingroup(chain, :β),:].value.data, dims=[2])
chain_reconstructed = hcat(Chains(betas, ["real_β[$i]" for i in 1:size(X, 2)]), chain)
```

The same with QR decomposition:

```julia
using LinearAlgebra: qr

Q, R = qr(X)
Q_ast = Matrix(Q) * sqrt(size(X, 1) - 1)
R_ast = R / sqrt(size(X, 1) - 1);

model_qr = model(Q_ast, y)
chain_qr = sample(model_qr, ...)

# Reconstruction
betas = mapslices(x -> R_ast^-1 * x, chain_qr[:, namesingroup(chain_qr, :β),:].value.data, dims=[2])
chain_qr_reconstructed = hcat(Chains(betas, ["real_β[$i]" for i in 1:size(Q_ast, 2)]), chain_qr)
```

Would be real nice to have something like:

```julia

@model linreg(X, y; predictors=size(X, 2)) = begin
	#priors
	@qr(X) # <<< this
	α ~ Normal(mean(y), 2.5 * std(y))
	β ~ filldist(TDist(3), predictors)
	σ ~ Exponential(1)

	#likelihood
	y ~ MvNormal(α .+ X * β, σ)
end
```

And then it does everything for you and recovers back the original β's for interpretation.

**Comment by yebai** [comment]
Ideally, we can keep the number of macros minimal in Turing. Many advanced functionalities can be implemented via other mechanisms like multi-dispatching. Also, certain features like `noncentered` are probably better archived via a tutorial instead of more compiler transforms - my view is that `DynamicPPL` should only provide a tool for specifying models. The result should be addressed elsewhere.
