### ISSUE TITLE
Issue replicating Regression and Other Stories linear model

### ISSUE THREAD

**Issue by tjburch** [TuringLang/Turing.jl#1620]
I'm trying to replicate the Pearson and Lee heights example from Regression and other stories, the R code can be found [here](https://avehtari.github.io/ROS-Examples/PearsonLee/heights.html). The results I'm producing from Turing are different than those they show in R (the [python port](https://github.com/bambinos/Bambi_resources/blob/master/ROS/PearsonLee/heights.ipynb) also gets the same values as the original).

Code to replicate:

```
using DataFrames, StatsPlots, CSV, HTTP, Random
using Distributions, Turing, MCMCChains
data = "https://raw.githubusercontent.com/avehtari/ROS-Examples/master/PearsonLee/data/Heights.txt"
heights = CSV.File(HTTP.get(data).body, delim=" ") |> DataFrame
@model function m1(h_m, h_d)
    σ ~ Exponential(3)
    α ~ Normal(0, 100)
    β ~ Normal(0, 10)
    μ = α .+ β * h_m
    h_d ~ MvNormal(μ, σ)
end;
model1 = m1(heights.daughter_height, heights.mother_height)
fit1 = sample(model1, NUTS(), 4000)
summarystats(fit1)
```
gives a mean of:

σ = 32.99
α = 0.42
β = 2.08

Compared to the original notebook of 29.81, 0.54, and 2.26 respectively.

Any suggestions?

**Comment by devmotion** [comment]
> @model function m1(h_m, h_d)

and

> model1 = m1(heights.daughter_height, heights.mother_height)

seem inconsistent, maybe the arguments should be switched?

**Comment by tjburch** [comment]
Yep, that'll do it. Can't believe how long I stared at this and missed that. Sorry for the noise - thanks @devmotion.
