### ISSUE TITLE
Dealing with different parameter subspaces

### ISSUE THREAD

**Issue by marius311** [TuringLang/Turing.jl#1625]
It was suggested on Slack to ask this here. Basically I'm implementing a custom estimator based on a Turing PDF which needs gradients w.r.t. to different user-specified sub-spaces of the parameters and does something slightly differently with each. More or less something like:

```julia
@model function funnel(x=missing)
    θ ~ Uniform(-10, 10)
    z ~ MvNormal(zeros(50), exp(θ/2))
    x ~ MvNormal(z, 1)
end

x = funnel()()
model = funnel(x)

myestimate(model, subspace1=:θ, subspace2=:z)
```

and inside `myestimate` I need to do `gradient_logp(model)` w.r.t. `θ` and w.r.t. to `z` separately (one call would be ok too, as long as I know which indices in the gradient vector are which, granted this would lead to some wasted computation). 

I suspect this is what `Selector` is for but I'm having trouble parsing the code. If I'm wrong about this, any suggestions how to go about this would be very helpful anyway.

**Comment by devmotion** [comment]
`Selector` is only used in Gibbs sampling and isn't actually needed there anymore, as discussed in https://github.com/TuringLang/Turing.jl/pull/1500#discussion_r564677990. I suggested to remove it but forgot about it and one would have to check first if it could be used to improve performance (which apparently was the reason why it was added initially).

**Comment by devmotion** [comment]
I guess you just have to define a function such as https://github.com/TuringLang/Turing.jl/blob/11fee520050226821624e3451218bb2cbfb2acbf/src/core/ad.jl#L109-L115 (and the ones for other AD backends) for whatever subset of parameters you're interested in, and then compute the gradient manually, similar to the implementation of `gradient_logp`.

**Comment by marius311** [comment]
Thanks, thats helpful to know. So is it fair to say to do what I'm looking for I should instead try to understand the code regarding `space` ?

**Comment by devmotion** [comment]
You could just define a function that sets your parameters and evaluates the log pdf, similar to the example in the implementation of `gradient_logp` that I linked to above. I think this would be the most straightforward approach, and e.g. also used in the MLE/MAP functionality in Turing: https://github.com/TuringLang/Turing.jl/blob/11fee520050226821624e3451218bb2cbfb2acbf/src/modes/ModeEstimation.jl#L142-L148

**Comment by marius311** [comment]
Thanks for your replies, thats very helpful. Still trying this out, will report back if this is what I needed.
