### ISSUE TITLE
Don't `sort` chain by default

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/Turing.jl#1626]
IMO we should drop the `sort` from https://github.com/TuringLang/Turing.jl/blob/11fee520050226821624e3451218bb2cbfb2acbf/src/inference/Inference.jl#L359-L365

Reasons:
- Performance. For larger chains, the `sort` is actually really expensive.
- Chain having the same order as the underlying `VarInfo` simplifies a lot, e.g. bugs relating to `DynamicPPL.setval!` and `DynamicPPL.setval_and_resample!`, which then propopagates to `predict` and `generated_quantities`, keep popping up and these could completely be avoided.
  - Ideally we'd of course have a better solution, allowing values to be set using whatever ordering, but that is a non-trivial task AFAIK.
- IMO the `NaturalSort` that we're using doesn't make much sense in a lot of the cases, e.g. `x[1, 2] < x[2, 1]` which in turn means that when the user does `reshape(MCMCChains.group(chain, :x).value, ...)` they won't get the correct results back.
  - Of course this won't be resolved by not doing any sorting whatsoever, but it will resolve the simpler cases, e.g. `x ~ MvNormal(...)`, which are often those causing confusion.
  - I would also argue that it's more intuitive for the user that ordering follows execution order by default rather than a lexical sort that results in indices not being column-major.
    - Also, the user will likely just _observe_ the behavior and realize the ordering scheme being used, which is not as easy to realize with the current sorting.

Thoughts? @devmotion @yebai @cpfiffer

**Comment by cpfiffer** [comment]
I'm fine with it, as long as we add a keyword argument to turn it back on if people choose.

**Comment by devmotion** [comment]
Yes, I think the best would probably be a keyword argument (came up in some other issue not too long ago but I don't remember where).
