### ISSUE TITLE
Question: Broken link

### ISSUE THREAD

**Issue by Gregliest** [TuringLang/Turing.jl#1635]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_tutorials/04_hidden-markov-model.md

Link for "(more here on why this is useful)" is broken. Looks like it goes to https://turing.ml/docs/autodiff/, but maybe should go to https://turing.ml/dev/docs/using-turing/autodiff?

**Comment by cpfiffer** [comment]
Fixed upstream in https://github.com/TuringLang/TuringTutorials. It'll take a while for the changes to propagate, though.

Thanks!
