### ISSUE TITLE
No mixing in simple ODE model

### ISSUE THREAD

**Issue by fkrauer** [TuringLang/Turing.jl#1638]
Hi

I am new to Turing/Julia and I am trying to fit an epidemiological ODE model to data, but I just cannot get it to run properly. The complexity is slightly higher than the predator-prey model in your tutorials, but it is not an overly complicated model. I have rescaled all parameter so that they are [0,1]. 

I have pasted a MWE below, which has the following problems:
1) takes hours to complete (with only 1500 iterations and despite 3 threads)
2) does not mix at all (see plots below) 
3) the progress bar does not show either. 

I do get an `Info: Found initial step size` and some `Warning: The current proposal will be rejected due to numerical error(s). Isfinite [...] (true, true, false, true)`. 

I appreciate any help, thanks.

chains after 1500 iterations:
![SIR_NUTS_mixing](https://user-images.githubusercontent.com/36159611/121810751-4f0c4e80-cc62-11eb-92af-798e39f0b890.png)

code
```
using DifferentialEquations
using StatsPlots
using Turing
using Distributions
using Random
using StatsBase
using LabelledArrays

Random.seed!(42)

# ODE model: simple SIR model with seasonally forced contact rate
function SIR!(du,u,p,t)

    # states
    (S, I, R) = u[1:3]
    N = S + I + R
  
    # params
    β = p.β
    η = p.η
    φ = p.φ*364.0
    ω = p.ω
    μ = p.μ
    σ = p.σ
      
    # FOI
    βeff = β * (1.0+η*sin(2.0*π*(t-φ)/365.0))
    λ = βeff*I/N

    # change in states
    @inbounds begin
    du[1] = (μ*N - λ*S - μ*S + ω*R)
    du[2] = (λ*S - σ*I - μ*I)
    du[3] = (σ*I - μ*R - ω*R)
    du[4] = (σ*I) # cumulative incidence
    end
end
  
# Calculate incident cases from cumulative incidence
function get_incidence(sol)
    incidence = [sol.u[t].C - sol.u[t-1].C  for t = 2:length(sol.u)]
    incidence = ifelse.(incidence .< 0.0, 0.0, incidence)
    return incidence
end

# Solver settings
tmin = 0.0
tmax = 10.0*365.0
tspan = (tmin, tmax)
solvsettings = (abstol = 1.0e-6, 
                reltol = 1.0e-3, 
                saveat = 7.0,
                solver = Tsit5()) #AutoTsit5(Rosenbrock23())) #Tsit5()) # #AutoVern7(Rodas5()))

# Initiate ODE problem
theta_fix =  [1.0/(80*365), 1.0/5.0]
theta_est =  [0.28, 0.07, 1/365.0, 20]
p = @LArray [theta_est; theta_fix] (:β, :η, :ω, :φ, :μ, :σ)
u0 = @LArray [9998.0,1.0,1.0,1.0] (:S,:I,:R,:C)


# Initiate ODE problem
problem = ODEProblem(SIR!,u0,tspan,p)
sol = solve(problem, 
            solvsettings.solver, 
            abstol=solvsettings.abstol, 
            reltol=solvsettings.reltol, 
            isoutofdomain=(u,p,t)->any(x->x<0.0,u), 
            saveat=solvsettings.saveat)
#plot(sol)
incidence = get_incidence(sol)
#plot(incidence)

# Fake some data from model
data = round.(incidence .* rand(Uniform(0.5,1.5), size(incidence)))
#plot(incidence, legend = false); scatter!(data,legend = false)

# Fit model to fake data

# Set up as Turing model
Turing.setprogress!(true)
Turing.setadbackend(:forwarddiff)

@model turingmodel(data, problem, theta_fix, solvsettings) = begin

    # Priors
    β ~ Uniform(0.0,1.0) #truncated(Normal(0.5, 0.25), 0.0, 1.0) #
    η ~ Uniform(0.0,1.0)  #truncated(Normal(0.5, 0.25), 0.0, 1.0) #
    ω ~ Uniform(1/(5.0*365.0),1.0) #truncated(Normal(365.0, 365.0), 1.0, 5.0*365.0) #
    φ ~ Uniform(0.0,1.0)
    p_new = @LArray [β, η, ω, φ, theta_fix...] (:β, :η, :ω, :φ, :μ, :σ)
    # Update problem and solve ODEs
    problem_new = remake(problem, p=p_new) 
 
    sol_new = solve(problem_new, 
                    solvsettings.solver, 
                    abstol=solvsettings.abstol, 
                    reltol=solvsettings.reltol, 
                    isoutofdomain=(u,p,t)->any(x->x<0.0,u), 
                    saveat=solvsettings.saveat)

    #incidence = [sol_new.u[t].C - sol_new.u[t-1].C  for t = 2:length(sol_new.u)]
    cumul = Array(sol_new)[4,:] # Cumulative cases
    incidence = cumul[2:end] - cumul[1:(end-1)]
    incidence = ifelse.(incidence .< 0.0, 0.0, incidence)

    #incidence = get_incidence(sol_new)
    for i = 1:length(incidence)
        data[i] ~ Poisson(incidence[i])
    end
end

model = turingmodel(data, problem, theta_fix, solvsettings)

# Fit 3 independent chains with multithreading
@time chains = sample(model, NUTS(), MCMCThreads(), 1500, 3, progress=true) 

```

**Comment by itsdfish** [comment]
One reason a model can run slow is if it the log likelihood is slow to evaluate. However, that does not appear to be the case. It requires about .0003 seconds on my computer. I would expect the sampler to take less than a minute based on the this benchmark.

My best guess is that the geometry of the posterior distribution is irregular. NUTS works the best for a standard multivariate normal posterior. This would cause performance and convergence problems. Another possibility is that the model is unidentifiable. What happens if you estimate a single parameter?

**Comment by fkrauer** [comment]
If I just estimate beta, I have the same problem. This run took 5124 seconds. Changing the prior of beta to Beta(1,1) didn't improve things either. I have a suspicion that this has to do with the dual numbers that Turing produces during the AD, but I don't know how to address this issue. 
![SIR_NUTS_mixing_beta](https://user-images.githubusercontent.com/36159611/121962576-35a1fa00-cd69-11eb-838e-2aaccd6c95f6.png)

**Comment by itsdfish** [comment]
Yikes. This is indeed problematic.
