### ISSUE TITLE
Docstring for NUTS has a wrong name for a named arg

### ISSUE THREAD

**Issue by quildtide** [TuringLang/Turing.jl#1648]
https://github.com/TuringLang/Turing.jl/blob/dd5ce7eded5bd804377bd67cfb84307aeec0aea8/src/inference/hmc.jl#L337

Under the existing API, the last named arg `ϵ`, should actually be `init_ϵ` when given as a named arg (and for that specific constructor).

On the other hand, the actual field in the struct is called `ϵ`, but changing this around would break the existing API.

EDIT: an alternative solution that possibly (?) improves the API while not breaking it involves allowing that particular constructor to also understand `ϵ` as a named argument, in addition to `init_ϵ`

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/Turing.jl/pull/1649
