### ISSUE TITLE
Separate Out IS Into a New Package 

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/Turing.jl#1657]
As in the title, I'd like to propose separating out importance sampling into a new AdvancedIS package that includes both basic importance sampling and Pareto-Smoothed Importance Sampling, along with other algorithms to be added later (such as iterated moment matching, used [here](https://arxiv.org/pdf/1906.08850v1.pdf) to extend PSIS). I've already created a PSIS implementation that can be added to this if you're all interested, although I'm unsure what it would take to make it compatible with Turing.

**Comment by yebai** [comment]
Happy to create a new package for advanced importance sampling algorithms. For integration with Pareto-smoothed IS, you might want to take a look at the [`MCMCTempering`](https://github.com/TuringLang/MCMCTempering.jl) implementation, which provides an example of how to hook into Turing's DSL. We are also happy to help along the process. Also, the [`AdvancedPS` ](https://github.com/TuringLang/AdvancedPS.jl)package provides implementations of sequential Monte Carlo and particle MCMC sampling algorithms, which is related.
