### ISSUE TITLE
Documentation is not properly indexed by search engines

### ISSUE THREAD

**Issue by cloveranon** [TuringLang/Turing.jl#1659]
Take this page for example: https://turing.ml/dev/tutorials/02-logistic-regression/
Google and Bing are unable to find the page when searching either the title, quotes of entire paragraphs, or the url itself:
https://www.google.com/search?q=Turing.jl%20Bayesian%20Logistic%20Regression
https://www.google.com/search?q=%22In%20our%20example%2C%20we%27ll%20be%20working%20to%20predict%20whether%20someone%20is%20likely%20to%20default%20with%20a%20synthetic%20dataset%20found%20in%20the%20RDatasets%20package.%20This%20dataset%2C%20Defaults%2C%20comes%20from%20R%27s%20ISLR%20package%20and%20contains%20information%20on%20borrowers.%22
https://www.google.com/search?q=https%3A//turing.ml/dev/tutorials/02-logistic-regression/

Bing gives a more interesting result for the last one
![2021-07-13-090728_455x79_scrot](https://user-images.githubusercontent.com/58804713/125457309-6a850485-c469-4281-9979-ad609e81b726.png)
https://cc.bingj.com/cache.aspx?q=https%3A%2F%2Fturing.ml%2Fdev%2Ftutorials%2F02-logistic-regression%2F&d=4682790180358358&mkt=en-US&setlang=en-US&w=FWl1uc863KZRfKX_yyAY6Evm1kh-V-1z

EDIT: Possibly related? https://github.com/TuringLang/Turing.jl/issues/1647

**Comment by cpfiffer** [comment]
I don't have enough web-fu to understand this perfectly, but I wonder if it's because our robots.txt file points to a sitemap that does not seem to include the tutorials:

https://github.com/TuringLang/turing.ml/blob/gh-pages/dev/robots.txt
https://github.com/TuringLang/turing.ml/blob/gh-pages/dev/sitemap.xml

**Comment by yebai** [comment]
It seems work fine with keyword "Bayesian Logistic Regression Turing"
