### ISSUE TITLE
AbstractMCMC.step with different model at each step

### ISSUE THREAD

**Issue by acertain** [TuringLang/Turing.jl#1699]
I'm trying to implement EM. Towards that, I'd like to be able to specify a different model (/different conditioned values) in each MCMC step. Example:

```julia
model = condition(m, NamedTuple{(x,)}(2))
sampler = Sampler(NUTS(), model)
rng = Random.GLOBAL_RNG
sample, state = AbstractMCMC.step(rng, model, sampler)
model = condition(m, NamedTuple{(x,)}(4))
sample, state = AbstractMCMC.step(rng, model, sampler, state)
```

But at least HMC/NUTS stores the initial model & doesn't use the model passed at each step, so the second `step` still uses a model with `x = 2` (not `x = 4`).

Is this something that you'd consider supporting? Is there some other way I should do this?

**Comment by devmotion** [comment]
It's already supported by AbstractMCMC, I don't think there are any general limitations that disallow this use case. As far as I can tell the main issue might be a Turing-specific one: when the model is rerun, HMC uses `state.vi` as variables so I assume you should update the value of `x` in `state.vi` instead of creating a new model.

In general, if you want to do everything more automatically with `sample(...)`, maybe you could use something like
```julia
struct EMSampler{S} <: AbstractSampler
    sampler::S
end

# implement AbstractMCMC interface for `EMSampler` by forwarding everything to
# the corresponding call with `.sampler` and define
function AbstractMCMC.step(rng::AbstractRNG, model::AbstractModel, sampler::EMSampler, state; kwargs...)
    # update the state
    s = ....

    return step(rng, model, sampler, s; kwargs...)
end
```

**Comment by acertain** [comment]
`x` is not stored in`state.vi` after condition, I assume due to how condition works.

An issue with HMC is that the model is stored in closures in the `AHMC.Hamiltonian` created at the first step: https://github.com/TuringLang/Turing.jl/blob/master/src/inference/hmc.jl#L160-L164

**Comment by devmotion** [comment]
> `x` is not stored in`state.vi` after condition, I assume due to how condition works.

That's what I meant, I assume you would have to update `state.vi` manually currently.

> An issue with HMC is that the model is stored in closures in the `AHMC.Hamiltonian` created at the first step: https://github.com/TuringLang/Turing.jl/blob/master/src/inference/hmc.jl#L160-L164

As I said, this is an issue (at least in your case) with how Turing implements the HMC sampler. It's not a limitation of AbstractMCMC though it seems to me.

**Comment by yebai** [comment]
We will add this in https://github.com/TuringLang/Turing.jl/issues/1904
