### ISSUE TITLE
@code_warntype example from docs

### ISSUE THREAD

**Issue by robertdj** [TuringLang/Turing.jl#1702]
I'm trying out examples from the docs. The `tmodel` example for `@code_warntype` does not produce any output on My Machine (with Julia 1.6.0).
Am I missing something?

![image](https://user-images.githubusercontent.com/5703657/132404414-2619dfd5-f4e3-440b-beaa-de7a319b7cf9.png)

**Comment by devmotion** [comment]
The documentation is outdated, the internal dispatches changed. In more recent versions of DynamicPPL/Turing probably one has to use
```julia
@code_warntype model.f(
    model,
    Turing.VarInfo(model),
    Turing.SamplingContext(
        Random.GLOBAL_RNG, Turing.SampleFromPrior(), Turing.DefaultContext(),
    ),
    model.args...,
)
```
Can you check if it works?

**Comment by devmotion** [comment]
Basically, one tries to inspect type stability of the following call: https://github.com/TuringLang/DynamicPPL.jl/blob/86afffa967cb74d9e6d3551a9f91ed098300c257/src/model.jl#L465

**Comment by robertdj** [comment]
Your suggestion works 🥳 Thanks!

With your link I can see the function signature, but can you share how you found that?

**Comment by devmotion** [comment]
I contribute to DynamicPPL, so I know the code quite well 🙂
