### ISSUE TITLE
Stein Thinning

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/Turing.jl#1704]
Putting [this](https://arxiv.org/pdf/2005.03952.pdf) here as a suggestion for something I or someone else could work on later. It might speed up post-processing calculations (e.g. ParetoSmooth.jl) by letting you cut back on the chain length without losing accuracy; it also avoids having to discard burn-in samples.

**Comment by yebai** [comment]
It feels like the user should be in charge of this, rather than Turing automatically doing it. I am closing in on the principle of keeping Turing minimal and interoperable so users can combine Turing with addon libraries for more features.
