### ISSUE TITLE
Restricted parameters

### ISSUE THREAD

**Issue by robertdj** [TuringLang/Turing.jl#1708]
Hi

I want to do inference in a [Normal Inverse Gaussian distribution](https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/normalinversegaussian.jl), where the `β` parameter is restricted by the `α` parameter (`abs(β) < α`).

I have made the following model that resembles the `rand` method for the distribution:

```
using Turing

@model function nig(x)
    μ ~ Normal(0, 1)
    α ~ Exponential(1)
    δ ~ Exponential(1)

    β_limit = 0.99 * α
    β ~ TruncatedNormal(0, 1, -β_limit, β_limit)
    β = clamp(β, -β_limit, β_limit)
    γ = sqrt(α^2 - β^2)

    N = length(x)
    z ~ filldist(InverseGaussian(δ/γ, δ^2), N)
    x ~ arraydist([Normal(μ + β * z[i], sqrt(z[i])) for i in 1:N])
end
```

I sample with the following code.

```
μ = 0; α = 0.5; β = 0.0; δ = 1;
X = Distributions.NormalInverseGaussian(μ, α, β, δ)
data = rand(X, 1_000);

model = nig(data)
chain = Turing.sample(model, NUTS(), 1_000)
```

**My problem is that all the sampled values of `β` are identical.** How should I enforce the restriction?

I also get lots of rejected samples, but decreasing the factor 0.99 alleviates this. Without `clamp`'ing `β_limit`, I get samples where  `β > α` regardless of the value of `β_limit`.

With a fixed value of `β` everything works (e.g. by deleting `β` altogether). 

P.s.: Sorry for [cross-posting](https://discourse.julialang.org/t/normal-inverse-gaussian-distribution-in-turing/67831). Hoping for more luck here :-)

**Comment by devmotion** [comment]
Turing does not support distributions whose support is random, see eg https://github.com/TuringLang/Turing.jl/issues/1270 and https://github.com/TuringLang/Turing.jl/issues/1558.

A workaround is to define a custom distribution and bijector as described in https://github.com/TuringLang/Turing.jl/issues/1270 and https://github.com/TuringLang/Turing.jl/issues/1558.

**Comment by robertdj** [comment]
Thank you for the swift reply and links! I'll have a look.

**Comment by devmotion** [comment]
E.g., you could use:

```julia
using Turing

using LinearAlgebra
using Random

struct CustomDist <: ContinuousMultivariateDistribution end

function Base.rand(rng::Random.AbstractRNG, ::CustomDist)
    α = rand(rng, Exponential(1))
    β = rand(rng, truncated(Normal(), -α, α))
    return [α, β]
end

function Distributions.logpdf(::CustomDist, x::AbstractVector{<:Real})
    α, β = x
    return logpdf(Exponential(1), α) + logpdf(truncated(Normal(), -α, α), β)
end

function Bijectors.bijector(::CustomDist)
    # define bijector that transforms β based on the value of α
    mask = Bijectors.PartitionMask(2, [2], [1]) # 2 elements in vector, 2nd entry transformed based on 1st
    β_bijector = Bijectors.Coupling(mask) do α
        return Bijectors.TruncatedBijector(-α, α)
    end

    # bijector that transforms α and does not transform β 
    α_bijector = stack(Bijectors.Log{0}(), Identity{0}())

    return α_bijector ∘ β_bijector
end

@model function nig(x)
    μ ~ Normal()
    αβ ~ CustomDist()
    δ ~ Exponential(1)
    α, β = αβ
    x ~ filldist(NormalInverseGaussian(μ, α, β, δ), length(x))
end

μ = 0
α = 0.5
β = 0.0
δ = 1

Random.seed!(1234)
data = rand(NormalInverseGaussian(μ, α, β, δ), 1_000)

chain = sample(nig(data), NUTS(), 1_000)
```

With this seed I get (Julia 1.6.2)
```julia
julia> chain
Chains MCMC chain (1000×16×1 Array{Float64, 3}):

Iterations        = 501:1:1500
Number of chains  = 1
Samples per chain = 1000
Wall duration     = 21.66 seconds
Compute duration  = 21.66 seconds
parameters        = μ, αβ[1], αβ[2], δ
internals         = lp, n_steps, is_accept, acceptance_rate, log_density, hamiltonian_energy, hamiltonian_energy_error, max_hamiltonian_energy_error, tree_depth, numerical_error, step_size, nom_step_size

Summary Statistics
  parameters      mean       std   naive_se      mcse        ess      rhat   ess_per_sec
      Symbol   Float64   Float64    Float64   Float64    Float64   Float64       Float64

           μ   -0.0552    0.0494     0.0016    0.0024   455.8494    1.0016       21.0408
       αβ[1]    0.5009    0.0674     0.0021    0.0032   537.8974    0.9990       24.8279
       αβ[2]    0.0481    0.0344     0.0011    0.0015   458.4887    1.0023       21.1626
           δ    0.9715    0.0758     0.0024    0.0037   497.3237    1.0006       22.9552

Quantiles
  parameters      2.5%     25.0%     50.0%     75.0%     97.5%
      Symbol   Float64   Float64   Float64   Float64   Float64

           μ   -0.1581   -0.0879   -0.0529   -0.0207    0.0352
       αβ[1]    0.3797    0.4529    0.4944    0.5439    0.6393
       αβ[2]   -0.0110    0.0233    0.0455    0.0695    0.1211
           δ    0.8392    0.9167    0.9649    1.0200    1.1368
```

**Comment by robertdj** [comment]
Thanks a lot, it works like a charm :-)

**Comment by robertdj** [comment]
I have one more question :-) 
In some cases sampling directly from the NIG distribution gives numerical errors due to the Bessel function in its pdf:

> AmosException with id 4: input argument magnitude too large, complete loss of accuracy by argument reduction.

That is the reason why I tried to sample in two steps:

```
N = length(x)
z ~ filldist(InverseGaussian(δ/γ, δ^2), N)
x ~ arraydist([Normal(μ + β * z[i], sqrt(z[i])) for i in 1:N])
```

While the suggested approach

```
x ~ filldist(NormalInverseGaussian(μ, α, β, δ), length(x))
```

runs in ~ 20 seconds, my current ETA for two-step approach above is 12 hours on the same machine.
In my current usecase the latent `z` is not of interest. Can I ignore the `z` in the inference? Perhaps sampling from another custom dist that generates `z`, but only returns `x`?

**Comment by devmotion** [comment]
> In some cases sampling directly from the NIG distribution gives numerical errors due to the Bessel function in its pdf:

It seems this error is thrown in the evaluation of `besselk(1, r)` if `r = α * sqrt(δ^2 + (x - μ)^2)` becomes too large (in https://github.com/JuliaStats/Distributions.jl/blob/ed52948fb47e7e0aecaf81e99ebb090c2738cf0e/src/univariate/continuous/normalinversegaussian.jl#L61 and https://github.com/JuliaStats/Distributions.jl/blob/ed52948fb47e7e0aecaf81e99ebb090c2738cf0e/src/univariate/continuous/normalinversegaussian.jl#L56). A more detailed description of the underlying FORTRAN algorithm for `besselk` can be found here: https://github.com/JuliaMath/openspecfun/blob/74f7e65abc76de7c4c72b1c77b31f3846565c498/amos/zbesk.f#L92-L110

You could include a check for the magnitude of `r` and "discard" samples if it is too large, e.g.:
```julia
@model function nig(x)
    μ ~ Normal()
    αβ ~ CustomDist()
    δ ~ Exponential(1)
    α, β = αβ

    # https://github.com/TuringLang/Turing.jl/issues/1708#issuecomment-922349522
    r = α * hypot(δ, maximum(x -> abs(x - μ), x))
    if r > 1e9
        Turing.@addlogprob! -Inf
        return
    end

    x ~ filldist(NormalInverseGaussian(μ, α, β, δ), length(x))
    return
end
```

The problem with the two-step approach is that you don't marginalize out `z`: to evaluate the log pdf of a specific `x` you have to marginalize over the log joint density of `x` and `z` or you have to include (and save) `z` already in your sampling procedure and compute the log pdf of `x` conditional on `z`. So if you want to avoid the Bessel function you have to include `z` in your model as a proper additional random variable, but of course this will slow down sampling and convergence. I am surprised though that it becomes so much slower, maybe there are some underlying problems here eg regarding type stability? Maybe the broadcasting alternative is faster here,
```julia
z ~ filldist(InverseGaussian(δ/γ, δ^2), N)
x .~ Normal.(μ .+ β .* z, sqrt.(z))
```
or directly using an `MvNormal` (`arraydist` should return one anyway but the computation of the mean and covariance matrix should be faster):
```julia
z ~ filldist(InverseGaussian(δ/γ, δ^2), N)
x ~ MvNormal(μ .+ β .* z, Diagonal(z))
```

BTW, of course Distributions uses this two step algorithm for sampling from `NormalInverseGaussian`: https://github.com/JuliaStats/Distributions.jl/blob/ed52948fb47e7e0aecaf81e99ebb090c2738cf0e/src/univariate/continuous/normalinversegaussian.jl#L75-L82.

**Comment by robertdj** [comment]
Thanks for your suggestions -- they are very thorough!
