### ISSUE TITLE
Easy way to get gradient evaluation timing

### ISSUE THREAD

**Issue by maedoc** [TuringLang/Turing.jl#1721]
The [performance tips page](https://turing.ml/dev/docs/using-turing/performancetips) doesn't mention how to get timing on the gradient evaluation timing of a model.  CmdStan prints this before running the sampler, and it is a helpful number for distinguishing code performance issue from parametrisation issues.  Could a tip be added for this?

**Comment by torfjelde** [comment]
For just benchmarking the AD-performance, this used to work: https://gist.github.com/torfjelde/7794c384d82d03c36625cd25b702b8d7

Probably still works.

IMO we should at least show an estimate of "seconds per iteration" (yes, some samplers have varying seconds/iteration but this is still useful information).

**Comment by cpfiffer** [comment]
> IMO we should at least show an estimate of "seconds per iteration" (yes, some samplers have varying seconds/iteration but this is still useful information).

Agreed. I suppose we'd throw this into the default logger, no?

**Comment by yebai** [comment]
See https://github.com/TuringLang/DynamicPPL.jl/pull/346 and https://github.com/torfjelde/TuringBenchmarking.jl
