### ISSUE TITLE
Automatic lazy broadcasting/optimization for arrays of distributions

### ISSUE THREAD

**Issue by ElOceanografo** [TuringLang/Turing.jl#1723]
This issue follows up on this Discourse [discussion](https://discourse.julialang.org/t/making-turing-fast-with-large-numbers-of-parameters/69072/64?u=eloceanografo). As @mohamed82008 [explained](https://discourse.julialang.org/t/making-turing-fast-with-large-numbers-of-parameters/69072/68?u=eloceanografo), there multiple performance advantages to using a `LazyArray` inside an `arraydist`.  To realize them, however, one must a) know about this lazy-array trick, and b) remember/look up the `LazyArray` syntax (which unfortunately includes a macro `@~`, which is similar but unrelated to Turing/DynamicPPL's `~`).  

Would it be possible to make the lazy-array trick more automatic? From a user perspective, I can think of a couple of ways this would work:

1. Make `arraydist` convert its argument to a lazy array [automatically](https://discourse.julialang.org/t/making-turing-fast-with-large-numbers-of-parameters/69072/93?u=eloceanografo) (maybe based on some heuristic of when it's likely to benefit performance, and/or an optional argument `lazy=true`)
2. Provide a [macro](https://discourse.julialang.org/t/making-turing-fast-with-large-numbers-of-parameters/69072/94?u=eloceanografo) like `@lazyarraydist(...broadcasted computation...)` to do the same thing
3. Just make `.~` parse to a lazily broadcasted array distribution

If 3) could work, that would be best, though I don't know if it would come with hidden downsides or implementation challenges. Basically, anything that decreases the number of special-case optimization hacks a user has to remember would be great!

**Comment by dlakelan** [comment]
Hi, following this issue because I'm very interested in what ultimately is going to be the fast way to handle something like this. Currently the most reliable (doesn't cause crashes/backtraces) is for me to do `Turing.addlogprob!(sum(logpdf(....)))` all manually.

**Comment by yebai** [comment]
We will likely adopt https://github.com/TuringLang/Turing.jl/issues/1723#issuecomment-954023424. 

In addition, it is better to keep the `module` macro transparent so more performance optimisation can be done outside `DynamicPPL` / `Turing`. https://github.com/TuringLang/Turing.jl/pull/1900 should make this type of performance optimisation easier because the internal `SimpleVarInfo` data structure becomes more compatible with the Julia ecosystem.
