### ISSUE TITLE
Compat of Turing 0.19 and DifferentialEquations 6.20

### ISSUE THREAD

**Issue by Song921012** [TuringLang/Turing.jl#1733]
For Julia 1.6 version, Turing 0.19 (latest) and DifferentialEquations 6.20 (latest) are compatible.

But for Julia 1.7 version, Turing 0.19 and DifferentialEquations 6.20 are No more compatible.  If I added DifferentialEquations@6.20 first, I could only add Turing@0.15.

**Comment by devmotion** [comment]
This is not a problem with DifferentialEquations but with Julia 1.7. Turing is not compatible with it: https://github.com/TuringLang/Turing.jl/issues/1714 https://github.com/TuringLang/Turing.jl/issues/1713#issuecomment-932691445
