### ISSUE TITLE
Libtask error on Julia 1.7

### ISSUE THREAD

**Issue by tinjaca** [TuringLang/Turing.jl#1734]
Question on: https://github.com/TuringLang/Turing.jl/edit/master/docs/_docs/using-turing/get-started.md

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x62682211 -- getproperty at .\task.jl:170 [inlined]
produce at C:\Users\Rigoberto\.julia\packages\Libtask\OtgFl\src\ctask.jl:112
in expression starting at C:\Users\Rigoberto\.julia\packages\Turing\uAz5c\test\core\container.jl:12
getproperty at .\task.jl:170 [inlined]
produce at C:\Users\Rigoberto\.julia\packages\Libtask\OtgFl\src\ctask.jl:112
#196 at C:\Users\Rigoberto\.julia\packages\Turing\uAz5c\test\core\container.jl:27
#1 at C:\Users\Rigoberto\.julia\packages\Turing\uAz5c\src\core\container.jl:26
#1 at C:\Users\Rigoberto\.julia\packages\Libtask\OtgFl\src\ctask.jl:65
unknown function (ip: 0000000062682973)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1788 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:877
Allocations: 612069053 (Pool: 611960125; Big: 108928); GC: 471
ERROR: Package Turing errored during testing

**Comment by rikhuijzer** [comment]
Which Julia version are you running?

**Comment by tinjaca** [comment]
1.7.0

**Comment by devmotion** [comment]
The latest versions of Turing are not compatible with Julia 1.7 yet. It is blocked by Libtask whose binary dependencies have to be linked against specific Julia versions and which is broken on Julia 1.7.

**Comment by tinjaca** [comment]
Ok, thanks.

**Comment by trahflow** [comment]
> The latest versions of Turing are not compatible with Julia 1.7 yet. It is blocked by Libtask whose binary dependencies have to be linked against specific Julia versions and which is broken on Julia 1.7.

Is there an issue on julia side that tracks this? I couldn't find anything

**Comment by devmotion** [comment]
It's not a Julia but a Libtask issue (see e.g. https://github.com/TuringLang/Libtask.jl/issues/91 and https://github.com/TuringLang/Libtask.jl/issues/94). Currently, Libtask is redesigned in a way that avoids these problems (but has some other limitations currently): https://github.com/TuringLang/Libtask.jl/pull/93

**Comment by ParadaCarleton** [comment]
Going to close this and reopen the pinned version of this
