### ISSUE TITLE
Refactoring Glue Code

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/Turing.jl#1735]
Issue for keeping track of the process of removing glue code that is made unnecessary by the new simple varinfo.

**Comment by devmotion** [comment]
VarInfo isn't removed, so we still need all VarInfo code, don't we? We rather have to add some SimpleVarInfo code as well if it is added, or preferably generalize the code to AbstractVarInfo.

**Comment by torfjelde** [comment]
Nothing is made unnecessary by the new PR.
We simply have to update some functionality to be compatible with immutable implementations, where most of these can be found in #1726 .

**Comment by ParadaCarleton** [comment]
@yebai @cpfiffer did I misunderstand what we were talking about yesterday?

**Comment by yebai** [comment]
It should be refactoring the glue code, I think. We would like to create an interface between Turing-AbstractMCMC that can be shared by more samplers. For example,  AdvancedMH and AdvancedHMC can share the log density interface. At the moment there is a lot of redundancy in the glue code which we want to reduce via careful refactoring.

**Comment by torfjelde** [comment]
> For example, AdvancedMH and AdvancedHMC can share the log density interface. 

So this doesn't have anything to do with `SimpleVarInfo`, but rather it's related to https://github.com/TuringLang/AbstractMCMC.jl/issues/85, in particular this comment: https://github.com/TuringLang/AbstractMCMC.jl/issues/85#issuecomment-948983976

I've begun working along these lines here: https://github.com/TuringLang/AbstractMCMC.jl/pull/86.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/1904 where we will make an effort to reduce redundant glue code by using a cleaner `VarInfo` design from `DynamicPPL`.
