### ISSUE TITLE
Way to Declare Data

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/Turing.jl#1736]
Mentioned on the call today with Hong and Cameron -- perhaps we should add a wrapper type for data that throws an error if any variable is sampled from a distribution instead of being added to the log-likelihood. (Possibly exempting `missing` values.) Cameron suggested an `@data` convenience macro where users can list all their data variables and have them automatically converted by Turing.

This could avoid some of the errors we've been seeing on Discourse where users accidentally generate a sample instead of adding it to the log-likelihood.

**Comment by torfjelde** [comment]
IMO we should just do what's already done in https://github.com/TuringLang/DynamicPPL.jl/pull/275. 

The reason why I'm in favour of that instead of something like a wrapper-type will require changing the way we're performing checks, otherwise we'll run into method ambiguities real quickly. In contrast, the `@observe` approach is completely non-intrusive.

**Comment by ParadaCarleton** [comment]
> IMO we should just do what's already done in [TuringLang/DynamicPPL.jl#275](https://github.com/TuringLang/DynamicPPL.jl/pull/275).
> 
> The reason why I'm in favour of that instead of something like a wrapper-type will require changing the way we're performing checks, otherwise we'll run into method ambiguities real quickly. In contrast, the `@observe` approach is completely non-intrusive.

I think that makes sense; Cameron suggested the type approach as a way to avoid having to deal with metaprogramming here, but maybe using types isn't worth it. Maybe we should have a way declare a block of variables to be data at the start and then add `@observe` to anything involving those variables?

**Comment by yebai** [comment]
I think we can now make use of the nice callable object support to declare variables as data, e.g. 

```julia

struct MyModel
    a::Int
    x::Float64
end

is_observation(m::MyModel, s::Symbol) = s == :x ? true : false 


@model function (f::MyModel)(x)
    m ~ Normal(f.a, 1)
    # we can modify the `~` implementation to call `is_observation` internally. 
    return m.x ~ Normal(m, 1) 
end


```

**Comment by yebai** [comment]
We likely will promote the syntax in https://github.com/TuringLang/Turing.jl/issues/1736#issuecomment-1071148730 as a solution.
