### ISSUE TITLE
Improve usage and support for immutable `AbstractVarInfo`

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/Turing.jl#1752]
After #1726 we can make use of alternative implementations of `AbstractVarInfo`, in particular immutable implementations. This comes with a lot of benefits, with a big one being performance improvements for a large suite of models.

But current a lot of the codebase assumes `AbstractVarInfo` to be mutable, which first needs to change. This issue is for keeping track of what needs to be done.

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/Turing.jl/pull/1900
