### ISSUE TITLE
VectorizationBase problem

### ISSUE THREAD

**Issue by xijiang** [TuringLang/Turing.jl#1759]
Hi, Turing is preventing Julia to upgrade `VectorizationBase`. Turing's requirement is v0.16.2. This created [an issue](https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/129) about Octavian. With this issue, Octavian gave wrong `matmul` results. At the moment, I have to remove `Turing` to use `Octavian`.

**Comment by rikhuijzer** [comment]
In https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/129, I see that you are running Julia 1.7. Please note that Turing doesn't work for Julia 1.7 yet, see also https://github.com/TuringLang/Turing.jl/issues/1738.
