### ISSUE TITLE
Kernel dies with Gibbs or ADVI with models involving categorical or dirichlet

### ISSUE THREAD

**Issue by AmmarRashed** [TuringLang/Turing.jl#1777]
Question on: https://turing.ml/dev/tutorials/01-gaussian-mixture-model/

Hello,
I ran the code above on different machines and they all have the kernel die at the sampling step:
```
tchain = sample(gmm_model, gmm_sampler, MCMCThreads(), 100, 3);
```
I tried with single threading and without the Dirichlet prior. Same thing happened with me on a different model when using ADVI.
I could verify that the model is working by sampling with MH. But I need to use ADVI for another project.

This seems to be a consistent problem, not sure if it is just because of the categorical models, or something else.

Thanks,

**Comment by yebai** [comment]
@AmmarRashed Can you post your package environment so we can take a look?

**Comment by Red-Portal** [comment]
I'll close this due to inactivity.
