### ISSUE TITLE
type Trace has no field ctask

### ISSUE THREAD

**Issue by andreaskoher** [TuringLang/Turing.jl#1780]
Hey all,

after moving from Turing 19.2 to 20.3 on Julia 1.6.5 the following error appears in the simple example from the docs:

```julia
using Turing
@model function gdemo(x, y)
    s² ~ InverseGamma(2, 3)
    m ~ Normal(0, sqrt(s²))
    x ~ Normal(m, sqrt(s²))
    y ~ Normal(m, sqrt(s²))
end

sample(gdemo(1.5, 2), PG(10), 1000)
```

> type Trace has no field ctask

Same happens for the `SMC` sampler

**Comment by yebai** [comment]
@andreaskoher It works fine on my computer with Turing `v0.20.3`. Maybe try updating all the dependencies with `] up`?

**Comment by devmotion** [comment]
Should be fixed by https://github.com/TuringLang/Turing.jl/pull/1781.

**Comment by yebai** [comment]
thanks, @devmotion - I was working on a fix at the same time in https://github.com/TuringLang/Turing.jl/tree/hg/bug-fix-ctask
