### ISSUE TITLE
Broken doctests

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#1796]
There are some broken doctests that need to be fixed to make Documenter.jl happy.
- [ ] [src/inference/ess.jl#L7](https://github.com/TuringLang/Turing.jl/blob/master/src/inference/ess.jl#L7)
- [ ] [src/inference/Inference.jl:475-529](https://github.com/TuringLang/Turing.jl/blob/master/src/inference/Inference.jl#L475-L529)

**Comment by yebai** [comment]
Seems fixed on the `master` branch.
