### ISSUE TITLE
Question: Math rendering broken

### ISSUE THREAD

**Issue by pzeidman** [TuringLang/Turing.jl#1801]
Hi there, I'd love to read [this URL on variational inference in Turing.jl,](https://turing.ml/dev/docs/for-developers/variational_inference) but the math rendering seems to be broken. Thanks!

**Comment by yebai** [comment]
We are working on a new version of the website in https://beta.turing.ml/. Hopefully, the new Franklin-based system provide a more robust way of typesetting maths.
