### ISSUE TITLE
Turing.@addlogprob! -Inf does not cause sample to be rejected

### ISSUE THREAD

**Issue by damonbayer** [TuringLang/Turing.jl#1808]
Per [the documentation](https://turing.ml/dev/docs/using-turing/advanced#update-the-accumulated-log-probability-in-the-model-definition) `Turing.@addlogprob! -Inf` combined with an early `return` call should cause a sample to be rejected. In my [reproducible example](https://gist.github.com/damonbayer/2d6c75ac639e1a6707f006031b069aef#file-minimal_addlogprob_example-jl), this is not the case.

I apologize for the model code being quite complicated, but it is fast to run (2 min on my laptop) and I couldn't come up with anything simpler that causes the problem.

Some commentary on the code:

The model contains [these lines](https://gist.github.com/damonbayer/2d6c75ac639e1a6707f006031b069aef#file-minimal_addlogprob_example-jl-L189-L192), which mirror what is seen in this [tutorial](https://github.com/TuringLang/TuringTutorials/blob/71c6349a8a6194649e582667c9a161278b19e939/tutorials/10-bayesian-differential-equations/10_bayesian-differential-equations.jmd#L361-L363) from TuringTutorials:
```julia
    if sol.retcode != :Success
      Turing.@addlogprob! -Inf
      return("bad")
    end
```
So, if the ODE solver fails, then I should add `-Inf` to the logprob and make an early return.

However, after we do `sample`, we see that sample `998` returns `"bad"` when we call `generated_quantities`, meaning that the ODE solver failed.

```
julia> bad_index = 998
998

julia> generated_quantities(my_model, posterior_samples[bad_index, :, 1])
1×1 Matrix{String}:
 "bad"
```

As expected, checking the probability/likelihood of the model for these sample yield `-Inf`
```
julia> logprior(my_model, bad_sample_named_tuple)
-Inf

julia> logjoint(my_model, bad_sample_named_tuple)
-Inf

julia> loglikelihood(my_model, bad_sample_named_tuple)
-Inf
```

Unexpectedly, `lp` in the resulting `MCMCChains` is finite.
```
julia> posterior_samples[bad_index, :lp, 1]
-153.5053619340597
```

So, it seems there is some discrepancy between what happens during `sample`  and what happens during `generated_quantities` or `logprior `.

**Comment by devmotion** [comment]
I wonder if the problem is that `posterior_samples[bad_index, :, 1]` returns the parameters in a different order from what you and/or the model expects (there are some surprising issues caused by the order of parameters in MCMCChains, e.g., https://github.com/TuringLang/MCMCChains.jl/issues/311). Can you check that all parameters are assigned and retrieved correctly?

`@addlogprob!` is a quite simple macro (https://github.com/TuringLang/DynamicPPL.jl/blob/d222316a7a2fd5afe6ec74a7ec2a50c6f08c1d00/src/utils.jl#L71-L75), and hence I suspect that it is not responsible for these surprising results.

**Comment by damonbayer** [comment]
I have been bitten by an issue like that before, so I have been trying to be careful.

Here are some checks that make me think things are in the right order:

From this [gist](https://gist.github.com/sethaxen/b18e4101a7fd0b2cfe986dd240e99213):

```julia
julia> varnames_to_ranges(my_model)
Dict{AbstractPPL.VarName{sym, Setfield.IdentityLens} where sym, UnitRange{Int64}} with 18 entries:
  dur_latent_non_centered_omicron           => 23:23
  dur_latent_non_centered_non_omicron       => 16:16
  I_init_non_centered_omicron               => 28:28
  ϕ_cases_non_centered                      => 30:30
  IHR_non_centered_omicron                  => 25:25
  ϕ_hospitalizations_non_centered           => 31:31
  dur_hospitalized_non_centered_non_omicron => 19:19
  dur_hospitalized_non_centered_omicron     => 26:26
  IHR_non_centered_non_omicron              => 18:18
  I_init_non_centered_non_omicron           => 21:21
  case_detection_rate_non_centered_omicron  => 29:29
  dur_infectious_non_centered_omicron       => 24:24
  case_detection_rate_non_centered_other    => 22:22
  E_init_non_centered_non_omicron           => 20:20
  dur_infectious_non_centered_non_omicron   => 17:17
  R0_params_non_centered                    => 1:14
  prop_omicron_only_init_non_centered       => 15:15
  E_init_non_centered_omicron               => 27:27
```

```julia
julia> vcat(values(bad_sample_named_tuple)...) == vec(Array(posterior_samples[bad_index, :, 1]))
true
```

And if I construct `bad_sample_named_tuple` by name, rather than index, it produces the same result. 

```julia
julia> bad_sample_named_tuple_alt = (R0_params_non_centered = [posterior_samples[bad_index, Symbol("R0_params_non_centered[1]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[2]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[3]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[4]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[5]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[6]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[7]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[8]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[9]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[10]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[11]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[12]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[13]"), 1],
       posterior_samples[bad_index, Symbol("R0_params_non_centered[14]"), 1]],
       prop_omicron_only_init_non_centered = posterior_samples[bad_index, "prop_omicron_only_init_non_centered", 1],
       dur_latent_non_centered_non_omicron = posterior_samples[bad_index, "dur_latent_non_centered_non_omicron", 1],
       dur_infectious_non_centered_non_omicron = posterior_samples[bad_index, "dur_infectious_non_centered_non_omicron", 1],
       IHR_non_centered_non_omicron = posterior_samples[bad_index, "IHR_non_centered_non_omicron", 1],
       dur_hospitalized_non_centered_non_omicron = posterior_samples[bad_index, "dur_hospitalized_non_centered_non_omicron", 1],
       E_init_non_centered_non_omicron = posterior_samples[bad_index, "E_init_non_centered_non_omicron", 1],
       I_init_non_centered_non_omicron = posterior_samples[bad_index, "I_init_non_centered_non_omicron", 1],
       case_detection_rate_non_centered_other = posterior_samples[bad_index, "case_detection_rate_non_centered_other", 1],
       dur_latent_non_centered_omicron = posterior_samples[bad_index, "dur_latent_non_centered_omicron", 1],
       dur_infectious_non_centered_omicron = posterior_samples[bad_index, "dur_infectious_non_centered_omicron", 1],
       IHR_non_centered_omicron = posterior_samples[bad_index, "IHR_non_centered_omicron", 1],
       dur_hospitalized_non_centered_omicron = posterior_samples[bad_index, "dur_hospitalized_non_centered_omicron", 1],
       E_init_non_centered_omicron = posterior_samples[bad_index, "E_init_non_centered_omicron", 1],
       I_init_non_centered_omicron = posterior_samples[bad_index, "I_init_non_centered_omicron", 1],
       case_detection_rate_non_centered_omicron = posterior_samples[bad_index, "case_detection_rate_non_centered_omicron", 1],
       ϕ_cases_non_centered = posterior_samples[bad_index, "ϕ_cases_non_centered", 1],
       ϕ_hospitalizations_non_centered = posterior_samples[bad_index, "ϕ_hospitalizations_non_centered", 1]);

julia> bad_sample_named_tuple == bad_sample_named_tuple_alt
true
```

**Is there anywhere else I should check?**
Perhaps it requires digging in to `generated_quantities` or `logprior`. It would be surprising to me if there were something wrong there because I have a nearly identical model (multivariate random variables with weird names, ODE solver in the model, etc.) that works flawlessly with `generated_quantities`.

**Comment by devmotion** [comment]
I don't have time to look into it right now (unfortunately) but I would be very surprised if the problem is `@addlogprob!` (or `acclogp!!` that it calls) since it's so simple and accumulation is very very well tested, both with CI and in practice. I assume something else is going wrong. My guess would be it is rather `generated_quantities` than `logprior`.

**Comment by damonbayer** [comment]
Both `generated_quantities` and `logprior` think that the ODE cannot be solved, so the problem is likely shared between them. Does that make sense? Only `sample` seems to think it can be solved.

**Comment by devmotion** [comment]
Yeah, which could be the case if the parameters are in a different order during sampling and when evaluating. `logprior`, `logjoint`, `loglikelihood` should not be wrong (intuitively) but it could be that you don't evaluate the thing you want to evaluate.

**Comment by devmotion** [comment]
Can you sample `NamedTuple`s instead to rule out any such issues?

**Comment by burtonjosh** [comment]
I ran your code on my laptop and every index (including the "bad" index) returns "good" for me. I'm using Julia v1.6.2, Turing v0.20.4, DifferentialEquations v6.20.0, and LogExpFunctions v0.3.10

**Comment by damonbayer** [comment]
Thanks. I'll close this issue, then. Seems like it's a problem with my model, not Turing.

**Comment by burtonjosh** [comment]
You could try setting up the ODE problem outside the model and then using `remake` inside the model like in [,](https://turing.ml/dev/tutorials/10-bayesian-differential-equations/) to see if this makes a difference? Other than that I don't have any suggestions.

**Comment by damonbayer** [comment]
Reopening because this **does** appear to be a bug with Turing. @devmotion

It reveals a clear bug with the `predict` function, that I hope is related to the problems I'm seeing with `sample`.

I have a new (similar) [reproducible example](https://gist.github.com/damonbayer/c31c404781417b25582166be075a0791), but I have narrowed in on the problem. Here is the [key bit](https://gist.github.com/damonbayer/c31c404781417b25582166be075a0791#file-minimal_predict_example-jl-L307-L327):

```julia
julia> my_predictive_model = bayes_seihr(
           Vector{Union{Missing, Int64}}(undef, length(data_est_other_cases)),
           Vector{Union{Missing, Int64}}(undef, length(data_est_omicron_cases)),
           Vector{Union{Missing, Int64}}(undef, length(data_hospitalizations)),
           obstimes, param_change_times);
```

The bad index prints the message indicating the ODE cannot be solved (expected), but it still produces a posterior predictive sample (strange).

```julia
julia> Random.seed!(1);

julia> bad_posterior_predictive = predict(my_predictive_model, posterior_samples[bad_index, :, 1]);
sol.retcode: Unstable
logp: -52.82905200215432
Set logprob to -Inf
Updated logp: -Inf


julia> Array(bad_posterior_predictive)
1×33 Matrix{Float64}:
 51.0  55.0  61.0  49.0  59.0  70.0  34.0  35.0  …  3.0  2.0  10.0  10.0  13.0  2.0  13.0  6.0  10.0
```

The good index does not complain about the ODE (expected) and produces a posterior predictive sample (expected).

```julia
julia> Random.seed!(1);

julia> good_posterior_predictive = predict(my_predictive_model, posterior_samples[good_index, :, 1]);

julia> Array(good_posterior_predictive)
1×33 Matrix{Float64}:
 17.0  18.0  34.0  11.0  8.0  2.0  0.0  1.0  0.0  …  7.0  9.0  16.0  13.0  23.0  18.0  17.0  8.0  9.0
```

Sampling from the posterior predictive from the bad index and then the good produces the same draw from the bad index (strange, but now expected?) and the same draw from the good index (as expected).

```julia
julia> Random.seed!(1);

julia> good_bad_posterior_predictive = predict(my_predictive_model, posterior_samples[[good_index, bad_index], :, 1]);
sol.retcode: Unstable
logp: -52.82905200215432
Set logprob to -Inf
Updated logp: -Inf


julia> Array(good_bad_posterior_predictive)
2×33 Matrix{Float64}:
 17.0  18.0  34.0  11.0  8.0  2.0  0.0  1.0  0.0  …  7.0  9.0  16.0  13.0  23.0  18.0  17.0  8.0  9.0
 17.0  18.0  34.0  11.0  8.0  2.0  0.0  1.0  0.0     7.0  9.0  16.0  13.0  23.0  18.0  17.0  8.0  9.0
```

Sampling from the posterior predictive from the good index and then the bad produces the same draw from the good index (expected).
**That draw is re-used as the draw from the bad index (strange, but now we know where these values come from)**.

```julia
julia> Random.seed!(1);

julia> bad_good_posterior_predictive = predict(my_predictive_model, posterior_samples[[bad_index, good_index], :, 1]);
sol.retcode: Unstable
logp: -52.82905200215432
Set logprob to -Inf
Updated logp: -Inf


julia> Array(bad_good_posterior_predictive)
2×33 Matrix{Float64}:
 51.0  55.0  61.0  49.0  59.0  70.0  34.0  35.0  28.0  …  2.0  10.0  10.0  13.0   2.0  13.0  6.0  10.0
 17.0  18.0  34.0  11.0   8.0   2.0   0.0   1.0   0.0     9.0  16.0  13.0  23.0  18.0  17.0  8.0   9.0
```

So it appears that when `predict` encounter an early `return`, **the values for the variables in the latter part of the model are not erased, but they are retained from the previous sample!**

I suspect something similar is going on with `sample`.

**Comment by devmotion** [comment]
> So it appears that when predict encounter an early return, the values for the variables in the latter part of the model are not erased, but they are retained from the previous sample!

IIRC this is one of the limitations of `predict` and the whole pipeline for constructing variable objects from a chain. At least I remember (I think) there was some discussion in a PR about it, I'll try to find it.

**Comment by devmotion** [comment]
I guess it should be possible to simplify and improve this with the recently added NamedTuple-backed variable structure. Other main issues with the current implementation are that 1) we first have to run the model to figure out the variable (which doesn't work if the number or name of variables is stochastic) and 2) that it makes a difference for the model if there is a variable `m` or variables `m[1]` etc. (but from the chain we only get `m[1]`, which made it necessary to run the model first to figure out the variables). I assume it would be less error-prone to extract the variables on the fly, using our also relatively new context pipeline.

**Comment by damonbayer** [comment]
Do you think this issue with `predict` and the issue with `sample` are related?

At least for my case, I don't really care about what happens when I give bad parameter values to `predict`, I just don't want to get bad parameter values out of `sample`.

**Comment by devmotion** [comment]
This is unrelated of `sample`. The problem occurs when we extract parameters from chains internally, which we don't do during sampling.

**Comment by damonbayer** [comment]
Closing thanks to Chris Rackauckas pointing out that solving differential equations with the same values works differently inside and outside of Turing.
