### ISSUE TITLE
Posterior Predictive Checks

### ISSUE THREAD

**Issue by PeetoomHeida** [TuringLang/Turing.jl#1809]
Posterior predictive checks are an important part of Bayesian inference and checking to see if your model is running. At present, Turing does not seem to have any functions or plotting recipes associated with such checks. We should try to develop a few ways for users to run checks on their model after it has completed. Some of the potential issues I can see arising are that the highly customisable model specification means that it would be difficult to have a pre-fabbed function that could easily take a chain object as an argument, unless we were able to parse the likelihood expression out of the model definition. Perhaps the easiest route in the short term is to just provide some examples in the documentation so newer users can see how a posterior predictive check would be performed and visualized in Turing.

**Comment by SebastianCallh** [comment]
I realize this is quite old but since it was unanswered I just thought I'd ask if you have seen ArviZ? More specifically the `plot_ppc` function?

https://github.com/arviz-devs/ArviZ.jl

**Comment by ParadaCarleton** [comment]
> I realize this is quite old but since it was unanswered I just thought I'd ask if you have seen ArviZ? More specifically the `plot_ppc` function?
> 
> https://github.com/arviz-devs/ArviZ.jl

Yes--ArviZ.jl is great for this, and we highly recommend it. However, it's a separate package, so questions about it should go in the ArviZ.jl github, rather than here.
