### ISSUE TITLE
there is an erro in Variational inference (VI) of the Tutorials

### ISSUE THREAD

**Issue by huangruiping9** [TuringLang/Turing.jl#1820]
at the part of Copy-paste from 5. Linear regression

"¶remove_names = filter(x->!in(x, [:MPG, :Model]), names(data))" has an erro,should be replaced by
remove_names = filter(x->!in(x, ["MPG", "Model"]), names(data))

**Comment by yebai** [comment]
Likely fixed by recent updates to the `VI` tutorial.
