### ISSUE TITLE
Fix local website build

### ISSUE THREAD

**Issue by tomroesch** [TuringLang/Turing.jl#1855]
When trying to follow the instructions to locally build the documentation, a couple of issues come up. 

First issue comes up when running `make.jl`:

```julia
ERROR: LoadError: IOError: readdir("/var/folders/67/2rd1gct91876bvjs_7ny9rcw0000gn/T/jl_77ZIPRIyya/markdown"): no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error
   @ ./libuv.jl:97 [inlined]
 [2] readdir(dir::String; join::Bool, sort::Bool)
   @ Base.Filesystem ./file.jl:865
 [3] readdir
   @ ./file.jl:858 [inlined]
 [4] copy_tutorial(tutorial_path::String)
   @ Main ~/git/Turing.jl/docs/make-utils.jl:236
 [5] top-level scope
   @ ~/git/Turing.jl/docs/make.jl:24
```

This can be fixed by changing the path from `markdown` to `tutorials` is in the repo for Turing Tutorials https://github.com/TuringLang/TuringTutorials there is no folder called `markdown` anymore, but `tutorials`.

The next issue that pops up is happening in `make.jl`:
```
/Turing.jl/docs/.gems/gems/faraday-0.15.4/lib/faraday/options.rb:166:in `new': tried to create Proc object without a block (ArgumentError)
```

This can be solved by updating the `Gemfile` to a newer version of `faraday`. This allows for `make.jl` to run to the end.
The next issue occurs when trying to host the website

Next issue:
```
.gem/ruby/3.1.2/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
```

This issue can be solved by adding 
```
gem "webrick"
```
to the `Gemfile`. This allows for the website to be hosted locally on my machine. I will add a pull request with these changes. Maybe someone who knows more about this stuff can check this.

**Comment by devmotion** [comment]
Most of the logic for building the website is moved to https://github.com/TuringLang/turing.ml. One major change is that we don't run the tutorials anymore when building the website but just use the output in the TuringTutorialsOutput repo. That is, in particular the markdown part of the script is outdated and done differently in turing.ml.

**Comment by tomroesch** [comment]
This should be fixed by a [pull request](https://github.com/TuringLang/turing.ml/pull/33) in `turing.ml`.

**Comment by tomroesch** [comment]
Fixed by: https://github.com/TuringLang/turing.ml/pull/33
