### ISSUE TITLE
Error with bunchkaufman factorization

### ISSUE THREAD

**Issue by juliohm** [TuringLang/Turing.jl#1889]
Is there anything that I can do to help fix https://discourse.julialang.org/t/error-with-bunchkaufman-factorization-in-turing-jl/88174 ?

**Comment by devmotion** [comment]
I don't think that issue is Turing-specific, it seems that ForwardDiff just does not support `bunchkaufmann` (and the implementation in LinearAlgebra does not support dual numbers automatically). I assume probably it should be fixed in ForwardDiff or LinearAlgebra.

**Comment by juliohm** [comment]
Thank you @devmotion for clarifying it. I should probably open the issue in ForwardDiff.jl to see if there is an easy fix.
