### ISSUE TITLE
Feature request: Output maximized ELBO after variational inference

### ISSUE THREAD

**Issue by statenthusiast** [TuringLang/Turing.jl#1896]
It would be wonderful if users can have access to the maximized ELBO after running ADVI since it is a fast approximation to model evidence.

**Comment by Red-Portal** [comment]
Hi, this will be implemented in the future version of `AdvancedVI` currently under work in [this PR](https://github.com/TuringLang/AdvancedVI.jl/pulls). But you can do this already by calling `elbo` directly. See [here](https://github.com/TuringLang/AdvancedVI.jl/blob/master/src/objectives.jl).

**Comment by Red-Portal** [comment]
I'll close this issue for now.
