### ISSUE TITLE
`VarInfo`: dist ==> typeof{dist}

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#191]
The current `VarInfo` stores `dist` for each R.V. This is not necessary and could potentially cause subtle bugs. The reason is that `dist` could change when its parameters (depending on other random variables) change, but its type will never change. For example

```julia
x ~ Normal(0,1)
z ~ Normal(x,1) # dist = `Normal(x,1)`, and will change when `x` changes.
```

Perhaps it's better to store `typeof(dist)` (e.g. `Normal`) instead of `dist` in `VarInfo`?

UPDATE: `Truncated` might be hard to reconstruct if only storing distribution type?

Code that depend on `VarInfo.dist`

- https://github.com/yebai/Turing.jl/blob/156977348265f341457f08271030baefdcbf7831/src/samplers/support/helper.jl#L56

- https://github.com/yebai/Turing.jl/blob/156977348265f341457f08271030baefdcbf7831/src/samplers/support/helper.jl#L83

**Comment by xukai92** [comment]
I think we need to store more information than type because the dimension information of the variable also depends on the parameters of the distribution, which will be used for reconstructing vectorised variables.

**Comment by yebai** [comment]
That makes sense.

**Comment by yebai** [comment]
Perhaps we can store the following in `VarInfo.dist` 

```
type T{D,N,L,H} 
       dist  :: Distribution
       dim  :: Tuple
       low   :: Real
       high  :: Real
       T() = new(D,N,L,H)
 end
```

The allows us to keep essential information about distribution objects but don't need to update `VarInfo.dist` during inference (ie remove `setdist!(VarInfo)`.

**Comment by xukai92** [comment]
Another reason in favor of this (instead of storing distribution objects) is that if we want to store `x` as a variable instead of `x[1]`, `x[2]` ... for vectorization, we would need something to record the **true** dimension. This is because if we simply store `x` when calling `x ~ [Normal(...)]`, then the dimentionality indicated by the distribution object is no longer true.

**Comment by yebai** [comment]
> The reason is that dist could change when its parameters (depending on other random variables) change, but its type will never change. 

One counter example

```julia

x ~ Uniform(0 ,1)
y ~ Uniform(0, x)

```

Here the second distribution object has to be stored to correctly perform `link`/`invlink` functions. Everytime when the value of `x` changes, we will need to update the distribution object stored in `VarInfo`, whether it is a `Distributions.Distribution` type or some other type we define by ourselfves (e.g. `T` above).
