### ISSUE TITLE
@model scope and influence from global variables

### ISSUE THREAD

**Issue by filchristou** [TuringLang/Turing.jl#1915]
I think something is wrong with the scope of the parameters inside the `@model`.
Now I cannot say for sure what, but I will showcase how to reproduce and how this creates problems.

I am using Pluto to reproduce the [Turing introduction example](https://turing.ml/v0.21/tutorials/00-introduction/)

What happens is that Pluto re-evaluates the `@model` whenever I define a global variable with the same name as model's parameters. 

E.g. here whenever I redefine `p`, which is also a model parameter, `@model coinflip` is redefined and resampled.
I track this reevaluation with the `counter` vector that grows on every evaluation.
This is very tedious to take care for big notebooks. 
I think the scope of the @model should be strictly local and not influenced from global variables.
I also don't think this is a Pluto issue. So that's why I submitted my issue here.

_(sorry for the bad quality)_

https://user-images.githubusercontent.com/27723218/205041528-5ed021fd-4e67-49a7-8214-1bcb6f4bbea6.mp4

### Notebook on gist
https://gist.github.com/filchristou/1ba48989006aa7c72e02abc07de6a552

### System description
Julia version 1.8.1
Turing v0.22.0

**Comment by torfjelde** [comment]
> What happens is that Pluto re-evaluates the @model whenever I define a global variable with the same name as model's parameters.

This is a Pluto issue; not a `@model` issue, I'm afraid. It seems like Pluto doesn't know how to handle macros properly.

**Comment by filchristou** [comment]
Ah, true. I also find a relative Pluto issue https://github.com/fonsp/Pluto.jl/issues/196
I close this one.
