### ISSUE TITLE
The package dependency on Setfield is old (v0.8.2), which makes conflict with other packages.

### ISSUE THREAD

**Issue by linguo4** [TuringLang/Turing.jl#1935]
The package dependency on Setfield is old (v0.8.2), which makes conflict with other packages. Is it possible to make it uptodate (similar issue happens for DynamicPPL.jl and AbstractPPL.jl)?

![image](https://user-images.githubusercontent.com/67442207/211755847-a3cf8ca7-26dd-437e-82a2-818e613e5e26.png)
![image](https://user-images.githubusercontent.com/67442207/211756147-fe191caa-70cd-42c9-b0f7-b461cb6ceff0.png)
![image](https://user-images.githubusercontent.com/67442207/211756218-0d2df416-a756-4786-ba6a-24324a6e3868.png)
![image](https://user-images.githubusercontent.com/67442207/211756271-67881e59-4582-46d1-ba93-371bfa6036c5.png)
![image](https://user-images.githubusercontent.com/67442207/211756352-b16eda5b-75dd-4ee4-9e2d-d66299272578.png)

**Comment by torfjelde** [comment]
Turing allows both 0.8 and 1 though :confused:

**Comment by devmotion** [comment]
BTW GalacticOptim.jl has been renamed to and replaced with Optimization.jl, this could also be problematic.

**Comment by yebai** [comment]
This is held back by DynamicPPL / AbstractPPL, see https://github.com/TuringLang/DynamicPPL.jl/pull/440

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/AbstractPPL.jl/pull/76

**Comment by torfjelde** [comment]
Awesome! Thanks @yebai !
