### ISSUE TITLE
Strange posterior formula in the Variational Inference document

### ISSUE THREAD

**Issue by sboukortt** [TuringLang/Turing.jl#1939]
Hi,

Reading through https://turing.ml/dev/docs/for-developers/variational_inference#motivation, I was a bit puzzled to see:

$$p(z \mid \{x_i\}_{i=1}^n) = \prod_{i=1}^n p(z \mid x_i)$$

I am not sure where this comes from. Unless I am misreading this or missing something obvious (it is, after all, Monday morning here), it would seem to imply that the probability for $z$ can only ever decrease when adding a new data point $x_{n + 1}$, as the additional term in the product, i.e. $p(z | x_{n + 1})$, would necessarily be at most 1, and the rest unchanged.

What am I missing? Is this perhaps meant to be:

$$p(z \mid \{x_i\}_{i = 1}^n) \propto p(z) \cdot \prod_{i=1}^n p(x_i \mid z)$$

Thanks.

**Comment by tomroesch** [comment]
I don't think that is necessarily true, since when adding another data point $p(z|x_{n+1})$, you are changing the distribution and also the values for every $p(z|x_n)$ (first of all due to normalization), so they cannot stay unchanged.
 
 The definition in the docs simply states that the data points are independent.

**Comment by sboukortt** [comment]
Thank you, but I am not sure I follow:

> I don't think that is necessarily true, since when adding another data point $p(z \mid x_{n+1})$, you are changing the distribution

Which distribution? The distribution for $z$ given all the data points would be different than given all but the last (different in a possibly wrong way, it seems), but the distribution for $z$ given a specific set of data points should remain identical.

> and also the values for every $p(z \mid x_n)$ (first of all due to normalization), so they cannot stay unchanged.

Likewise, I don’t see why that would be the case (it’s a special case of my previous point) – why would $p(z \mid x_1)$ change just because $p(z \mid x_2)$ has been added to the equation?

If indeed $p(z \mid {x_i}\_{i=1}^n) = \prod\_{i=1}^n p(z \mid x_i)$ for any $n$ then it seems to me that we have:

$$
\begin{align*}
  p(z \mid {x_i}_{i=1}^{n+1}) & = \prod_{i=1}^{n+1} p(z \mid x_i) \\
  & = \left(\prod_{i=1}^n p(z \mid x_i)\right) \cdot p(z \mid x_{n + 1}) \\
  & = p(z \mid {x_i}_{i=1}^n) \cdot p(z \mid x_{n + 1}) \\
  & \leq p(z \mid {x_i}_{i=1}^n)
\end{align*}
$$

> The definition in the docs simply states that the data points are independent.

Wouldn’t that be:

$$p({x_i}\_{i=1}^n) = \prod\_{i=1}^n p(x_i)$$

**Comment by Red-Portal** [comment]
That is indeed incorrect. Good catch! It has now been fixed.
