### ISSUE TITLE
 UndefVarError: GLOBAL_RNG from Bijectors.jl

### ISSUE THREAD

**Issue by larschrj** [TuringLang/Turing.jl#1955]
Turing is not precompiling succesfully due, it seems, to Bijectors which throws: 

```
ERROR: LoadError: UndefVarError: GLOBAL_RNG not defined
```

Seems to be an issue with Bijectors@v0.10. Bijectors >= 0.11 does not seem to have this problem.

Versions:
Julia v1.8.5 and release-1.9
Turing v0.24

**Comment by devmotion** [comment]
https://github.com/TuringLang/Bijectors.jl/pull/248 should fix it.
