### ISSUE TITLE
Optimisers.jl v0.2.16 update breaks Turing, won't precompile

### ISSUE THREAD

**Issue by mistermichaelll** [TuringLang/Turing.jl#1971]
Figured this was worth flagging.

I was trying to install `Turing.jl` earlier and it kept failing when precompiling the package, specifically when it tried to precompile `Optimisers.jl`.

Some system info to start with. This was a fresh Julia installation:

```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

Here's the relevant error message:

```julia
julia> using Turing

[ Info: Precompiling Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0]

ERROR: LoadError: UndefVarError: AbstractWalk not defined

Stacktrace:
 [1] include
   @ ./Base.jl:419 [inlined]
 [2] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1554
 [3] top-level scope
   @ stdin:1
in expression starting at /Users/me/.julia/packages/Optimisers/V1Zt7/src/Optimisers.jl:1

in expression starting at stdin:1

ERROR: LoadError: Failed to precompile Optimisers [3bd65402-5787-11e9-1adc-39752487f4e2] to /Users/me/.julia/compiled/v1.8/Optimisers/jl_k35iO4.
```

This also results in `Tracker.jl` failing to compile.

I noticed that the version of Optimisers that was getting installed was `0.2.16`, which was [just released](https://github.com/FluxML/Optimisers.jl/releases/tag/v0.2.16).

So I tried `pkg> add Optimisers @v0.2.15`, and the errors went away and I was able to successfully precompile `Turing.jl`. 

I was able to reprex like this on a different computer like this:

```julia
pkg> activate --temp
pkg> add Turing 
julia> using Turing
#> ERROR: LoadError: Failed to precompile Optimisers [3bd65402-5787-11e9-1adc-39752487f4e2] to /Users/me/.julia/compiled/v1.8/Optimisers/jl_Ha1wZy........
#> ERROR: LoadError: UndefVarError: AbstractWalk not defined...
```

**Comment by devmotion** [comment]
It seems Optimisers 0.2.16 was broken (incorrect compat entry: https://github.com/FluxML/Optimisers.jl/pull/134). AFAICT the issue should be fixed automatically once the broken release is yanked from the registry since then Optimisers 0.2.15 will be the latest version compatible with Turing.

**Comment by mistermichaelll** [comment]
> It seems Optimisers 0.2.16 was broken (incorrect compat entry: [FluxML/Optimisers.jl#134](https://github.com/FluxML/Optimisers.jl/pull/134)). AFAICT the issue should be fixed automatically once the broken release is yanked from the registry since then Optimisers 0.2.15 will be the latest version compatible with Turing.

Awesome - I can close this out once that change happens then 👍

**Comment by mistermichaelll** [comment]
https://github.com/JuliaRegistries/General/pull/80197 fixed this issue.
