### ISSUE TITLE
ERROR: Mutating arrays is not supported when using arrays of parameters and Zygote

### ISSUE THREAD

**Issue by jarroyoe** [TuringLang/Turing.jl#1984]
I'm using Turing.jl to estimate the parameters of an ODE model using [this tutorial](https://turing.ml/v0.22/tutorials/10-bayesian-differential-equations/#scaling-to-large-models-adjoint-sensitivities). My model has a ton of identical equations, differing only by the parameter values. The easiest way to store those parameters is by putting them as an array and then flattening them so they can be used by Zygote.

My code looks something like this:

```
using DifferentialEquations, Zygote, SciMLSensitivity, Turing, LinearAlgebra

a = [1,2]
b = [3,4]

p = float.(collect(Iterators.flatten([a,b])))

function dynamics!(dN,N,p,t)
	a = p[1:2]
	b = p[3:4]
	for i in 1:2
		dN[i] = a[i]*N[i]-b[i]
	end
end

ic = rand(2)
prob = ODEProblem(dynamics!,ic,(0.,2.),p)
sol = solve(prob,Tsit5(),saveat = 0.1)
data = Array(sol)

@model function fitmodel(data, prob)
	σ ~ InverseGamma(2,3)
	a ~ Product(Uniform.(repeat([0.],2),5))
  	b ~ Product(Uniform.(repeat([0.],2),5))
	p = float.(collect(Iterators.flatten([a,b])))

	predicted = solve(prob, AutoTsit5(Rosenbrock23()); p = p, saveat = 0.1)
	for i in 1:length(predicted)
		data[:,i] ~ MvNormal(predicted[i], σ^2 * I)
  	end
	return nothing
end

setadbackend(:zygote)
model = fitmodel(data,prob)
fittest = sample(model,NUTS(0.65), 10; progress = true)
```
Which yields [the following error](https://pastebin.com/b6ysjkQz). This error doesn't show up when I comment the `setadbackend` line.

I'm not sure where `push!` is being called on this line, but that's not supported by Zygote.

**Comment by devmotion** [comment]
Try to replace
```julia
a ~ ...
b ~ ...
p = ...
```
with
```julia
	a ~ filldist(Uniform(0, 5), 2)
  	b ~ filldist(Uniform(0, 5), 2)
	p = vcat(a, b)
```
(the last line should fix the issue with `collect` mentioned in the stacktrace, the other two changes are unrelated improvements)

**Comment by jarroyoe** [comment]
Thank you that worked seamlessly
