### ISSUE TITLE
BUG WEBSITE: Some tutorials on the webpage are immediately redirecting to the landing page

### ISSUE THREAD

**Issue by schlichtanders** [TuringLang/Turing.jl#2010]
Hi there,

I wanted to take a look at the https://turing.ml/v0.22/tutorials/09-variational-inference tutorial, but realised something is buggy - I am directly redirected to the landingpage such as there was a 404 not found error.

Would be great if this could big fixed,
best,
Stephan

**Comment by devmotion** [comment]
This is a known problem with the old webpage turing.ml which has not been updated for quite some time. Turing docs, tutorials, etc. are hosted at turinglang.org.

**Comment by schlichtanders** [comment]
Surprising. It would be great if the old webpage could eithr directly redirect to the new one, or at least put a warning on the top, that there is a newer website/version

**Comment by schlichtanders** [comment]
the more thank you very much for your patience. I am for sure the 30th+ person to ask such question about the documentation
