### ISSUE TITLE
Saving generated values

### ISSUE THREAD

**Issue by ya0** [TuringLang/Turing.jl#2059]
For diagnostics about my models I had the need to save spesific generated values. for example the individual predictions IPRED in longitudinal models or the cumulative hazard for survival models. It there a way to save such values already?

In the beginning i developt a cumstom distribution to help with this. Later on I found the `Dirac` distribution which basically gives this functionality. The value given to the distribution is the value that will be sampled. For the Turing framework it will look like a prior and thus will populate this value and then save it to the chains output.

E.g. how to save IPRED in the linear regression turorial
```julia
# Bayesian linear regression.
@model function linear_regression(x, y)
    # Set variance prior.
    σ² ~ truncated(Normal(0, 100); lower=0)

    # Set intercept prior.
    intercept ~ Normal(0, sqrt(3))

    # Set the priors on our coefficients.
    nfeatures = size(x, 2)
    coefficients ~ MvNormal(Zeros(nfeatures), 10.0 * I)

    # Calculate all the mu terms.
    mu = intercept .+ x * coefficients

    # Use dirac distrubution to save the individual predictions IPRED
    IPRED ~ Dirac.(mu)

    return y ~ MvNormal(mu, σ² * I)
end
```
This allows you to plot IPRED vs OBS and lets you define IRES = IPRED - OBS and plot IRES vs come covariates etc. I assume some people would be interested in this functionality. This could be included in the documentation somewhere. I am not sure how the documentation is structured or where to put it.

**Comment by torfjelde** [comment]
This issue has come up quite a few times and the `Dirac` solution, even though it's indeed the go-to at the moment, it does end up breaking sampling with AD-based samplers, e.g. NUTS, as Turing ends up treating the `Dirac` variable (`IPRED` in your case), as a random variable to be sampled.

There are a few ways to address this, but the _preferred_ way is to instead make use of `generated_quantities`: https://turinglang.org/library/DynamicPPL/stable/api/#DynamicPPL.generated_quantities

**Comment by ya0** [comment]
Generated quantities looks like a solution.

I did not encounter any issures with AD samplers (NUTS). I do not condition on the IPRED variable. I use it strictly as a "prior" to be "sampled" by a turing sampling algorithm for the posterior.
