### ISSUE TITLE
Can't apply Bijectors.ordered to TDist(), says it's constrained

### ISSUE THREAD

**Issue by boogiewoogit** [TuringLang/Turing.jl#2064]
The following fails with the error `ArgumentError: ordered transform is currently only supported for unconstrained distributions.`:

```
using Turing

Bijectors.ordered(filldist(TDist(1),2))
```

However, the t-distribution is supported on the real line and thus in fact unconstrained in the sense of this package.

**Comment by Red-Portal** [comment]
Could you file this to [Bijectors.jl](https://github.com/TuringLang/Bijectors.jl)?

**Comment by Red-Portal** [comment]
The reason seems to be that `TDist`'s support result in the wrong type:
```julia
julia> bijector(TDist(1))
Bijectors.TruncatedBijector{Float64, Float64}(-Inf, Inf)
```

On a side note, `Distributions` also has [MvTDist](https://github.com/JuliaStats/Distributions.jl/blob/c664d2591dd823483240b799387b049dc5f6851b/src/multivariate/mvtdist.jl#L65) for this purpose, but this doesn't work either, which I think it should. So this is probably a bug.

**Comment by Red-Portal** [comment]
In the meantime, you can bypass the check by calling the constructor directly:
```julia
julia> Bijectors.transformed(filldist(TDist(1), 2), Bijectors.OrderedBijector())

MultivariateTransformed{Product{Continuous, TDist{Float64}, FillArrays.Fill{TDist{Float64}, 1, Tuple{Base.OneTo{Int64}}}}, Bijectors.OrderedBijector}(
dist: Product{Continuous, TDist{Float64}, FillArrays.Fill{TDist{Float64}, 1, Tuple{Base.OneTo{Int64}}}}(v=Fill(TDist{Float64}(ν=1.0), 2))
transform: Bijectors.OrderedBijector()
)
```
But please report this to `Bijector` when you can since there seem to be at least two to three bugs here!

**Comment by boogiewoogit** [comment]
Thanks a lot for sharing the method to bypass!

I have filed the issue at `Bijectors.jl`: https://github.com/TuringLang/Bijectors.jl/issues/287.
