### ISSUE TITLE
How to conduct Bayesian inference using an existing posterior samples as new prior distribution, as well as new observations in Turing?

### ISSUE THREAD

**Issue by KennethAnn** [TuringLang/Turing.jl#2069]
I am conducting a Bayesian inference on a relatively large ordinary differential equations system with four  different sets of observations. However, it seems extremely time-consuming when directly constraining the model using all oservations. Therefore, I am trying to conduct a four-stage Bayesian Inference to constrain the data one by one. And in different stages, we could also add new parameters. The general idea is as below:
![image](https://github.com/TuringLang/Turing.jl/assets/89579419/b96e9d6e-e6f7-4694-8b33-730ff2b739e0)

So I am wondering whether the above process is necessary and what the best execise is to finish such procedure?

**Comment by devmotion** [comment]
Sequential Monte Carlo methods (see e.g. https://en.wikipedia.org/wiki/Particle_filter or https://www.ida.liu.se/divisions/stima/fokurser/smc/#material and the references therein) would be my initial suggestion for such sequential Bayesian updates.

**Comment by KennethAnn** [comment]
Thanks for your kind response. Here I am attempting a simple approach that sequentially conducting Bayesian inference step by step. Thus I am trying to establish the sampled posterior distributions as discrete parameter distributions. However, when I testthe function DiscreteNonParametric() in Distributions.jl to generate the distribution for Turing model function. A model error is thrown out. I am wondering whether the error can be solved? ERROR: MethodError: objects of type DiscreteNonParametric{Float64, Float64, Vector{Float64}, Vector{Float64}} are not callable

The motion is to replace InverseGamma distribution in its discrete form, see the codes below:
```Julia
using Distributions, Turing
xs = rand(InverseGamma(2, 3), 1000000)
ps = ones(Float64, length(xs)) ./ length(xs)
dists = DiscreteNonParametric(xs, ps)

@model function gdemo(x, y)
    s² ~ dists()
    m ~ Normal(0, sqrt(s²))
    x ~ Normal(m, sqrt(s²))
    return y ~ Normal(m, sqrt(s²))
end

chn = sample(gdemo(1.5, 2), NUTS(), 1000)
```

**Comment by KennethAnn** [comment]
Thanks for your kind response. Here I am attempting a simple approach that sequentially conducting Bayesian inference step by step. Thus I am trying to establish the sampled posterior distributions as discrete parameter distributions. However, when I testthe function DiscreteNonParametric() in Distributions.jl to generate the distribution for Turing model function. A model error is thrown out. I am wondering whether the error can be solved? ERROR: MethodError: objects of type DiscreteNonParametric{Float64, Float64, Vector{Float64}, Vector{Float64}} are not callable

The motion is to replace InverseGamma distribution in its discrete form, see the codes below:
```Julia
using Distributions, Turing
xs = rand(InverseGamma(2, 3), 1000000)
ps = ones(Float64, length(xs)) ./ length(xs)
dists = DiscreteNonParametric(xs, ps)

@model function gdemo(x, y)
    s² ~ dists()
    m ~ Normal(0, sqrt(s²))
    x ~ Normal(m, sqrt(s²))
    return y ~ Normal(m, sqrt(s²))
end

chn = sample(gdemo(1.5, 2), NUTS(), 1000)
```

Another choice is to establish a binned univariate continous distribution by using EmpiricalDistributions.jl, but similar, objects of type are not callable. See:

using Distributions, StatsBase, EmpiricalDistributions, Turing
X_uv = rand(InverseGamma(2, 3), 1000000)
p_uv = ones(Float64, length(X_uv)) * 1 / length(X_uv)
uvhist = fit(Histogram, X_uv; nbins=100000)
uvdist = UvBinnedDist(uvhist)

```Julia
@model function gdemo(x, y)
    s² ~ uvdist()
    m ~ Normal(0, sqrt(s²))
    x ~ Normal(m, sqrt(s²))
    return y ~ Normal(m, sqrt(s²))
end

chn = sample(gdemo(1.5, 2), NUTS(), 1000)
```

**Comment by Red-Portal** [comment]
You cannot use `DiscreteNonParameteric` or something like a binned histogram with gradient-based MCMC algorithms like `NUTS` since their log-pdf is not well-behaved. You could, in principle use kernel density estimates, but this will work poorly on any interesting real-world problem. As @devmotion  has suggested, online inference for Bayesian models are usually done through particle filtering (this is what @devmotion called SMC) or particle MCMC. But I'm not sure if there is a good example of doing this using Turing.

**Comment by KennethAnn** [comment]
> You cannot use `DiscreteNonParameteric` or something like a binned histogram with gradient-based MCMC algorithms like `NUTS` since their log-pdf is not differentiable. You could, in principle, use kernel density estimates, but this will work poorly on any interesting real-world problem. As @devmotion has suggested, online inference for Bayesian models are usually done through particle filtering (this is what @devmotion called SMC) or particle MCMC. But I'm not sure if there is a good example of doing this using Turing.

Thanks! Very clear to me. I will try some other approaches to finish my task.
