### ISSUE TITLE
DynamicNUTS (via DynamicHMC) no longer works in Julia v1.9.  

### ISSUE THREAD

**Issue by celise88** [TuringLang/Turing.jl#2090]
Running e.g.:

using Turing, MCMCChains, DynamicHMC, AdvancedHMC
chain = sample(model, DynamicNUTS(), 1000, thinning = 3, discard_adapt = true)

throws the following error:

ERROR: UndefVarError: `DynamicNUTS` not defined

**Comment by devmotion** [comment]
I assume you use Turing >= 0.28? Since Turing 0.28 you have to use `sample(model, externalsampler(DynamicHMC.NUTS()), 1_000: ...)`: https://turinglang.org/v0.28/docs/using-turing/dynamichmc/

**Comment by celise88** [comment]
Thanks so much! I missed that. I'll close the issue.
