### ISSUE TITLE
Return Multivariate/Vector of derived (determinist) parameters from `@model` 

### ISSUE THREAD

**Issue by arthurmloureiro** [TuringLang/Turing.jl#2103]
Hi!

I am finding extremely difficult to extract derived or determinist variables from inside `@model`. The `return` keyword appears to be ignored and doesn't return any deterministc variables. 

For example, in this model here
```julia
@model function model(data, cov::Vector{Float64}) 
    a ~ MvNormal(diagm(cov))
    m = exp.(a)
    data ~ MvNormal(a)
    return m
end
```
I want to return `m` as a variable, too.

Is that possible? I've seen several issues suggesting using `Dirac` or creating a deterministic distribution but I was wondering if there's no proper way of doing that nor any plans for doing that as this is extremely useful in several fields of science.

**Comment by torfjelde** [comment]
`generated_quantities` is the way to go: https://turinglang.org/library/DynamicPPL/stable/api/#DynamicPPL.generated_quantities

**Comment by arthurmloureiro** [comment]
Hi @torfjelde ,

Thank you! That worked as intended! I had no idea about the `DynamicPPL` package, does it appear anywhere in the `Turing.jl` documentation?

**Comment by devmotion** [comment]
It's documentation is included in the Turing homepage as part of the libraries in the Turing ecosystem: https://turinglang.org/library It also appears in a few tutorials, e.g., https://turinglang.org/v0.29/tutorials/00-introduction/

**Comment by torfjelde** [comment]
What @devmotion said:) But yes, we'll eventually get around to making these functionalities more obvious to use in the tutorials, etc.!
