### ISSUE TITLE
Docs: setadbackend

### ISSUE THREAD

**Issue by ya0** [TuringLang/Turing.jl#2155]
See docs [autodiff](https://turinglang.org/v0.30/docs/using-turing/autodiff) it mentions the function `Turing.setadbackend` but when i try to use this I get the error:

```julia
julia> Turing.setadbackend(:reversediff)
ERROR: UndefVarError: `setadbackend` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ REPL[35]:1
```

I assume it is connected to PR #2047

**Comment by torfjelde** [comment]
`setadbackend` should still be defined after that PR.

What version of Turing.jl are you on?

**Comment by ya0** [comment]
The version v0.30.1

Look at this comming on master: https://github.com/TuringLang/Turing.jl/commit/d0691e039ca7617173dade783b36ef23ca7de726

The docs i linked above at v30. the stable and dev versions look about the same.

**Comment by devmotion** [comment]
It was removed in #2134 and, it seems, incorrectly deprecated in #2144.
