### ISSUE TITLE
`Prior` sampler should use `PriorContext`, not `DefaultContext`

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/Turing.jl#2169]
Example Thanasi Bakis in Slack:
```julia
using Turing

function loglik(θ, x)
    println("In loglik")
    
    return logpdf(Normal(θ, 1), x)
end

@model function test(x)
    θ ~ Normal(0, 1)

    if DynamicPPL.leafcontext(__context__) !== Turing.PriorContext()
        println(DynamicPPL.leafcontext(__context__))
        Turing.@addlogprob! sum(loglik.(θ, x))
    end
end

sample(test(randn(100) * 1000), Prior(), 100)
```
results in `DefaultContext` rather than `PriorContext`.

**Comment by thanasibakis** [comment]
Thanks!!

**Comment by torfjelde** [comment]
As noted by @thanasibakis , the above snippet now does evaluate the code using the `DefaultContext` after v0.31.4 since we're now re-evaluating the model to convert parameters from internal to user-facing representation. 

I don't think this causes any bugs, as this is just a post-inference step, but it _does_ cause additional computation overhead, which is an issue I also raised in the PR that introduced this change https://github.com/TuringLang/Turing.jl/pull/2202, and is thus related to https://github.com/TuringLang/Turing.jl/issues/2215.

No matter, we should maybe be running this value extraction using the `PriorContext` anyways, since we're only interested in hitting that part of the `~` pipeline.
