### ISSUE TITLE
ADVI does not work with new DynamicPPL.jl Conditioning Syntax

### ISSUE THREAD

**Issue by h-spiess** [TuringLang/Turing.jl#2178]
Hey,

It seems that Turing's ADVI does not work with the new conditioning syntax in DynamicPPL.jl, which I think is becoming the default.

Example using ForwardDiff (also fails for the other Backends):

```
using Random
using Turing

@model function model()
    s ~ InverseGamma(2, 3)
    m ~ Normal(0.0, sqrt(s))
    x .~ Normal(m, sqrt(s))
end

@model function model_old(x)
    s ~ InverseGamma(2, 3)
    m ~ Normal(0.0, sqrt(s))
    x .~ Normal(m, sqrt(s))
end

x = randn(2000)

m = model() | (x=x, )
m_old = model_old(x)

advi = ADVI(10, 1000)
q = vi(m, advi) # ERROR: BoundsError: attempt to access 2-element Vector{ForwardDiff.Dual{ForwardDiff.Tag{AdvancedVI.var"#f#25"{AdvancedVI.ELBO, ADVI{AdvancedVI.ForwardDiffAD{0}}, ...
q = vi(m_old, advi) # works
```

I'm using the newest versions of the relevant packages on an M1 macbook.

```
julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
```

```
pkg> st
Status `~/.julia/dev/playground/PPLsForKernelCompletion/Project.toml`
  [80f14c24] AbstractMCMC v5.2.0
  [b5ca4192] AdvancedVI v0.2.4
  [76274a88] Bijectors v0.13.8
  [31c24e10] Distributions v0.25.107
  [366bfd00] DynamicPPL v0.24.9
⌃ [c7f686f2] MCMCChains v6.0.5
  [fce5fe82] Turing v0.30.5
```

**Comment by torfjelde** [comment]
This is not an issue with ADVI + `condition` syntax, but an issue with your model definition.

Internally, every `~` statement is converted into `=` + extras, and similarly `.~` is converted into `.=` + extras.

This means that when you write

``` julia
x .~ Normal(...)
```

this will result in some expression involving

``` julia
x .= ...
```

But, as this is just standard Julia code, this won't work if `x` is not yet defined!

In your "old" model, i.e.

``` julia
@model function model_old(x)
    s ~ InverseGamma(2, 3)
    m ~ Normal(0.0, sqrt(s))
    x .~ Normal(m, sqrt(s))
end
```

`x` is provided as an argument, and is thus defined. In your new model, `x` is not defined before we hit the `.~` (and thus `.=`).

Unfortunately this is not clear from the exception thrown.

The first thing to do when something fails with a model is to just check if you can run it without any inference, e.g.

``` julia
julia> using Turing

julia> @model function model()
           s ~ InverseGamma(2, 3)
           m ~ Normal(0.0, sqrt(s))
           x .~ Normal(m, sqrt(s))
       end
model (generic function with 2 methods)

julia> model_instance = model();

julia> model_instance()
ERROR: UndefVarError: `x` not defined
...
```

Here we see that we get a more informative error message:)

So, the way to write a `.~` + use the new condition syntax is to specifically allocate the `x` before we hit `.~`:

``` julia
julia> @model function model_v2(n)  # need to specify the length as input
           s ~ InverseGamma(2, 3)
           m ~ Normal(0.0, sqrt(s))
           x = Vector(undef, n)
           x .~ Normal(m, sqrt(s))
       end
model_v2 (generic function with 2 methods)

julia> model_instance = model_v2(10);

julia> model_instance()
10-element Vector{Float64}:
  1.4266801924189414
  0.8200920046396959
  0.7113019610151704
  1.231743385599
 -0.5561762370549463
  1.4947248221581675
 -0.9162359604360499
 -1.2980392578414817
 -1.3348312021509032
 -0.44033058315337587
```

Now, using a `Vector(undef, n)` is not a great idea in general, as this leads to type-instabilities.

Following advice in the docs (https://turinglang.org/v0.30/docs/using-turing/performancetips#ensure-that-types-in-your-model-can-be-inferred), we should instead to

``` julia
@model function model_v3(n, ::Type{TV}=Vector{Float64}) where {TV}
    s ~ InverseGamma(2, 3)
    m ~ Normal(0.0, sqrt(s))
    x = TV(undef, n)
    x .~ Normal(m, sqrt(s))
end
```

Now this will be performant + useable with AD.

As a final note: if you know that a particular variable is _always_ going to be conditioned on and you don't need the flexibility of easily being able to change the values, etc., using the "old" syntax is probably still the way to go as it will be slightly more performant in these cases. If you want performance, `.~` is always going to be slower than, say, `x ~ filldist(Normal(m, sqrt(s)), length(x))`.

Hope this helps!
