### ISSUE TITLE
refactor tests into multiple Github CI steps

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#2179]
Similiar to https://github.com/TuringLang/JuliaBUGS.jl/issues/149. 

Let's remove the complex macros including `numerical_testset`, and `turing_testset` etc. Instead, let's simply group tests by files and run these test files in different CI runners. 

Useful resource for local test: https://gist.github.com/torfjelde/62c1281d5fc486d3a404e5de6cf285d4

**Comment by torfjelde** [comment]
Very much agree with this :+1:

**Comment by torfjelde** [comment]
> We only need to test gradient evaluation for the AD functionality test, but we currently run HMC, which is an overkill.

A counter point to this: https://github.com/TuringLang/DynamicPPL.jl/issues/612

Sometimes AD only breaks when we're sampling 😬
