### ISSUE TITLE
init_params in v.0.30.1

### ISSUE THREAD

**Issue by evolbeginner** [TuringLang/Turing.jl#2192]
Dear Turing,

I upgraded turing from v0.29 to v0.30 and seems that v0.30.1 does not consider init_params. for example, the following worked well in v.29.3 within a few seconds but took a very long time in v0.30.1.

```Julia
@model function demo()
                 X = Vector{Real}(undef, 30)

                 for i in 1:length(X)
                         X[i] ~ Uniform(0,1)
                 end

                 for i in 1:(length(X)-1)
                      if !(X[i] < X[i+1])
                          Turing.@addlogprob! -Inf
                          return
                      end
                  end
              return X
       end

chain = sample(demo(), NUTS(100,0.65), 10000, init_params=range(0.01,0.99,length=30))
```

actually, it gave me a warning msg saying that "try to provide initial values of the parameters by init_params".

Would you please mind having a look at it? Thank you much!

**Comment by devmotion** [comment]
The keyword argument was changed to `initial_params`: https://github.com/TuringLang/Turing.jl/issues/2150#issuecomment-1875220643

**Comment by evolbeginner** [comment]
> The keyword argument was changed to `initial_params`: [#2150 (comment)](https://github.com/TuringLang/Turing.jl/issues/2150#issuecomment-1875220643)

Thanks so much! It worked well.
