### ISSUE TITLE
Merge SMC and PG?

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#222]
Is it possible to somehow merge the code of SMC and PG and let SMC run as PG with iteration num = 1

**Comment by yebai** [comment]
Yes, that sounds possible. We used to have two different replaying mechanisms (TraceR, TraceC) for SMC and PG, but this does not seem necessary anymore.

**Comment by yebai** [comment]
- [ ] Make `Trace` produce `vi` instead of weights.

**Comment by yebai** [comment]
Closing now since particle samplers have been refactored into [`AdvancedPS.jl`  ](https://github.com/TuringLang/AdvancedPS.jl)
