### ISSUE TITLE
Using the score function estimator as gradient for VI

### ISSUE THREAD

**Issue by arnauqb** [TuringLang/Turing.jl#2287]
Hello,

Imagine we have a model that looks like this

```julia
@model function m(data)
    θ ~ Normal(0, 1)
    x ~ f(θ)
    data ~ Normal(x, 1.0)
end
```

Where `f` is some let's say physics simulator that may not be differentiable but that I have implemented as a custom distribution with `logpdf` defined.

In order to fit the model using VI, I want to use the **score-function estimator** to estimate the gradient throughout the simulator (see e.g.,  [https://arxiv.org/pdf/1906.10652](https://arxiv.org/pdf/1906.10652)).

The functionality I need is to sample $\{\theta_i\} \sim q_\phi(\theta)$ where $q$ is the variational distribution with parameters $\phi$ and compute

$$
\nabla_\phi\log q_\phi (\theta) f(\theta)
$$

Looking at the internals of Turing.jl, it seems that the AD backends are defined in https://github.com/tpapp/LogDensityProblemsAD.jl however I am not sure how to reach $\nabla_\phi \log q_\phi$ when I am implementing a custom derivative of $f$.

Edit:

I think Pyro deals with this automatically for non-parameterizable variables under the hood: https://pyro.ai/examples/svi_part_iii.html

**Comment by arnauqb** [comment]
Thanks @sunxd3 and @Red-Portal  for the replies. 

I have been able to implement a working score-based estimator with the current master of AdvancedVI.jl.
I can submit a PR if its of interest to have it as an example or part of the main code.

**Comment by Red-Portal** [comment]
@arnauqb By the current master, do you mean v0.3.0 version? Either way, if you submit a PR, I would be happy to take a look. Ideally, it would be best to mix score and reparameterization gradients, but I am currently unsure how to do it. I might take a look at how Pyro does it in more detail.

**Comment by arnauqb** [comment]
leaving here for reference:

https://github.com/TuringLang/AdvancedVI.jl/pull/72

As I mention in the PR, right now I define a new variational objective and all the model is optimized using the score estimator. However, ideally we would like to use the pathwise where possible.

@sunxd3 I'm not very familiar with the DynamicPPL syntax, but I noticed that Turing supports [mixed autodiff](https://turinglang.org/v0.24/docs/using-turing/autodiff). Would it be possible to do something similar for the score estimator? That is, the user could specify in the model declaration that a certain logpdf gradient needs to be estimated using the score estimator. I am not sure how one can get access to the `logpdf` of the samples that are being passed from inside a ChainRulesCore declaration.

**Comment by arnauqb** [comment]
also this package may be relevant to achieve this: https://github.com/JuliaDecisionFocusedLearning/DifferentiableExpectations.jl @gdalle

**Comment by gdalle** [comment]
Yeah that package of mine is still in the early stages (definitely use the version on main rather than the last one we registered), but the goal is to implement score function / reinforce gradients as well as reparametrization. Any feedback and suggestions are appreciated!
@BatyLeo

**Comment by gdalle** [comment]
Also I'd be thrilled to figure out if we can make this more Turing-friendly
