### ISSUE TITLE
Multithread tests fail on master

### ISSUE THREAD

**Issue by mhauru** [TuringLang/Turing.jl#2302]
This happened recently:

> We seem to have an unfortunate case here where a PR that passed tests (https://github.com/TuringLang/Turing.jl/pull/2291) was merged, and then immediately after merging tests on master started to fail (https://github.com/TuringLang/Turing.jl/actions/runs/10281463329/job/28451089388). It's a concurrency problem of some kind, only appears on multithreaded. Haven't dug into it yet.

That's still the case on master. Looking into this now.

**Comment by devmotion** [comment]
Was curious and checked the logs: The final culprit seems to be the write access in https://github.com/JuliaLang/julia/blob/96fd25a764c316e9e09dfd7de8e84d854a73b2cd/base/logging/ConsoleLogger.jl#L112 but AFAICT it is only triggered by the deprecation warning of ADTypes triggered in LogDensityProblemsAD.

**Comment by devmotion** [comment]
https://github.com/tpapp/LogDensityProblemsAD.jl/pull/34 should fix the deprecation warning

**Comment by mhauru** [comment]
Thanks @devmotion! I was looking at the ConsoleLogger bit as well, and I find it alarming that calling `depwarn` (or probably other logging calls would do as well) can cause a concurrency error. I just posted on Julia's Slack to see if anyone can tell me more about thread safety of logging.

**Comment by devmotion** [comment]
It seems fixing the ADTypes deprecations resolved the test error: https://github.com/TuringLang/Turing.jl/actions/runs/10322735917/job/28712240978

**Comment by mhauru** [comment]
Great, thanks!

**Comment by mhauru** [comment]
The root cause is this long standing Julia issue: https://github.com/JuliaLang/julia/issues/34600
