### ISSUE TITLE
Julia 1.7 tests are failing

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/Turing.jl#2305]
All tests on Julia 1.7 are failing, see e.g. this run on #2304 https://github.com/TuringLang/Turing.jl/actions/runs/10378600942

I suspect it's because on Julia 1.7, ADTypes resolves to v0.2.7 (probably because some other dependency like SciMLBase specifies that), and that breaks when used with the new v1.9.1 of LogDensityProblemsAD (despite the compat entry being modified in https://github.com/tpapp/LogDensityProblemsAD.jl/pull/34).

In contrast, on Julia 1.10, ADTypes resolves to v1.7.1 and all is good.

I'm not sure how Pkg handles version conflicts like these. I do find it weird that it resolved the environment to include both v1.9.1 of LogDensityProblemsAD and v0.2.7 of ADTypes, which are incompatible — intuitively, I'd have expected it to pick a lower version of LogDensityProblemsAD.

**Comment by penelopeysm** [comment]
Oh, I'm guessing it's because ADTypes is a weak dependency of LogDensityProblemsAD, and Pkg 1.7 doesn't understand those as extensions were introduced in Julia 1.9.

On Julia 1.10 if you try to do `]add LogDensityProblemsAD` and `]add ADTypes@0.2`, Pkg correctly downgrades LogDensityProblemsAD to v1.9.0.

**Comment by mhauru** [comment]
Some possibly relevant context: At some point we [dropped](https://github.com/TuringLang/Turing.jl/pull/2243) support for ADTypes v0.2, then [ran into trouble](https://github.com/TuringLang/Turing.jl/issues/2251) with that, and [reintroduced](https://github.com/TuringLang/Turing.jl/pull/2252) it.

**Comment by penelopeysm** [comment]
Ah that's very good to know. The issue isn't really with Turing, though. I think the "issue" is with LogDensityProblemsAD, because any package that uses julia<1.9 with ADTypes and LogDensityProblemsAD will run into the same issue.

Even more generally, one would expect situations like these to happen with any package that uses extensions. Surely *someone* has solved this or run into this before? But I couldn't find anything on GitHub issues, Discourse, or Slack.

**Comment by devmotion** [comment]
I guess one problem is that LogDensityProblemsAD uses Requires to load the optional dependencies on Julia < 1.9, but does not e.g. load them unconditionally on older versions by making them proper dependencies on Julia < 1.9. Then dependencies and compat entries would be respected by Pkg also on Julia < 1.9 as expected. But it's somewhat understandable does LogDensityProblemsAD does not want to depend on all AD packages... I guess we can easily fix the current regression but the problem will come up with other updates again.

Another problem on Julia < 1.9 is that SciML basically dropped support for Julia < 1.9 in almost all packages. Which makes it quite annoying and somewhat challenging to keep support Julia < 1.9 if you depend on parts of the SciML stack. So maybe we should generally consider dropping support for Julia < 1.9 (or not depend on SciML as much by default)?

**Comment by devmotion** [comment]
https://github.com/tpapp/LogDensityProblemsAD.jl/pull/35 should be a quick hotfix for Julia < 1.9 + ADTypes 0.2.

**Comment by penelopeysm** [comment]
Thanks for the super quick fix @devmotion!

Separately, I've posted on Discourse, https://discourse.julialang.org/t/compat-entries-for-weakdeps-on-julia-1-9/118172 but I'm not sure that there's a nice solution to it here.

It appears to me the least bad way is for LogDensityProblemsAD to declare a requirement of julia >= 1.9, since that's the only way the compat entries will be respected. This is definitely suboptimal, because there are cases under which it could be compatible with < 1.9 and some people may well want to use that, but this is the only way to guarantee that it will work going forward. And I suppose it might be worth doing anyway based on how the Julia ecosystem is moving, though you all are the experts here.

**Comment by penelopeysm** [comment]
Oh, I see you just said the same thing there. :)

Anyway, will rerun tests later today once the registry is updated and close this issue if they pass with the new version.

**Comment by penelopeysm** [comment]
Working now: https://github.com/TuringLang/Turing.jl/actions/runs/10389651637
