### ISSUE TITLE
Dead code in `mcmc/hmc.jl`?

### ISSUE THREAD

**Issue by sunxd3** [TuringLang/Turing.jl#2311]
I don't think these are in use
https://github.com/TuringLang/Turing.jl/blob/07cc40beb0c6caa60e945e204f0fbc88cd3d4362/src/mcmc/hmc.jl#L567-L620

reason is there is a call to function `gen_∂logπ∂θ` which I can not find the definition of, and the call to `HMCState` seems out of date with the current `HMCState` type

**Comment by devmotion** [comment]
`gen_∂logπ∂θ` was used for a long time to construct something similar to the `LogDensityFunction` for HMC algorithms. Probably we just forgot to remove this code.
