### ISSUE TITLE
Nested sampling integration

### ISSUE THREAD

**Issue by mvsoom** [TuringLang/Turing.jl#2329]
Very happy to hear about the funding from Alan Turing Institute!

I was wondering if there is still interest for working on [the NestedSamplers integration](https://github.com/TuringLang/NestedSamplers.jl/issues/29), as this is possibly a very powerful sampling backend (for example popular in the astronomy community). Previous attempts seem to have stranded.

Very willing to help out by testing and contributing to the nested sampling code itself, but the integration into Turing is well over my head.

**Comment by Red-Portal** [comment]
Integrating Turing is now way easier than it used to be. There are few examples that should be straightforward to follow. See [this repo](https://github.com/torfjelde/AutomaticMALA.jl), which is intended as a tutorial. Also [this one](https://github.com/TuringLang/SliceSampling.jl), which is a more realistic example.

**Comment by mvsoom** [comment]
OK, I'll take a look in some time. Thanks
