### ISSUE TITLE
`ForwardDiff.gradient` is slow

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#234]
It seems the new `gradient` function based on `ForwardDiff.gradient` is very slow, e.g. on the model `Turing/benchmarks/naive.bayes.run.jl`.

**Comment by ChrisRackauckas** [comment]
Should probably use in-place gradient functions. But reverse mode is probably more efficient here, so you should probably follow the developments of Cassette.jl

**Comment by yebai** [comment]
Closed by #485
