### ISSUE TITLE
coveralls actions fails randomly

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/Turing.jl#2386]
see e.g. https://github.com/TuringLang/Turing.jl/actions/runs/11594848843/job/32282087314

No idea why this is happening, but almost certainly an upstream issue, maybe with some server. Maybe we should just mark this step as `continue-on-error: true`?

**Comment by willtebbutt** [comment]
Sadly, I did not. It seems to have stabilised for Mooncake, so the issue that I opened has been closed: https://github.com/codecov/codecov-action/issues/1538 . However, it looks like someone else has reported this issue and, at the request of the maintainer, opened a separate issue: https://github.com/codecov/codecov-action/issues/1602

**Comment by penelopeysm** [comment]
I think it's a different action; the one in the run above is [coveralls](https://github.com/coverallsapp/github-action/) whereas the one you ran into @willtebbutt is [codecov](https://github.com/codecov/codecov-action).

I'm not actually super familiar with these coverage services so I don't know if we need both. In practice I'm not sure we even pay any of them very much attention.

**Comment by willtebbutt** [comment]
🤦 sorry -- I wrote my reply sufficiently quickly that I didn't check the coverage provider. Apologies!

**Comment by penelopeysm** [comment]
I don't think this is reproducible.
