### ISSUE TITLE
Merge `Trace.vi` and `vi`?

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#249]
We currently maintain two copies of `vi`, one stored in `Trace`, another is passed to model through keyword arguments. Perhaps we should merge this `vi`'s to reduce confusion.

Ref: #247, #246, #248

**Comment by xukai92** [comment]
How can we bind randomness to `Trace` then?

**Comment by yebai** [comment]
Related https://github.com/TuringLang/Turing.jl/issues/1019
