### ISSUE TITLE
Do not extend functions from Base or other packages on types not from this package

### ISSUE THREAD

**Issue by tkelman** [TuringLang/Turing.jl#252]
Ref https://github.com/yebai/Turing.jl/pull/66#discussion_r112798061 and https://github.com/yebai/Turing.jl/pull/112#discussion_r112798149 and https://github.com/yebai/Turing.jl/pull/85#discussion_r112797746 - this is known as type piracy and has global side effects, and can change the behavior of completely unrelated code. Method extension is safe when either the function or at least one of the input types is from this package. If the function and all the types are from Base or some other package (like Distributions), then the method extension shouldn't be defined in this package.

**Comment by yebai** [comment]
Many thanks for pointing these issues out, we will fix this issues in the next release (v0.2.1). Will be coming soon!

**Comment by xukai92** [comment]
Closed by #316

**Comment by tkelman** [comment]
You're still changing the behavior of Distributions.jl. Please reopen this and/or fix that.

**Comment by tkelman** [comment]
You're also overwriting `Base.produce(::Any)` here https://github.com/yebai/Turing.jl/blob/61f6e659c3f838288be9d7fc708173ea222ff24a/src/trace/taskcopy.jl#L41

Please don't do that - anywhere you're getting a method overwrite warning that you're hiding with `@suppress_err`, it's because you're doing something you shouldn't be doing. Use types and functions specific to this package to extend behavior, don't make global overwrite modifications.

**Comment by tkelman** [comment]
This is still a problem.

**Comment by yebai** [comment]
> This is still a problem.

We'll see what we can do after fixing #173, https://github.com/yebai/Turing.jl/issues/330

**Comment by tkelman** [comment]
Okay sounds good, thanks for reopening

**Comment by yebai** [comment]
Should be fixed now.
