### ISSUE TITLE
Generic support for GMM type in Distributions.jl

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#266]
GMM implemented in notebook (https://github.com/yebai/Turing.jl/pull/262/commits/498b6ea1fde2f48f9c26eccc26ccd3413c321566) use the UnivariateGMM which has bad generic support yet. Need to make a PR for that.

**Comment by xukai92** [comment]
PR: https://github.com/JuliaStats/Distributions.jl/pull/615

**Comment by xukai92** [comment]
@yebai I may leave it for a while because finishing the PR would cost a lot of time to fixing things other than `logpdf` (e.g. their `cdf` and stuff are all the way not support generic, which already cost me lot of time to figure out which piece of code to fix). I would gradually work on this issue from time to time.

**Comment by yebai** [comment]
Fixed by https://github.com/JuliaStats/Distributions.jl/pull/615
