### ISSUE TITLE
Pre-cond seems unstable/buggy

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#284]
Sometimes when the sampler start to using pre-cond matrix, it constantly gives numerical errors.

**Comment by xukai92** [comment]
See https://travis-ci.org/yebai/Turing.jl/jobs/239948016: HMCDA has the issue but NUTS seems all fine.

**Comment by yebai** [comment]
@xukai92 see https://github.com/yebai/Turing.jl/issues/289#issuecomment-368570037

**Comment by xukai92** [comment]
Closed by PR #436
