### ISSUE TITLE
Make sure HMCDA is not buggy

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#289]
some of my runs of HMCDA gives error.

**Comment by xukai92** [comment]
*NOTE*: MoC sometimes gives error using HMCDA and NUTS (but HMC also works).

**Comment by xukai92** [comment]
Maybe related to https://github.com/yebai/Turing.jl/issues/284

**Comment by yebai** [comment]
@xukai92 The current code in https://github.com/yebai/Turing.jl/blob/master/src/samplers/support/adapt.jl#L74 might suffer from loss of precision. An alternative algorithm is the Welford accumulator (also used by Stan), see https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online_algorithm

**Comment by yebai** [comment]
@xukai92 

The following Stan C++ files contain implementation for variance and covariance adaption for NUTS

- https://github.com/stan-dev/math/blob/c36cfa2becfcc2a0673addb1600e9133e822998d/stan/math/prim/mat/fun/welford_var_estimator.hpp#L23

Stan basically uses a Welfard accumulator to calculate variance/covariance, then it adds a small identity matrix to make sure the returned covariance is positive definite, see the following file

- https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/var_adaptation.hpp#L27

**Comment by xukai92** [comment]
Closed by PR #436.
