### ISSUE TITLE
Use vec/parallelisation/GPU to speed up link/invlink

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#314]

**Comment by ChrisRackauckas** [comment]
GPU usage needs to be careful about data transfers: I'm not sure that's actually helpful here. But you can use GPUArrays.jl. If you wrap things in a GPUArray, then the vectorized operations in would be parallelized. By default it will multithread it, but then the user can change the backend to make that work on the GPU via CUDA or OpenCL (that's an easy way to support it and also test if it's actually beneficial). However, as with all GPU stuff, you'll need to make sure you don't do slicing and either replace those operations with views or reformulate the algorithm.

**Comment by yebai** [comment]
I think this can be done on the user side instead of in Turing.
