### ISSUE TITLE
Remove Flat distribution 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#315]

**Comment by xukai92** [comment]
How do you mentioned to remove `Flat`? I tried the below which doesn't work

```julia
d = Uniform(-Inf, Inf)
rand(d) # => NaN
```

**Comment by yebai** [comment]
This is likely an issue with the Distributions package, see

```julia
rand(rng::AbstractRNG, d::Uniform) = d.a + (d.b - d.a) * rand(rng)
```
https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/uniform.jl#L109

Do we actually need to sample from a flat distribution?

**Comment by xukai92** [comment]
I introduced `Falt` because some models used in Stan are doing so - i.e. do not have a prior and only sampling from the likelihood. E.g. mu in https://github.com/yebai/Turing.jl/blob/master/example-models/stan-models/school8-stan.model.jl

**Comment by bhgomes** [comment]
I may still want to use improper priors (see #812) so how will this removal of `Flat` reflect my ability to use these kinds of priors?

**Comment by yebai** [comment]
I'm leaning towards to rename `Flat` to something more specific, but generally ok to keep it around.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/812
