### ISSUE TITLE
A mixture of Poisson model

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#356]
```julia
# Load packages
using Turing, Distributions

# Define model
@model mix_of_p(M, counts) = begin
    N = length(counts)
    lambdas = tzeros(Float64, M)
    for m = 1:M
        lambdas[m] ~ Gamma(1, 2)    # Gamma is conjugate prior for Poissons
    end
    indicators =  tzeros(Int, N)
    ps ~ Dirichlet(ones(M))
    for n = 1:N
        indicators[n] ~ Categorical(ps)
        counts[n] ~ Poisson(lambdas[indicators[n]]) # observe data
    end
end

# Generate some toy data
M = 4
N = 100
lambdas = [1, 2, 4, 8]
ps = ones(M) ./ M
counts = []
for n = 1:N
    ind = rand(Categorical(ps))
    push!(counts, rand(Poisson(lambdas[ind])))
end

# Rune inference
chain = sample(mix_of_p(2, counts), PG(20, 200))

# Report results
println("Lambda 1: $(mean(chain[:(lambdas[1])]))")
println("Lambda 2: $(mean(chain[:(lambdas[2])]))")
println("Lambda 3: $(mean(chain[:(lambdas[3])]))")
println("Lambda 4: $(mean(chain[:(lambdas[4])]))")
```

I was helping with my friend using Turing.jl for a mixture of Poisson model. This example I wrote above runs quite slow when N is like 2,000. Any idea how to make it faster? @yebai

**Comment by yebai** [comment]
I played with the code a bit. The issue seems related to PG code not correctly using coroutine copying. Will try to look further into this issue together with #341.

**Comment by xukai92** [comment]
Yes - also it seems that PG doesn't free the memory it uses: I experienced memory overflow when running that for a relative long iteration (like 1,000) with not-small number of particles (like 100) with my Linux machine with 8GB memory.

**Comment by xukai92** [comment]
By memory overflow I simply means my computer freezes.

**Comment by yebai** [comment]
This is working fine on the master branch now.
