### ISSUE TITLE
Handling several vectors of random variables with random size

### ISSUE THREAD

**Issue by emilemathieu** [TuringLang/Turing.jl#367]
Hi all,

I found several issues preventing from performing inference in Turing on models with several vectors of random variables with random size. Handling this case is really important for Turing to be really "universal".

* Random lengths issues:
  * Wrapping samples in `Chain` at the end of `Sample(model::Function, alg::T)` calls `flatten!(chn::Chain)` which relies on the assumption that each samples contains the same random variables.
  * Some harmless `NaN` can be in the returned samples because of the way `CSMC` is implemented. We might want to remove them.

  * Saving in cache (`spl.info[:idcs]`) results of `getidcs(vi::VarInfo, spl::Sampler)` when called.

* Random order issues:
  * Calling `checkindex(vn, vi, spl)` in `assume{T<:Union{PG,SMC}}(spl::Sampler{T},...)`, if random variables can be sampled in different order.

  * `newtrace.vi[getretain(newtrace.vi, index, trace.spl)] = NULL` in `forkr(trace...)` can erase variables that should be kept. For instance if we have `vi.vals=...,NaN,1.0`, the `NaN` will be kept at some point but  `1.0` will be reset (set to `NaN`).

I'd be happy to get feedbacks on these limitations, especially since I didn't design them. I could be wrong or didn't fully understand how some part work.

Best,
Emile

**Comment by xukai92** [comment]
I believe our current design of `VarInfo` only supports **varied number of variables** but not **varied dimension of the same variable**. @yebai Are you agree on this?

I agree there are some bugs on varied dimension now. Ideally both PG and HMC should be able to do inference on models with varied number of variables. Maybe we should agree on some concrete examples and try to fix them?

**Comment by emilemathieu** [comment]
Some issues that I encountered are related to **vectors of random variables (i.e. multivariate random variables with size nx1) with random length** (n random), and others are related to random variables being **sampled in different orders**. I've updated my first post.

**Comment by emilemathieu** [comment]
I currently see 2 ways to handle sampling variables in random orders for `CSMC`:

* In `assume` when a `NaN` value is encountered, in addition to `setval!` and `setgid!` another function `updateidcsvals!(vi, vn, index)` could be called. This function would check whether `vi.idcs[vn]==index`. If not, the current sampled value `vn` and the one having `index` as value in `vi.idcs` would be swap (both in `vi.idcs` and `vi.vals`). This might be an computational overhead but only for models with random sampling order.

* Otherwise `VarInfo` could have another attribute `produce::Dict{Int,Vector{VarName}}`. This dict would be filled when a new entry is pushed to VarInfo (via `push!(vi...)`) with `push!(produce[vi.produce], vn)`. Then `getretain` would return `hcat([produce[i] for i in maximum(keys(produce)):-1:(n_retain+1)])`. I think that this solution yields less overhead but unfortunately for all models.

**Comment by emilemathieu** [comment]
This first solution described above is the following

```julia
assume{T<:Union{PG,SMC}}(spl::Sampler{T}, dist::Distribution, vn::VarName, _::VarInfo) = begin
...
      updateidcsvals!(vi, vn)
      setval!(vi, vectorize(dist, r), vn)
      setgid!(vi, spl.alg.gid, vn)
...
end

updateidcsvals!(vi::VarInfo, vn::VarName) = begin
  if getidx(vi, vn) != vi.index
    old_index = vi.idcs[vn]
    old_vns = [key for key in keys(vi.idcs) if getidx(vi, key) == vi.index]
    @assert length(old_vns) == 1 "updateidcsvals! failed: old_vns=$old_vns, vi.index=$(vi.index), vn_now=$(vn)"
    old_vn = old_vns[1]

    old_vals = getval(vi, old_vn)
    vi.idcs[vn] = vi.index
    vi.idcs[old_vn] = old_index
    setval!(vi, old_vals, old_vn)
  end
end
```

**Comment by emilemathieu** [comment]
@yebai have you read that ?

**Comment by yebai** [comment]
I need a bit time to refresh my memory about relevant data structures - will try to address this issue in the next 2 days.

**Comment by emilemathieu** [comment]
Another way to fix that would be to avoid situations like `vi.vals=...,NaN,1.0` by creating "fresh" particles in `CSMC`'s `step` method, by setting `vi = VarInfo()` instead of `vi[getretain(vi, 0, spl)] = NULL`.
Moreover, in `forkc(trace,...)` we would copy only the part of `trace.vi` which corresponds to the existing randomness with 

```julia
if is_ref
    n_rand = min(trace.vi.index, length(getvns(trace.vi, trace.spl)))
    newtrace.vi = deepcopywithoutrandomness(trace.vi, n_rand, trace.spl)
  else
    newtrace.vi = deepcopy(trace.vi)
  end
```

and `deepcopywithoutrandomness` defined as
```julia
deepcopywithoutrandomness(vi::VarInfo, n_retain::Int, spl::Sampler) = begin
  new_vi = VarInfo()
  new_vi.logp = copy(vi.logp)
  new_vi.index = copy(vi.index)
  new_vi.num_produce = copy(vi.num_produce)

  gidcs = getidcs(vi, spl)
  removing = map(i -> gidcs[i], length(gidcs):-1:(n_retain + 1))
  retains = filter(i -> !(i in removing) ,1:length(vi.gids))

  new_vi.idcs = Dict(vn=>idx for (vn,idx) in vi.idcs if idx in retains)

  new_vi.vns = copy(vi.vns[retains])
  new_vi.ranges = copy(vi.ranges[retains])
  new_vi.dists = copy(vi.dists[retains])
  new_vi.gids = copy(vi.gids[retains])
  new_vi.trans[end] = copy(vi.trans[end][retains])

  for range in vi.ranges[retains]
    for idx in range
      push!(new_vi.vals[end], vi.vals[end][idx])
    end
  end

  new_vi
end
```

I guess the reason why you chose to fill `vals` with `NaN`s is for performance purposes.

**Comment by emilemathieu** [comment]
@yebai don't hesitate if you have any question on that, things are bit subtle but this required for BNP models.

**Comment by yebai** [comment]
> @yebai don't hesitate if you have any question on that, things are bit subtle but this required for BNP models.


I'll post something soon.

**Comment by yebai** [comment]
I have reviewed all the relevant code, I think the best approach to solve these problems in one stroke is to remove `VarInfo.index` and index random variables through variable name (`VarName`) only. The reason that we kept `VarInfo.index` is mainly for sanity checks --  to ensure that particle copying/replaying is correctly implemented. However, this has become a burden since in order to support such sanity checks we have to implement many utility functions such as above proposed by Emile. 

The whole list of functions that depends on `VarInfo.index` is listed below. Most places except those in `trace.jl` can be simply removed. The functions including `forkc` and `forkr` requires some deeper work. 


 https://github.com/yebai/Turing.jl/blob/bb7ea9f8e2d2e4b11a13b4769235f21a10da4bb0/src/samplers/pgibbs.jl#L55

https://github.com/yebai/Turing.jl/blob/bb7ea9f8e2d2e4b11a13b4769235f21a10da4bb0/src/samplers/pgibbs.jl#L146

https://github.com/yebai/Turing.jl/blob/4ae4717348c63cdeaf23d0127effbbe765affd3c/src/samplers/pmmh.jl#L179

https://github.com/yebai/Turing.jl/blob/3f788de312222cfb03b7c5bdd91f734c27c6feff/src/samplers/smc.jl#L54

https://github.com/yebai/Turing.jl/blob/3f788de312222cfb03b7c5bdd91f734c27c6feff/src/samplers/support/hmc_core.jl#L5

https://github.com/yebai/Turing.jl/blob/3f788de312222cfb03b7c5bdd91f734c27c6feff/src/trace/trace.jl#L62

https://github.com/yebai/Turing.jl/blob/3f788de312222cfb03b7c5bdd91f734c27c6feff/src/trace/trace.jl#L84

https://github.com/yebai/Turing.jl/blob/3f788de312222cfb03b7c5bdd91f734c27c6feff/src/trace/trace.jl#L100

https://github.com/yebai/Turing.jl/blob/3f788de312222cfb03b7c5bdd91f734c27c6feff/src/trace/trace.jl#L108

**Comment by yebai** [comment]
@emilemathieu could you post a minimal example that can re-produce the issue you met? I tried to run the code you privide above with a SMC sampler, but without success.

**Comment by emilemathieu** [comment]
@yebai  I'll try to upload some reproducible bug, but the issue is with [that sort of models](https://github.com/yebai/Turing.jl/issues/367#issuecomment-342854179).

For instance let's focus on the [infinite mixture model](https://github.com/yebai/Turing.jl/blob/project-bnp/test/rpm.jl/imm.jl),  performing inference with a Gibbs sampler with an `CSMC` step targeting `p(z1,...,zn|rest)` (and `MH` for instance for J1,...,JK and x1,...,xK).
 * Random variables will be initialised in `Gibbs` and therefore sampled in a specific order, eg. `vi.vns=[...,z9,z10,J3,x3]` if z10 is a new cluster (`z10>max(z1,...,z9)`) and only 2 clusters existed before.
 * Then in the `CSMC` step, values in `vi.vals` will be set to `NaN` for the non-reference particles.
 * A particle could sample random variables in the order `...,z9,J3,x3,z10`.
 * Therefore at iteration 9 within `CSMC` for that particle (in `consume`), we have `vi.vals=[...,3,NaN,J3,x3]`.
 * Consequently during the resampling step, if this particle is forked, a `vi` object with `vi.vals=[...,3,NaN,J3,NaN]` will be created since `vi.index` = 9+3x2=15 (and `length(vi.vns)=16`).
 * Then at the last iteration (still within `CSMC`) for that forked particle, we might have `vi.vals=[...,3,2,J3,NaN]` or `vi.vals=[...,3,4,J3,NaN,J4,x4]`. So if `z10` is not 3, will have a missing value `x3`in that sample...

**Comment by emilemathieu** [comment]
@yebai when you say
> I think the best approach to solve these problems in one stroke is to remove VarInfo.index and index random variables through variable name (VarName) only

are you referring to the 2sd solution in https://github.com/yebai/Turing.jl/issues/367#issuecomment-343270076 ?

Otherwise have you looked at solution https://github.com/yebai/Turing.jl/issues/367#issuecomment-344032331 ? Could you explained why you chose to set values to `NaN` in `vi` ?

**Comment by yebai** [comment]
> Otherwise have you looked at solution #367 (comment) ? Could you explained why you chose to set values to NaN in vi ?

I think the original motivation is to use `NaN` as a marker for which entries are deleted. The use of `NaN` is motivated by computational performance, but perhaps we could change this to missing value type (e.g. use the [`Missings.jl`](https://github.com/JuliaData/Missings.jl) package) - like what I suggested in #386.

**Comment by yebai** [comment]
> are you referring to the 2sd solution in #367 (comment) ?

Not quite - I'm looking into a possible alternative solution without using `VarInfo.index`.

**Comment by xukai92** [comment]
@yebai After discussing with Emile, we agreed on use the 2nd proposal (i.e. introducing another filed to `VarInfo` called `produce` or `order` to record the order of variables (in this case `vi.index` can also be removed).

**Comment by emilemathieu** [comment]
I've pushed a PR with the solution implemented https://github.com/yebai/Turing.jl/pull/395

**Comment by emilemathieu** [comment]
PR https://github.com/yebai/Turing.jl/pull/395 merged.

**Comment by emilemathieu** [comment]
@yebai @xukai92 shouldn't we set `spl.info[:cache_updated] = CACHERESET` in `updategid!(vi, vn, spl)` ?

**Comment by emilemathieu** [comment]
I've also spotted another error which is setting `spl.info[:wum][:stds] = ones(length(vi[spl]))` at the beginning of `HMC`. If at some iteration `length(vi[spl])` changes (new variables) error will appear at `randn(length(getranges(vi, spl))) .* spl.info[:wum][:stds]` and `p_orig = p ./ spl.info[:wum][:stds]`.

We could either resize `spl.info[:wum][:stds]` at each iteration if needed, or avoid performing these operations for `HMC` since this if for `HMCDA` and `NUTS`.
