### ISSUE TITLE
[BNP] Q-class

### ISSUE THREAD

**Issue by emilemathieu** [TuringLang/Turing.jl#374]
Sample from Q-class: `rand` and `logpdf` for total mass and size biased sampling.

 - [x] Implement DP, PYP via stick breaking: [Here](https://github.com/yebai/Turing.jl/blob/project-bnp/src/samplers/support/rpm/pyp.jl)
  - [x] Q-class total mass: `rand(ExpTiltedSigma(sigma, tau))`: [Here](https://github.com/yebai/Turing.jl/blob/project-bnp/src/samplers/support/rpm/ngip.jl) 
  - [ ] Q-class total mass: `logpdf(ExpTiltedSigma(sigma, tau))`
  - [x] Q-class new weight with sigma=0.5: `rand` : [Here](https://github.com/yebai/Turing.jl/blob/project-bnp/src/samplers/support/rpm/ngip.jl) 
  - [ ] Q-class new weight with sigma=0.5: `logpdf`
  - [ ] Q-class new weight with sigma<0.5: `rand` and `logpdf`

Draft here https://github.com/yebai/Turing.jl/tree/project-bnp/src/samplers/support/rpm

**Comment by ae-foster** [comment]
For efficient sampling of exponentially tilted stable random variables, Devroye double rejection sampling sounds efficient: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.157.9416&rep=rep1&type=pdf (see page 21 for the actual algorithm)

**Comment by mlomeli1** [comment]
The current code is based on Hoffert (2011)
http://delivery.acm.org/10.1145/2050000/2043638/a3-hofert.pdf?ip=131.111.5.148&id=2043638&acc=ACTIVE%20SERVICE&key=BF07A2EE685417C5%2E6CDC43D2A5950A53%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=1005798912&CFTOKEN=54131981&__acm__=1510664595_6a074af8f4a60fe0f0f69844e6a1389b
He refers to Devroye (2009) and compares against it. If you would like to know when Devroye is more suitable, please read the paper.

**Comment by ae-foster** [comment]
Oh tx @mlomeli1 - I guess we're good to leave as is until we notice a bottleneck in the total mass sampler :)

**Comment by mlomeli1** [comment]
I just realised the link doesn't work. The paper is "Sampling Exponentially Tilted Stable Distributions" by Marius Hoffert. I think you have a good point but am just saying that you should have a look at that paper to know when the double rejection sampling of Devroye (2009) is better, i.e. there might be some tilting parameters for which it performs better. If that is the case, then it might be worth to implement it as well and then depending on the range of the tilting parameter choose either Hoffert (2011) or Devroye (2009) so we have a more robust implementation.

**Comment by ae-foster** [comment]
Huh the link worked for me. Yeah they have a criterion for choosing between the methods. I wouldn't invest time in it though, unless we see that a lot of time is spent on total mass sampling

**Comment by emilemathieu** [comment]
So would you know how to compute `logpdf(ExpTiltedSigma(sigma, tau))` (at least for `sigma=0.5`) and the `logpdf` of `p(Vj | V_1, ..., V_{j-1}, T)`  for the NGGP (at least for the NIGP) ?

**Comment by mlomeli1** [comment]
Have a look at the first Equation in page 51 of my thesis. This expression is the conditional distribution of k size-biased weights, the corresponding partition given the total mass. If we multiply it by the total mass's prior which is proportional to h(t)*f(t), then we get the joint of interest.  We also need to plug in the Levy density of the 0.5-Stable and h(t) is the exponentially tilt function for NIG so it has an analytic expression.

**Comment by emilemathieu** [comment]
I agree, but the way to compute such a joint in a PPL is to replay the model and when a sample/assume statement is encountered, the (log)pdf - associated with that distribution and the saved in memory value - is computed and increments the joint. For Pitman-Yor `p(Vj | V_1, ..., V_{j-1}, T)` is `pdf(Beta(1 - alpha, theta + j * alpha), Vj)`. For NIGP we have
```
Distributions.rand(d::V_SBS_NIGP) = begin
  X = sqrt(rand(Gamma(3/4, 1)))
  Y = sqrt(rand(InverseGamma(1/4, 1/(64 * d.T_surplus^2))))
  X / (X + Y)
end
```
Do we already know how to compute its pdf ? It might not be that hard to derive analytically for this NIGP case.

Otherwise for the total mass, I agree that the tilting density `h(t)`  can easily be computed, but what about `f(t)` ? I thought that it was intractable for sigma stable processes.

**Comment by mlomeli1** [comment]
yes, Equation in page 51  is the log-joint pdf, by plugging in the Levy density of the sigma-Stable and replacing the h(t) of NGG, etc. I agree, the sigma stable density f(t) is intractable for sigma !=0.5. We could use the integral representation given by Zolotarev and have a MonteCarlo estimate of it:
V. M. Zolotarev, One-Dimensional Stable Distributions, American Mathematical Society, Providence, R.I., 1986. 
Alternatively, we can have a look at Matlab's implementation to see how they implement the sigma-Stable density?

**Comment by mlomeli1** [comment]
I remember using this one in matlab: http://math.bu.edu/people/mveillet/html/alphastablepub.html
We could just translate it to Julia and use it @emilemathieu

**Comment by mlomeli1** [comment]
I've added the Matlab toolbox in the dropbox @emilemathieu .

**Comment by emilemathieu** [comment]
Good idea for the sigma-Stable density !
Otherwise do you have an idea for the density of `p(Vj | V_1, ..., V_{j-1}, T)` ?

**Comment by mlomeli1** [comment]
I'll write down the expression and send it to you shortly.

**Comment by mlomeli1** [comment]
The expression is given in the generative process of page 31, first unnumbered Equation, of my thesis after plugging in the sigma-Stable Lévy measure and the exponentially tilted sigma stable density. Note that 
p(Vj | V_1, ..., V_{j-1}, T)=p(Vj |T-V_1, ...-V_{j-1}) because it satisfies a Markov property. I have written down the Equation for the sigma-Stable exponentially tilted case here(with 4 weights):

(sig/SpecialFunctions.digamma.(1-sig))*(v_5^(-sig)/(t-v_1-v2-v3-v_4))*h(t-v_1-v2-v3-v_4-v_5)*f_sigma(t-v_1-v2-v3-v_4-v_5)/h(t-v_1-v2-v3-v_4)*f_sigma(t-v_1-v2-v3-v_4)

I've sent you a  handwritten note with the general case.

**Comment by mlomeli1** [comment]
Hi all, I was wondering if the Q-class method already accepts different prior distributions for the exponentially tilted parameter, @emilemathieu ? For example, tau~f_Gamma(1,k) or tau = delta_{tau=fixed_value}. Also, what about the case where sigma ≠ 0.5. I have some code in Julia for this case,for both sampling the new size biased weight and for the conditional distribution. I can contribute with it and we can test it. I need some guidance about how to do this, @yebai, could we meet this week?

**Comment by emilemathieu** [comment]
Hi @mlomeli1, I ported your [*exptiltedsigma* code](https://github.com/yebai/Turing.jl/blob/project-bnp/src/samplers/support/rpm/exptiltedsigma.jl) but didn't implement the generic Q-class. You can find the [`PYP`](https://github.com/yebai/Turing.jl/blob/project-bnp/src/samplers/support/rpm/pyp.jl) and the [`NIGP`](https://github.com/yebai/Turing.jl/blob/project-bnp/src/samplers/support/rpm/nigp.jl). You can indeed implement the case `sigma ≠ 0.5` in the existing file [`NGGP`](https://github.com/yebai/Turing.jl/blob/project-bnp/src/samplers/support/rpm/nggp.jl).

**Comment by mlomeli1** [comment]
Great, thanks @emilemathieu ! I'll have a go at it and report back.
