### ISSUE TITLE
[Gibbs] Increase performance when subsamplers have several iterations

### ISSUE THREAD

**Issue by emilemathieu** [TuringLang/Turing.jl#378]
When a sampler is used within `Gibbs` such as `MH` or `HMC`, there is an overhead at each iteration when this subsampler's `step` method is called. For instance in `HMC` there is
```julia
if spl.alg.gid == 0
    link!(vi, spl)
    runmodel(model, vi, spl)
end
...
if spl.alg.gid != 0 invlink!(vi, spl); cleandual!(vi) end
```

These blocks could be refactored in `prepare` and `unprepare` functions which would then be called before and after this subsampled is called in `Gibbs`:
```julia
prepare(vi, local_spl)
for _ = 1:local_spl.alg.n_iters
...
end
unprepare(vi, local_spl)
```

@xukai92 do you know whether this is a big overhead ?

**Comment by xukai92** [comment]
Good idea! I think we do need to do something to avoid the transformation if it is not necessary, and your proposal makes sense.

This is actually a known overhead to Hong and I. The main reason we had such bit of codes is because HMC do inference in the **transformed space** but particle based algorithms do inference in the **original space**. Also, particle based algorithms don't require gradient information.

One thing I would like to discuss morel is that your proposal means that we will need to write `prepare` and `unprepare` specifically for each sampler in Gibbs, which was I was trying to avoid by putting those codes inside step. 

Maybe an alternative way to solve this is to allow `step` to take the number of steps as an argument, and do the loop inside step. Then the Gibbs code will be more elegant.

**Comment by emilemathieu** [comment]
I like your solution @xukai92 ! Something like
```julia
step(model::Function, spl::Sampler, vi::VarInfo, nb_steps::Int=1) = begin
# link!, runmodel, etc
# do step

  if nb_steps > 1
    step(model, spl, vi, nb_steps-1)
  else
    # unlink!, runmodel, etc
    vi
  end
end
```

**Comment by emilemathieu** [comment]
Or maybe it'd be cleaner something like

```julia
steps(model::Function, spl::Sampler, vi::VarInfo, nb_steps::Int=1) = begin
  vi = prepare(model::Function, spl::Sampler, vi::VarInfo)

  while nb_steps >= 1
    vi = step(model, spl, vi)
    nb_steps -= 1
  end

  vi = unprepare(model::Function, spl::Sampler, vi::VarInfo)

  vi
end
```

with `steps` being a method for all samplers, and each sampler having a `prepare`, `unprepare` and `step` specific method. These specific methods could also be used for refactoring in `sample` methods.

What do you think @xukai92 @yebai ?

**Comment by xukai92** [comment]
I like this design! It makes sense to have `prepare()` and `unprepare()` interface as well.

Actually with the design, we may not need `unprepare()` any more? As we can also make sure vi is prepared by `prepare()`. This may reduce some unnecessary transformations.

**Comment by xukai92** [comment]
Of course in this case we also need have a `prepare()` before outputting into `Chain`...

**Comment by emilemathieu** [comment]
@xukai92 One issue with this is when `thin=false`, since now we only get one sample per sub_sampler per iteration (`sample_n = n * (alg.thin ? 1 : length(spl.info[:samplers]))`) whereas before we could have n_iters samples per sub_sampler per iteration (`sample_n = n * (alg.thin ? 1 : sum(sub_sample_n))`).

**Comment by emilemathieu** [comment]
I've pushed a PR https://github.com/yebai/Turing.jl/pull/404

**Comment by xukai92** [comment]
I see. Yes this is an issue. I think a common approach to fix this is change the signature of function like this:

```julia
y = f(x)
output_container[i] = y
```

to

```julia
f!(x, output_container, i)
```

Also in this case `f()` can just use `f!()` as `f(x) = (output_container=Vector(1);f!(x, output_container, 1); output_container);` or something similar.

**Comment by xukai92** [comment]
And this may also reduce some memory allocation overhead?

**Comment by emilemathieu** [comment]
I'm not sure to follow :/ what's `f` ? Is it `steps` and is `output_container` the `samples` ?

**Comment by xukai92** [comment]
Yes. It's a general design pattern which pass a pre-allocated container to the function and store the results in that container.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/AbstractPPL.jl/pull/44
