### ISSUE TITLE
Debugging tools

### ISSUE THREAD

**Issue by emilemathieu** [TuringLang/Turing.jl#379]
Fo this package to be easy to extend and enhance, it needs more **debugging tools**, **along with a detailed wiki** (which is currently lacking).  The `setverbosity` command is awesome for instance. Here are some more ideas, please contribute so that we pick and implement the best.

* `time_elapsed = @elapsed vi = step(model, spl, vi, i == 1)` prevent from debug inside `step` which means that each time someone want to debug that, he needs to remove the part before `vi`.

* In `SMC` and `CSMC`, be able to only print things for a specific particle and/or consume index.

* Can we set a breakpoint in Juno ??

**Comment by xukai92** [comment]
> `time_elapsed = @elapsed vi = step(model, spl, vi, i == 1)` prevent from debug inside step which means that each time someone want to debug that, he needs to remove the part before vi

Maybe we could `tic()` and `toc()` instead.

> In SMC and CSMC, be able to only print things for a specific particle and/or consume index.

Sounds like a good idea. How do you plan to do that?

> Can we set a breakpoint in Juno ??

Juno does support basic debugging tools like setting breakpoints, step in/out/over, etc. But I experienced some difficulty using it long time ago due to the fact that our model is wrapped by a `@model` macro. I switched to VSCode for a while so please let me know if it is working in Juno now or not.

**Comment by emilemathieu** [comment]
> Sounds like a good idea. How do you plan to do that?
I'm not sure; could we have in `current_trace()` the current particle's index ?

I believe that we can have the consume index with `current_trace().vi.num_produce`.

> Juno does support basic debugging tools like setting breakpoints, step in/out/over, etc. But I experienced some difficulty using it long time ago due to the fact that our model is wrapped by a @model macro. I switched to VSCode for a while so please let me know if it is working in Juno now or not.

Indeed with Juno we can't get in the models' execution... Maybe by calling `model=model_name(args)` before. How can we set breakpoint ? I only use `@step function_name(args)` currently :/

**Comment by emilemathieu** [comment]
Is Gallium not available for Julia 0.6 ?

**Comment by xukai92** [comment]
Their GitHub pages says

> ... Please note that the 0.6 version of this package currently does not support breakpointing, C/C++ debugging or native code inspection.

:(

**Comment by yebai** [comment]
Closed because it is better to fix this issue at a language level (i.e. Julia). See https://julialang.org/blog/2019/03/debuggers
