### ISSUE TITLE
[Gibbs] Load conditioned random variables

### ISSUE THREAD

**Issue by emilemathieu** [TuringLang/Turing.jl#385]
Within a Gibbs sampler, is there a way to load random variables that are not updated by the current sampler (i.e. are conditioned) at the beginning of calling `model(vi=vi, sampler=spl)` ?

For instance in this [infinite mixture model](https://github.com/yebai/Turing.jl/blob/project-bnp/test/rpm.jl/imm_hmc_sticks.jl#L16), if `:x,:V` are updated with `HMC` then in some `CSMC` step updating `:z` I'd like to have some Vs and xs loaded at the beginning of the model.

An hacky way would be to add at the begging of the model:
```julia
if sampler != nothing && typeof(sampler.alg) == Turing.PG
  max_index = maximum([vn.indexing for vn vi.vns if vn.sym == :V])
  for l in 1:max_index
    V[k] ~ V_SBS_DP(10)
    x[k] ~ H
  end
end
```

How could that be done in a clean way in Turing @yebai ?
Is that something that PPSs usually allow @twgr ?

**Comment by twgr** [comment]
Sorry what to mean by load - just have them in scope?  All assume and observe statements are exchangeable up to having everything defined so if you have everything already its fine from a statistical perspective if you careful to evaluate all the same assume and observes for a trace.  If variables get renamed at some point though there could be some semantical complications.  It seems like the problem here is more that you might what to explicitly encode the model through two gibbs updates rather than one model?  I don't understand though why you would need them in scope unless you actually have different programs for each update.

**Comment by emilemathieu** [comment]
@twgr yes having loaded in the scope. In the IMM example i'd like to have the existing `V`s and `x`s so that `z`s in `CSMC` can be assigned to any existing clusters (https://github.com/yebai/Turing.jl/blob/project-bnp/test/rpm.jl/imm_hmc_sticks.jl#L24). And then create new clusters (V[k+1] and x[k+1]) if `z[i]` is bigger than the number of existing clusters.
Otherwise that means that `z[1]` will always be assign to cluster 1, `z[2]` to 1 or 2, etc

What do you mean by exchangeable ?

**Comment by twgr** [comment]
In the statistical sense - the model is unchanged by the order the probabilistic statements are made provided variables are not overwritten.  What your proposing worries me a little and I don't think it is necessary so we should probably chat in person at some point.  I think the problem you are trying to overcome is actually not there though (at least asymptotically) as even though z[1] is always cluster 1, the interpretation of what cluster 1 is will be completely independent if an entirely new retained particle is generated.  If you're not generating entirely new retained particles then pgibbs won't really be working anyway

**Comment by yebai** [comment]
There is currently no such a mechanism in Turing except rewriting the program such that these variables are defined at the beginning of a program- we chose to follow the standard Julia syntax for Turing programs, which means Julia's scoping rules also apply to Turing programs.

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/DynamicPPL.jl/pull/337
