### ISSUE TITLE
[TESTS] Use `@test` instead of `check_numerical`

### ISSUE THREAD

**Issue by emilemathieu** [TuringLang/Turing.jl#399]
For robustness when merging new features, I believe that we should use `@test` instead of `check_numerical` in `test/...` and include these tests in `test/runtests.jl`.
Because of stochasticity, so as to avoid randomly failing tests, we could use `srand` to set randomness.

**Comment by xukai92** [comment]
Yes it makes sense. The reason of having `check_numerical` was to avoid rare broken of test because of randomness. If we use `srand` it seems unnecessary then.
