### ISSUE TITLE
help with model

### ISSUE THREAD

**Issue by drbenvincent** [TuringLang/Turing.jl#412]
Hi, I've managed to get some models working with Turing, but I'm having trouble with one and hoped someone could point out where I'm going wrong with this model. The model runs (doesn't error), but still not sure if the issue is the model spec or inference

```julia
@model model2infer(Δμ,T,L,R) = begin
    σ² ~ Uniform(0,10)
    λ ~ Beta(1,1)
    b ~ Normal(0,10)
    x = zeros(T, length(Δμ), 2)
    for c ∈ 1:length(Δμ)
        for t ∈ 1:T
            # true location, L
            L[t,c] ~ Categorical([0.5, 0.5])
            
            # observer's observations, x
            for n ∈ 1:2
                if L[t,c] == n
                    x[t,c,n] = rand(Normal(Δμ[c], √σ²))
                else
                    x[t,c,n] = rand(Normal(0, √σ²))
                end
            end
            
            # observer response R given x, b, λ
            if (x[t,c,1]-x[t,c,2]) > b
                R[t,c] ~ Categorical([1-(λ/2), λ/2])
            else
                R[t,c] ~ Categorical([λ/2, 1-(λ/2)])
            end

        end
    end
    return σ², λ, b
end
```

which is supposed to implement this (right)
![](https://raw.githubusercontent.com/drbenvincent/bayesian2afc-julia/566e97a8f3aa4e7ff4efd4554060542ca2af90db/img/model2.png)

I'm doing some parameter recovery and the inference is just giving identical values for all chain values.

Full (short) Jupyter notebook here [https://github.com/drbenvincent/bayesian2afc-julia/blob/master/model2.ipynb](https://github.com/drbenvincent/bayesian2afc-julia/blob/master/model2.ipynb) which shows the data + result of inference.

**Comment by xukai92** [comment]
From the plate diagram and your comments I can see `x` is an observation - I guess in the simulation you should save `x` and provide it as data during inference time.
