### ISSUE TITLE
Abandoning "Mamba.Chain"

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#413]
Current use of "Mamba.Chain"leads to problem like #390 and #406. Some of them is very hard to resolve (e.g. #390) within "Mamba.Chain"

For this reason, @yebai and I decided to build our own `Chain` type now. (FYI the main reason we used `Mamba.Chain` was to re-use all the diagnosing function written in `Mamba`). This would requires use to generally build these functions (like ESS) for our own chain type (or somehow reuse them in a way which allow missing values).

For `describe` function is self, the most important two to implement are

- [ ] ESS
- [ ] MCSE

And for `plot`, we may use `Plot.jl` to plot trace and density (in stead of Gadfly.jl).

And don't remember these functions to diagnose convergence in `Mamba.jl` which are also sort of wanted.

Discussion are encouraged on this!

**Comment by keorn** [comment]
Sounds like a good change, it could enable the support of arbitrary sample types too.

**Comment by xukai92** [comment]
Note: fetch matrix indexing (i.e. `v[:,i]`) from `Mamba.Chain` is broken now. Need to make sure new solution support it.

**Comment by yebai** [comment]
I just noticed that there is already a GSoC project working on the varying dimension constraint of `Mamba`. According to a [blog](https://julialang.org/blog/2017/09/GSOC-MCMC-with-flexible-numbers-of-parameters) from the main developer, the refactored `Chain` (see [here](https://github.com/jamesonquinn/Mamba.jl/tree/gsocMNVP)) can already store samples with varying sizes. Perhaps we can adapt his code for our purpose?

**Comment by xukai92** [comment]
Another choice: https://github.com/arviz-devs/arviz/issues/97#issuecomment-391452259

**Comment by yebai** [comment]
Closed by new `MCMCChain` package.
