### ISSUE TITLE
Bug of using SGLD and SGHMC with chunk-wise AD

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#415]
For the same subset AD model may be evaluated for multiple times with different indices

**Comment by emilemathieu** [comment]
Hi Kai! Could you give more details about the bug ?

**Comment by xukai92** [comment]
This is related to the chunk-wise forward-mode AD we used before:

- Say we use a chunk-size of 50 and the input vector is of size 100
- What we do to get the gradient is by run the model twice to get the gradient of the first and second 50 dimension
- Different runs of the program is on different sub-set so they are non-consistent

As you know in PR https://github.com/yebai/Turing.jl/pull/428, Turing.jl is working with ReverseDiff.jl now. So this might not be a problem if we decide to remove the support of ForwardDiff.jl.

BTW in the PR I haven't integrated the new gradient function with SGLD and SGHMC yet.

**Comment by yebai** [comment]
This should be fixed now #515
