### ISSUE TITLE
Add L-BFGS to Turing

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#421]
The [`Optim.jl`](https://github.com/JuliaNLSolvers/Optim.jl) package provides an implementation of BFGS, perhaps we can integrate it with Turing?

**Comment by xukai92** [comment]
Note: link for LBFGS in Optim.jl - http://julianlsolvers.github.io/Optim.jl/stable/algo/lbfgs/

**Comment by emilemathieu** [comment]
In what context shall L-BFGS (a memory efficient quasi-Newton method) be added to Turing ? Is Turing now supporting some sort of optimisation paradigm ?

**Comment by yebai** [comment]
The [Flux.jl ](https://github.com/FluxML/Flux.jl) package has implementations for several popular optimisation algorithms in ML. Perhaps we can consider to re-use them in Turing:

http://fluxml.ai/Flux.jl/stable/training/optimisers.html

@xukai92 @ChrisRackauckas

**Comment by willtebbutt** [comment]
I completely agree with @yebai that we should try to make use of Flux's optimisers. This is perhaps a useful conversation to have at JuliaCon. It's not clear to me whether making this work would simply be a case of using a Turing.jl `VarInfo` to construct a Flux.jl `param`, and then adding a couple of methods to make stuff work with [the new optimiser interface](https://github.com/FluxML/Flux.jl/pull/283), or whether it will be a bit trickier for some reason.

**Comment by xukai92** [comment]
The new interface seems to be compatible with what Turing.jl's internals can provide. Though until they adapt a generic AD I would assume their `grad` may have problem with `Distributions`?

**Comment by MikeInnes** [comment]
We don't currently have any gradient definitions for Distributions, but they are easy to add and we'd be very happy to have them in Flux. Let me know if you have any trouble getting that set up; I'll also be around at JuliaCon and would be happy to meet up over this stuff.

**Comment by willtebbutt** [comment]
> I'll also be around at JuliaCon and would be happy to meet up over this stuff.

This would be very helpful.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/605
