### ISSUE TITLE
SMC arguments

### ISSUE THREAD

**Issue by awellis** [TuringLang/Turing.jl#426]
Sorry if the answer to this question is obvious, but can the SMC function take other arguments than the number of particles, e.g. resampling threshold/method? Also, is it possible to retrieve the weights from the SMC sampler, along with the samples?

**Comment by emilemathieu** [comment]
Hi !
It's indeed not clearly documented but the objected returned when calling `sample()` on a `model` is a [`Chain`](https://github.com/yebai/Turing.jl/blob/master/src/core/io.jl#L87). It has a `value2` attribute being an array of all samples, each [`Sample`](https://github.com/yebai/Turing.jl/blob/master/src/core/io.jl#L9) having a `weight` attribute.

Best,
regards

**Comment by awellis** [comment]
Hi, 
I've been trying out Turing again, and as I'm  quite new to Julia, how to extract samples and weights isn't obvious to me.

As far as I can, I can obtain a matrix containing all particles from the `value` attribute of a `Chain` and in the `value2` attribute, I get a `Sample` object, which contains a `weight` and a dictionary of samples for each iteration.

It seems that the `weight` represents the log evidence at each iteration, but is it possible to access the weight of each particle at each iteration? This would be useful, e.g. for plotting a weighted mean of the state variables, if resampling is not performed at each time step, and the weights are not uniform. 

Is this currently possible? (Sorry if the answer is obvious)

My other question referred to the resampling method and resampling threshold: is it possible to use any resampling method other than the default (resampleSystematic), and to change the threshold used for resampling?

cheers,
Andrew

**Comment by emilemathieu** [comment]
Hi Andrew !

Indeed [`Chain.value2`](https://github.com/TuringLang/Turing.jl/blob/master/src/core/io.jl#L89) is a list of `Sample` with the `weight` being the log evidence at each iteration. You are right, it would be better to have each particle weight at each iterations, you could modify the [`SMC` code](https://github.com/TuringLang/Turing.jl/blob/master/src/samplers/smc.jl#L64) to save all particles weights.

Concerning your 2nd question, there is a [`resampler` argument in `SMC`](https://github.com/TuringLang/Turing.jl/blob/master/src/samplers/smc.jl#L30), for which you can use one of the [implemented resampling schemes](https://github.com/TuringLang/Turing.jl/blob/master/src/samplers/support/resample.jl).

Cheers,
Emile

PS: This should change in the future to be easier to use cf https://github.com/TuringLang/Turing.jl/issues/413.

**Comment by awellis** [comment]
Hi Emile,

thanks for your reply. I will try to modify the `SMC` code to save the particle weights at each iteration, and I've figured out how to use the `resampler` argument, thanks.

I'm wondering if there might be a problem with resampling. I've been playing around with a state space model (using SMC), and it seems that no matter how low I set the resampling threshold, the particles are resampled at the first iteration, which results in all particles having the same value [example](https://nbviewer.jupyter.org/gist/awellis/63bbe67a87015068cd4dcd88e9ef2925).

Is this intended behaviour?

cheers,
Andrew

**Comment by emilemathieu** [comment]
Hi Andrew,

In `SMC`, the `resampler_threshold ` is used here: https://github.com/TuringLang/Turing.jl/blob/master/src/samplers/smc.jl#L59.

I'm not sure why that's happening. You should try to print `ess` and `spl.alg.resampler_threshold * length(particles)` to understand why the condition `ess <= spl.alg.resampler_threshold * length(particles)` is always true.

May be related to the fact that the [particles' weights are all initialised to 0](https://github.com/TuringLang/Turing.jl/blob/master/src/core/container.jl#L45).

Cheers,
Emile

**Comment by awellis** [comment]
ok, thanks. 

It'll take me a while to figure out how to do that, I'm pretty new to Julia. Any hints on how to print `ess`?

But even if resampling is performed, this shouldn't result in the particles all being descended from one ancestor, should it?

**Comment by emilemathieu** [comment]
Not necessarily indeed, but it could if you have to few particles and one of them therefore dominates the others (in terms of associated weights).

You can use `println("ess: $(ess)")`.

**Comment by awellis** [comment]
`println("ess: $(ess)")`: that is clear, but how do I get the `ess` value during execution of the model?

**Comment by emilemathieu** [comment]
If you add `println("ess: $(ess)")` in the [`SMC` file after computing the `ess`](https://github.com/TuringLang/Turing.jl/blob/master/src/samplers/smc.jl#L80).
This file can be found in `~/.julia/v0.6/Turing/src/samplers/smc.jl` in macOS.

**Comment by awellis** [comment]
ok, thanks, that worked ok. I'll spend some time looking at this.

**Comment by emilemathieu** [comment]
The `step` method is called when `SMC` is used within a `Gibbs` sampler (i.e. `CSMC`).

This seems weird indeed, i’ll Look into it

Cheers,
Emile

**Comment by awellis** [comment]
hi Emile, 

I still think it looks like something is going wrong at the first iteration. Changing the initialisation of the weights doesn't seem to have any effect.

cheers,
Andrew

**Comment by awellis** [comment]
Hi Emile, 

sorry to keep bothering you about this, but I'm having problems with modifying the SMC code so that the weights of all particles are returned for each iteration. Currently, the `value2` attribute returned after sampling has a weight for each trajectory, i.e. the log evidence for each particle summed over all iterations. Is that correct? I need at least the sum of the log weights for each iteration, or just the weights.

The reason for doing this is that I want to do a model comparison at each iteration during a run of a particle filter. I realise that this may not really be the intended usage of the SMC algorithm, but are there any guidelines on how to proceed?

best wishes, 
Andrew

**Comment by emilemathieu** [comment]
Hi Andrew,

Something seems weird indeed.

In `SMC` things are happening at [`consume(particles)`](https://github.com/TuringLang/Turing.jl/blob/master/src/samplers/smc.jl#L79). 

Then at each iterations the weights are computed by [`_, z2      = weights(pc)`](https://github.com/TuringLang/Turing.jl/blob/master/src/core/container.jl#L106). So you want to replace that line by `Ws, z2      = weights(pc)` and then save these weights `Ws` in `pc` (as a matrix or as you'd like).

Please tell me if that does not help enough.

Cheers,
Emile

**Comment by awellis** [comment]
ok, thanks, I'll try it tonight and let you know.

**Comment by awellis** [comment]
ok, so far, adding `Ws, z2 = weights(pc)` works, and I can print the vector of weights to the console at each iteration, but saving the weights in the ParticleContainer is beyond me at the moments. I'd really appreciate any help.

**Comment by emilemathieu** [comment]
You could update [ParticleContainer](https://github.com/TuringLang/Turing.jl/blob/master/src/core/container.jl#L10), [Consume](https://github.com/TuringLang/Turing.jl/blob/master/src/core/container.jl#L77) and [sample](https://github.com/TuringLang/Turing.jl/blob/master/src/samplers/smc.jl#L73)  with the code below.

In _**src/core/container.jl**_
```julia
type ParticleContainer{T<:Particle}
  model :: Function
  num_particles :: Int
  vals  :: Array{T,1}
  logWs :: Array{Float64,1}  # Log weights (Trace) or incremental likelihoods (ParticleContainer)
  logWst :: Array{Array{Float64,1},1}  # Log weights saved BOTH in time and particle index
  logE  :: Float64           # Log model evidence
  # conditional :: Union{Void,Conditional} # storing parameters, helpful for implementing rejuvenation steps
  conditional :: Void # storing parameters, helpful for implementing rejuvenation steps
  n_consume :: Int # helpful for rejuvenation steps, e.g. in SMC2
  ParticleContainer{T}(m::Function,n::Int) where {T} = new(m,n,Array{Particle,1}(),Array{Float64,1}(),Array{Float64,1}(),0.0,nothing,0)
end

function Base.consume(pc :: ParticleContainer)
  @assert pc.num_particles == length(pc)
  # normalisation factor: 1/N
  _, z1      = weights(pc)
  n = length(pc.vals)

  particles = collect(pc)
  num_done = 0
  logWst = zeros(Float64, n)
  for i=1:n
    p = pc.vals[i]
    score = consume(p)
    score = isa(score, ForwardDiff.Dual) ? realpart(score) : score
    if isa(score, Real)
      score += isa(getlogp(p.vi), ForwardDiff.Dual) ? realpart(getlogp(p.vi)) : getlogp(p.vi)
      resetlogp!(p.vi)
      increase_logweight(pc, i, Float64(score))
      logWst[i] = Float64(score)
    elseif score == Val{:done}
      num_done += 1
    else
      error("[consume]: error in running particle filter.")
    end
  end
  push!(pc.logWst, logWst)
  if num_done == length(pc)
    res = Val{:done}
  elseif num_done != 0
    error("[consume]: mis-aligned execution traces, num_particles= $(n), num_done=$(num_done).")
  else
    # update incremental likelihoods
    _, z2      = weights(pc)
    res = increase_logevidence(pc, z2 - z1)
    pc.n_consume += 1
    # res = increase_loglikelihood(pc, z2 - z1)
  end

  res
end
```

In _**src/samplers/smc.j**_
```julia
function sample(model::Function, alg::SMC)
  spl = Sampler(alg);

  particles = ParticleContainer{Trace}(model)
  push!(particles, spl.alg.n_particles, spl, VarInfo())

  while consume(particles) != Val{:done}
    ess = effectiveSampleSize(particles)
    if ess <= spl.alg.resampler_threshold * length(particles)
      resample!(particles,spl.alg.resampler)
    end
  end
  w, samples = getsample(particles)
  res = Chain(w, samples)
  return res, particles.logWst
end
```

Then run the sampler and get the results
```julia
chain, logWst = sample(StateSpaceModel_1(y, true), SMC(100))
```

Hope that this helps you !
Cheers

**Comment by awellis** [comment]
Thank you! I guess these are the unnormalised weights, right? The output (logWst) is a vector of vectors, but the length is equal to n_iterations + 1, with the final weights vector consisting of zeros.

**Comment by emilemathieu** [comment]
They are unnormalised indeed.
Update `consume` with the version below, you shouldn't have the extra vector or zeros.

```julia
function Base.consume(pc :: ParticleContainer)
  @assert pc.num_particles == length(pc)
  # normalisation factor: 1/N
  _, z1      = weights(pc)
  n = length(pc.vals)

  particles = collect(pc)
  num_done = 0
  logWst = zeros(Float64, n)
  for i=1:n
    p = pc.vals[i]
    score = consume(p)
    score = isa(score, ForwardDiff.Dual) ? realpart(score) : score
    if isa(score, Real)
      score += isa(getlogp(p.vi), ForwardDiff.Dual) ? realpart(getlogp(p.vi)) : getlogp(p.vi)
      resetlogp!(p.vi)
      increase_logweight(pc, i, Float64(score))
      logWst[i] = Float64(score)
    elseif score == Val{:done}
      num_done += 1
    else
      error("[consume]: error in running particle filter.")
    end
  end
  
  if num_done == length(pc)
    res = Val{:done}
  elseif num_done != 0
    error("[consume]: mis-aligned execution traces, num_particles= $(n), num_done=$(num_done).")
  else
    # update incremental likelihoods
    push!(pc.logWst, logWst)
    _, z2      = weights(pc)
    res = increase_logevidence(pc, z2 - z1)
    pc.n_consume += 1
    # res = increase_loglikelihood(pc, z2 - z1)
  end

  res
end
```

**Comment by awellis** [comment]
Thank you very much!

**Comment by emilemathieu** [comment]
Hey ! Did you eventually succeeded @awellis ?

**Comment by awellis** [comment]
@emilemathieu 
Hi, I did get it to work, thanks. I am currently trying to get it work in Julia 1.0

**Comment by awellis** [comment]
@emilemathieu got it working in Julia 1.0 as well. I [forked](https://github.com/awellis/Turing.jl) the Turing.jl repository.

I guess there must be a more elegant way of saving the weights, though, without hacking the `sample` method.

**Comment by trappmartin** [comment]
@awellis would it be sufficient to store statistics on the weights? 

We could try to provide these in the resulting Chain object for particle-based methods by default. Storing all particle weights for each iteration, however, sounds rather costly.

**Comment by emilemathieu** [comment]
@trappmartin could be optional and set to False by default ?

**Comment by trappmartin** [comment]
If it's not necessary, I would prefer to only store statistics on the particle weights. Are there cases, apart from debugging, where it would be necessary to return the particles and their weights for each iteration?

**Comment by awellis** [comment]
@trappmartin @emilemathieu I think the history of the log evidence ( i.e. the sum of the log weights for each iteration) would actually be sufficient.

**Comment by emilemathieu** [comment]
@awellis's case ?
it would be a huge tool for debugging indeed !

**Comment by awellis** [comment]
I am using the weights so that I can visualize the SMC performance

**Comment by trappmartin** [comment]
I can see the benefit but I'm still not convinced as storing weights for a few thousand particles over a reasonable number of iterations would easily generate a large memory overhead. Even with 16bit precision. And if I understand it right, visualizing statistics on the weights would actually be already quite informative. @awellis is this correct?

I'll make a new issue for this as it seems to be a feature many people could be interested in.

**Comment by awellis** [comment]
@emilemathieu @trappmartin  visualizing statistics on the weights would be fine for me.
