### ISSUE TITLE
vi.vals or vi.rvs? design of internal variable type

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#433]
During my work on PR #428, I tend to feel that it makes sense to store variables internally without vectorization. I created this issue to discussion the pros and cons of doing so. In my opinion, the benefits are

- reduction in memory re-allocation: basically the same variable sampled in `@model` is just the one we stored;
- improvement in Turing.jl's internal typing: it is known that better typing can improve code efficiency in Julia (see discussions in https://github.com/yebai/Turing.jl/issues/400);
- Simplification in Turing.jl's internal APIs: basically we no more needs `vectorize` and `reconstruct`; because of this, Turing.jl will also be faster.

The disadvantage would be

- a major refactoring: I attempted to do that in #428 but didn't managed; basically this change in `VarInfo`  affects almost everywhere in Turing.jl; this actually indicates we need to refactor `VarInfo` for better decomposition of modules;
- samplers' APIs may become complex than before: one of the original motivation of doing the vectorizaiton is to run HMC easily; vectorizaiton basically provides the internal sampling space as a vector; this may also be solved if we done #431 correctly.

**Comment by yebai** [comment]
We have a lot of discussions early days regarding this issue. One additional problem that's not mentioned here is that we still need to `deepcopy` variables, since e.g.

```julia
x ~ Normal([0,0], eyes(2))
x[1] = 5 # This would change value stored in VarInfo, so we need a deepcopy
```

I lean towards using a flat vector for internal storage of parameters, cause it substantially simplifies the design of future new inference algorithms (e.g. variational inference, and new sampling algorithms).

cc'ing @willtebbutt

**Comment by willtebbutt** [comment]
I basically agree with @yebai on this issue. I'm not overly familiar with the gritty details of `vectorize` and `reconstruct`, but I agree with @xukai92 that it's a thorny issue trying to ensure type stability when it's possible that we will need to have various different types stored behind the scenes. Here's how I see things:
- If a programme comprises entirely `Float64`-valued random variables (and arrays, tuples etc thereof) whose dimensionality fixed (i.e. we know whether it's a `Vector{Float64}` or a `Matrix{Float64}` at compile-time), then it's not a problem. You can just store a flattened vector of `Float64`s in `VarInfo` and pull out the appropriate data structure using a `view` with the corresponding size information, and everything should be type-stable.
- If a programme comprises a mixture of data types, let's say `Float64` and `Int` for concreteness, and for each RV we know their types, then we either need to sacrifice type-stability to be able to store everything in a single flattened (i.e. `Vector{Union{Int, Float64}}`) or do something slightly more sophisticated, such as having two vectors, one containing `Float64`s and one `Int`s, and pull values out of the appropriate vector -- which vector to pull values out of would also need to be deduced statically to ensure type stability.
- Conversely, if the type of the samples of a particular RV can change dynamically between `Float64` and `Int`, then clearly we cannot possibly produce type stable code. One way to handle this would simply be to introduce another vector whose type is `Vector{Union{Float64, Int}}` for such RVs. This would essentially mean that we're type-stable where we can be, but don't error if type stable code isn't produced.

My understanding is that Stan takes the view that everything must be a `Float64` (perhaps other types of floats as well?), but clearly we don't have this option as we support discrete RVs, so presumably we must at least support the first two of the above scenarios. We could explicitly disallow the third, but I suspect that supporting it will be relatively straightforward given that we support the first two things (don't quote me on that though), and perhaps there are good examples of where you might want to produce a model that isn't possible to make type stable?

More speculatively, I would guess that the storage of everything in a flattened vector that is accessed (at least close to) sequentially will yield better access patterns, and so _might_ be faster a number of situations. It's hard to reason about this without being empirical, so my point is that I don't think it's immediately obvious which approach is likely to yield the best performance.

I only partially agree regarding the simplification of new inference algorithms, as it should be possible to make it appear to an inference algorithm like the data is stored in a single `Vector` regardless of how it actually looks in memory using something like [CatViews.jl](https://github.com/ahwillia/CatViews.jl). I'm not sure what the performance implications of something like this are though - for RVs which are large-ish `Arrays` it should be fine, but for scalars it might produce quite a lot of overhead (I'm actually not sure that CatViews can even handle scalars...)
