### ISSUE TITLE
RFC: Ideas for codebase cleanup

### ISSUE THREAD

**Issue by hessammehr** [TuringLang/Turing.jl#445]
Just hoping to get the ball rolling on getting the package slimmer code- and dependency-wise.

Some low-hanging fruit:
- Move example models to a separate repository, e.g. Turing-examples.

I've also noticed that the dependency on Stan is solely for the purpose of testing/benchmarking, which wouldn't be immediately of interest to users. Two possible solutions:

- Have this code live in a separate repository, e.g. Turing-benchmarks.
- Use something like [Require.jl]() to evaluate this code only if the Stan.jl is installed.

**Comment by willtebbutt** [comment]
+1 regarding putting examples in a separate repo. Might it make sense to create a Turing organisation to group together examples + core codebase + any other side-projects that get created in the future?

I believe the Stan dependency is also required for their NUTS implementation, but @yebai or @xukai92 know more about this than I do.

**Comment by yebai** [comment]
> +1 regarding putting examples in a separate repo. 

Yes, we can do that relatively quickly. 
@xukai92  what do you think?

> I believe the Stan dependency is also required for their NUTS implementation, but @yebai or @xukai92 know more about this than I do.

We currently use `Stan.jl`'s sampler's configuration type in Turing. It is not a huge burden to implement a new type of NUTS configurations, we might do that in the near future.

**Comment by trappmartin** [comment]
+1 for creating a Turing github organization to group Turing related packages.

**Comment by yebai** [comment]
@hessammehr @willtebbutt @xukai92 @wesselb Following up our discussion, I have created an organisation account `TuringLang`. I have also transferred the `Turing.jl` repo to the organisation account. This might cause some issues if you have your local repo stilling pointing to my personal repo, but should be easy to fix. 

@hessammehr could you create a PR to separate Turing examples into a separate repo?

**Comment by ChrisRackauckas** [comment]
Github auto-forwards so there shouldn't be any URL issues. But you should put in a METADATA PR  to change the URL anyways.

**Comment by xukai92** [comment]
Maybe we could arrange the repos in this way.

- Turing.jl
  - Use `Require.jl` for the part of code which only for the support of Stan's construction
- Turing-examples
  - This has dependencies on Turing.jl and Stan.jl
  - Make benchmark scripts as tests for Turing-examples repo

**Comment by yebai** [comment]
@hessammehr Many thanks for the help!

**Comment by yebai** [comment]
@xukai92  could you create a PR for the following 2 tasks you suggested, please?

> Use Require.jl for the part of the code which only for the support of Stan's construction

> Make benchmark scripts as tests for Turing-examples repo

**Comment by yebai** [comment]
@willtebbutt @trappmartin @wesselb @emilemathieu pls feel free to suggest any improvements that make Turing more readable and organized!

**Comment by xukai92** [comment]
@yebai I was trying to enable Travis on Turing-Examples but recevied "You don't have sufficient rights to enable this repo on Travis."

**Comment by yebai** [comment]
> @yebai I was trying to enable Travis on Turing-Examples but recevied "You don't have sufficient rights to enable this repo on Travis."

@xukai92 should be working now!

**Comment by xukai92** [comment]
Thanks! I can fix the .yml then

**Comment by xukai92** [comment]
@yebai Need some more work to fix the Stan dependency. I will probably do that after the current PR I'm working on so I created an issue (https://github.com/TuringLang/Turing.jl/issues/447) for that.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/689
