### ISSUE TITLE
Argument to pass warmup sample size.

### ISSUE THREAD

**Issue by Vaibhavdixit02** [TuringLang/Turing.jl#448]
I couldn't find any documentation on passing warmup sample size to the samplers, from https://github.com/TuringLang/Turing.jl/issues/265 I understand you use 1k as the default warmup sample size? 
It would be a good addition to have a argument that would allow the user to pass in the required warm up sample size.

**Comment by xukai92** [comment]
Sorry about our bad documentation. There are actually ways to pass it. Either
- Constructing samplers with additional arguments by `HMCDA(5000, 2000, ...)` (the second integer is considered as warmup size), or
- Passing `sa::Stan.Adapt` to `sample` by `sample(...; adapt_conf=sa)`

**Comment by trappmartin** [comment]
Thanks for the clarification.

But I guess this will only work for Hamiltonian subtyped methods. Is this correct?

If so we could maybe find a common interface for this purpose. If not we should maybe think about a more convenient interface or kw argument?

**Comment by Vaibhavdixit02** [comment]
Thanks for the clarification @xukai92. I think having kwarg for this would be a nice feature to have.

**Comment by yebai** [comment]
Closed by #793
