### ISSUE TITLE
Minor Comment Correction

### ISSUE THREAD

**Issue by wesselb** [TuringLang/Turing.jl#450]
```
  stats = stats > 1 ? 1 : stats # stats = δ - H_t, where δ is target accept prob
```
from [here](https://github.com/TuringLang/Turing.jl/blob/6f144d41f815b0fb2c72b6e26228279931e42234/src/samplers/support/adapt.jl#L95): Is `stats = δ - H_t` in the comment correct? I think `stats` is the average acceptance MH probability.

**Comment by willtebbutt** [comment]
Closed by #515
