### ISSUE TITLE
Diagnosing HMC: Energy Distribution

### ISSUE THREAD

**Issue by wesselb** [TuringLang/Turing.jl#454]
To better diagnose HMC, in particular the choice of kinetic energy and adaptation thereof, it may be worthwhile to provide metrics that compare the marginal and conditional (on a particular location) energy distributions. As explain on p. 28 in [1], mismatch between the two may greatly negatively impact performance of the sampler. A simple metric to compute is outlined in Section 6.1, also in [1]. 

[1] https://arxiv.org/pdf/1701.02434.pdf

**Comment by yebai** [comment]
Closed by https://github.com/TuringLang/AdvancedHMC.jl/pull/5
