### ISSUE TITLE
JuliaCon hackathon?

### ISSUE THREAD

**Issue by hessammehr** [TuringLang/Turing.jl#458]
Sorry if this is not be the ideal place to discuss a hackathon (and I wonder if this has already been discussed elsewhere) but with JuliaCon only a week away I was wondering if we have enough contributors attending to propose a Turing/probabilistic programming hackathon.

Personally, my knowledge of MCMC is limited but I would love to learn more about the internals of Turing and start contributing should there be a Turing hackathon. I imagine there being quite a few JuliaCon participants in the same positions so this might be a good opportunity to attract potential contributors.

**Comment by yebai** [comment]
@hessammehr It's a great idea. There are quite a few Turing team members attending JuliaCon, including @trappmartin @wesselb @willtebbutt. 

@xukai92  didn't get a ticket yet but would like to attend if possible. 

cc'ing @MikeInnes @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
I will likely be spending a lot of time with the DifferentialEquations.jl group during the Hackathon, but I will stop by and @Vaibhavdixit02 should as well.

**Comment by Vaibhavdixit02** [comment]
That sounds like an awesome idea and I would love to take part in such a hackathon!
