### ISSUE TITLE
A higher level API for Bayesian statistical models

### ISSUE THREAD

**Issue by DominiqueMakowski** [TuringLang/Turing.jl#460]
The recently developed [rstanarm](https://github.com/stan-dev/rstanarm) initiated a take-off in the adoption rate of the Bayesian framework by "general" scientists. It implements a high level API to fit all traditional regression models in a Bayesian framework just by adding "stan_" in front of the model's name (`stan_glm()`, `stan_lmer()`...). Critically, it includes good default for the priors, so that the end-user can directly fit a model without having to care about these things (which is good from a beginner-friendliness perspective).

I understand that this might not be the scope of Turing. Nevertheless, I was wondering if there were any plans to implement something similar (maybe in another package), allowing to do for instance `bayes_glm(y ~ x)` and fit a Bayesian regression. Thanks!

**Comment by willtebbutt** [comment]
This is definitely something that could be supported -- there's probably already some useful work in [Turing-Examples](https://github.com/TuringLang/Turing-Examples) that could just be tidied up a bit. I agree that it would be helpful to have non-expert-friendly implementations of these things. One could imagine having a Turing `stdlib`, which contains a large collection of standard models for which we recommend samplers. We could then use `Turing-Examples` purely as a place for notebook tutorials.

@yebai @xukai92 do we already have any code like this lying around other than in the examples package?

**Comment by yebai** [comment]
> @yebai @xukai92 do we already have any code like this lying around other than in the examples package?

I agree this is a great idea. We haven't made any serious efforts towards this direction in the past. Perhaps we can try to organise some meetups/hackathons to help people implement new models and store them in Turing-Examples? Please feel free to make suggestions!

@DominiqueMakowski Some people are talking about a Turing hackathon on Saturday. Perhaps we can discuss more there?

**Comment by DominiqueMakowski** [comment]
@yebai Unfortunately I'm not physically attending the conference, but I'll follow what happened there :)

**Comment by yebai** [comment]
See e.g. https://github.com/TuringLang/TuringGLM.jl
