### ISSUE TITLE
Turing.plot is not work

### ISSUE THREAD

**Issue by lucasfreitas1988** [TuringLang/Turing.jl#461]
When testing the gdemo example, I can not plot the generated chains.

When I call Turing.plot the message - UndefVarError: plot not defined.

The Gadfly package looks good, what could be happening?
(I tested several plots and everything seems to work...)

Thanks!

**Comment by yebai** [comment]
@lucasfreitas1988 Turing is using `Mamba` for plotting and MCMC diagnostics.  Try 

```julia
using Turing, Mamba

Mamba.plot(...)

```

**Comment by yebai** [comment]
Perhaps try to run `Mamba.plot` from Julia terminal directly first. The following code runs correctly on my Julia terminal

```julia

c6 = sample(gdemo([1.5, 2]), NUTS(1000,  0.65))

# Summarise results
Mamba.describe(c3)

# Plot results 
p = Mamba.plot(c3)
Mamba.draw(p, fmt=:pdf, filename="gdemo-plot.pdf")
```

**Comment by lucasfreitas1988** [comment]
Running in the terminal seems like a good idea!

But, now, Julia shows me the message: Press ENTER to draw next plot - and the plot does not appear. Not even in the language folder.  I tried to change pdf to svg and nothing happened.

Sorry for the many questions!

Thanks!!

**Comment by yebai** [comment]
The plot will only be saved after you press the `ENTER` key.

**Comment by lucasfreitas1988** [comment]
This is my point. After pressing enter, I can not find the saved file.
Is weird.

**Comment by xukai92** [comment]
What's your Julia version and Turing.jl version?

**Comment by xukai92** [comment]
I just tried with Julia 0.6.4 and master branch of Turing.jl - it works for me. My code is 

```julia
using Turing

@model gdemo(x) = begin
         s ~ InverseGamma(2,3)
         m ~ Normal(0,sqrt(s))
         x[1] ~ Normal(m, sqrt(s))
         x[2] ~ Normal(m, sqrt(s))
         return s, m
end

c = sample(gdemo([1.5, 2]), NUTS(1000,  0.65))

using Mamba

# Plot results 
p = Mamba.plot(c)
Mamba.draw(p, fmt=:pdf, filename="gdemo-plot.pdf")
```

The `.pdf` file should appear in the same folder where you start your julia. Otherwise please use an absolute path for it. If you use the same code as me but still get problem, maybe try use the master branch of Turing.jl by `Pkg.checkout("Turing")`.

**Comment by lucasfreitas1988** [comment]
Pkg.checkout("Turing")  worked fine, the PDF was generated in the folder Julia!

Thank you very much!!!!

**Comment by xukai92** [comment]
Great! Feel free to post more issues and we're here to help :D
