### ISSUE TITLE
Remove customised `dprintln` logging function

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#471]

**Comment by willtebbutt** [comment]
So that it doesn't get lost, I suggested in #469 that we should use [Memento.jl](https://github.com/invenia/Memento.jl) for our logging, as it is substantially more feature-ful than the stdlib logging, and Invenia are committed to supporting it.

**Comment by willtebbutt** [comment]
Not sure. @omus @iamed2 is there a canonical reference for @xukai92 's question above?

**Comment by iamed2** [comment]
There isn't yet, but I should write one. The only thing that stdlib logging offers is *zero*-overhead *debug* logging. In Memento if you log something but filter it out, there is a small cost for checking the levels. In stdlib logging, you pay a similar cost except for debug logs, which are compiled out by default.

**Comment by xukai92** [comment]
We decided to use the stdlib for now - mostly because of the simplicity + we don't need one more dependency for Turing.jl. 

We can always change it to Memento.jl later if needed.

**Comment by xukai92** [comment]
Commits from f2dba79 to 3d1ea43 resolve this issue. We shall close it after the whole PR is merged.

**Comment by trappmartin** [comment]
It's all set for the #469 to be merged soon. Therefore, closing this issue.
