### ISSUE TITLE
Compiler: move `model_f(;data=Dict())` from compiler to utilities

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#475]
The current compiler generates a sugar syntax that allows passing all data to a model using a dictionary. This feature is similar with the interface used by the Stan.jl. Implementing this feature at a compiler level is probably not necessary. Perhaps we should move this to utility functions, e.g. 

```julia

model_f(@data data_dict)

```

This requires implementing a macro named `@data` which will act similarly as `(x...)`.

**Comment by willtebbutt** [comment]
Specifically on the manipulation of kwargs, look at [MacroTools.jl](https://github.com/MikeInnes/MacroTools.jl). Specifically the stuff towards the bottom on function-expression de-structuring. I've found this package indispensable when doing any metaprogramming.

**Comment by trappmartin** [comment]
Thanks, @willtebbutt I'll have a look at it. I'm sure there is a better way then how I do it currently.

**Comment by trappmartin** [comment]
We can now do the following: 

```julia
julia> f(x, y) = 2*x*y^2
julia> dict = Dict(:x => 1, :y => 10)
julia> f( Turing.data(dict, [:x, :y])... )
200
julia> Turing.data(dict, [:x, :y])
(x = 1, y = 10)
julia> f( Turing.data(dict, [:y, :x])... )
20
julia> Turing.data(dict, [:y, :x])
(y = 10, x = 1)
julia> Turing.data(dict, [:x, :y, :z])
ERROR: AssertionError: ...
```
which is a cheap solution to the problem. Note that the ordering of the symbols in the second argument of `Turing.data` is deciding the ordering of the entries in the tuple, see last lines.

**Comment by yebai** [comment]
This looks good!
