### ISSUE TITLE
Implementing a matlab / JAGS algorithm in turing?

### ISSUE THREAD

**Issue by DominiqueMakowski** [TuringLang/Turing.jl#478]
I would be interested in implementing [this](https://github.com/metacoglab/HMeta-d/blob/master/fit_meta_d_mcmc.m) algorithm in Julia. 

However, my expertise with matlab, JAGS, Turing and even Julia remains quite limited. Therefore, I would like to have your opinion and advice on the feasibility and difficulty of such task, *i.e.,* translating this algorithm from Matlab/JAGS to Julia. Thanks!

**Comment by awellis** [comment]
The actual Jags model is in the file "Bayes_metad_rc.txt". This is the model that you want to implement in Turing, right?

**Comment by DominiqueMakowski** [comment]
@awellis Yes, as well as the wrapper around I believe...

**Comment by awellis** [comment]
@DominiqueMakowski 
I have a hunch that this could be pretty straightforward to implement as an ordinal (profit) regression model using [brms](https://github.com/paul-buerkner/brms/tree/master/R), although I haven't really thought about it much.

**Comment by DominiqueMakowski** [comment]
@awellis you mean for R? but what about Julia? I am wondering if we could bypass the need for applied modelling tools (provided in R by brms or rstanarm) or if it's better to wait for such tools

**Comment by awellis** [comment]
@DominiqueMakowski 
Sure you can implement it in Turing/Julia, and it would be much nicer than doing the same in Stan/R or Jags, or whatever. I think Turing already is much nicer to use for hand-coded models.

On the other hand, the ordinal regression model isn't straightforward to code, and making it multilevel makes it even more tedious. This work has already been done in brms. My idea (this was actually more of a question): Isn't this meta d' model actually 'just' an ordinal regression model, that has been coded in a manner that makes it hard to understand?

**Comment by DominiqueMakowski** [comment]
@awellis haha that's possible, I haven't try deciphering the code in details (yet), I was looking for some general opinion to start :)

**Comment by DominiqueMakowski** [comment]
alright, so the first step for me is to find out how to write a probit (would logistic work?) model in Turing 😄

**Comment by trappmartin** [comment]
@DominiqueMakowski did you manage to implement the model you were interested in?

**Comment by DominiqueMakowski** [comment]
Not at all, but I'll try in the future. I'll close this issue and will reopen it if every needed, thanks
