### ISSUE TITLE
Refactoring: better organisation of tests

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#479]
I think we need better organisation tests. It's a bit difficult to run tests from individual folders at the moment. Perhaps we can have a `runtests` file in each test sub-folder, e.g. 

```julia
test/runtests.jl
   ad/runtests.jl
   core/runtests.jl
   trace/runtests.jl
```

This allows us to run tests for specific categories, i.e. we can run

```julia
include("test/runtests.jl") # run all tests. this script executes all subfolder runtests.jl scripts.
include("test/ad/runtests.j") # run ad related tests only
```

@xukai92 @wesselb @trappmartin

**Comment by xukai92** [comment]
Good idea. Let's make this change in Friday's hackathon

**Comment by trappmartin** [comment]
Excluding only a group of tests is now more convenient. To skip a test in a test group folder one has to add a `skip_tests` file in the folder and list all files that should be skipped. See `test/compiler.jl/skip_tests` for an example.
