### ISSUE TITLE
Compiler: remove `return vi::VarInfo`.

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#483]
The current compiler replaces all `return` statements with `return vi::VarInfo` as a mechanism for allowing a user to specify which parameter needs to be stored in `Chain`. 

```julia
@model mdemo() = begin

   return x, y # only x and y will be stored in Chain
end
```

This design is a bit obsolete now since we can nicely store all parameters (using the proposed indexing scheme #484).

**Comment by yebai** [comment]
@xukai92 are you aware of any dependencies on this feature?

**Comment by xukai92** [comment]
Internally we sometimes do `vi = model()`. But this could be changed by initialising `vi` manually and always assume the model will amend it in-place, i.e. `vi = VarInfo(); model(vi)`. 

PS: maybe we should call it `model!(vi)` then?

**Comment by yebai** [comment]
> PS: maybe we should call it model!(vi) then?
 
sounds good!
