### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by willtebbutt** [TuringLang/Turing.jl#488]
Please feel free to shut me down if this isn't a discussion we want to have right now, but there are a number of inconsistent / unusual conventions that we're following throughout the codebase. Given that we're about to embark on rather a lot of work, and there are a number of new people coming on board, it might be an opportune time to decide on some rules that we enforce (in a meticulous manner) in all new PRs, and apply retrospectively as we get around to it. We need a full style guide really, and I'm happy to provide suggestions on this front, but below are a few issues that I feel need to be addressed fairly urgently.

1. Firstly, there are currently two (long) function declaration styles used throughout the package:
```julia
foo(x) = begin
# code
end
```
and
```julia
function foo(x)
# code
end
```
I have a strong preference for the second one, as it is substantially more prevalent throughout other Julia packages and is IMHO substantially cleaner.

2. Short-style function declarations: we really should stick to the 92 character line-limits. So while
```julia
foo(x) = # code
```
seems fine to me provided that the entire line comes to under 92 characters, we should enforce that anything over 92 characters use the long-style format.

3. Multi-line function declarations: sometimes long-style functions declarations
```julia
function foo(x, y, z, ...) where {stuff}
```
will go over 92 characters. In this case, I've seen a few conventions, but I'm personally a fan of
```julia
function foo(
    arg1,
    arg2,
) where {stuff}
 # code
end
```
I'm not sure if we currently have a policy on this or not...

4. Comments in code:
```julia
function foo(x)

    # comment
    code

    # another comment
    some_more_code
end
```
as opposed to
```julia
function foo(x)
    # comment
    code
    # another comment
    some_more_code
end
```
seems reasonable to me.
5. (Disclaimer: this is entirely personal preference, and I am _totally_ happy for someone to tell me that this isn't going to happen) indentation: we're using 2-space indentation. I've seen this convention used in Flux.jl, but all of `Base` and the `stdlib` are written with 4 spaces, as are just about every other package in the eco-system. I would advocate enforcing 4 spaces everywhere.

The above basic suggestions are straightforward, and I really think that we need a more all-encompassing set of rules, but hopefully this is the start of a discussion on the matter.

**Comment by mohamed82008** [comment]
Recent style guidelines of JuMP: http://www.juliaopt.org/JuMP.jl/latest/style.html. With the exception of their ! convention, the rest seem reasonable.

**Comment by willtebbutt** [comment]
What's there looks good. @omus is Invenia's style guide public?

**Comment by willtebbutt** [comment]
The basic [Julia style guide ](https://docs.julialang.org/en/v1.0.0/manual/style-guide/) is something we should be following anyway, but it's not as specific as we require to be honest.

**Comment by trappmartin** [comment]
I think this discussion is very important. It would probably be a good idea to develop a policy and include it in the repo so that contributors can easily follow the policy.

**Comment by willtebbutt** [comment]
Here's Invenia's style guide, which they have kindly allowed me to provide. It's fairly exhaustive, and I think it's the level of detail that we aught to be going for.
[style_guide.txt](https://github.com/TuringLang/Turing.jl/files/2354904/style_guide.txt)

(It's a markdown file, not a text file, so bear that in mind when trying to view it)

**Comment by trappmartin** [comment]
@willtebbutt this looks like a very reasonable style guide. To which extent are we allowed to reuse parts of the style guide?

**Comment by willtebbutt** [comment]
This issue is superseded by #494.
