### ISSUE TITLE
Documentation Overhaul 

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#494]
Make the documentation more thorough, cohesive, and helpful. Here are a handful of the big steps I see

- [x] Gather and update/polish existing tutorials so they are easily searched for and clearly labeled
- [ ] Add additional tutorials to help showcase a variety of things possible with Turing (see [Edward](http://edwardlib.org/tutorials/))
- [x] Move over to a [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl) documentation structure
- [x] Set the new documentation up to automatically pull in all the docstrings we have in place where useful
- [ ] Standardize docstring formats (if necessary)
- [x] Add style guide

Likely more tasks to follow, but those are kind of the broad strokes of my responsibilities as I see them so far. Anyone have anything to add or expand on regarding documentation and tutorials?

**Comment by willtebbutt** [comment]
Looks good to me.
> Set the new documentation up to automatically pull in all the docstrings we have in place where useful

Documenter makes it really straightforward to achieve. This would also be a really good opportunity to assess where our docstrings could do with some more work. It would be very helpful if we could establish some ground rules for docstring formatting (related to #488), and make sure that they are followed.

**Comment by cpfiffer** [comment]
> It would be very helpful if we could establish some ground rules for docstring formatting

I agree completely. I haven't yet done a survey of all the docstrings we have in place yet, but I imagine once I have them all more or less assembled some of them will be of varying degrees of usefulness. I'll throw that on the list too.

**Comment by willtebbutt** [comment]
[style_guide.txt](https://github.com/TuringLang/Turing.jl/files/2361690/style_guide.txt)

@cpfiffer here's the style guide that @yebai @trappmartin and went through today and agreed on. Would it please be possible to work it into the documentation somehow?

**Comment by cpfiffer** [comment]
Yep, I'll set up a newer "Contributing" section with the style guide in there.

**Comment by cpfiffer** [comment]
Hey everyone, the new documentation formatting has been completed and set up to work with Travis, so that the docs will be rebuilt with every push to the master. You can see an example of the new docs [here](http://cameron.pfiffer.org/Turing.jl/latest/). I'll be following up sometime today or tomorrow with a pull request to merge this over to current branch. It also has our first official tutorial, with a couple more on the way.

**Comment by yebai** [comment]
Perhaps we can close this issue now?

**Comment by cpfiffer** [comment]
I see no reason not to. Consider it closed.
