### ISSUE TITLE
logsum -> logsumexp

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Turing.jl#500]
https://github.com/TuringLang/Turing.jl/blob/70640d35805bb46a54c04d9ff25e5a90f22eee2b/src/core/util.jl#L23

I believe this is the famous log-sum-exp function.

**Comment by mohamed82008** [comment]
Can also use a `mapreduce` there to avoid allocating `ys`.

**Comment by willtebbutt** [comment]
Huh. We should probably be using a standard implementation for this stuff eg. that in [StatsFuns.jl](https://github.com/JuliaStats/StatsFuns.jl)
This probably also applies to `logit` and `invlogit` / `logistic`.

**Comment by mohamed82008** [comment]
Apparently, `StatsFuns` is not registered so I am just renaming `logsum` to `logsumexp` in Turing.

**Comment by trappmartin** [comment]
Maybe we could do the performance improvement you proposed while renaming? Log-sum-exp can be quite a performance bottleneck for certain types of models, e.g. deep mixtures.

**Comment by yebai** [comment]
> Apparently, StatsFuns is not registered so I am just renaming logsum to logsumexp in Turing.

Seems the following command works on my computer:
```julia
(v1.0) pkg> add StatsFuns
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed Graphics ─ v0.4.0
  Updating `~/.julia/environments/v1.0/Project.toml`
  [4c63d2b9] + StatsFuns v0.7.0
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [a2bd30eb] ↑ Graphics v0.3.0 ⇒ v0.4.0
```

**Comment by mohamed82008** [comment]
hmm that's weird, it doesn't work on mine. I will upgrade everything and try again.

**Comment by mohamed82008** [comment]
Actually now it works no idea what changed. Anyways, back to plan A then.

**Comment by nalimilan** [comment]
Note that with https://github.com/JuliaStats/StatsFuns.jl/pull/97, StatsFuns is going to implement a faster version of `logsumexp`, so it would be worth using it instead of an internal implementation.

**Comment by devmotion** [comment]
I replaced the internal implementation with StatsFuns.logsumexp last year (https://github.com/TuringLang/Turing.jl/commit/6e5843517d71cd55429afdeb6abcb97a0bbe7361).
