### ISSUE TITLE
Clean up the compiler code

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#501]
The current compiler code is a bit messy and hard to unit test. I'll try to separate function out of the code to allow for better unit testing and add more tests.

**Comment by yebai** [comment]
Some known  incomplete/inconsistent implementations of the compiler

- Return keyword https://github.com/TuringLang/Turing.jl/issues/483 (related issues #83 #81)
- `sample(gdemo([0, 1]), alg)` is implemented instead of `sample(gdemo(y=[0, 1]), alg)`

**Comment by yebai** [comment]
Ps. some further notes 

```
# interface 1: all data passed in explicitly.
sample(gdemo([0, 1]), alg)            

 # interface 2, current compiler does not support yet?     
sample(gdemo(;y=[0, 1]), alg)    

# interface 3, all data passed in through `data` Dict.       
sample(gdemo(; data=data::Dict), alg)      
```

I'm not sure whether interface 2 has been implemented (probably not).

**Comment by trappmartin** [comment]
I agree, for #475 to work with interface 1, which is the one we want, we need to get access to the function definition or at least the arguments list of the function to pass the arguments in the correct order. I'll check how to do that.

**Comment by yebai** [comment]
Perhaps we can do:
```julia

@data dict # pour all entries of dict into the current scope

sample(gdemo(x,y,theta), alg)  

```

**Comment by trappmartin** [comment]
The downside with this approach is that we would overwrite the values of all variables in the global scope that occur as a key in the dict. This might lead to unexpected behaviour. 

I'll invest a bit of time to see if we can get the function signature and argument names somehow instead.

**Comment by yebai** [comment]
How about
```julia
model_f(@data(data_dict::Dict, (:x, :y, :theta))
```

This removes the complexity of extracting function argument names..

**Comment by trappmartin** [comment]
Sounds good to me.

The macro would do something like this:
```julia
julia> f(x = 2, y = 2;) = 2*x*y
julia> f( eval(Expr(:tuple, Expr(:(=), :x, 10), Expr(:(=), :y, 1)))... )
20
```
What do you think?

**Comment by yebai** [comment]
Looks good except that we have many models written without default values, something like:
```julia
julia> f(x, y;) = 2*x*y
```

**Comment by trappmartin** [comment]
This should still be fine, I'll check.
