### ISSUE TITLE
observe and assume

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#504]
I think the following points regarding the current code might be problematic and changing them could improve our codebase.

1. Assume and observe dispatch on the sampler type (which is fine) but also on `Nothing`. This forces us to pass `nothing` to the functions if no sampler is defined and have a `Union{Nothing, Sampler}` for the model functions. I think we can circumvent this by having different function signatures, one with and one without the sampler argument. Or do I miss something here?

2. Currently assume and observe do in-place operations and not in-place operations at the same time More precisely, they change the VarInfo variable and also return values that are used later on. This is inconsistent and might lead to strange behaviour. I would prefer to make this consistent and ensure that all operations are either in-place or not. I feel the mixed behaviour is not very clean. See for example: https://github.com/TuringLang/Turing.jl/blob/7cb84a5a12dd604fae6b4b0e983b499d4dabb5ac/src/samplers/sampler.jl#L93 and https://github.com/TuringLang/Turing.jl/blob/7cb84a5a12dd604fae6b4b0e983b499d4dabb5ac/src/samplers/sampler.jl#L42
Or is there a reason why cannot do all operations in-place?

cc: @yebai

**Comment by willtebbutt** [comment]
> Currently assume and observe do in-place operations and not in-place operations at the same time More precisely, they change the VarInfo variable and also return values that are used later on. This is inconsistent and might lead to strange behaviour. I would prefer to make this consistent and ensure that all operations are either in-place or not. I feel the mixed behaviour is not very clean. See for example:

I don't know how straightforward it will be to move towards immutability using the current `VarInfo` design, which is entirely formulated entirely around mutation. I do not believe that the current mutating design is a good choice for a number of reasons, however, it will be a substantial amount of work to move away from it. Consequently, the only viable resolution to your concern at the minute is to do everything via mutation. On the other hand, how much of an issue actually is this? I'm not aware of any conventions that advocate for avoiding it, although I do agree that it's not the most obvious design.

Also bear in mind that we're not getting the performance gains anymore as we're not using `ReverseDiff` (not that we should be relying on our AD to achieve good performance).

**Comment by yebai** [comment]
> Assume and observe dispatch on the sampler type (which is fine) but also on Nothing. This forces us to pass nothing to the functions if no sampler is defined and have a Union{Nothing, Sampler} for the model functions. I think we can circumvent this by having different function signatures, one with and one without the sampler argument. Or do I miss something here?

This is fixed by https://github.com/TuringLang/Turing.jl/pull/706

**Comment by yebai** [comment]
Closed by #995
