### ISSUE TITLE
Refactoring: remove `cleandual!` and `realpart!`

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#509]
Shall we remove the function `cleandual!` since our AD is using standard `ForwardDiff` and `Flux` interface now? We can always do

```julia
vi[spl] = theta::Vector{Float64}
```
after each AD iteration to ensure `vi` has the right types.

**Comment by willtebbutt** [comment]
I agree we should remove it, but this actually highlights a bug that I hadn't realised would exist in the AD code. We're not ensuring that the `logp` field of `VarInfo` isn't a `Dual` or `Tracked`. I'll tack that onto my soon-to-be-opened AD-related PR, and remove `cleandual!`.

**Comment by willtebbutt** [comment]
We might also be able to get rid of `realpart` if we're not contaminating things with `Dual`s anymore. Will look into it.

**Comment by willtebbutt** [comment]
Closed by #515
