### ISSUE TITLE
Reexport Distributions

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Turing.jl#518]
I noticed that most usage example go like:
```julia
using Distributions, Turing
...
```
So I think it would be nice to just use [Reexport.jl](https://github.com/simonster/Reexport.jl) and reexport `Distributions.jl` to make Turing self-sufficient. The same thing can be done for `MCMCChain.jl` I suppose. What do you think?

**Comment by yebai** [comment]
Since it’s just a macro, can we just copy the code and its license instead of adding one more decency..

**Comment by willtebbutt** [comment]
Is there any particular reason that you're concerned about the extra dependency? I don't see what we lose by doing so, particularly given the new package manager, and it avoids adding yet _more_ code that isn't really central to what we do to Turing

**Comment by mohamed82008** [comment]
It's a 20 line macro, but let's keep as much code as we can out of Turing, 20 lines at a time. If it gets abandoned, we can pull it in, but it seems actively maintained and watched by some solid programmers. PR coming.
