### ISSUE TITLE
Failed to Precompile

### ISSUE THREAD

**Issue by revendrat** [TuringLang/Turing.jl#521]
Have tried it on Mac as well as on Windows 10, failing to precompile at both while using Turing for the first time. Was using packages in first cell in this notebook: https://github.com/TuringLang/TuringExamples/blob/master/notebooks/Workflow.ipynb
Here is the message. Could you please suggest what to do?

┌ Info: Precompiling Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0]
└ @ Base loading.jl:1186
ERROR: LoadError: syntax: extra token "Sampler" after end of expression
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:319 [inlined]
 [6] eval(::Expr) at ./client.jl:389
 [7] top-level scope at ./none:3
in expression starting at /Users/rev/.julia/packages/Turing/SDG4M/src/Turing.jl:90

`Failed to precompile Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0] to /Users/rev/.julia/compiled/v1.0/Turing/gm4QC.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834
 [9] top-level scope at In[3]:1`

**Comment by trappmartin** [comment]
Are you using the master branch of Turing? It seems you are using Julia 1.0. For Turing to work on Julia 1.0 you have to add the master. To do so, run
```julia
pkg> add Turing#master
```
in the Julia package manager REPL.

**Comment by revendrat** [comment]
Thank you @trappmartin!  Now, I got a few warnings. Hope these won't pose any problem while using Turing
WARNING: could not import LinearAlgebra.gradient into Interpolations
WARNING: could not import Base.showcompact into Stan
┌ Warning: Environment variable CMDSTAN_HOME not found. Use set_cmdstan_home!.
└ @ Stan /Users/rev/.julia/packages/Stan/a6xnA/src/Stan.jl:18
WARNING: could not import NNlib.cudata into Tracker
┌ Info: [Turing]: AD chunk size is set as 40
└ @ Turing /Users/rev/.julia/packages/Turing/ltzCi/src/Turing.jl:52

**Comment by trappmartin** [comment]
Please note that the example you linked to is slightly outdated if you use the master branch. It is probably better to try the example shown in the README or the [this](https://github.com/TuringLang/TuringTutorials/blob/master/0_Introduction.ipynb) one. We are currently working on improving the tutorials and documentation. So if you run into problems or need some help, feel free to ask.

cc @cpfiffer

**Comment by revendrat** [comment]
Thank you @trappmartin! The tutorial has executed flawlessly, except for the animation plot. Thank you @cpfiffer for an elaborate tutorial.
