### ISSUE TITLE
Refactoring: remove `_lp` from generated model functions

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#524]
At the moment, we have 2 variables for tracking log joint probability, namely

- `VarInfo.logp`
- `_lp` inserted into generated model functions

This seems unnecessary and introduces an extra requirement for keeping them synchronised. Perhaps we should consider to remove `_lp` and use `VarInfo.logp` everywhere. 

Related: https://github.com/TuringLang/Turing.jl/pull/513#issuecomment-420952515

**Comment by trappmartin** [comment]
This sounds good as it would further simplify the compiler code.
