### ISSUE TITLE
Debug statements etc

### ISSUE THREAD

**Issue by willtebbutt** [TuringLang/Turing.jl#526]
We have quite a lot of `@debug` statements floating around the code base, and I wonder how much additional value a lot of them provide. Debug messages like `@debug "run model..."` in a function called `runmodel` really don't provide any additional information over and above what a stack trace already provides, while cluttering the code.

I would be keen to understand whether
1. anyone feels that these debug messages provide value over and above what we get for free from stack traces and
2. there would be any objections to removing a lot of the debug messages.

**Comment by yebai** [comment]
@willtebbutt That's a good point - many of these code are written when Julia's debugging environment isn't so mature.  Indeed, some `@debug` messages are a bit redundant and can be safely removed.

**Comment by willtebbutt** [comment]
Great. I'll do this once #513 is merged.
