### ISSUE TITLE
Support DynamicHMC in Turing

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#527]
Excerpt from https://github.com/TuringLang/Turing.jl/issues/324#issuecomment-420995014

> DymanicHMC is a very well designed and tested NUTS implementation together with adaption for preconditioning matrix. We can try to plug DynamicHMC into Turing and compare its results against our NUTS sampler. We can also try to refactor our NUTS sampler following DynamicHMC's design. Ideally, the sampler code should be testable and benchmarkable without dependency on other parts of Turing.

https://github.com/tpapp/DynamicHMC.jl/

**Comment by xukai92** [comment]
Closed by https://github.com/TuringLang/Turing.jl/pull/549
