### ISSUE TITLE
No v0.7 release?

### ISSUE THREAD

**Issue by ChrisRackauckas** [TuringLang/Turing.jl#528]
https://github.com/TuringLang/Turing.jl/compare/v0.4.4...master#diff-58476995b642435595799e856c5d2a74R1

v0.7 is used for updating packages, so there should be a working v0.7 release to help downstream packages upgrade.

**Comment by yebai** [comment]
@ChrisRackauckas we’ll make a beta release over the weekend. we planned to release 0.5 after current refactoring is complete, but a beta should be fine.

**Comment by yebai** [comment]
New release tagged: https://github.com/JuliaLang/METADATA.jl/pull/18024

**Comment by ChrisRackauckas** [comment]
Thanks!
