### ISSUE TITLE
Compiler generated aliases

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#533]
Check which of the generated alias functions are necessary.

**Comment by mohamed82008** [comment]
May you elaborate?

**Comment by trappmartin** [comment]
The compiler currently generates alias functions for the closure function (model function). We should check after merging #513 which of those alias functions are actually required.

**Comment by mohamed82008** [comment]
Is this still an issue? It seems that the current closure definitions handle the cases of:
1. No input - for convenient sampling from prior.
2. `vi` input with no sampler which is convenient for MAP optimization as in https://github.com/TuringLang/Turing.jl/issues/605.
3. Sampler and vi inputs which is used inside of Turing a lot.

**Comment by mohamed82008** [comment]
The aliases were removed from the compiler in #965. Different methods were defined for `(model::Model)(...)` instead but all seem to be useful.
