### ISSUE TITLE
LineNumberNode(-1) when constructing @~ macro

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#534]
Current we have

```julia
if (ex.head === :call && ex.args[1] === :(~))
    ex.head = :macrocall; ex.args[1] = Symbol("@~")
    insert!(ex.args, 2, LineNumberNode(-1)) # NOTE: a `LineNumberNode` object is required
                                            #       at the second args for macro call in 0.7
...
```

where the new required LineNumberNode is set to -1. I don't know how it is used and whether it will cause any problem or not.

**Comment by mohamed82008** [comment]
Should probably replace `-1` with `@__LINE__`. This is used for debugging AFAIK to give correct line info in a stacktrace.

**Comment by trappmartin** [comment]
Changed to `@__LINE__` as proposed.
