### ISSUE TITLE
Link to Git Workflow 

### ISSUE THREAD

**Issue by wesselb** [TuringLang/Turing.jl#535]
In `docs/src/contributing/guide.md`, it might be better to link to a well-maintained guide. Options:

* https://guides.github.com/introduction/flow/
* https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md

**Comment by cpfiffer** [comment]
The section now reads:

>### What Can I Do?
>Look at the [issues](https://github.com/TuringLang/Turing.jl/issues) page to find an outstanding issue. For instance, you could implement new features, fix bugs or write example models.
>
>### Git Workflow
>
>For more information on how the Git workflow typically functions, please see the [GitHub's introduction](https://guides.github.com/introduction/flow/) or [Julia's contribution guide](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md).

Anything else to add?

**Comment by yebai** [comment]
Closed by #512
