### ISSUE TITLE
Scope question

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#545]
Is anyone aware a package/way for extracting scoping structure of a Julia function? For a special reason, I need to implement a macro that can rename variables in child scopes so that variables that exist in both parent scope and child scopes are renamed to different names.

@mohamed82008 @ChrisRackauckas @mikeinnes @StefanKarpinski

**Comment by mohamed82008** [comment]
Why not just replace every symbol in the body of every function by a unique `gensym()` keeping track of the mapping of which symbol became which other symbol? This should be possible with `@capture` and `postwalk` of `MacroTools.jl`. To make the global-only variables visible and not error, you will need to replace the variables on the LHS of an assignment first. Then whatever was replaced from the LHS, you then replace those all over the function in a for loop of `postwalk`s. To keep track of what was replaced you can do something like:
```julia
julia> using MacroTools

julia> mapping = Dict{Symbol, Symbol}()
Dict{Symbol,Symbol} with 0 entries

julia> MacroTools.postwalk(x -> x == :x ? (newx = gensym(x); mapping[x] = newx; newx) : x, :(x = 1))
:(##x#358 = 1)

julia> mapping
Dict{Symbol,Symbol} with 1 entry:
  :x => Symbol("##x#358")
```
This is one approach anyways.

**Comment by yebai** [comment]
Thanks, @mohamed82008.  This problem becomes complicated when we re-usd variable names between child and parent scopes. Consider the following example

```julia

using Turing

@model gdemo(x) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  z  ~ Bernoulli(0.5)
  x  ~ Normal(m+1, sqrt(s))  # x1

  let 
    if z == 1
        x ~ Normal(m+1.5, sqrt(s)) # x2
    else 
        x ~ Normal(m+2, sqrt(s))  # x2
    end
  end

  for i=1:5
     x ~ Normal(m+3, sqrt(s)) # x3
  end

  return s, m
end

```

Here we re-used variable names `x` for 3 different purposes. We want to rename `x` consistently so that `x` in different scopes are mapped to different names (e.g. `x1`, `x2`, `x3`). It's possible to solve this task using `MacroTools`, but I think it'll involve writing a scope parser, which might take a lot of time.

**Comment by yebai** [comment]
Hi @mohamed82008, could you:

- turn this into a PR with some tests
- add support for multi-level of nesting scopes (e.g. let let end end)
- add support for other Julia language structs which can introduce new scopes.
