### ISSUE TITLE
Turing webpage broken

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#551]
Currently the Turing webpage [turing.ml](http://turing.ml) seems to be broken.
@cpfiffer Is this related to the merged PR on the documentation system?

**Comment by cpfiffer** [comment]
Yes, it is. There's an additional procedure we need to do to get it back. The quick way is for someone to add a `gh-pages` branch, set the repo to serve GitHub pages from that branch, and then I'll send a pull request for the version I have stored.

Eventually, someone with access to the repository's deploy keys (I'd assume @yebai) needs to follow the steps [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/) in the "SSH Deploy Keys" section. The important steps are to run the following:

```julia
using Documenter
Travis.genkeys("Turing.jl")
```
Then:

>Add the public ssh key to your settings page for the GitHub repository that you are setting up by following the .../settings/key link provided. Click on Add deploy key, enter the name documenter as the title, and copy the public key into the Key field. Note that you should include no whitespace when copying the key. Check Allow write access to allow Documenter to commit the generated documentation to the repo.

>Next add the long private key to the Travis settings page using the provided link. Again note that you should include no whitespace when copying the key. In the Environment Variables section add a key with the name DOCUMENTER_KEY and the value that was printed out. Do not set the variable to be displayed in the build log. Then click Add.

This will allow Travis to rebuild our documentation whenever there's changes, and make sure our docstrings and such are current. This will create a `gh-pages` branch which currently lacks our webpage, but I'll send a pull request to get it up to snuff when it exists.

**Comment by cpfiffer** [comment]
Update: The site is now live at [turing.ml](http://turing.ml), and the documentation can be found at [turing.ml/latest](http://turing.ml/latest/). I won't close this issue yet as I still have to set up the deploy keys on Travis.

**Comment by cpfiffer** [comment]
Travis is now set up to automatically update our documentation. I'll monitor the build log to make sure it's doing everything it's supposed to.

**Comment by yebai** [comment]
Thanks, @cpfiffer.
