### ISSUE TITLE
Replace `Stan.Adapt + WarmUpManager + adaption code` with `DynamicHMC.AbstractTuner` 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#552]
The `AbstractTuner` type in DynamicHMC looks like a sensible replacement for 
`Stan.Adapt + WarmUpManager + adaption code` 

https://github.com/tpapp/DynamicHMC.jl/blob/master/src/sampler.jl#L148

perhaps we can adapt this bit of code for our HMC sampler family? This would fix the following related issues:

- Better adaptation configuration interface https://github.com/TuringLang/Turing.jl/issues/491 
- Support pre-cond with full covariance https://github.com/TuringLang/Turing.jl/issues/279
- Robust adaption for NUTS https://github.com/TuringLang/Turing.jl/issues/324
- Remove Stan dependency on Turing https://github.com/TuringLang/Turing.jl/issues/447

**Comment by yebai** [comment]
It appears that DynamicHMC is taking an opaque approach here: although there exists DualAveragingParameters type, there is no NUTS constructor that accept and pass through dual averaging parameters. NUTS is always using default adaption parameters for leapfrog stepsize. 

The default parameters should be good enough here. Why do you want to change adaption parameters? We almost always use the default values in Turing too..

**Comment by xukai92** [comment]
Current targets:
- Move adaptation related parameters from `Sampler` to a separate type `Tuner`
- Change the interface of `sample` so that it takes both sampler and tuner to do the sampling
- Adapt the design of `Tuner` from DynamicHMC

**Comment by xukai92** [comment]
Closed by https://github.com/TuringLang/Turing.jl/pull/597
