### ISSUE TITLE
Clean up `docs/` folder

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#556]
The current `docs` folder on the master branch is not consistent with the `gh-pages` branch, e.g.

- It seems the `unused` folder on the master branch is not used. Perhaps consider to  remove it?
- The landing page for `turing.ml` does not exist in `docs` on the master branch. 
- The `_includes` folder does not exist in `docs` on the master branch. 
- Perhaps consider removing `docs/src/ex/` since its always copied from `TuringTutorials` automatically.

EDIT: it'll be nice to sync 

- `index.md` 
- `_layouts`
- `assets`
- `_includes`

when they are changed on the master branch.

**Comment by yebai** [comment]
@cpfiffer Could you take a look at this? Thanks!

**Comment by cpfiffer** [comment]
The unused and examples folders have been removed. 

In addition, there is now a `homepage-updater.jl` script in the `docs/` folder. This is a fairly rudimentary script to copy the contents of the `docs/homepage` folder into the `gh-pages` branch, so any changes you need to make to the homepage should go into the `docs/homepage` folder. Anything else you'd like to tack on there?

**Comment by yebai** [comment]
Thanks, @cpfiffer. This looks good now. One more thing, the latest commit of `gh-pages` is two days ago. It seems changes on the `master` branch does not trigger an auto update of `gh-pages`?

**Comment by cpfiffer** [comment]
The updates are only triggered when a Travis passes a build -- we have to fix the issue that's happening with the [non-postive definite matrix](https://travis-ci.org/TuringLang/Turing.jl/jobs/432014941) before anything will update.

**Comment by yebai** [comment]
Perhaps consider separating the build script of doc into a separate `Travis` job, something similar to 

https://travis-ci.org/uber/pyro
