### ISSUE TITLE
Incorrect formating in documentation - Style Guide

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#558]
http://turing.ml/latest/contributing/style_guide.html#Whitespace-1

**Comment by cpfiffer** [comment]
Solved (eventually) via commit 4ce748b19e70d693bcf11536bd8753434fe3d545.

This fix isn't going to show up for the moment as the Travis build is [failing](https://travis-ci.org/TuringLang/Turing.jl/jobs/431657735) for a Stats requirement error:

```
ERROR: Unsatisfiable requirements detected for package Stats [072d6d2a]:
 Stats [072d6d2a] log:
 ├─possible versions are: [0.0.1, 0.1.0] or uninstalled
 ├─restricted to versions 0.0.0-* by an explicit requirement, leaving only versions [0.0.1, 0.1.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```
