### ISSUE TITLE
MCMCChain.plot(c3)  -> ERROR: MethodError: no method matching plot(::Turing.Chain{AbstractRange{Int64}})

### ISSUE THREAD

**Issue by zenon** [TuringLang/Turing.jl#562]
Hello,

I started with the basics. I.e. 

http://turing.ml/latest/guide.html

and after a bit more than a dozen copied & pasted lines, it breaks.

p = MCMCChain.plot(c3)

leads to

ERROR: MethodError: no method matching plot(::Turing.Chain{AbstractRange{Int64}})
Closest candidates are:
  plot(::MCMCChain.AbstractChains, ::Array{Symbol,1}; args...) at C:\Users\z\.julia\packages\MCMCChain\aJ17d\src\plot.jl:227
  plot(::MCMCChain.AbstractChains, ::Symbol; args...) at C:\Users\z\.julia\packages\MCMCChain\aJ17d\src\plot.jl:233
Stacktrace:
 [1] top-level scope at none:0

What have I done wrong?

My state of Julia:

julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)

(v1.0) pkg> status
    Status `C:\Users\z\.julia\environments\v1.0\Project.toml`
  [861a8166] Combinatorics v0.7.0
  [31c24e10] Distributions v0.16.4
  [587475ba] Flux v0.6.7
  [1671dc4f] MCMCChain v0.2.0
  [f0f68f2c] PlotlyJS v0.11.1
  [91a5bcdd] Plots v0.20.2
  [92933f4c] ProgressMeter v0.6.0
  [2913bbd2] StatsBase v0.25.0
  [fce5fe82] Turing v0.5.0
  [37e2e46d] LinearAlgebra

Thank you, and kind greetings,

z.

**Comment by trappmartin** [comment]
Closing in favour of issue #563.

**Comment by zenon** [comment]
Thank you. StatPlots it is, then?

Installed it, and a window opened with the title bar "GKS QtTerm", and completely white. While in the shell I got the following message:

julia> plot(c3)
┌ Warning: No strict ticks found
└ @ PlotUtils C:\Users\z\.julia\packages\PlotUtils\qtCfE\src\ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils C:\Users\z\.julia\packages\PlotUtils\qtCfE\src\ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
┌ Warning: No strict ticks found
└ @ PlotUtils C:\Users\z\.julia\packages\PlotUtils\qtCfE\src\ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW

**Comment by trappmartin** [comment]
Did the `savefig` create the png file? 
As long as there are only warning messages, which they are, and if the png was created I would not be too concerned about it.

If you have problems with the plotting it's probably best to raise an issue on JuliaPlots/Plots.jl or JuliaPlots/StatPlots.jl as `MCMCChains` only defines recipes for the plotting and does not implement the core routines.

**Comment by zenon** [comment]
Ah, okay. Indeed, it did.

Note, in case anyone arrives at the same point: Adding a plotly() before the plot(c3) produces a picture immediatedly (in the browser), without the confusing empty window; yet then savefig(..) doesn't do.

Thank you Martin!
