### ISSUE TITLE
Guide on http://turing.ml/latest/guide.html is broken

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#563]
Currently, the example code on http://turing.ml/latest/guide.html is incorrect. See issue #562 for the correct code.

@cpfiffer could you have a look at this, please?

**Comment by cpfiffer** [comment]
Absolutely, probably should have caught this when the last changes to `MCMCChain` came through.

**Comment by cpfiffer** [comment]
Updated. I'll go through the rest of the documentation to make sure the `MCMCChain` stuff is current.

**Comment by trappmartin** [comment]
Thanks a lot!
