### ISSUE TITLE
Resume interface

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#566]
Currently, we have two different ways to resume a sampling process.
```julia
@model gdemo(x) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0, sqrt(s))
  x[1] ~ Normal(m, sqrt(s))
  x[2] ~ Normal(m, sqrt(s))
  return s, m
end
chn1 = sample(gdemo([1.5, 2.0]), sampler; save_state=true)

# version 1
resume(chn1, 1000)

# version 2
sample(gdemo([1.5, 2.0]), sampler; resume_from=chn1)
```
where the `resume` function is basically an alias for the second version. 

One drawback of the current approach is that we need to store the `model function`, `sampler` and further information inside the Chains type.
https://github.com/TuringLang/Turing.jl/blob/27b0933b917f2fce389f2f60190b716c52aa0785/src/utilities/io.jl#L203-L207

From my point of view, resuming a sampling process should no restrict the user to a particular sampler but rather to a class of samplers. If I understand the HMC code on this correctly, we currently discard the selected HMC algorithm if we resume a sampling.
https://github.com/TuringLang/Turing.jl/blob/27b0933b917f2fce389f2f60190b716c52aa0785/src/samplers/hmc.jl#L109-L111

**Question 1**: Would it be better to store only the type of the sampler or do we want to keep the sampler as a whole and instead adjust the code base so that we do not discard the user specified algorithm? Keeping the sampler would have the advantage that we can resume with exactly the same parameters.

**Question 2**: Is there a way that we can drop the VarInfo instance? Many fields can be recovered from the Chains type while others, e.g. https://github.com/TuringLang/Turing.jl/blob/414b3b068219ae1c6d5c5958f0f9fd4a0d5429eb/src/core/varinfo.jl#L51-L53 are not recoverable unless we adjust the Chains type. I feel we should think about a refactoring of this.

cc: @yebai @xukai92

**Comment by yebai** [comment]
Closed by #793
