### ISSUE TITLE
`docs` folder structure

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#569]
The current `docs` folder mixes `template` and actual doc contents together. Perhaps we can re-organise a bit, e.g. in the following way

```
docs/ 
docs/markdown # Storing all doc contents including landing page 
docs/template  # Storing all Jekyll template related files
```

This would remove/rename the following folders

- `docs/homepage`: split into `docs/markdown` and `docs/template`
- `docs/src`: redundant with `docs/homepage/_docs` and `docs/homepage/_tutorials`

EDIT:

- We should probably add a `readme` file in the `docs` folder, with some instructions on how to build and serve the docs locally. 
- perhaps: rename `homepage` ==> `site`

**Comment by yebai** [comment]
> I'm hesitant to split the docs/homepage directory up because it introduces a lot of moving parts. The current way the folder is structured, the webpage can be built locally from the master branch without any fuss. If we broke it into docs/markdown and docs/template anyone making local changes to test anything out would have a bad time.

Ah, I see. 

> You could even make a good argument that we should add docs/homepage/_tutorials and docs/homepage/_docs to the .gitignore as it's all meant to be built and immediately upload to gh-pages, but that would make it slightly harder to immediately serve the site locally. Thoughts on that?

I guess we can add these files to `.gitignore` and then write down the exact instructions on how to build and serve the site locally in a `README` file.

**Comment by cpfiffer** [comment]
I'll add a README to the `docs/homepage` directory so it's easier to build for everyone.
