### ISSUE TITLE
Add assertions to compiler

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#575]
We should add assertions to the compiler code to be able to throw useful errors in case of errors in the model definition.

- Add assertion if right-hand side of ~ is not a distribution or vector of distributions.
- ~Add assertion if right-hand side of = is a distribution.~ <- Note sure this would be a problem.

**Comment by mohamed82008** [comment]
Typo: first `left-hand` -> `right-hand`.

**Comment by trappmartin** [comment]
Closing because of PR #585
