### ISSUE TITLE
Typo in 2nd menu of turing.ml

### ISSUE THREAD

**Issue by tlienart** [TuringLang/Turing.jl#581]
Apologies for raising a trivial issue (and maybe not the best spot for it but it's a quick fix so shouldn't matter too much).

![screen shot 2018-10-09 at 7 16 12 pm](https://user-images.githubusercontent.com/10897531/46655606-d4105180-cbf7-11e8-85c6-aa373378dcf2.png)

"Documenation" -> "Documentation"

**Comment by cpfiffer** [comment]
Should be fixed with 9a42a065 in the next half hour or so. Thanks for informing me!
