### ISSUE TITLE
Pass number of parallel chains as an argument

### ISSUE THREAD

**Issue by fisherc2** [TuringLang/Turing.jl#582]
Hi-

I would like to make a feature request based on a discussion on [discourse](https://discourse.julialang.org/t/learning-bayesian-data-analysis-using-julia/5370/18). In many MCMC packages (e.g. Mamba.jl, Stan, PyMC3), it is possible to specify the number of parallel chains as an argument for the sampling function. Having this capability is very convenient, as it is terse and does not require the user to create as much boilerplate code and to figure out how to put the results in the Chain object via `@distributed` or `pmap` for post processing. 

Thank you for considering this feature request.

**Comment by colehurwitz31** [comment]
+1

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/698
