### ISSUE TITLE
Simple correlation example

### ISSUE THREAD

**Issue by DominiqueMakowski** [TuringLang/Turing.jl#593]
While I use Bayesian analyses in my everyday work since quite a while now, I still mostly rely on high-level fitting packages (such as rstanarm). I recently decided to dive into the manual specification of models. I decided to start from scratch, with a basic correlation, and I found this [great blogpost](https://baezortega.github.io/2018/05/28/robust-correlation/) explaining the technical, but also the theoretical bits, which was very helpful for my understanding of the different aspects and thinking behind Bayesian models.

As I am not familiar with stan, I would like to "adapt" this in Turing. Provided that someone would help me correctly and efficiently (the julian/turing way) specify the model below, I could try implementing a nice post for the [tutorial repo](https://github.com/TuringLang/TuringTutorials) if you're interested 😃 

```stan
data {
    int<lower=1> N;  // number of observations
    vector[2] x[N];  // input data: rows are observations, columns are the two variables
}

parameters {
    vector[2] mu;                 // locations of the marginal t distributions
    real<lower=0> sigma[2];       // scales of the marginal t distributions
    real<lower=1> nu;             // degrees of freedom of the marginal t distributions
    real<lower=-1, upper=1> rho;  // correlation coefficient
}

transformed parameters {
    // Covariance matrix
    cov_matrix[2] cov = [[      sigma[1] ^ 2       , sigma[1] * sigma[2] * rho],
                         [sigma[1] * sigma[2] * rho,       sigma[2] ^ 2       ]];
}

model {
  // Likelihood
  // Bivariate Student's t-distribution instead of normal for robustness
  x ~ multi_student_t(nu, mu, cov);
    
  // Noninformative priors on all parameters
  sigma ~ normal(0,100);
  mu ~ normal(0, 100);
  nu ~ gamma(2, 0.1);
}

generated quantities {
  // Random samples from the estimated bivariate t-distribution (for assessment of fit)
  vector[2] x_rand;
  x_rand = multi_student_t_rng(nu, mu, cov);
}
```

**Comment by cpfiffer** [comment]
I think we'd enjoy having a write-up to post!

When I get a moment to sit down and look at this I'll provide the specifications for the model. Unless one of the other Turing people beat me to it.

**Comment by cpfiffer** [comment]
@DominiqueMakowski I've added a model specification at the bottom of this post, hope it helps.

As a side note to any of the other Turing people, could you take a look at this? I had a little trouble getting this to get closer to the actual covariance matrix.

Here's the actual covariance:
```
2×2 Array{Float64,2}:
 1.01824    5.35655
 5.35655  108.08
```

Here's what I calculate after taking the mean parameters:
```
2×2 Array{Float64,2}:
 1.21787   4.41931
 4.41931  73.0534
```

Here's the model specification. There is some extra stuff at the bottom for extracting parameter observations and comparing covariance matrices.

```julia
using Turing, Random

Random.seed!(1)

# Specify Turing model.
@model correlation(x, N) = begin
    # Create mu variables.
    mu = TArray{Any}(2)
    mu[1] ~ Normal(0, 100)
    mu[2] ~ Normal(0, 100)

    # Create sigma variables.
    sigma = TArray{Any}(2)
    sigma[1] ~ Normal(0, 100)
    sigma[2] ~ Normal(0, 100)

    # Create rho.
    rho ~ Beta(1, 1)

    # Generate covariance matrix.
    p = sigma[1]*sigma[2]*rho
    cov = [sigma[1]^2 p;
            p sigma[2]^2]

    # Iterate through each datapoint, and observe its likelihood.
    for i in 1:N
        x[i,:] ~ MvNormal([mu[1], mu[2]], cov)
    end
end

# Helper function to generate a covariance matrix.
function tcovar(sigma, rho)
    p = sigma[1]*sigma[2]*rho
    return [sigma[1]^2 p;
            p sigma[2]^2]
end

# Number of datapoints to generate.
N = 100

# Target covariance matrix.
target_covariance = tcovar([1, 10], 0.5)

# Generate random data.
target_dist = MvNormal([0.0, 0.0], target_covariance)
df = rand(target_dist, N)'

# Sample using Metropolis-Hastings.
chain = sample(correlation(df, N), MH(10000))

# Extract our sigma and rho variables.
sig = hcat(chain[:sigma]...)'
rho = chain[:rho]

_, maxlp = findmax(chain[:lp])

# Calculate the covariance matrix using the average
# sigma and rho.
co = tcovar(mean(sig, dims=1), mean(rho))

# Print the covariance matrix we calculated.
display(co)

# Print the observed covariance matrix.
display(cov(df))
```

**Comment by cpfiffer** [comment]
@DominiqueMakowski I have made a couple of changes to the model I gave you above to increase performance and accuracy.

Here's a summary of the changes:

1. I've used the `Truncated` version of distributions to force the parameters to have bounds. Previously, `sigma` and `mu` used regular `Normal` distributions, which meant they were pretty much free to take on any value. The `Truncated` versions apply bounds to sampled values and allow the sampler to converge better.
2. The sampler is now `HMC` ([Hamiltonian Monte Carlo](http://turing.ml/docs/library/#Turing.HMC)) and not `MH` ([Metropolis-Hastings](http://turing.ml/docs/library/#Turing.MH)). 
3. I changed the automatic differentiation mode to `forward_diff`, which is more performant for the moment.
4. Because we're now using `forward_diff` and things run quicker, I've also increased the sample size to 1,000. The covariance matrix now converges far closer to the actual model.

Let us know if we can be of further help!

```julia
using Turing, Random

Random.seed!(1)

# Specify Turing model.
@model correlation(x, N) = begin
    # Create mu variables.
    mu = TArray{Any}(2)
    mu[1] ~ TruncatedNormal(0, 100, -10, 10)
    mu[2] ~ TruncatedNormal(0, 100, -10, 10)

    # Create sigma variables.
    sigma = TArray{Any}(2)
    sigma[1] ~ TruncatedNormal(0, 100, 0, 10)
    sigma[2] ~ TruncatedNormal(0, 100, 0, 10)

    # Create rho.
    rho ~ Truncated(Uniform(-1, 1), -1, 1)

    # Generate covariance matrix.
    p = sigma[1]*sigma[2]*rho
    cov = [sigma[1]^2 p;
            p sigma[2]^2]

    # Iterate through each datapoint, and observe its likelihood.
    for i in 1:N
        x[i,:] ~ MvNormal([mu[1], mu[2]], cov)
    end
end

# Helper function to generate a covariance matrix.
function tcovar(sigma, rho)
    p = sigma[1]*sigma[2]*rho
    return [sigma[1]^2 p;
            p sigma[2]^2]
end

# Number of datapoints to generate.
N = 1000

# Target covariance matrix.
target_covariance = tcovar([1, 10], 0.5)

# Generate random data.
target_dist = MvNormal([0.0, 0.0], target_covariance)
df = rand(target_dist, N)'

# Use forward differentiation.
Turing.setadbackend(:forward_diff)

# Sample using HMC.
chain = sample(correlation(df, N), HMC(1000, 0.01, 5))

# Extract our sigma and rho variables.
sig = hcat(chain[:sigma]...)'
rho = chain[:rho]

# Calculate the covariance matrix using the average
# sigma and rho.
co = tcovar(mean(sig, dims=1), mean(rho))

# Print the covariance matrix we calculated.
display(co)

# Print the observed covariance matrix.
display(cov(df))
```

**Comment by DominiqueMakowski** [comment]
@cpfiffer Many thanks!! I will have a look, try to familiarize with it and will try to start writing the tuto 😃

**Comment by yebai** [comment]
I'm closing this issue for now. Please re-open if you have any further questions.
