### ISSUE TITLE
Improve Docstrings

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#609]
Many of the inline documentation strings for the samplers are extremely bare bones and often unhelpful outside of the basics of argument location. Browsing through the [samplers section](http://turing.ml/docs/library/#samplers) of the website (which mirrors the current docstrings in the codebase) might not be all that helpful to some people.

It might be a good idea to expand the docstrings to provide a little more guidance on the following:

- The meaning of arguments -- what do they actually do? 
- Are there common pitfalls or helpful tips we can include for specific samplers? A good example that comes to mind is just including a line stating that gradient issues with `HMC` might be solved by setting a smaller `epsilon` parameter.

Any other goals for docstrings would be helpful, so throw them in if you've got them.

This came up in the [Slack channel](https://julialang.slack.com/messages/turing/):

> Richard Torkar: @kai When I do `?NUTS` it doesn’t describe the function much, is there other documentation I’m missing?

> @xukai92: Sorry that our inline documentation is not well-written. @cpfiffer do we have a plan to improve these type of documentation? Maybe we should have a single page to explain all the parameters for sampling algorithms.

Additional thoughts welcome. I don't know how much help I can be discussing the technical details of the samplers, but I can definitely include some tips and tricks I've picked up.

**Comment by yebai** [comment]
Fixed by #618.
