### ISSUE TITLE
Sample from prior when the input is `missing` or `Vector{Missing}`.

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Turing.jl#644]
Currently, when a missing scalar data is `nothing`, it is sampled from prior. Supporting `missing` also makes sense. For vectors, a `Vector{Missing}` input can be changed to `Vector{Real}` of the same length and then treated as a parameter. Both of these currently don't work properly, so this is not a breaking change. Opinions?

**Comment by mohamed82008** [comment]
In the future, after #637 is merged, we can change `Real` to a compile-time version of `eltype(vi[spl])` which should have a better performance.

**Comment by yebai** [comment]
I second @cpfiffer's proposal, using something like

```julia
sample( gdemo(Vector{Missing}(undef, 30)) )
```

leads to a consistent solution for passing in `missing` data without requiring a model redefinition for different data sizes and dimensions.
