### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by willtebbutt** [TuringLang/Turing.jl#645]
Following from a discussion on slack:

I suggested that we should consider implementing some of the integration tests in [this paper](https://arxiv.org/abs/1412.5218)

@mlomeli1 recommended looking at [this](https://www.jstor.org/stable/27590449?seq=1#metadata_info_tab_contents) for directions for implementing significance tests such that the Geweke tests can be fully automated in our testing pipeline.

@xukai92 pointed out that we have some [legacy code](https://github.com/TuringLang/TuringBenchmarks/blob/master/benchmarks/gdemo-geweke.run.jl) that does some Geweke tests

(I've not had time to look through either @mlomeli1 or @xukai92 suggestions, I'm just posting this here so that it doesn't get lost)

**Comment by willtebbutt** [comment]
@yebai kindly pointed me towards [the paper](https://www.minneapolisfed.org/research/SR/SR148.pdf) where the Geweke tests are introduced:

**Comment by yebai** [comment]
Closing because the tests in Turing got many improvements. Happy to revisit in the future if needed.
