### ISSUE TITLE
Upper bounding step size to 1.0 for stability

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#659]
In https://github.com/TuringLang/Turing.jl/pull/621 I added code to set an upper bound for the step size (https://github.com/TuringLang/Turing.jl/blob/89e012567774e2c4c749ce47646cc85be918a6e4/src/samplers/adapt/stepsize.jl#L97).

We would like to either formally justify this upper bounding or remove it when other stability issues is resoled.

**Comment by yebai** [comment]
Fixed by #709
