### ISSUE TITLE
is NegativeBinomial AD supported?

### ISSUE THREAD

**Issue by staples6** [TuringLang/Turing.jl#661]
```julia
using Turing

@model mymod(y, r) = begin
    p ~ Beta(2, 1)
    y ~ NegativeBinomial(r, p)
end

chn = sample(mymod(2,5), NUTS(1000, 200, .75))
```
I get the following error

MethodError: no method matching unsafe_convert(::Type{Float64}, ::ForwardDiff.Dual{Nothing,Float64,1})

Is it expected to draw from Gamma and Poisson in order to produce a NegativeBinomial?

**Comment by mohamed82008** [comment]
Seems to be a `StatsFuns` `ccall` problem. I think this needs another AD workaround like #601 and #616 .

**Comment by staples6** [comment]
thanks for the quick resolution!
