### ISSUE TITLE
Method Error when trying to estimate degree of freedom with TDist

### ISSUE THREAD

**Issue by LukasUlrych** [TuringLang/Turing.jl#673]
Hi,
the following code throws an error (on Julia 1.0.3)

`using Turing
y = rand(TDist(4),100)
@model est_TD(y) = begin
    nu ~ LogNormal(0,2)
    [y[i] ~ TDist(nu) for i = 1:length(y)]
end
out_HMC = sample(est_TD(y),HMC(500,1e-4,5))`

It seems that it has something to do with differentiation. Is there something wrong with trying to estimate the degree of freedom from the data? Has anyone encountered this before and/or found some workaround?

I will be thankful for any help

**Comment by mohamed82008** [comment]
Looks like another one of #661. Requires a fix like #664.

**Comment by mohamed82008** [comment]
A bit of context: `StatsFuns.jl` uses `ccall` to find the `logpdf` of a number of distributions. `ccall` doesn't support AD, so it needs to be worked around.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/674
