### ISSUE TITLE
Make sure all distributions support AD where possible

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Turing.jl#674]
The following link shows the list of distributions that `StatsFuns` uses `ccall` for: https://github.com/JuliaStats/StatsFuns.jl/blob/7473d0d8f7c5b2f4a53f0625ada5f2323c84ffe4/src/rmath.jl#L99. We should make AD workarounds for all of these.

Supersedes #673

**Comment by xukai92** [comment]
There are some distributions in this list which already have callback functions, e.g. `beta` (https://github.com/JuliaStats/StatsFuns.jl/blob/7473d0d8f7c5b2f4a53f0625ada5f2323c84ffe4/src/distrs/beta.jl). I actually implemented those in StatsFun for the AD purpose in Turing so I'm happy to work on this issue on the StatsFuns side (they gave quite good review on numerical stability).

I think you also implemented some on the Turing side, e.g. https://github.com/TuringLang/Turing.jl/pull/664/files. Maybe we should port them to StatsFuns (and DiffRules) as well. How do you think?

**Comment by mohamed82008** [comment]
@xukai92  Yes, `StatsFuns` or `DiffRules` with `StatsFuns` in a `require` block are the more stable solutions here (no type piracy).

**Comment by yebai** [comment]
Here is the ful list of distributions that requires  special treatments for AD: 
- [ ] beta beta α β
- [ ]  binom binom n p
- [ ] chisq chisq k
- [ ] fdist d1 d2
- [ ] gamma gamma α β
- [ ] hyper hyper ms mf n
- [ ] norm norm μ σ
- [ ] nbinom nbinom r p
- [ ] pois pois λ
- [ ] t tdist k
- [ ] nbeta nbeta α β λ
- [ ] nchisq nchisq k λ
- [ ] nf nfdist k1 k2 λ
- [ ] nt ntdist k λ

**Comment by xukai92** [comment]
We also need to test both forward and reverse mode (different AD implementation). And vector operations (different in bijection mapping) for all.

**Comment by yebai** [comment]
Currently, the following distributions need a generic Julia implementation for `logpdf`, 

- [ ] nbinom nbinom r p #664
- [ ] nbeta nbeta α β λ
- [ ] nchisq nchisq k λ
- [ ] nfdist k1 k2 λ
- [ ] ntdist k λ

This can be done in a similar way to JuliaStats/StatsFuns.jl#21, or #664. We should also consider moving the hotfixes for `pois`, `nbinom` and `binom` into `StatsFuns.jl/src/distrs/`.

**Comment by yebai** [comment]
It seems that the only distributions from `Distributions.jl` without `FluxAD` support are

- `MvNormal` https://github.com/TuringLang/Turing.jl/issues/717
- `UniveriateGMM` https://github.com/TuringLang/Turing.jl/issues/722

**Comment by mohamed82008** [comment]
This seems to be fixed now. I will close the issue.
