### ISSUE TITLE
unexpected renaming of a continuous prior: "p" -> "pAny"

### ISSUE THREAD

**Issue by mkarikom** [TuringLang/Turing.jl#684]
I'm assuming this a feature, not a bug, but I don't know what the motivation is and wondering if there is diagnostic information being offered.  In the following model, there are only two priors: p and z.  The a_0 dimensional (4 in the case of the used data) Dirichlet p is the only continuous one.

    @model SBM_Pi_Z(Y, B) =
    begin
       N = size(Y)[1]
       C = size(B)[1]
        # specify a write on copy array for the categorical, safe for particle gibbs
        z = tzeros(Int, N)
        p = Array{Float64}(undef, N, C)
    
        # define the dirichlet prior (use the same alpha for all C)
        for i = 1:N
            p[i,:] ~ Dirichlet(a₀)
        end
    
        # define the cluster prior (categorical)
        for i = 1:N
            z[i] ~ Categorical(p[i,:])
        end
    
        # define the likelihood (Bernoulli)
        for j = 1:N
            for k = 1:N
                Y[j,k] ~ Bernoulli(B[z[j],z[k]])
            end
        end
    
        # return the prior
        return(z, p)
    end
    
    SBM = SBM_Pi_Z(Y = Y, B = B₀)
    fit = sample(SBM, PG(20, 5000))
    @save "fit1m-pz.jld2" fit
    

Looking at a few sample lines from output of describe(fit), and noticed that p had changed names. 
 Also I'm **really sorry in advance for the mess**, I tried round(fit[:pAny], 3), and googling for anything remotely similar to Matlab format(), and this seems to be rather a can of worms at the moment, one problem at a time I guess...

    Quantiles:
                                          2.5%                           25.0%                     50.0%                     75.0%                 
    97.5%      
               z[12] 1.00000000000000000000000000000000000 4.00000000000000000000000 4.00000000000000000000000 4.00000000000000000000000 4.000000000000000
               z[8] 2.00000000000000000000000000000000000 2.00000000000000000000000 2.00000000000000000000000 2.00000000000000000000000 3.000000000000000
               pAny[5, Colon[]][1] 0.00000000027148504776898732042439781 0.00000000027148504776899 0.00000000027148504776899 0.00000000027148504776899 0.019209769673527
               pAny[5, Colon[]][2] 0.00000000000000018185054905415603225 0.04846837427912770862592 0.04846837427912770862592 0.04846837427912770862592 0.048468374279128

**Comment by mohamed82008** [comment]
This looks like a bug to me. I will look into it.

**Comment by mohamed82008** [comment]
@mkarikom This example doesn't run. Please post an example that I can copy and paste into REPL. It seems that a0 is not defined.

**Comment by mkarikom** [comment]
> @mkarikom This example doesn't run. Please post an example that I can copy and paste into REPL. It seems that a0 is not defined.

Hi @mohamed82008 so sorry about that.  [Here is a jld file](https://drive.google.com/open?id=1tPkx5nzhCF476BFiwRWfkcPOjt75V4Zk) with test data and an update of the script where a is passed properly instead of just being globally defined....

    @model SBM_Pi_Z(Y, B, a) =
    begin
    N = size(Y)[1]
    C = size(B)[1]
    # specify a write on copy array for the categorical, safe for particle gibbs
    z = tzeros(Int, N)
    p = Array{Float64}(undef, N, C)

    # define the dirichlet prior (use the same alpha for all C)
    for i = 1:N
        p[i,:] ~ Dirichlet(a)
    end

    # define the cluster prior (categorical)
    for i = 1:N
        z[i] ~ Categorical(p[i,:])
    end

    # define the likelihood (Bernoulli)
    for j = 1:N
        for k = 1:N
            Y[j,k] ~ Bernoulli(B[z[j],z[k]])
        end
    end

    # return the prior
    return(z, p)
    end

    SBM = SBM_Pi_Z(Y = Y, B = B₀, a = a₀)
    fit = sample(SBM, PG(20, 1000))
