### ISSUE TITLE
HMC RFC: introduce a type for Hamiltonian (or not)

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#691]
The current Turing internal for HMC is pure functional. This leads to problems when pre-conditioning is used in HMC. To be more specific, the momentum variable `p` should be manipulated according to different pre-conditioning method being used, in 3 places
1. when generating the momentum
2. when computing the Hamiltonian energy
3. (in NUTS) when computing the No-U-Turn criteria
We are currently doing this by generating specific functions for these purpose depending on the conditioner type. I wonder would introducing a type for Hamiltonian would simplify the code, and still support pure functional use of the HMC internals.

**Comment by xukai92** [comment]
I'm going to start designing types for HMC by refactoring my old Turing-independent NUTS code (https://github.com/xukai92/HMC). My goal is trying to get a minimal type system for HMC that makes the main algorithm as well as the adaption easy + better unit testing. I hope this can also serve a numerical testing for the current HMC code inside Turing. Later we can either port the codes from this repo to Turing or just move the repo under TuringLang and make Turing dependent on it.

**Comment by yebai** [comment]
Closed by https://github.com/TuringLang/AdvancedHMC.jl/pull/5
