### ISSUE TITLE
Mechanism to reject samples

### ISSUE THREAD

**Issue by sdewaele** [TuringLang/Turing.jl#702]
It would be useful to have a way for a probabilistic program to reject a sample. A possible implementation is that the program throws a specific exception to signal rejection.

**Comment by sdewaele** [comment]
Just to clarify the relationship with #703: Even with safe mode 'off', the exception that would be thrown for sample rejection would not cause the sampling to fail; only to reject the sample. Anyway, perhaps the dev team will decide on a different implementation than an exception.

**Comment by xukai92** [comment]
During sampling, at least for HMC, we reject samples for which the energy is `Inf` or `NaN`. So, if you simply implement you model such that it returns `Inf` when you want to reject that sample, the inference would work correctly.

Why not exception? Simply because it is slow. But you can always catch error and return `Inf` in your model definition (or `logpdf` for customised distribution).

**Comment by mohamed82008** [comment]
One can now do `@logp() = -Inf; return` to reject a sample in #965.

**Comment by yebai** [comment]
> One can now do @logpdf() = -Inf; return to reject a sample in #965.

Might be worth to add this to the docs.

**Comment by mohamed82008** [comment]
Sure!

**Comment by sdewaele** [comment]
Thanks for implementing this!

**Comment by yiyuezhuo** [comment]
What's current way to do it? `@logpdf` have been removed in https://github.com/TuringLang/Turing.jl/commit/fa44e8b9ad3d02dbd4ae9a69d731557b7d117f1a#diff-107480759ab6311e0ad3c775750a1047

**Comment by devmotion** [comment]
The current way is
```julia
Turing.acclogp!(_varinfo, -Inf)
```
which uses the internal variable `_varinfo`. In upcoming Turing versions you should use
```julia
@addlogprob!(-Inf)
```
instead (see https://github.com/TuringLang/DynamicPPL.jl/pull/143 and the issue linked therein).

**Comment by devmotion** [comment]
Closed by https://github.com/TuringLang/Turing.jl/pull/1391.
