### ISSUE TITLE
Option to reject samples that cause errors

### ISSUE THREAD

**Issue by sdewaele** [TuringLang/Turing.jl#703]
In certain circumstances a correctly written probabilistic program can cause errors due to numerical errors in the computation as the parameter space is explored. For example, rounding errors may cause a negative value for the σ of a normal distribution. For this purpose, it would be useful to have the option to have the sampler reject this sample, instead of raising and exception. For example, this could be implemented as a `safe` option in `sample`.

**Comment by xukai92** [comment]
You can achieve this by defining custom distributions, e.g.

```julia
struct SafeNormal <: ContinuousUnivariateDistribution
   mu
   sig
end

function Distributions.logpdf{T<:Real}(d::SafeNormal, x::T)
   try logpdf(Normal(mu, sig))
   catch
    Inf
   end
end
```

The sampler will reject samples with `Inf` log-joint automatically. 

We don't handle this due to performance reason, i.e. try-catch would be slow.

**Comment by xukai92** [comment]
@sdewaele You may look for this https://github.com/mlubin/NaNMath.jl

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/702
