### ISSUE TITLE
Remove sample storage from Chains

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#724]
Currently, we store samples in two places. One is in the `chn.value` field of a `Chains` object, and the other is in `chn.info.samples`. This is a legacy of the older Turing specific `Chain` object that should probably be removed sometime before v0.7.

Two requirements:

1. When the internal samples array is unwrapped into a chain, the sample weights need to be stored as their own internal parameter. 
2. A new function `_make_samples(c::MCMCChains.Chains)` needs to be added, which would return a `Array{Samples}` object for use in resuming sampling.

I'll work on this sometime soon, but right now I thought I'd add an issue to remind me to do this.

**Comment by yebai** [comment]
@cpfiffer Is this fixed by #793?

**Comment by cpfiffer** [comment]
Yes, the new interface removed the need for this and I deleted the useless code.
