### ISSUE TITLE
turing.ml website 'not secure', e.g. https is not yet enabled

### ISSUE THREAD

**Issue by jlewis91** [TuringLang/Turing.jl#733]
Hey! Just a quick note (and thank you for the great documentation)!

Fix: https://github.blog/2018-05-01-github-pages-custom-domains-https/ to switch on https.

<img width="580" alt="Screen Shot 2019-03-27 at 21 24 54" src="https://user-images.githubusercontent.com/4462211/55109791-e8c5a080-50d6-11e9-8a89-b220b99f19a3.png">

**Comment by yebai** [comment]
This should be fixed now. It might take 24 hours before the new setting took effect.
