### ISSUE TITLE
Why is standard deviation parameterized as σ² in the logistic regression?

### ISSUE THREAD

**Issue by jlewis91** [TuringLang/Turing.jl#736]
See: http://turing.ml/tutorials/2-logisticregression/

```
σ² is the standard deviation we want to assume for our priors.
```

Probably a beginner's question, but shouldn't this be `σ`?

**Comment by trappmartin** [comment]
I think this is a mistake, it should probably be `\sigma` and not `\sigma^2`. cc: @cpfiffer

**Comment by trappmartin** [comment]
However, it doesn't change the predictions in this case as `σ² = 1` in the example. That was lucky. :)

**Comment by jlewis91** [comment]
Great. Thanks. Will submit a PR.
