### ISSUE TITLE
Dirichlet priors ignored on initialisation?

### ISSUE THREAD

**Issue by mmattocks** [TuringLang/Turing.jl#738]
I've become very confused by the behaviour of the Tutorial 4 model. It seemed to me that the Dirichlet priors on the transition state matrix were being ignored. I wasn't too sure whether this could be attributed to the random seed or the supplied sequence. It seemed like the values for T[3][3] were consistently way too low for an uniformative prior. Therefore I tried to check whether I could produce meaningfully different distributions for the initial sample of T[3][3] from the Dirichlet prior, given many different random seeds and an input sequence y drawn from the same prior. I used this code:

```
# Load libraries.
using Turing, Plots, Random
# Set a random seed and use the forward_diff AD mode.
Turing.setadbackend(:forward_diff);

# Turing model definition.
@model BayesHmm(y, K, prior) = begin
    # Get observation length.
    N = length(y)

    # State sequence.
    s = tzeros(Int, N)

    # Emission matrix.
    m = Vector{Real}(undef, K)

    # Transition matrix.
    T = Vector{Vector}(undef, K)

    # Assign distributions to each element
    # of the transition matrix and the
    # emission matrix.
    for i = 1:K
        T[i] ~ Dirichlet(prior)
        m[i] ~ Normal(i, 0.5)
    end

    # Observe each point of the input.
    s[1] ~ Categorical(K)
    y[1] ~ Normal(m[s[1]], 0.1)

    for i = 2:N
        s[i] ~ Categorical(T[s[i-1]])
        y[i] ~ Normal(m[s[i]], 0.1)
    end
end;

function t33_initial_sampler(prior, K)
    initial_T33 = Array{Float64}(undef,1000)
    for i in 1:1000
        Random.seed!(i)

        y = Array{Int}(undef,15)
        for i in 1:length(y)
            y[i] = rand(Categorical(rand(Dirichlet(prior))))
        end

        g = Gibbs(1, HMC(2, 0.001, 7, :m, :T), PG(20, 1, :s))
        c = sample(BayesHmm(y, K, prior), g);
        initial_T33[i] = get(c, :T).T[9][1]
    end
    return initial_T33
end

# Define the emission parameter.
K = 3;
uninformative_T_prior = ones(K)/K
three_bias_T_prior = [.1,.1,100]

uninformative_T33 = t33_initial_sampler(uninformative_T_prior, K)
three_bias_T33 = t33_initial_sampler(three_bias_T_prior, K)

using StatsPlots
histogram(uninformative_T33)
histogram(three_bias_T33)
```

It seems to me that if the prior and the generative model are both uninformative, a sample of first-iterate T[3][3] should be evenly distributed across 0-1, whereas the T3-biased prior and generative model should give high values for T[3][3]. Both produce similar distributions centered around ~.06 or so. Am I misunderstanding something about the way priors should work in this model? It seems like the chain wants to start the transition matrix from the same sorts of values no matter what.

![dist](https://user-images.githubusercontent.com/28366182/55192262-6ee6f300-517a-11e9-8cc8-a01e34422ac4.png)

**Comment by yebai** [comment]
This might be because the `HMC` sampler will always initialise continuous parameters (including Dirichlet) from a uniform distribution. This was meant to provide a robust initialization for HMC. 

The code can be found here: https://github.com/TuringLang/Turing.jl/blob/master/src/utilities/robustinit.jl#L2

You can run a different sampler in order to disable this behavior from HMC, for example

```julia
 c = sample(BayesHmm(y, K, prior), PG(10, 100));
```

**Comment by mmattocks** [comment]
I saw that code, but if that's so, shouldn't the distribution of initial samples for any Dirichlet parameter be uniformly distributed? I don't understand why the matrix would be initialised in such a way that the third state's persistence is always disfavoured even if it's drawn from a uniform prior, if you see what I mean.

I coded another, different, model and found that even with a different # of states and 1st-order dependency in output, the sampler still always seemed to favour low state values and disfavour higher ones for the transition matrix. It's strange because the underlying Distributions.jl structs seem to be working fine with rand etc.

**Comment by yebai** [comment]
These parameters initialised from a uniform are in the transformed space.  When converted back to the constrained space, they will be biased towards lower indexes. Turing's transform for simplex distribution is the same as Stan's, see 

https://mc-stan.org/docs/2_18/reference-manual/simplex-transform-section.html

**Comment by mmattocks** [comment]
I see, thank you for the explanation!! I obviously have some reading to do :smile:

**Comment by mmattocks** [comment]
Oh, and thank you very much for the rapid replies!
