### ISSUE TITLE
Linear Regression Example Credible Intervals

### ISSUE THREAD

**Issue by jzicker** [TuringLang/Turing.jl#751]
This goes in the help wanted category.  Can anyone share the calculation of credible intervals for the linear regression tutorial?   I want to plot the linear regression mean estimate line with upper and lower credible intervals.

**Comment by cpfiffer** [comment]
If you're using MCMCChains v0.3.7 (update if not) you can get those using `hpd(chn)`.

**Comment by cpfiffer** [comment]
I'm closing this for now. Let me know if this didn't work for you.
