### ISSUE TITLE
Increase upper bound for MCMCChains requirement

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/Turing.jl#752]
While we were troubleshooting an [issue](https://github.com/TuringLang/MCMCChains.jl/issues/88) with updating MCMCChains.jl, another person in the discussion found that the requirements listed in [Compat.toml](https://github.com/JuliaRegistries/General/blob/master/T/Turing/Compat.toml#L70) might be preventing users from updating to MCMCChains v.0.3.7.

**Comment by yebai** [comment]
@JuliaRegistrator register()
