### ISSUE TITLE
Function to add to logp within @model Turing model 

### ISSUE THREAD

**Issue by jonasmac16** [TuringLang/Turing.jl#754]
Following from a discussion on Slack #turing I am opening this issue to request the possibility  to add to `logp` of sample from within Turing model defined with the macro @model and to discuss what the best implementation would look like.

Two suggestions so far where 
1. Directly adding to the `logp` variable like this `logp += log(1.0)`
2. Having a function that handles the adding e.g.  `acclogpdf!(log(1.0))`

@trappmartin suggested the second to be potentially the better solution as it is independent of how the `logp` value is reflected internally and you don't add to an "undefined" variable like in option 1.

**Comment by mohamed82008** [comment]
@xukai92 suggested before to have some way to get the `VarInfo` inside the model. I think we can some function `__getvarinfo__()` for this purpose. So at the beginning of the model call function body generated by the macro, we can have:
```julia
__getvarinfo__() = $vi_sym
```
where `vi_sym` is the generated symbol for `vi::VarInfo`. `acclogp!` is defined for `VarInfo`.

**Comment by mohamed82008** [comment]
This is also useful for #703 where the user can use their own `try`-`catch` block or any more performant error avoidance mechanism, e.g. checking for signs of individual failure modes, and then if a failure mode is detected, `logp` can be set to `-Inf` and `return` can be called to interrupt.

**Comment by trappmartin** [comment]
> @xukai92 suggested before to have some way to get the `VarInfo` inside the model. I think we can some function `__getvarinfo__()` for this purpose. So at the beginning of the model call function body generated by the macro, we can have:
> 
> ```julia
> __getvarinfo__() = $vi_sym
> ```
> 
> where `vi_sym` is the generated symbol for `vi::VarInfo`. `acclogp!` is defined for `VarInfo`.

I was thinking about replacing `acclogp!` and every `$lp_ += ...` statement with a macro call, e.g. `@acclogp ...` which would remove the need of passing a VarInfo object. I think it would be the best if the user doesn't need to pass a VarInfo object and doesn't need to know about the `vi_sym` or similar. 

In the macro, we would still manipulate the varinfo object but without the user having to know about it.

What do you think?

**Comment by trappmartin** [comment]
> This is also useful for #703 where the user can use their own `try`-`catch` block or any more performant error avoidance mechanism, e.g. checking for signs of individual failure modes, and then if a failure mode is detected, `logp` can be set to `-Inf` and `return` can be called to interrupt.

A `@acclogp -Inf` macro call would be all we need for this case.

**Comment by mohamed82008** [comment]
Hmm, you mean `@acclogp -Inf` will be replaced in `@model` with `vi.logp += -Inf`? This also seems like a nice solution.

**Comment by mohamed82008** [comment]
#965 now provides a way to access the `VarInfo` using `@vi()` in the model.

**Comment by mohamed82008** [comment]
This was solved by #965.
