### ISSUE TITLE
Linear Regression - prediction function - error in tutorial

### ISSUE THREAD

**Issue by Pindar777** [TuringLang/Turing.jl#758]
Hi there,

I'm trying to replicate the linear regression example and get an error in the prediction function:
https://turing.ml/tutorials/5-linearregression/

The error results from using the mean function on α and β (see below):

`function prediction(chain, x)
    α = chain[:intercept][200:end]
    β = chain[:coefficients][200:end]
    return mean(α) .+ x * mean(β)
end`

I managed to modify it, but it's clumsy. Is there a better way?

`function prediction_test(chain, x)
    α = chain[:intercept][200:end]
    β = chain[:coefficients][200:end]
    return mean(α.mean) .+ x *  describe(β)[1][:mean]
end`

result (in my run Bayes loss not as good as reported in the tutorial):
    Bayes loss: 68.00979321046884
    OLS loss: 67.56037474764624
Test set:
    Bayes loss: 242.57948201282844
    OLS loss: 270.94813070761944

ERROR
`mean(β)
ERROR: MethodError: no method matching iterate(::MCMCChains.Chains{Union{Missing, Float64},Float64,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:samples, :hashedsummary),Tuple{Array{Turing.Utilities.Sample,1},Base.RefValue{Tuple{UInt64,ChainDataFrame}}}}})
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:568
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:568
  iterate(::ExponentialBackOff) at error.jl:199
  ...
Stacktrace:
 [1] mean(::typeof(identity), ::MCMCChains.Chains{Union{Missing, Float64},Float64,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:samples, :hashedsummary),Tuple{Array{Turing.Utilities.Sample,1},Base.RefValue{Tuple{UInt64,ChainDataFrame}}}}}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Statistics\src\Statistics.jl:58
 [2] mean(::MCMCChains.Chains{Union{Missing, Float64},Float64,NamedTuple{(:parameters,),Tuple{Array{String,1}}},NamedTuple{(:samples, :hashedsummary),Tuple{Array{Turing.Utilities.Sample,1},Base.RefValue{Tuple{UInt64,ChainDataFrame}}}}}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Statistics\src\Statistics.jl:42
 [3] top-level scope at `none:0``

**Comment by cpfiffer** [comment]
Currently there's not really a much better way. I'm working on some stuff for MCMCChains to reconstruct vector-valued parameters like the above to make the math dirt-simple.

Another way is the following:

```julia
# Make a prediction given an input vector.
function prediction(chain, x)
    p = get_params(chain[200:end, :, :])
    α = mean(p.intercept)
    β = collect(mean.(p.coefficients))
    return  mean(α) .+ x * β
end
```

Thanks for catching this bug and letting us know. I'm updating the site to remove this.

**Comment by Pindar777** [comment]
@cpfiffer Thanks for providing this alternative. I prefer it over my workaround since it makes use of general functions instead of harvesting descriptive statistics. 
Incorporating MCMCChains for such tasks is a good idea since in GLM only `.predict()`. is needed to get the results.

Cheers

**Comment by cpfiffer** [comment]
Closed for the moment. Thanks!
