### ISSUE TITLE
Consider a CITATION.bib file

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Turing.jl#759]
There's kind of a discussion going on in the Slack #academia channel right now about a better citation infrastructure for Julia packages. [This PR](https://github.com/JuliaLang/julia/pull/31794) suggests including a `CITATION.bib` file in the top level of the repo. What are everyone's thoughts about that?

**Comment by ViralBShah** [comment]
Bumping this. Would be great to have.
