### ISSUE TITLE
Observe vectorisation issue.

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#761]
We increase `vi.num_produce` on `observe` only for a single distribution and not during vectorisation.
Note: This is only required for Particle based samplers.

https://github.com/TuringLang/Turing.jl/blob/65371ce4d5a241f123d00e413f02080b387370b4/src/inference/Inference.jl#L182-L187

**Comment by mohamed82008** [comment]
Closed via #965.
