### ISSUE TITLE
Improve code for initialising `Sampler`

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#768]
Codes are quite inconsistent, including
- check `space`
  - sometimes we pass `model` for this purpose
- we could simplify a lot of overloading by `s::Selector=Selector()`

**Comment by mohamed82008** [comment]
See the `Turing.Inference.init_spl` function in [#660](https://github.com/TuringLang/Turing.jl/tree/mt/type_stability2/) which is relevant.

**Comment by yebai** [comment]
Duplicate of https://github.com/TuringLang/Turing.jl/issues/746
