### ISSUE TITLE
Use ModelingToolkit for frontend or IR?

### ISSUE THREAD

**Issue by datnamer** [TuringLang/Turing.jl#789]
http://juliadiffeq.org/DiffEqTutorials.jl/html/ode_extras/ModelingToolkit.html

Any thoughts on using that for turing? Seems like it could help relieve some maintenance burden and/or help with static analysis.

**Comment by yebai** [comment]
Closed by https://github.com/TuringLang/Turing.jl/pull/965, and planned work to create [DynamicPPL.jl](https://github.com/TuringLang/DynamicPPL.jl)
