### ISSUE TITLE
Documentation: Code error in Guide

### ISSUE THREAD

**Issue by zenon** [TuringLang/Turing.jl#795]
In https://turing.ml/docs/guide/ I found some issues:

"Note that the key (:var_1) should be a symbol. For example, to fetch x[1], one would need to do chn[Symbol(:x[1])." 

However, Symbol(:x[1]) doesn't work. Symbol("x[1]") works, but I can't judge whether it does the right thing.

Lower on the same page:

    xs = generated[:x]
    xs[15]

The latter line doesn't work:

ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [1]

There I'm still stuck.

**Comment by zenon** [comment]
Thank you!

**Comment by cpfiffer** [comment]
Closed by #797.

**Comment by cpfiffer** [comment]
Also @zenon, let me know if the updates to the guide didn't help. I'm happy to add a bit more to explain whatever's not clear.
