### ISSUE TITLE
Juno Progress Metres

### ISSUE THREAD

**Issue by MikeInnes** [TuringLang/Turing.jl#799]
Turing's HMC sampler currently logs its progress in the terminal. While this is nice in a pure REPL, inside Juno it'd be even better to use the progress API. This has a number of nice features, including a built in ETA, as well as being able to work well with nested progress metres (e.g. in deep learning we have progress for both individual epochs and the overall training).

**Comment by willtebbutt** [comment]
When you say the `Progress API`, are you referring to `ProgressMeters`, or something else?

**Comment by yebai** [comment]
https://docs.junolab.org/latest/man/juno_frontend/#Progress-Meters-1

**Comment by cpfiffer** [comment]
How does this work outside Juno? Couldn't quite tell from the link.

**Comment by MikeInnes** [comment]
Currently it does nothing outside of Juno, so you'd want to keep the current behaviour depending on whether Juno is active.

**Comment by cpfiffer** [comment]
Ah, okay. I think it's pretty cool, might be worth building into the sampling API for #746 once the bulk of the work is done there. It'll get rid of a lot of replicated code and help integrate us a bit better with the IDE ecosystem, however slightly.

**Comment by yebai** [comment]
@MikeInnes Does progress API work for Jupyter notebooks?

**Comment by devmotion** [comment]
Usually I don't work with notebooks so I can't say anything about the progress API support in that setting, but in general it seems it would be nice to make use of https://github.com/JunoLab/ProgressLogging.jl. With Juno one gets a nice progress bar, and on the REPL one could get the current `ProgressmMeter` output with the https://github.com/tkf/ConsoleProgressMonitor.jl backend. I used that combination successfully in a project some weeks ago.

**Comment by devmotion** [comment]
This was solved by https://github.com/TuringLang/Turing.jl/pull/1134.
