### ISSUE TITLE
Extracting `docs` from a closed PR

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#805]
It seems that we have some `doc` updates in the following PR (which is closed in favour of a newer PR). Can we extract these doc updates into a separate PR?

https://github.com/TuringLang/Turing.jl/pull/749

**Comment by mohamed82008** [comment]
On it.

**Comment by mohamed82008** [comment]
All the doc changes from that PR seem to be already there. I am not sure what changes you are referring to.

**Comment by yebai** [comment]
Hmm, the docs are already updated by https://github.com/TuringLang/Turing.jl/pull/757/files. Sorry for the confusion!
