### ISSUE TITLE
Documentation Search always(?) leads to 404

### ISSUE THREAD

**Issue by alecloudenback** [TuringLang/Turing.jl#806]
Whenever you click on a result that appears in the search box on the documentation site, the URL leads to a 404.

Steps to reproduce:
1. Go to: [https://turing.ml/docs/](https://turing.ml/docs/)
2. Click on search icon in top right.
3. Enter query, e.g. `linear`
4. Click on result, e.g. `Linear Regression`
5. Get taken to a page with `404` error.

**Comment by alecloudenback** [comment]
#808 seems to have fixed the issue, thanks!

**Comment by cpfiffer** [comment]
Thanks for catching this!
