### ISSUE TITLE
Jeffreys Priors

### ISSUE THREAD

**Issue by bhgomes** [TuringLang/Turing.jl#813]
I believe it would be very useful to be able to mechanically compute [Jeffreys Priors](https://en.wikipedia.org/wiki/Jeffreys_prior) for the likelihood distributions in our priors. Here's an example of the functionality:

```julia
@model example(x) = begin
    σ² ~ InverseGamma(2, 3)
    μ ~ Jeffreys()
    for i in eachindex(x)
        x[i] ~ Normal(μ, √σ²)
    end
end
```

This is related to #812 since many Jeffreys Priors are improper.

**Comment by yebai** [comment]
@bhgomes Thanks for raising the discussion. Can you try to create a PR for this (if it does not require a lot of time)? We are considering adding a `contrib/distributions/` folder to `Turing` so that user-implemented features can be added after some peer review.

**Comment by yebai** [comment]
I think this is better implemented from the user-side by following Distributions API.
