### ISSUE TITLE
Hack to get strictly typed Duals?

### ISSUE THREAD

**Issue by ChrisRackauckas** [TuringLang/Turing.jl#818]
```julia
  @model bif(x) = begin
    val ~ priors[1]
    theta = Vector{typeof(val)}(undef,length(priors))
    for i in 1:length(priors)
      theta[i] ~ priors[i]
    end
    val2 ~ likelihood_dist_priors[1]
    σ = Vector{typeof(val)}(undef,length(priors))
    for i in 1:length(likelihood_dist_priors)
      σ[i] ~ likelihood_dist_priors[i]
    end
```

I was hoping this would work, but I get Dual{Real}s out.

From: https://github.com/JuliaDiffEq/DiffEqBayes.jl/pull/75

**Comment by mohamed82008** [comment]
The example is not runnable.

**Comment by ChrisRackauckas** [comment]
`]add DiffEqBayes#like`. https://github.com/JuliaDiffEq/DiffEqBayes.jl/blob/master/test/turing.jl

**Comment by mohamed82008** [comment]
The example below is concretely typed using #819.

```julia
using Turing

function f(priors)
	@model bif() = begin
		val ~ priors[1]
		@show typeof(val)
		theta = Vector{typeof(val)}(undef, length(priors))
		for i in 1:length(priors)
			theta[i] ~ priors[i]
		end
	end
end
model = f([Normal()])()
alg = HMC(1000, 0.1, 5)
sample(model, alg)
```

**Comment by mohamed82008** [comment]
I am getting some bounds error from that example, seems to be an off-by-1 error in DiffEqBayes IIUC. Please double check it.

**Comment by mohamed82008** [comment]
Turing master now supports type parameters using the following syntax:
```julia
@model gauss2(x, ::Type{TV}=Vector{Float64}) where {TV} = begin
    s = TV(undef, 2)
    ....
end
```
which eliminates the need for using `Real` in models and for the hack above. I will close this issue for now. Please feel free to open it again if you think we need to address something else here.
