### ISSUE TITLE
Lightweight benchmarking on Github Actions 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Turing.jl#822]
We would like to gradually move some simple benchmarking models into `Turing.jl/benchmarks/*` from `TuringBenchmarks`. These models would form a lightweight benchmarking suite, which we can run on Travis for every new PR. After Travis completion, the benchmarking results should be posted back as a comment to the PR. This allows us to have a quick inspection before merging PRs. 

This is already partially implemented by https://github.com/TuringLang/Turing.jl/pull/816, although we still need to add some models to `Turing.jl/benchmarks/` and write a `runbenchmarks.jl` script. 

Example models

- [`gdemo` ](https://github.com/TuringLang/AdvancedHMC.jl/issues/26)
- [`MvNormal`](https://github.com/TuringLang/AdvancedHMC.jl/blob/master/README.md)
- Bayesian Logistic Regresion

and 
- comparison of different Turing samplers see e.g. https://dm13450.github.io/2019/04/10/Turing-Sampling-Speed.html

Any comments?

**Comment by mohamed82008** [comment]
I like the idea!

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/DynamicPPL.jl/pull/346
