### ISSUE TITLE
Docstrings for `assume` and `observe`

### ISSUE THREAD

**Issue by willtebbutt** [TuringLang/Turing.jl#828]
There aren't currently any docstrings for `assume` and `observe`. While these aren't strictly user-facing functions, they're kind of important and could do with at least some basic docstring-documentation, in addition to the `Advanced Usage` bit of the docs.

**Comment by yebai** [comment]
Some further excerpts from slack:

> @willtebbutt In particular, what are we required to return from `assume` and `observe` when implementing them? From scanning the implementations of `assume` it looks like you have to return a tuple of `(sample, logp_of_sample)`, and for `observe` just `logp_of_sample`, but docstrings would have been helpful.
