### ISSUE TITLE
parallel logpdf

### ISSUE THREAD

**Issue by arzwa** [TuringLang/Turing.jl#830]
Hi, I have been trying to use Turing for Bayesian inference for a model where the likelihood should be evaluated using some form of parallelism (I have previously discussed this on the Turing Slack channel). @mohamed82008 suggested using the `KissThreading` library for multi-threading and was so friendly to provide a branch (mt/parallel) with the `observe` routine implemented with multi-threading for iid observations.

While this works, I'm having trouble in my particular application, where the multi-threaded version requires too much memory for realistically sized data-sets. In the past I have used DistributedArrays for computing the likelihood with a mapreduce approach, and this worked well without requiring too much memory. 

To use this in Turing, my first thought was to implement my custom Distribution (`WhaleModel`) with a `logpdf` method that evaluates in parallel, and treat the iid observations as a vector observed from a Multivariate distribution, something like this:

```julia
@model whale(x) = begin
    ν ~ InverseGamma(10.)
    η ~ Beta(10, 2)
    λ ~ MvLogNormal(ones(nrates(st)))  # st is some other (constant) object
    μ ~ MvLogNormal(ones(nrates(st)))
    x ~ WhaleModel(st, λ, μ, η)
end

# logpdf method for `WhaleModel` with DArray
logpdf(m::WhaleModel, xs::DArray) = mapreduce((x)->logpdf(m, x), +, xs)
```

(I know this is not a MWE, but the principle can equally well be applied to a simple Normal model for instance). This works for the Metropolis Hastings sampler, but does not play well with AD (see https://github.com/JuliaDiff/ForwardDiff.jl/issues/320). I assume that the problem of AD failing with distributed functions will also be there when the `observe` routine is implemented using a distributed for loop or mapreduce operation (i.e. as in the mt/parallel branch but using distributed computing instead of multi-threading for parallelism).

A solution to get both parallelism and AD, which I have used successfully for doing maximum likelihood estimation for this model using Gradient descent with Optim.jl, is to compute the gradient with a mapreduce approach. I have used something like this with Optim:

```julia
gradient(m::WhaleModel, xs::DArray) = mapreduce((x)->gradient(m, x), +, xs)

function gradient(m::WhaleModel, x)
    v = asvector(m)
    f = (u) -> logpdf(WhaleModel(m.S, u), x)
    g = ForwardDiff.gradient(f, v)
    return g[:, 1]
end
```

But I'm unsure whether and how I could get this to work in Turing? Thanks for any help, suggestions or tips!

**Comment by trappmartin** [comment]
I'll soon try to make a PR on the way we accumulate the logpdf value. This will also include (hopefully) a thread safe way how we manipulate the logpdf field such that you will be able to write something like this.

```julia
@model whale(x) = begin
    N = length(x)
    ν ~ InverseGamma(10.)
    η ~ Beta(10, 2)
    λ ~ MvLogNormal(ones(nrates(st)))  # st is some other (constant) object
    μ ~ MvLogNormal(ones(nrates(st)))
    @distributed for n in 1:N
        x[n] ~ WhaleModel(st, λ, μ, η)
    end
end
```

Would this be useful for your task?

**Comment by arzwa** [comment]
Yes, I think that would be useful. It might not work right-away with the `DArray` approach I've been using mostly in these situations (since that doesn't support parallel for loops with the `@distributed` macro as far as I know), but it is indeed this kind of general pattern I'm referring to. If the likelihood function is fairly computationally intensive and there are a lot of iid observations, than having the logpdf accumulated in parallel would be great.

**Comment by trappmartin** [comment]
True, the use of threads is probably more sensitive which is also slightly easier to realise than distributed computation.

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/DynamicPPL.jl/pull/92
