### ISSUE TITLE
Incorrect algorithm specification doesn't throw an error.

### ISSUE THREAD

**Issue by xukai92** [TuringLang/Turing.jl#831]
This algorithm specification should throw an error but not
```julia
Turing.NUTS(10,5,0.2,3,0.8)
```
Found by @jonasmac16

**Comment by xukai92** [comment]
So I guess we just need to constraint the type of `space` to be `Union{Tuple{},Tuple{Symbol}}?

**Comment by xukai92** [comment]
Will need to see how to proceed it in https://github.com/TuringLang/Turing.jl/pull/826 or after that be merged.

**Comment by mohamed82008** [comment]
Yes this is simple. I fixed it on 826. Running tests, then pushing.
