### ISSUE TITLE
HMC on product distributions

### ISSUE THREAD

**Issue by OlfwayAdbayIgbay** [TuringLang/Turing.jl#848]
For many hybrid models it is useful to be able to Sample from Products and Sums of Random Variables, such as:
`
    @model product(z) = begin

        a ~ Normal(2.0,0.1)

        b ~ LogNormal(2.0,0.5)

        c ~ a*b

    return c

`

As far as I can see there is no way in Turing for sampling c or for conditioning on c, as the sample() routine only returns values for a and b.

Is there a way to do this in Turing, or are there plans on implementing this?

**Comment by yebai** [comment]
I think this is possible by implementing a customised distribution, i.e. `prod(x) = Normal(x) * LogNormal(x)`, then define the model as

```julia

@model product(z) = begin
    c ~ prod()
end
```

See https://turing.ml/docs/advanced/ for an example on defining new distributions for Turing.

**Comment by mohamed82008** [comment]
To elaborate on @yebai's approach, you can do:
```julia
struct Delta{T} <: ContinuousUnivariateDistribution
    v::T
end
Distributions.rand(d::Delta) = d.v
Distributions.logpdf(d::Delta, x::T) where {T <: Real} = x == d.v ? zero(T) : T(-Inf)

@model product(c, a_dist, b_dist) = begin
    a ~ a_dist
    b ~ b_dist
    c ~ Delta(a*b)
end
c_dist = product(a_dist = Normal(2.0, 0.1), b_dist = LogNormal(2.0, 0.5))

# Samples from c
c_dist()
```

**Comment by OlfwayAdbayIgbay** [comment]
Thanks for the replies!
But shouldn't one of the advantages of HMC be that one can use autodifferentiation over the product operations that are applied to the samples to build a gradient, to circumvent the sampling problems that come with a delta measure?

**Comment by xukai92** [comment]
Unless you mean something like this?
```julia
@model test(data) = begin
    a ~ Normal(2.0,0.1)
    b ~ LogNormal(2.0,0.5)
    c = a * b
    data ~ Normal(c, 1)
end
```
