### ISSUE TITLE
NUTS/HMC not working on .6.19

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/Turing.jl#864]
Hi all-

After upgrading to .6.19, I noticed none of my code is working. Here is a minimum working example: 

```
using Turing

# Define a simple Normal model with unknown mean and variance.
@model gdemo(x, y) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x ~ Normal(m, sqrt(s))
  y ~ Normal(m, sqrt(s))
end

#  Run sampler, collect results
chn = sample(gdemo(1.5, 2), NUTS(2000,1000,.8))
```
Partial Error Message
```
ERROR: MethodError: no method matching AdvancedHMC.DualValue(::Float64, ::Float64)
Closest candidates are:
  AdvancedHMC.DualValue(::Tv<:AbstractFloat, ::Tg<:AbstractArray{Tv<:AbstractFloat,1}) where {Tv<:AbstractFloat, Tg<:AbstractArray{Tv<:AbstractFloat,1}} at /home/dfish/.julia/packages/AdvancedHMC/VOToJ/src/hamiltonian.jl:13
Stacktrace:...
```

In another model, I also received the following error (truncated for space):

```
ERROR: BoundsError: attempt to access 1-element Array{Float64,1} at index [2]
Stacktrace:
 [1] getindex at ./array.jl:729 [inlined]
 [2] ∂H∂θ(::AdvancedHMC.Hamiltonian{AdvancedHMC.Adaptation.DenseEuclideanMetric{Float64,Array{Float64,1},Array{Float64,2},LinearAlgebra.UpperTriangular{Float64,Array{Float64,2}}},getfield(Turing.Inference ...
```
I cannot share this model at the moment, but I might be able to try to reproduce it with a different one.

**Comment by mohamed82008** [comment]
What is the result of `using Pkg; Pkg.installed()["AdvancedHMC"]`?

**Comment by mohamed82008** [comment]
We probably just need to increase the `compat` lower bound version on `AdvancedHMC in the `Project.toml` file.

**Comment by itsdfish** [comment]
Here is what I get:

 using Pkg; Pkg.installed()["AdvancedHMC"]
ERROR: KeyError: key "AdvancedHMC" not found
Stacktrace:
 [1] getindex(::Dict{String,Union{Nothing, VersionNumber}}, ::String) at ./dict.jl:478
 [2] top-level scope at none:0

**Comment by yebai** [comment]
This is caused by some recent breaking changes to AHMC.  @xukai92 already created a PR on the Turing side (https://github.com/TuringLang/Turing.jl/pull/849), and a new Turing release is in progress - mhttps://github.com/JuliaRegistries/General/pull/2254.

Pls, note that there might still be some glitches around due to breaking changes introduced by several recent PRs. The situation should improve when   `v0.7` is released.

**Comment by itsdfish** [comment]
Thanks for the info. Out of curiosity, can you tell me if these breaking changes are primarily internal or on the user side?

**Comment by yebai** [comment]
> Thanks for the info. Out of curiosity, can you tell me if these breaking changes are primarily internal or on the user side?


It is primarily internal:

- remvoing rid of unnecessary gradient evaluations in AHMC
- switching to a new more efficient HMC variant: NUTS with Multinomial sampling
- improving the codebase by adding more diagnostics etc.

**Comment by mohamed82008** [comment]
Oh you need to run `Pkg.add("AdvancedHMC")` sorry.

**Comment by itsdfish** [comment]
> Oh you need to run `Pkg.add("AdvancedHMC")` sorry.

No problem. Here is what I get now:

```
(v1.1) pkg> st AdvancedHMC
    Status `~/.julia/environments/v1.1/Project.toml`
  [0bf59076] AdvancedHMC v0.2.0
  [d96e819e] Parameters v0.10.3
  [2913bbd2] StatsBase v0.31.0

```

> > Thanks for the info. Out of curiosity, can you tell me if these breaking changes are primarily internal or on the user side?
> 
> It is primarily internal:
> 
> * removing unnecessary gradient evaluations in AHMC
> * switching to a new more efficient HMC variant: NUTS with Multinomial sampling
> * improving the codebase by adding more diagnostics etc.

Good to know. Thanks.

**Comment by yebai** [comment]
This should be working now with Turing `v0.6.22` and AHMC `v0.2.1`.

**Comment by xukai92** [comment]
Yes please do an update on AdvancedHMC
