### ISSUE TITLE
Simple model fails to converge with N = 500

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/Turing.jl#866]
In the example below, the model fails to converge when the number of data points approaches 500. Varying the target acceptance rate doesn't seem to matter. In addition, I encountered similar results with a LogNormal model. 

```
using Turing,Random

Random.seed!(111)

@model model(y) = begin
    μ ~ Normal(0,1)
    s ~ Truncated(Cauchy(0,1),0,Inf)
    for i in 1:length(y)
        y[i] ~ Normal(μ,s)
    end
end

y = rand(Normal(0,1),500)

@time chain = sample(model(y),NUTS(2000,1000,.8))
println(chain)
```

Results:

```
Summary Statistics

│ Row │ parameters │ mean     │ std         │ naive_se    │ mcse    │ ess     │ r_hat    │
│     │ Symbol     │ Float64  │ Float64     │ Float64     │ Float64 │ Any     │ Any      │
├─────┼────────────┼──────────┼─────────────┼─────────────┼─────────┼─────────┼──────────┤
│ 1   │ s          │ 4.53592  │ 8.88623e-16 │ 2.81007e-17 │ 0.0     │ 4.01606 │ 0.998999 │
│ 2   │ μ          │ 0.053412 │ 1.38847e-17 │ 4.39074e-19 │ 0.0     │ 4.01606 │ Inf      │
```
System Info:

Julia 1.1.0
```

(v1.1) pkg> st Turing
    Status `~/.julia/environments/v1.1/Project.toml`
  [0bf59076] AdvancedHMC v0.2.1
  [31c24e10] Distributions v0.21.0
  [c7f686f2] MCMCChains v0.3.10
  [4c63d2b9] StatsFuns v0.8.0
  [fce5fe82] Turing v0.6.22
  [e88e6eb3] Zygote v0.3.2

(v1.1) pkg> st AdvancedHMC
    Status `~/.julia/environments/v1.1/Project.toml`
  [0bf59076] AdvancedHMC v0.2.1
  [d96e819e] Parameters v0.10.3
  [2913bbd2] StatsBase v0.31.0
```

P.S. The updates seem to be much faster. Great work!

**Comment by xukai92** [comment]
This model seems to quite sensitive to initialization when the number of data points gets large. Try `chain = sample(model(y),NUTS(2000,1000,.8), init_theta=[rand(), rand() + 1.0])`. Or maybe a different prior on your standard deviation?

I'm not sure what's the best way to improve the roubustness on initialisation... Wonder if @yebai has some thoughts on it.

**Comment by itsdfish** [comment]
I've tried `s~TruncatedNormal(1,1,0,Inf)`, with no success. I also tried fixing `s = 1`, which produces approximately 150 numerical errors

```
using Turing,Random

Random.seed!(111)

@model model(y) = begin
    μ ~ Normal(0,1)
    #s ~ TruncatedNormal(1,1,0,Inf)
    s=1
    for i in 1:length(y)
        y[i] ~ Normal(μ,s)
    end
end

y = rand(Normal(0,1),500)

@time chain = sample(model(y),NUTS(2000,1000,.8))
println(chain)
```

**Comment by xukai92** [comment]
I created a PR to improve the numerical stability on the AdvancedHMC.jl side. This model works stably on my local now. I will let you know when the PR is merged and tagged.

**Comment by yebai** [comment]
This issue is likely due to the posterior become peaky with more observations. The new Multinomial sampling scheme in AHMC manipulates MH probabilities in the real space, while causes underflow when MH probabilities are small. https://github.com/TuringLang/AdvancedHMC.jl/pull/86 switches to log MH probabilities, so the numerical stability should improve.
