### ISSUE TITLE
Sampling from an InverseWishart with HMC 

### ISSUE THREAD

**Issue by bennevans** [TuringLang/Turing.jl#883]
Hi,

I'm trying to sample from the [InverseWishart](https://github.com/JuliaStats/Distributions.jl/blob/master/src/matrix/inversewishart.jl) distribution from Distributions.jl. When I use the `IPMCMC` sampler it succeeds, but when using `HMC` I receive the following error:

>ERROR: PosDefException: matrix is not Hermitian; Cholesky factorization failed.

For reference, here is my code:
```
using Turing
using LinearAlgebra

@model test_model(ν, Ψ) = begin
    Σ ~ InverseWishart(ν, Ψ)
end

function test()
    d = 5
    ν = d+1
    A = rand(d,d)
    Ψ = A' * A

    println(ishermitian(Ψ)) # prints true

    model = test_model(ν, Ψ)
    sampler = HMC(100, 0.05, 10) # does not work
    # sampler = IPMCMC(100, 100, 4, 2) # works

    chain = sample(model, sampler)
end
```

Is this behavior expected?

I am using Turing v0.6.23 and Julia 1.1.1.

Thanks,
Ben

Also, I'm not sure if this is related, but in running the tests for Turing.jl, one of the (many) errors I recieve is 
>PDMatDistribution Tracker AD: Error During Test at /home/ben/.julia/packages/Turing/eIa7P/test/core/ad.jl:310
  Got exception outside of a @test
  MethodError: no method matching cholesky(::TrackedArray{…,Array{Float64,2}}; check=false)

**Comment by yebai** [comment]
This should be fixed with current AHMC and Turing. Please re-open if the error is met again.
