### ISSUE TITLE
Wrapping an external sampler: PolyChord

### ISSUE THREAD

**Issue by aplavin** [TuringLang/Turing.jl#895]
Recently we had a short discussion on discourse (https://discourse.julialang.org/t/mcmc-landscape/25654/83 and around) about using an external nested sampling implementation (e.g. [PolyChord](https://github.com/PolyChord/PolyChordLite)) with Turing. I made a thin wrapper (https://github.com/aplavin/Polychord.jl) around the underlying C/Fortran library half a year ago that works fine, but it would be nice to benefit from Turing model definition language. However, I couldn't find a simple way to add this a a Turing sampler - looking at existing samplers it looks like the control flow has somewhat "inverted" direction in Turing and in PolyChord library, at least regarding priors. The workflow for the latter looks like this:
```julia
# `prior` converts from uniform cube to model parameters
# e.g. if we have two parameters, one with Normal(0, 1) prior and the other with Normal(5, 2):
prior(cube::Vector{Float})::Vector{Float} = invcdf.([Normal(0, 1), Normal(5, 2)], cube)

# computes likelihood for given model parameters
loglike(params::Vector{Float})::Float = ...

run_polychord(prior, loglike, options)
```
Any suggestions on how to wrap it as a Turing sampler?

**Comment by xukai92** [comment]
IS might not be typical because it's not a MCMC sampler. I wonder if we can clean up the MH code a bit and make that as an example.

**Comment by yebai** [comment]
@cpfiffer Good idea to improve our MH sampler, in terms of modularity, better interface, and advanced features (e.g. adaptive variants). 

Some recent related discussions:

- Adaptive Metropolis Algorithm (RAM) - https://discourse.julialang.org/t/mcmc-landscape/25654
- MH-sampler in BAT.jl 
  - https://discourse.julialang.org/t/ann-dynamichmc-2-0/28314/22
  - https://github.com/bat/BAT.jl

**Comment by cpfiffer** [comment]
It looks like David Anthoff [implemented RAM](https://github.com/anthofflab/RobustAdaptiveMetropolisSampler.jl) last month. This also looks pretty easy to migrate over to the interface.

**Comment by yebai** [comment]
Yes; I added it [here](https://github.com/TuringLang/Turing.jl/issues/886) a few days ago. I feel we can have a really flexible/advanced MH sampler in Turing, by falling back to different MH backends (e.g. Emsemble, RAM, vanilla MH).

**Comment by yebai** [comment]
It should be significantly easier to get the prior probability of parameters, and likelihood probabilities separately after https://github.com/TuringLang/Turing.jl/issues/989 is merged. This might pave the way for integrating/implementing nested sampling algorithms.

**Comment by yebai** [comment]
Another implementation of nested sampling: https://github.com/joshspeagle/dynesty

Speagle, J. S. (2019) ‘dynesty: A Dynamic Nested Sampling Package for Estimating Bayesian Posteriors and Evidences’, arXiv [astro-ph.IM]. Available at: http://arxiv.org/abs/1904.02180.

**Comment by JohannesBuchner** [comment]
Even simpler to implement than MultiNest (dynesty and nestle implement it in Python) and parameter-free is MLFriends. It is illustrated and explained a bit at https://johannesbuchner.github.io/UltraNest/method.html

**Comment by yebai** [comment]
See https://github.com/TuringLang/NestedSamplers.jl
