### ISSUE TITLE
Incompatibilty with LocationScale

### ISSUE THREAD

**Issue by theogf** [TuringLang/Turing.jl#916]
Here is a MWE (with master)
```
@model mwemodel(y) = begin
    z ~ Normal()
    y ~ LocationScale(z,1.0,TDist(3.0))
end
sample(mwemodel(2.0),HMC(0.2,2),10)
```
Does not work both for forwarddiff and backwarddiff.
A temporary fix is to write `y ~ LocationScale(z,one(z),TDist(3.0))` since the problem comes from `LocationScale` expecting two first arguments of the same type.

**Comment by mohamed82008** [comment]
Try with Distributions master, seems like it should work https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/locationscale.jl#L41.

**Comment by mohamed82008** [comment]
Closing because I am unable to reproduce. Please reopen it again if facing the same issue after updating Distributions.jl.
