### ISSUE TITLE
Add LKJ Correlation Distribution

### ISSUE THREAD

**Issue by joshualeond** [TuringLang/Turing.jl#924]
I was trying to reproduce some Stan code and was looking for the `LKJ` distribution in Turing and didn't find it. I took to Slack and asked about it on the Turing channel and was asked to open an issue to add the distribution.

A couple of references came up on the Slack channel so I'll put them here as well:
1. The LKJ Correlation Distribution reference paper: [here](https://www.sciencedirect.com/science/article/pii/S0047259X09000876)
2. An implementation of the LKJ distribution in an existing Julia package (`AltDistributions`): [here](https://github.com/tpapp/AltDistributions.jl)

There was also some info on adjusting the `LKJ` implementation within AltDistributions to make it work seen on [this](https://github.com/StatisticalRethinkingJulia/TuringModels.jl/issues/1) other Github issue I had created.

**Comment by sdaxen** [comment]
Just wondering, why wouldn't LKJ be added directly to `Distributions`?

**Comment by joshualeond** [comment]
Good point, perhaps it should. My intent was to use it with Turing and I saw that Turing had a few custom distributions (Flat, FlatPos, etc.). I can move the issue to `Distributions` though.

**Comment by xukai92** [comment]
It's interesting that the distributions defined in AltDistributions.jl do not follow the type system from Distributions.jl

**Comment by joshualeond** [comment]
I just wanted to update this issue given that `Distributions.jl` appears to have an LKJ distribution now:
https://github.com/JuliaStats/Distributions.jl/pull/1066. This issue can likely be closed.

**Comment by cpfiffer** [comment]
Thanks!
