### ISSUE TITLE
Typeassert error with HMC

### ISSUE THREAD

**Issue by toreerdmann** [TuringLang/Turing.jl#930]
Hello, I am getting this error:
ERROR: TypeError: in typeassert, expected Float64, got ForwardDiff.Dual{Nothing,Float64,1}
I see that it's related to autodiff, and I am not sure if its because autodiff cannot work (for this model, which works with the IS sampler) or whether it's a bug.

Here's a minimal example:

```julia
dat = sample(1:3, 20)
function get_probs(tau)
    probs = rand(20, 3)
    probs[:,3] .= probs[:,3] .* tau
    probs
end
@model m(dat) = begin
    tau ~ Gamma(1, 1)
    probs = get_probs(tau)
    for i in 1:length(dat)
        dat[i] ~ Categorical(probs[i,:] ./ sum(probs[i,:]))
    end
end
chain = sample(m(dat), HMC(.05, 10), 10)
```

**Comment by mohamed82008** [comment]
Use:
```julia
function get_probs(tau)
    probs = zeros(typeof(tau), 20, 3)
    probs .= rand.()
    probs[:,3] .= probs[:,3] .* tau
    probs
end
```
Your code needs to be generic to enable automatic differentiation.
