### ISSUE TITLE
Long load times

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/Turing.jl#934]
Hi-

I noticed that Turing requires a lot of memory and time to load. Here is an example with Julia 1.2 using Plots as a point of comparison:

```
@time using Plots
  3.294392 seconds (4.33 M allocations: 247.371 MiB, 8.13% gc time)

 @time using Turing
 65.944560 seconds (86.03 M allocations: 5.664 GiB, 3.60% gc time)

(v1.2) pkg> st Turing
    Status `~/.julia/environments/v1.2/Project.toml`
  [0bf59076] AdvancedHMC v0.2.7
  [31c24e10] Distributions v0.21.3
  [f6369f11] ForwardDiff v0.10.3
  [c7f686f2] MCMCChains v0.3.14
  [4c63d2b9] StatsFuns v0.8.0
  [9f7883ad] Tracker v0.2.3
  [fce5fe82] Turing v0.7.0
  [e88e6eb3] Zygote v0.3.4
```
The results are even worse for Julia 1.3 RC4:

```
 @time using Turing
159.389266 seconds (249.46 M allocations: 17.804 GiB, 2.81% gc time)
```

**Comment by cpfiffer** [comment]
I've noticed that it takes a long time as well, but not nearly 159 seconds (!). Do you have `Revise` loaded by default in your startup file? 

Mine takes far less time on 1.3 RC3:

```julia
julia> @time using Turing
  8.797555 seconds (26.40 M allocations: 1.525 GiB, 3.37% gc time)
```

**Comment by mohamed82008** [comment]
It does take quite a bit of time to precompile the first time you load it on your device, especially if building Libtask too. The second time onwards should be much faster, in a new Julia session.

**Comment by mohamed82008** [comment]
It takes around 16 s the second time onwards on my machine on Julia 1.1 and around 19 s on Julia 1.2. I still think this is too long and we should look into reducing it somehow though.

**Comment by itsdfish** [comment]
My load times used to be around 6-8 seconds, but recently slowed down. What is really strange about this is that the load times are consistent for me, but on occasion it shows that Libtask is recompiled. It almost seems like Turing does not precompile properly, but it does not always print the precompiling notice. Here is an example pasted directly from the REPL. 


```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time using Turing
 55.246815 seconds (86.72 M allocations: 5.693 GiB, 3.95% gc time)

julia> exit()
(base) dfish@dfish-MS-7850:~$ '/home/dfish/Julia 1.2.0/bin/julia' 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time using Turing
 56.413187 seconds (86.72 M allocations: 5.694 GiB, 3.93% gc time)

julia> exit()
(base) dfish@dfish-MS-7850:~$ '/home/dfish/Julia 1.2.0/bin/julia' 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time using Turing
[ Info: Recompiling stale cache file /home/dfish/.julia/compiled/v1.2/Turing/gm4QC.ji for Turing [fce5fe82-541a-59a6-adf8-730c64b5f9a0]
  Building Libtask → `~/.julia/packages/Libtask/RjRkK/deps/build.log`
 73.879141 seconds (87.63 M allocations: 5.739 GiB, 3.01% gc time)

```

**Comment by itsdfish** [comment]
I think I identified the culprit. After reinstalling a fresh copy of Julia, I systematically installed my packages and found that one of my development projects included a spurious call to install packages in the main package file. I'm not even sure why the install packages call was there and why it only affected Turing. In either case, my best guess is that it was probably trying to install packages during precompilation and corrupted cache files or some other internal package files. As far as I can tell, removing this seems to have fixed the issue. 

I'll leave this open since @mohamed82008 indicated it might be possible to reduce the load times. I can confirm that last summer load times were around 6-8 seconds and now they are about 14-16 seconds on my system.

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/Turing.jl/issues/1504
