### ISSUE TITLE
Test for RandomMeasures fail

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Turing.jl#973]
Tests in the distributions testset pass, however, all other testsets chinese restaurant processes, stick breaking, and size-based resampling error due to a KeyError when calling Libtask.consume(::Trace).

**Comment by devmotion** [comment]
I noticed that sampling from these models works fine (without the KeyError) in the Julia REPL ([code](https://gist.github.com/devmotion/1fde42d174c6f53c9f7f749aaf4d6706)).

**Comment by yebai** [comment]
Likely fixed by recent updates to `Libtask`. In addition, `TArray` will be removed after https://github.com/TuringLang/Turing.jl/pull/1858
