### ISSUE TITLE
Persistent numerical issues

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/Turing.jl#974]
A few weeks ago I posted a model with numerical problems on Slack. I wanted to bring up the issue again because information tends to get lost on Slack and the problem seems to occur for other models in my experience. Here is the [model](https://github.com/itsdfish/Miscellaneous/blob/master/examples/LNR/Run_LNR_Sim.jl).

Following Trapmartins advice, I reparameterized the cauchy distribution to improve efficiency. Although this also helped to reduce the number of numerical errors (and successfully eliminated the issue in Stan), the number remains quite large.  

Here is a tabulation of the numerical errors extracted from the chain object 
```
Summary Stats:
Length:         50
Missing Count:  0
Mean:           30.200000
Minimum:        9.000000
1st Quartile:   12.250000
Median:         20.000000
3rd Quartile:   29.000000
Maximum:        227.000000
Type:           Float64
```
For some reason, the number or errors printed to the REPL is 267 (as opposed to 1500 in the chain object). In either case, this quite high and does not seem to be a problem with parameterization because it does not reproduce in Stan.

**Comment by xukai92** [comment]
Thanks for reporting the issue here again. 

I digged it a bit and found that it's due to the numerical issue from `log`. By doing the following can get rid of the warnings completely.

`log(1 - cdf(LogNormal(m, σ), t - ϕ))` -> `log(1 - cdf(LogNormal(m, σ), t - ϕ) + eps(eltype(t)))`

I'm not sure why Stan simply doesn't have it. I guess it might be the case its cdf implementation deals with it somehow or log is by default with some eps for stability?

Another related thing for which it would be nice to get your opinions here:

As I mentioned before, what you get from chains `:numerical_error` are a mix of both i) numerical error that related to `Inf` and `NaN` and ii) those related to any energy difference larger than Δmax. Now in the context of actully want to debugging real numerical errors, I realise this is not quite informative.  I think I can potentially rename `numerical_error` to `divergent` and use `numerical_error` to indicate those which related to `Inf` and `NaN`. How do you think?

Also, do you think such warning message should be only visible when DEBUG is on?

@sethaxen probably can also throw some ideas here.

**Comment by itsdfish** [comment]
Thank you, Kai. I really appreciate your help. Your solution did indeed eliminate the numerical errors. It still get the following from the chain:

```
Summary Stats:
Length:         50
Missing Count:  0
Mean:           30.440000
Minimum:        8.000000
1st Quartile:   13.000000
Median:         17.000000
3rd Quartile:   24.750000
Maximum:        206.000000
Type:           Float64
```
 Is this something I should be concerned about?

Yes. I like your proposal to track divergence with its own variable and make numerical_error more informative. My mind could be changed, but I thinking printing the warning messages  should be the default behavior. It could be useful to add the option to suppress the warnings. 

By the way, can you direct me to info for using the Debug mode? Unfortunately, I cannot find this information.

**Comment by itsdfish** [comment]
P.S. I forgot to mention that `log1mexp` from StatsFuns did not solve the problem. Do you think it should have. Maybe they could incorporate your eps solution

**Comment by devmotion** [comment]
I would have suggested trying to use `log1p`, but I just saw that `logccdf(LogNormal(...))` is already implemented in Distributions.jl. Maybe it's numerically more stable?

**Comment by itsdfish** [comment]
Thanks, devmotion. I think one problem is that I need `log(1-cdf(LogNormal(...))`. So `logcdf` would not work by itself. I did try `log1mexp(logcdf(LogNormal(...)))`, but to no avail.

**Comment by devmotion** [comment]
Isn't `logccdf` (with two c) exactly what you need? Both `logcdf` and `logccdf` are implemented in Distributions.

**Comment by itsdfish** [comment]
My apologies. The double c is hard for me to see. Yes. This solved the problem and looks much cleaner.

**Comment by xukai92** [comment]
> Is this something I should be concerned about?

Those caused by exceeding Δmax should be normal and I believe Stan's chain has them as well.

> Also, do you think such warning message should be only visible when DEBUG is on?

https://docs.julialang.org/en/v1/stdlib/Logging/#Environment-variables-1

> P.S. I forgot to mention that log1mexp from StatsFuns did not solve the problem.

This is solving a different issue in which exponentiating a number might cause numerical overflow.

**Comment by xukai92** [comment]
logccdf is neat. Thanks @devmotion

**Comment by itsdfish** [comment]
Thanks again for your help Kai and devmotion. I'll close this issue.

**Comment by yebai** [comment]
Does it make sense to have a page in our docs dedicated to common numerical issues, in a similar spirit to performance tips?

**Comment by itsdfish** [comment]
I think so. Interestingly, I made this suggestion to TrapMartin on Slack last night.

**Comment by sethaxen** [comment]
> As I mentioned before, what you get from chains `:numerical_error` are a mix of both i) numerical error that related to `Inf` and `NaN` and ii) those related to any energy difference larger than Δmax. Now in the context of actully want to debugging real numerical errors, I realise this is not quite informative. I think I can potentially rename `numerical_error` to `divergent` and use `numerical_error` to indicate those which related to `Inf` and `NaN`. How do you think?

I like this idea. I think it's more in line with how the terms are used elsewhere. For reference, Stan's behavior seems to be to fail when it encounters a `NaN`: https://mc-stan.org/docs/2_21/stan-users-guide/floating-point-representations.html#not-a-number-values.

**Comment by juliohm** [comment]
I am searching the docs for tips on numerical errors. Is there a guide somewhere that could help us debug similar warnings? We are getting these warnings with `LogitNormal` variables. Basically we define `LogitNormal(a + b*x, s)` with `a`, `b` and `x` `Normal(0,1)`. Is there a workaround to avoid the warnings?

**Comment by rikhuijzer** [comment]
> I am searching the docs for tips on numerical errors. Is there a guide somewhere that could help us debug similar warnings? We are getting these warnings with `LogitNormal` variables. Basically we define `LogitNormal(a + b*x, s)` with `a`, `b` and `x` `Normal(0,1)`. Is there a workaround to avoid the warnings? The model is not converging with NUTS.

I also think that is a good idea. Maybe at <https://turing.ml/dev/docs/using-turing/performancetips>?

For your problem, sometimes using the HMC sampler might help.

**Comment by juliohm** [comment]
Isn't NUTS using HMC behind the scenes but with the `No U-Turn` heuristic?
