### ISSUE TITLE
Segmentation fault in Julia 1.3 RC-5 when running chains in parallel

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/Turing.jl#981]
I receive the following error when running a custom model with Turing #master and Julia 1.3.0 rc-5:

```
      From worker 2:
      From worker 2:    signal (11): Segmentation fault
      From worker 2:    in expression starting at none:0
      From worker 2:    jl_lookup_generic_ at /buildworker/worker/package_linux64/build/src/gf.c:2251 [inlined]
      From worker 2:    jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2301
      From worker 2:    jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1631 [inlined]
      From worker 2:    jl_f__apply at /buildworker/worker/package_linux64/build/src/builtins.c:627
      From worker 2:    #_#3 at /home/dfish/.julia/packages/Turing/B22xC/src/Turing.jl:72
      From worker 2:    Model at /home/dfish/.julia/packages/Turing/B22xC/src/Turing.jl:72 [inlined]
      From worker 2:    VarInfo at /home/dfish/.julia/packages/Turing/B22xC/src/core/RandomVariables.jl:183 [inlined]
      From worker 2:    Sampler at /home/dfish/.julia/packages/Turing/B22xC/src/inference/hmc.jl:306
      From worker 2:    Sampler at /home/dfish/.julia/packages/Turing/B22xC/src/inference/hmc.jl:304 [inlined]
      From worker 2:    #sample#2 at /home/dfish/.julia/packages/Turing/B22xC/src/inference/Inference.jl:163
      From worker 2:    _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2141 [inlined]
      From worker 2:    jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
      From worker 2:    sample at /home/dfish/.julia/packages/Turing/B22xC/src/inference/Inference.jl:162
      From worker 2:    #51 at /home/dfish/.julia/dev/ACTRModels/src/Utilities/Turing Utilities.jl:4
      From worker 2:    unknown function (ip: 0x7f69888db436)
      From worker 2:    _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2141 [inlined]
      From worker 2:    jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
      From worker 2:    jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1631 [inlined]
      From worker 2:    jl_f__apply at /buildworker/worker/package_linux64/build/src/builtins.c:627
      From worker 2:    #108 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Distributed/src/process_messages.jl:294
      From worker 2:    run_work_thunk at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Distributed/src/process_messages.jl:79
      From worker 2:    macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Distributed/src/process_messages.jl:294 [inlined]
      From worker 2:    #107 at ./task.jl:333
      From worker 2:    _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2135 [inlined]
      From worker 2:    jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2305
      From worker 2:    jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1631 [inlined]
      From worker 2:    start_task at /buildworker/worker/package_linux64/build/src/task.c:659
      From worker 2:    unknown function (ip: 0xffffffffffffffff)
      From worker 2:    Allocations: 55810977 (Pool: 55802976; Big: 8001); GC: 50
```
I have no idea what role Turing might play and I will need some time to find a MWE (plus I cannot currently share my code). In either case, I wanted to put this on the radar of the Turing team in case you have ideas for a MWE. The following seems to work:

```
using Distributed
addprocs(4)
@everywhere using Turing
 
@everywhere @model model(y) = begin 
    μ ~ Normal(0,1)
    for i in 1:length(y)
        y[i] ~ Normal(μ, 1)
    end
end

y = rand(Normal(0, 1), 10)

reduce(chainscat, pmap(x->sample(model(y), NUTS(1000, .85), 2000), 1:4))
```

The main difference that I can identify at this point is that the problematic model has a custom distribution.

**Comment by mohamed82008** [comment]
This is indeed weird but without additional information, it will be hard to help. I think it is worth running the Turing tests on this version of Julia to see if any test there triggers the same error.

**Comment by itsdfish** [comment]
Yeah. My apologies for not being able to identify the source of the problem yet. Since it seems to be a serious error, I want to report it sooner rather than later. 

I can verify that my logpdf function evaluates correctly on all processors. So it does not appear to be isolated exclusively to that code. 

I ran the tests but did not identify anything that seemed to be related to the segmentation fault. I attached the test output here:
[test.txt](https://github.com/TuringLang/Turing.jl/files/3874562/test.txt)
There were several errors in the test that traced, which could have halted the code before it could produce the segmentation fault. So unfortunately, the tests are somewhat ambiguous. 

Over the next couple days I will continue searching for a MWE that I can share.

**Comment by itsdfish** [comment]
I traced the problem back to a convenience function I have been using for quite some time without problems. 

```
using Distributed
addprocs(4)
@everywhere using Turing
 
@everywhere @model model(y) = begin 
    μ ~ Normal(0,1)
    for i in 1:length(y)
        y[i] ~ Normal(μ, 1)
    end
end

y = rand(Normal(0, 1), 10)

function wrapper(model, config, Nsamples)
    return reduce(chainscat, pmap(x->sample(model, config, Nsamples), 1:4))
end
config = NUTS(1000, .8)
Nsamples = 2000
#this works
reduce(chainscat, pmap(x->sample(model(y), config, Nsamples), 1:4))

#This fails
wrapper(model(y), config, Nsamples)

```
I have not yet produced this error using simpler analogs that exclude Turing. Do you have any ideas?

**Comment by devmotion** [comment]
Could it be related to the fact that you're using global variables in one case but not in the other? There's a section about global variables in the documentation of parallel computing: https://docs.julialang.org/en/v1/manual/parallel-computing/#Global-variables-1

**Comment by itsdfish** [comment]
Thanks. I'll have to read into that in more detail later. My initial thoughts are (1) usually scoping problems have a message like " x not defined on worker 2" and (2) this has been working on other versions of julia including 1.2.0. I think that is a good lead. So I'll see if anything in 1.3.0 could have changed the behavior.

**Comment by itsdfish** [comment]
P.S. Here is one of my attempts to create an analog without Turing. Is this missing anything important?

```
using Distributed
addprocs(4)

#sample analog
@everywhere function f1(f2, x)
    println("hi")
    return f2(x)
end

#model analog
@everywhere f2(x) = x + 2

function wrapper(fun, x, N)
    pmap(x->f1(fun, x), 1:N)
end

N = 5
#An input to pass to f1, then to f2
x = 3
wrapper(f2, x, N)
```

**Comment by devmotion** [comment]
I suspect there is some problem with the serialization or deserialization since I get error messages such as `      From worker 2:    unknown function (ip: 0xffffffffffffffff)` if I try to run your Turing example above on Julia 1.3.0 rc5.

However, the following seems to work:
```julia
function wrapper(model, y, config, Nsamples)
    return reduce(chainscat, pmap(x->sample(model(y), config, Nsamples), 1:4))
end

wrapper(model, y, config, Nsamples)
```
Interestingly, the following also works:
```julia
let model=model(y)
    reduce(chainscat, pmap(x->sample(model, config, Nsamples), 1:4))
end
```

**Comment by itsdfish** [comment]
Thanks @devmotion.  I will use your first solution for the time being. 

Do you think this is a problem with Turing?

**Comment by devmotion** [comment]
Honestly, I don't know. I played around with your example a bit and tried to reproduce or fix it, but I haven't managed to condense it to a simpler example that clearly shows what's causing these issues.
