### ISSUE TITLE
Proposal Distribution in Turing

### ISSUE THREAD

**Issue by donhausk** [TuringLang/Turing.jl#996]
The current setting for proposal distributions is rather difficult to use. Especially because the proposal distributions must be defined in advanced. However, for example for SMC sampling, it would be great if the proposal distributions could be computed in the model. This would allow the usage of methods like the Laplace approximation for the proposal of the SMC sampler.

Would it not be possible to implement something like this:
`
y ~ Exponential() | Normal() 
`
`
x ∼ Normal() | Normal(x, y)
`
where the proposal distribution is the one the | . In addition, the compiler would have to change this distribution to:
(x) -> Normal(x, y)

and x will be internally threated as the previous element of the MCMC chain.

**Comment by donhausk** [comment]
``

**Comment by devmotion** [comment]
It seems with your suggestion one also has to specify a proposal distribution a priori? But just in the model instead of the construction of the sampler?

Intuitively, I would say that the proposal distribution rather belongs to a certain algorithm/sampler than the model. Is it not sufficient to define approximations such as `LaplaceApproximation`, handle them internally, and specify those instead of an explicit proposal distribution?

**Comment by donhausk** [comment]
I totally agree with you. This is not a very clean way. However, it could be improved for example by using 
`
y ~ Exponential() | SCM:Normal()
`
Of course, the syntax is not very good and must be taken into consideration. To give a short context why something like this would be helpful in my opinion. Assume that we have some heavy matrix computations required to compute the distributions (for example the GP-SSM models), for example:
`
x ∼ MvNormal(mu,sigma)
`
`
muy,sigmay = someheavymatrixcomp(x)
`
`
muy_p, sigmay_p = proposaldist(muy,sigmay)
`
`
y ~ MvNormal(muy,simgay) | SCM:Normal(muy_p,sigmay_p)
`
Now if we have to pass the proposals as functions in the algorithm, we would have only access to x and not to muy and sigmay. This would force us to redo the whole procedure.

However, I clearly see the inconsistency of this approach. I am mainly asking for solutions in this direction.

**Comment by yebai** [comment]
I think annotating the model with additional information to help inference is an interesting approach, particularly for particle samples, where proposal distribution is critical to reduce degeneracy.  I agree it requires a bit of design work to ensure a clean syntax. 

Luckily, it is straightforward to remove/transform such annotations using metaprogramming in Julia. So, one can generate a "clean" version of a model if needed, i.e. removing all the annotations not specific to modelling.

**Comment by xukai92** [comment]
The proposed syntax looks reminds me of the guide stuff in Pyro. The difference/tricky thing here (in Turing) is that we do not name variables explicltly thus it's nontrivel to set a proposal distribution for a specific random variable. But as a first step, with the `Named` synatx proposed in https://github.com/TuringLang/Turing.jl/issues/972#issuecomment-555117648, we could just introduce a function called `setproposal(::Named, proposal)` and one can use this before each `~` if needed. We can improve the modelling syntax later if needed.

**Comment by yebai** [comment]
Ideally, we'd like to keep modelling and inference decoupled. Additional inference related annotation can be added via other mechanisms such as https://github.com/TuringLang/DynamicPPL.jl/pull/347
